### ISSUE TITLE
Bootstrapping and Listing tasks should not require signingConfig

### ISSUE THREAD

**Issue by Nutomic** [Triple-T/gradle-play-publisher#100]
I've set up the plugin as described in the Readme, but all tasks are shown as "not found". They also aren't listed in `./gradlew tasks`. 

Console Output:
```
$ gradle publishApkRelease
Could not find ZipAlign task. Did you specify a signingConfig for the variation Release?

FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishApkRelease' not found in root project 'syncthing-android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.471 secs
```

[Code is here](https://github.com/syncthing/syncthing-android/tree/translation-uploads)

**Comment by ivanove** [comment]
Hi 

if you are on MAC, run this " ./gradlew task" you will find the correct name, because publishApkRelease is just an example, for me the task is "publishMyAppplicationApkRelease" so did like I told you.

**Comment by Nutomic** [comment]
Like I said, I already tried that. `./gradlew tasks | grep publish` is empty.

**Comment by bhurling** [comment]
The plugin only creates those tasks when there is a valid signingConfig for the release type. It even prints a warning if there is something wrong with that signingConfig (see the first output line in your example). 

Please make sure to create a valid keystore and set it up for the release build type.

**Comment by ivanove** [comment]
Look when I try ./gradlew tasks
the gradle output is that :

Play Store tasks
----------------
bootstrapBusinessAppsReleasePlayResources - Downloads the play store
listing for the BusinessAppsRelease build. No download of image resources.
See #18.
bootstrapBusinessReleasePlayResources - Downloads the play store listing
for the BusinessRelease build. No download of image resources. See #18.
generateBusinessAppsReleasePlayResources - Collects play store resources
for the BusinessAppsRelease build
generateBusinessReleasePlayResources - Collects play store resources for
the BusinessRelease build
publishApkBusinessAppsRelease - Uploads the APK for the BusinessAppsRelease
build
publishApkBusinessRelease - Uploads the APK for the BusinessRelease build
publishBusinessAppsRelease - Updates APK and play store listing for the
BusinessAppsRelease build
publishBusinessRelease - Updates APK and play store listing for the
BusinessRelease build
publishListingBusinessAppsRelease - Updates the play store listing for the
BusinessAppsRelease build
publishListingBusinessRelease - Updates the play store listing for the
BusinessRelease build


2015-10-08 5:22 GMT+01:00 Björn Hurling <notifications@github.com>:

**Comment by Nutomic** [comment]
@bhurling Ah I see. The thing is, we already use Jenkins for APK releases. Now I want to add gradle-play-publisher only to upload translations to the Play Store. Those shouldn't require a signing config, right?

Would "Bootstrapping and Listing changes should not require signingConfig" be a better title then?

**Comment by bhurling** [comment]
You're absolutely right. The signingConfig is not needed when you just want to upload the listing. I will change the title of this issue and take a look into it

**Comment by Nutomic** [comment]
Thanks :)
