### ISSUE TITLE
APK uploaded successfully, but not available on playstore console

### ISSUE THREAD

**Issue by sudansh** [Triple-T/gradle-play-publisher#1002]
### Describe the bug

I am uploading an apk to internal track. The gradle runs successfully and reports that apk has been uploaded but I can't see that new build in playstore console

### How To Reproduce

> ./gralew  ./gradlew uploadReleasePrivateApk
Console output.
...
Uploading APK: 44% complete
Uploading APK: 49% complete
Uploading APK: 55% complete
Uploading APK: 60% complete
Uploading APK: 66% complete
Uploading APK: 71% complete
Uploading APK: 77% complete
Uploading APK: 82% complete
Uploading APK: 88% complete
Uploading APK: 93% complete
Uploading APK: 99% complete

> Task :app:uploadDevelopmentReleasePrivateApk
APK upload complete
Upload successful: `link to uploaded apk` this opens the playstore and I can install the buidl

#### Versions

- Gradle Play Publisher: 3.6.0
- Gradle Wrapper: 7.0.2
- Android Gradle Plugin: 7.0.2

#### Tasks executed

./gradlew uploadReleasePrivateApk      

### Expected behavior

The apk is uploaded to internal track and I can see that build in internal testing in playstore console.

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
The terminology is confusing. You're uploading to the Internal Sharing track which is a completely separate thing from normal publishing. Use `./gradlew publishReleaseApk`.

**Comment by sudansh** [comment]
@SUPERCILEX I meant the internal sharing only. I am unable to view the apk in the Internal track of playstore console

**Comment by SUPERCILEX** [comment]
Right, [internal sharing](https://support.google.com/googleplay/android-developer/answer/9844679?hl=en) is *not* the same as the internal track. `uploadReleasePrivateApk` does not upload your APK to any track at all: it goes to internal sharing. `publishReleaseApk` uploads APKs to a track (in your case the internal track).
