### ISSUE TITLE
A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishInternalSharingBundle$BundleUploader          > Error writing request body to server

### ISSUE THREAD

**Issue by rey9230** [Triple-T/gradle-play-publisher#1006]
Failde when running  ./gradlew uploadReleasePrivateBundle with gradle distribution 7.0.2 throwing following error message:

Execution failed for task ':app:uploadReleasePrivateBundle'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishInternalSharingBundle$Processor
   > There was a failure while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishInternalSharingBundle$BundleUploader
         > Error writing request body to server

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

It does not provide enough degub information to find out what is really wrong and i haven't found any related issue

How To Reproduce
Versions
Gradle Play Publisher: 3.7.0-SNAPSHOT
Gradle Wrapper: 7.0.2
Android Gradle Plugin: 7.0.2
Tasks executed
 ./gradlew uploadReleasePrivateBundle
Expected behavior
No error occurred.

**Comment by SUPERCILEX** [comment]
That looks like a networking error to me. Does this happen every time?
