### ISSUE TITLE
Read time out when updating to 3.6.0-agp4.2

### ISSUE THREAD

**Issue by mochadwi** [Triple-T/gradle-play-publisher#1007]
### Describe the bug

I'm not sure if this is jcenter issue or the Triple-T 🙏 as it happened in our CI & Local machines

### How To Reproduce

Trying to upgrade to `3.6.0-agp4.2` trying to sync and build, but failed

#### Versions

- Gradle Play Publisher: 3.6.0-agp4.2
- Gradle Wrapper: 7.1.1
- Android Gradle Plugin: 4.2

#### Tasks executed

Doing a trivial task such as sync or build

### Expected behavior

Able to sync or build

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by mochadwi** [comment]
confirmed https://status.gradle.com/?utm_source=embed

<img width="933" alt="Screen Shot 2021-09-16 at 5 01 54 PM" src="https://user-images.githubusercontent.com/7057959/133592984-6f96c97f-dc84-43f5-b9b5-c1862cb95e94.png">

**Comment by SUPERCILEX** [comment]
Thanks for finding the source of the error. :)
