### ISSUE TITLE
Promote to beta/production task

### ISSUE THREAD

**Issue by shiraji** [Triple-T/gradle-play-publisher#103]
I want to have a feature that promotes apk to beta or production. Following is possible task names:
- promoteAlphaToBeta
- promoteAlphaToProduction
- promoteBetaToProduction

gradle-play-publisher has a userFraction so it may be better that when user promote to the production, it set userFraction as well. 

I'm not sure if someone already try to implement this. If not, I am happily to do so. I don't know if `google-api-services-androidpublisher` offers that kind of functions. If you know that let me know.

**Comment by Frequencies** [comment]
awesome, thanks

**Comment by shiraji** [comment]
No problem. 

But, it's not merged, yet. @bhurling may not like it...

**Comment by SUPERCILEX** [comment]
@bhurling I have similar thoughts here as in https://github.com/Triple-T/gradle-play-publisher/issues/104#issuecomment-391416685

**Comment by bhurling** [comment]
I agree. Especially since we only know what app to talk to after other plugins have run a bunch of tasks like manifest merging. Also, they introduced an additional track and this approach doesn't seem to scale well
