### ISSUE TITLE
Prices are missing for the following billable countries: LB

### ISSUE THREAD

**Issue by nicolabeghin** [Triple-T/gradle-play-publisher#1031]
### Describe the bug

Trying to upload bundle, the following error is thrown by APIs.
![image](https://user-images.githubusercontent.com/2743637/147086391-373cf3b5-67eb-419a-be06-1a3211b32c4b.png)

### How To Reproduce
Run gradle 
#### Versions
3.7.0-agp4.2

- Gradle Play Publisher: 
- Gradle Wrapper: 
- Android Gradle Plugin: 

#### Tasks executed

What tasks did you run? `publishFullGplayBundle`.

### Expected behavior

Publication happens on Play Store.

### Additional context (if a crash, provide stack trace)

Lebanon (LB) pricing is not available at all in Google Play Console.

**Comment by SUPERCILEX** [comment]
You presumably need to add that currency to your product json file. Or you could just run the bootstrap task again

**Comment by nicolabeghin** [comment]
@SUPERCILEX thanks for your kind reply. I ran `boostrapListing` gradle task but still same error. Could you provide an hint on the aforementioned product json file? thanks!

**Comment by SUPERCILEX** [comment]
Inside `play/products`, you'll have a bunch of json files that define in-app purchase prices, etc. You're probably missing LB somewhere in there. Though if you don't know what I'm talking about, you're probably not using that feature anyway so you should just delete the `products` directory.

**Comment by nicolabeghin** [comment]
thanks @SUPERCILEX I cannot find any directory named `products`

    find . -name "products" -print | wc

leads to 0 results. Could it be because I'm leveraging
```
plugins {
    id 'com.github.triplet.play' version '3.7.0-agp4.2'
```

as per https://github.com/Triple-T/gradle-play-publisher/issues/1035 since I'm using latest Android Studio 2021.1.1?
<img width="639" alt="image" src="https://user-images.githubusercontent.com/2743637/162627402-5a97354b-d465-4652-8563-37da7300bb0d.png">

**Comment by SUPERCILEX** [comment]
Hmmm, can you run the build command with `-S`? It'll show a full stack trace so the source of the request can be traced. It could be that you need to fix something in the console before it lets you publish.

**Comment by nicolabeghin** [comment]
Still nothing, but got around by excluding Lebanon from targeted countries.

> My solution was to remove country Lebanon from Countries / Regions until resolved.
> Console → Production → Country / Regions (tab) → then click on “Remove Countries / Regions”.

ref. https://forums.expo.dev/t/eas-submit-failed-with-google-api-error-invalid-request-prices-are-missing-for-the-following-billable-countries-lb/58581/4

**Comment by SUPERCILEX** [comment]
Awesome!
