### ISSUE TITLE
suppport  Android Gradle plugin (AGP)   7.1.0

### ISSUE THREAD

**Issue by periva101** [Triple-T/gradle-play-publisher#1035]
### Problem description
after I updated from  (AGP)4.x  Triple-T  is not working anymore

right now  I use
        classpath 'com.github.triplet.gradle:play-publisher:3.7.0'

I think is problem is
AndroidComponentsExtension is depredated

**Comment by SUPERCILEX** [comment]
Please fill out the bug template: https://github.com/Triple-T/gradle-play-publisher/issues/new?assignees=&labels=bug&template=1-bug.md. I need to know exact versions.

**Comment by sacclynrey** [comment]
I also encountered this error 

version: 
`com.github.triplet.gradle:play-publisher:3.7.0`
`com.android.tools.build:gradle:7.0.4`

TargetSdkVersion and CompileSdkVersion = 31

command used: 
`./gradlew publishUatbuildUatBundle --track alpha`

**Comment by SUPERCILEX** [comment]
@sacclynrey That's a separate issue: you probably have different versions of the plugin or AGP mixed together. Look through these issues: https://github.com/Triple-T/gradle-play-publisher/issues?q=artifacttype%24bundle.

@periva101 Not a bug with this plugin. It's because of AndroidX Navigation:
```
java.lang.NoClassDefFoundError: com/android/build/api/extension/AndroidComponentsExtension
        at androidx.navigation.safeargs.gradle.SafeArgsPlugin.apply(SafeArgsPlugin.kt:72)
        at androidx.navigation.safeargs.gradle.SafeArgsPlugin.apply(SafeArgsPlugin.kt:41)
```

https://developer.android.com/jetpack/androidx/releases/navigation#2.5.0-alpha01

**Comment by mathieudebrito** [comment]
Hello @SUPERCILEX !

I also have the exact same issue as @periva101, here are the exact versions : 

    classpath 'com.android.tools.build:gradle:7.1.2'
    classpath "com.github.triplet.gradle:play-publisher:3.7.0-agp4.2"
       
    minSdkVersion = 23
    targetSdkVersion = 30
    compileSdkVersion = 29
    buildTools = '30.0.2'
    
This issue is closed, maybe the problem is already solved somehow and I missed it ?

Thank you very much !

**Comment by periva101** [comment]
@mathieudebrito no one solve the issue
