### ISSUE TITLE
Support gradle 7.4

### ISSUE THREAD

**Issue by b95505017** [Triple-T/gradle-play-publisher#1037]
#### Versions

- Gradle Play Publisher: 3.7
- Gradle Wrapper: 7.4
- Android Gradle Plugin:  7.1.1

```
\--- com.github.triplet.play:com.github.triplet.play.gradle.plugin:3.7.0
     \--- com.github.triplet.gradle:play-publisher:3.7.0
          +--- com.github.triplet.gradle:android-publisher:3.7.0
          |    +--- com.github.triplet.gradle:common-utils:3.7.0
          +--- com.github.triplet.gradle:common-utils:3.7.0
          +--- com.github.triplet.gradle:common-validation:3.7.0
Gradle 7.4
+--- com.android.tools.build:gradle:7.1.1
|    \--- com.android.tools.build:gradle:3.5.1 -> 7.1.1 (*)
|    +--- com.android.tools.build:gradle:7.0.4 -> 7.1.1 (*)
```

```
* What went wrong:
@Option 'resolution-strategy' linked to multiple elements in class 'com.github.triplet.gradle.play.tasks.PublishBundle_Decorated'.
```

**Comment by ZacSweers** [comment]
This appears due to these two using the same `resolution-strategy` value

```kotlin
@get:OptionValues("resolution-strategy")
val resolutionStrategyOptions: List<String>

@get:Internal
@set:Option(
        option = "resolution-strategy",
        description = "Set the version conflict resolution strategy."
)
var resolutionStrategyOption: ResolutionStrategy
```

**Comment by SUPERCILEX** [comment]
Hmmm, no idea how to fix this without copying all our options into every task. Also, the resolution strategy stuff is a red herring, it'll fail at other options if you remove that one. Definitely seems like a Gradle bug though. Filed https://github.com/gradle/gradle/issues/19868

**Comment by ZacSweers** [comment]
I don't think that's a gradle bug, there are indeed two different options defining the same argument name

**Comment by SUPERCILEX** [comment]
No, [OptionValues](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/options/OptionValues.html) is not an option. It specifies a list of valid strings to be passed into some other option. Just to be 100% sure, I commented out `resolutionStrategyOptions` and the bug still occurs.

**Comment by SUPERCILEX** [comment]
Keeping this open until it's resolved in the Gradle side.

**Comment by SUPERCILEX** [comment]
Fixed on the Gradle side.

**Comment by Calldorado-com** [comment]
Works for us, thanks. Updated to Gradle 7.6
