### ISSUE TITLE
Change userFraction after publishing apk

### ISSUE THREAD

**Issue by shiraji** [Triple-T/gradle-play-publisher#104]
`gradle-play-publisher` has `userFraction` but it only useful when user publishs apk. I want to change userFraction after publishing apk.

`./gradlew changeUserFraction -PuserFraction=0.5`

This may be a different task but I want to pass userFraction as a parameter. Because I don't want users to change `build.gradle` every time executing this command. 

Creating tasks for all userFraction like `changeUserFractionTo05` could be possible work around.

**Comment by SUPERCILEX** [comment]
This plugin is meant to support continuous integration, not be a replacement for the Play Console. I think updating the user fraction could easily be done in the Google Play Console Android app or on the website. @bhurling what do you think?

**Comment by shiraji** [comment]
I really didn't know this plugin is only for supporting CI. You need to close #108 and #110, too. I created this issue and PR because I run this plugin in command line. I wanted to keep changing fraction based on the feature I would like to release.

**Comment by SUPERCILEX** [comment]
I wouldn't say it's _only_ meant CI, but we're spread a little thin and trying to mirror the Play Console would be major overkill IMO. However, @bhurling has the final say so I'd wait for his opinion. 😄

**Comment by bhurling** [comment]
I agree that batch updating the user fractions can be very useful for maintainers of whitelabel Apps. And that's basically why this plugin was created in the first place. Not sure about the API, though. @gtcompscientist do you have any thoughts?

**Comment by gtcompscientist** [comment]
@bhurling I think that there are a lot of updating tasks that don't include the APK would be useful for people managing projected with lots of variants.
