### ISSUE TITLE
Override existing release notes

### ISSUE THREAD

**Issue by msarelo** [Triple-T/gradle-play-publisher#1040]
Is it possible to override existing release notes?

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher#uploading-release-notes. If you use that, your release notes will be overriden.

**Comment by msarelo** [comment]
> See https://github.com/Triple-T/gradle-play-publisher#uploading-release-notes. If you use that, your release notes will be overridden.

Overriding not working for me, I can upload it once, only release notes was empty before.

**Comment by SUPERCILEX** [comment]
You'll need to use the promote task with the update flag: https://github.com/Triple-T/gradle-play-publisher#promoting-artifacts

**Comment by msarelo** [comment]
`   {
       "code": 400,
       "errors": [
         {
           "domain": "global",
           "message": "Release notes are badly constructed or have duplicates.",
           "reason": "badRequest"
         }
       ],
       "message": "Release notes are badly constructed or have duplicates.",
       "status": "INVALID_ARGUMENT"
     }`

**Comment by SUPERCILEX** [comment]
What are the contents of your release notes?

**Comment by msarelo** [comment]
simple text
