### ISSUE TITLE
How to update release notes by version name?

### ISSUE THREAD

**Issue by msarelo** [Triple-T/gradle-play-publisher#1041]
Is it possible to update release notes by version name?
Eg. I have 2 versions in GPC on internal track: 1.0.0 and 1.1.0, I would like to update release notes for 1.0.0.

Is it possible to do that in that way when I put file in specific folder eg:
 /app/main/play/1.0.0/internal.xml
or
by arguments eg:
promoteReleaseArtifact --update nternal --releasne-name 1.0.0?

**Comment by SUPERCILEX** [comment]
No, and I don't plan to support that. The logic is already complicated and that would make things worse.
