### ISSUE TITLE
400 Bad Request while uploading bundle (TOS NOT ACCEPTED)

### ISSUE THREAD

**Issue by ViacheslavSiz** [Triple-T/gradle-play-publisher#1042]
### Describe the bug

400 Bad Request while uploading bundle
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "message": "UploadException: TOS_NOT_ACCEPTED [[]] (com.***.app)",
      "reason": "failedPrecondition"
    }
  ],
  "message": "UploadException: TOS_NOT_ACCEPTED [[]] (com.***.app)",
  "status": "FAILED_PRECONDITION"
}

### How To Reproduce

./gradlew uploadPrivateBundle

I did not find any TOS I have to accept anywhere

**Comment by SUPERCILEX** [comment]
You need to accept the terms of service in the play console.

**Comment by ViacheslavSiz** [comment]
@SUPERCILEX thanks, thats what I can really read from the error.
But I can not find anywhere any place to accept TOS. Not in play console under API section, nor in google console

**Comment by SUPERCILEX** [comment]
Unfortunately I haven't seen this before so your best bet would be to contact play support and ask them about it.

**Comment by AntipovAlexander** [comment]
hey

faced the same issue. @SUPERCILEX have you found where the TOS can be accepted?

**Comment by AleksandarIlic** [comment]
Hey @ViacheslavSiz and @AntipovAlexander, 

Did you find the cause for this issue? I'm experiencing the same problem when I try to `uploadPrivateBundle`. 

We have Android app in the PlayStore under Open Testing track and no Production builds. I'm wondering if this is the problem.
