### ISSUE TITLE
Release note not publishing in Google Play Store

### ISSUE THREAD

**Issue by waleedasad** [Triple-T/gradle-play-publisher#1043]
### Describe the bug
Release note not publishing in Google Play Store while using Internal track. Although the file is present in this directory : "/app/src/publishDevReleaseApk/play/release-notes/en-US/internal.txt" but still I'm unable to publish the release notes on Google Play Store.

#### Versions

- Gradle Play Publisher: 2.0.0-rc1
- Gradle Wrapper: 6.7.1
- Android Gradle Plugin: 4.1.3

#### Tasks executed

./gradlew publishDevReleaseApk

### Expected behavior

I have added this in .travis.yml:

 before_deploy:
        - export APP_CHANGELOG=$(cat app/src/publishDevReleaseApk/play/release-notes/en-US/internal.txt)
        
Before deploying it should add Release notes but it isn't adding release notes although I have verified the file is present at the above location.

**Comment by SUPERCILEX** [comment]
https://github.com/Triple-T/gradle-play-publisher#uploading-release-notes

Please read the source set docs. You probably want `app/src/devRelease`, but it'll depend on your configuration.

**Comment by waleedasad** [comment]
@SUPERCILEX , 
Thanks for responding, I changed the directory to see what impact it will have. Now I'm getting this error although default.txt and internal.txt files are present in that directory: 

*** What went wrong:
Execution failed for task ':app:generateDevReleasePlayResources'.
> Unknown file: /home/travis/build/Tixsee/intermiami-android/app/src/devRelease/play**

I followed "https://github.com/Triple-T/gradle-play-publisher#uploading-release-notes" but I'm unable to publish release notes.

**Comment by SUPERCILEX** [comment]
Seems like you have a file named "play". It shouldn't be there.

**Comment by waleedasad** [comment]
No there is no file naming play, it's a folder.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/25791333/158543580-59e57775-30a4-4d25-824e-81b168513afe.png">

**Comment by SUPERCILEX** [comment]
You didn't ls the same directory (so maybe it's missing?). Also, that directory you showed shouldn't exist because it's under the build directory and yet has "src" in its path.

**Comment by mskvorcovs** [comment]
Same here
id 'com.github.triplet.play' version "3.7.0"

The structure below was generated after running `bootstrapMarketReleaseListing`
![image](https://user-images.githubusercontent.com/19667811/161535763-8e17b51a-0452-4ec4-9f11-bebdb1cbf2bd.png)

This is my config

play {
    serviceAccountCredentials = file('***.json')
    track.set("internal")
    releaseStatus.set(ReleaseStatus.COMPLETED)
    defaultToAppBundles.set(true)
}

Now, after some edits in changelog I run `publishMarketReleaseBundle` to internal track and get the bundle uploaded, but not the release notes.
