### ISSUE TITLE
Release notes are not upladed when calling publishBundle

### ISSUE THREAD

**Issue by mskvorcovs** [Triple-T/gradle-play-publisher#1045]
Release-notes are not being published when running publishBundle command. Thea same as mentioned here: https://github.com/Triple-T/gradle-play-publisher/issues/1043#issue-1167999984

com.github.triplet.play:com.github.triplet.play.gradle.plugin:3.7.0
Gradle 7.2
com.android.tools.build:gradle:7.1.2

The structure below was generated by running `bootstrapMarketReleaseListing`. I have renamed the production.txt -> default.txt to be able to use the same release notes for internal track.

![image](https://user-images.githubusercontent.com/19667811/161535763-8e17b51a-0452-4ec4-9f11-bebdb1cbf2bd.png)

This is my config

```
play {
    serviceAccountCredentials = file('***.json')
    track.set("internal")
    releaseStatus.set(ReleaseStatus.COMPLETED)
    defaultToAppBundles.set(true)
}
```

Now, after edits in changelog I run `publishMarketReleaseBundle` to internal track and get the bundle uploaded, but not the release notes.

**Comment by mskvorcovs** [comment]
It seems that 'release-notes' directory is empty

![image](https://user-images.githubusercontent.com/19667811/161716509-3d5f111e-971e-4a14-8a14-b863e06b0600.png)

Is there anything I've missed?

**Comment by SUPERCILEX** [comment]
Ah, well that would be your issue. When you run a build, is the `:app:generateMarketReleasePlayResources` task running?

**Comment by mskvorcovs** [comment]
According to the console output the task IS running (see below), but it is running BEFORE app:clean (might be the issue)

```
gradle publishMarketReleaseBundle --stacktrace 
=======================================================
 
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

> Configure project :app

> Task :app:generateMarketReleasePlayResources UP-TO-DATE
> Task :app:clean
```

**Comment by SUPERCILEX** [comment]
That's definitely the issue lol. Just run clean in a separate build invocation and you should be good.

**Comment by mskvorcovs** [comment]
I'm not sure if I understood you correctly, how am I supposed to fix that? I'm NOT calling the `app:clean` task, it's being invoked by the `gradle publishMarketReleaseBundle --stacktrace `

**Comment by SUPERCILEX** [comment]
The clean task does not invoke itself. Look through your build logic for the string "clean" and you'll probably find something that triggers it.

**Comment by mskvorcovs** [comment]
OMG, that's embarrasing! Thank you! Sorry for taking your time!

**Comment by SUPERCILEX** [comment]
No prob
