### ISSUE TITLE
Not working with AGP 7.3.0-alpha07 and Gradle 7.4

### ISSUE THREAD

**Issue by ArcherEmiya05** [Triple-T/gradle-play-publisher#1046]
### Describe the bug

Creating a release no longer works on pipeline after updating with AGP 7.3.0-alpha07 and Gradle 7.4

### How To Reproduce

Update AGP and Gradle

Error
`@Option 'from-track' linked to multiple elements in class 'com.github.triplet.gradle.play.tasks.internal.UpdatableTrackLifecycleTask_Decorated'.`

- Gradle Play Publisher:  3.7.0
- Gradle Wrapper: 7.4
- Android Gradle Plugin: 7.3.0-alpha07

**Comment by SUPERCILEX** [comment]
Use 7.4.1: https://github.com/Triple-T/gradle-play-publisher/issues/1037

**Comment by ArcherEmiya05** [comment]
> Use 7.4.1: #1037

You mean Gradle Wrapper 7.4.1?

**Comment by SUPERCILEX** [comment]
Yep
