### ISSUE TITLE
Is it possible to download signed (by Google Play) universal APK file after publication?

### ISSUE THREAD

**Issue by amal** [Triple-T/gradle-play-publisher#1048]
Couldn't find anything about such feature and it's very important in many cases.

**Comment by SUPERCILEX** [comment]
No, but you can probably use curl against the API yourself: https://developers.google.com/android-publisher/api-ref/rest

**Comment by amal** [comment]
not stale

**Comment by eirnym** [comment]
@amal could you describe what your use case is?

Based on the sole fact that issue is located here, my guess is the fresh build and signed APK is needed. If this is the case, I believe that this signed APK is located on the file system and it can be retrieved by magic of CI you use.

**Comment by amal** [comment]
@eirnym my local bundle/APK is signed with upload key certificate which is different from resulting app signing key certificate.  Also I'm uploading bundle, not APK and need the resulting universal APK signed by Google Play.  It's required on CI for internal release tests and for uploading to the different stores (e.g. Amazon, Huawei, etc.)  Currently, it's done manually and I'm looking for automation.

**Comment by eirnym** [comment]
So you following need a process to if I read your comment correctly:

1. Build an app bundle
2. Run some tests
3. Publish to Google Play
4. Download from Google Play
5. Run more tests
6. Publish to other stores

and you're stuck at bullet 4?

**Comment by amal** [comment]
@eirnym, yes, exactly!

**Comment by eirnym** [comment]
May I ask to feed my curiosity, why do you need bundle app signed by Google to publish to other stores? Is it a requirement or a suggestion?

**Comment by amal** [comment]
@eirnym, bundle publication is a recommended way for Google Play right now, so the final signing is made by google. In the future it maybe the only way for publication.

For manual tests, auto-testing and other stores publication we need the final universal apk with the final signing (available only from Google Play), otherwise it will be incompatible with what users obtain from the store. We have the same apk signature for every store to allow users choose what they like and update apps from any store at any moment.

**Comment by amal** [comment]
not stale

**Comment by Jacks0N23** [comment]
I have the same problem with downloading, because we have visa sdk that need google play signing and only after that we'll be able to manually test some cases with visa sdk on prod build. So having this task will be very helpful to do it consistently
