### ISSUE TITLE
Triplet play not working on agp 7.2.1

### ISSUE THREAD

**Issue by Pitam-Poudel** [Triple-T/gradle-play-publisher#1049]
An exception occurred applying plugin request [id: 'com.github.triplet.play', version: '3.5.0-agp7.0']

#### Versions
- Gradle Play Publisher:   id("com.github.triplet.play") version "3.5.0-agp7.0"
- Gradle Wrapper:  gradle-7.3.3-bin.zip
- Android Gradle Plugin:  com.android.tools.build:gradle:7.2.1

**Comment by SUPERCILEX** [comment]
Please provide a stack trace.

**Comment by MarineDr** [comment]
Sorry, I realize yesterday that i haven't the last version. I upgrade it and no more problem. Thank you for your replies.
