### ISSUE TITLE
best way to manage versionCode

### ISSUE THREAD

**Issue by k2s** [Triple-T/gradle-play-publisher#105]
do I have to manualy increase versionCode before each publish ?
couldn't there be task/function to receive latest published version and autoincrement it ?

thank you for sharing this code with us.

**Comment by doubleo2** [comment]
Have you searched for ways to auto increment the versionCode? There are lots of ways to do it and pretty thorough explanations available online. For instance, you can use the BUILD_NUMBER from your CI server as the versionCode. The right method will depend on your workflow, but the play publisher plugin is almost certainly not the right place to implement it.

**Comment by bhurling** [comment]
Gradle is very powerful so you can do some handy calculations. See this nice little snippet: https://plus.google.com/+JakeWharton/posts/6f5TcVPRZij

That combined with @doubleo2's answer should give you all you need.

Closing this one as out-of-scope
