### ISSUE TITLE
Ability to upload AAB release build file

### ISSUE THREAD

**Issue by ArcherEmiya05** [Triple-T/gradle-play-publisher#1050]
This command `./gradlew :app:publishReleaseBundle` builds aab and release it to internal track. But what if we wanted to reuse the generated aab file for other purposes? Can we instead build aab file with gradle and provide it to GPP in the command to save build minute for CI CD? Thanks

**Comment by SUPERCILEX** [comment]
Yes: https://github.com/Triple-T/gradle-play-publisher#uploading-a-pre-existing-artifact

**Comment by ArcherEmiya05** [comment]
> Yes: https://github.com/Triple-T/gradle-play-publisher#uploading-a-pre-existing-artifact

Thanks a lot, one more question does `./gradlew :app:publishReleaseBundle` command generates AAB file? Cause we want to use that AAB that GPP task created for other task as well.

**Comment by ArcherEmiya05** [comment]
We want to achieve something like this `./gradlew :app:publishReleaseBundle :app:uploadToAppSweepRelease`.
Where `:app:publishReleaseBundle` will generate release AAB file then publish it in internal track and `:app:uploadToAppSweepRelease` task reuses the cached results from this task and doesn't run everything again.

**Comment by ArcherEmiya05** [comment]
Thanks a lot!

**Comment by ArcherEmiya05** [comment]
> Publish just depends on the bundle task from AGP (don't remember what it's called).
> 
> https://github.com/Triple-T/gradle-play-publisher/blob/4273731c8126cdbf071300882718ec2ae12f3e3c/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt#L464
> You'll want to use the `variant.artifacts.get(...)` part.

I just want to follow up, does `./gradlew :app:publishReleaseBundle` command uses `:app:assembleRelease` internally?

**Comment by SUPERCILEX** [comment]
No because that's a human task. There's an underlying task the AGP API gives us which does the actual building. If you want to use a named task, you can probably just depend on `bundleRelease`. (`assembleRelease` is for APKs)

**Comment by ArcherEmiya05** [comment]
> No because that's a human task. There's an underlying task the AGP API gives us which does the actual building. If you want to use a named task, you can probably just depend on `bundleRelease`. (`assembleRelease` is for APKs)

Is this the equivalent of `./gradlew :app:publishReleaseBundle` in a more manual approach?

build.gradle
```
play {
    serviceAccountCredentials.set(file(PLAY_API_KEY_FILE))
    artifactDir.set(file("app/build/outputs/bundle/release"))
}
```

Gradle command
`./gradlew clean :app:bundleRelease :app:publishBundle`

Is the artifact dir here is enough or we should also explicitly add `app-release.aab` in it?

**Comment by SUPERCILEX** [comment]
Oh, you need to run those in two separate builds or muck around with the task dependencies. If you use artifactDir, `publishBundle` will run immediately (without waiting for bundleRelease to finish).

**Comment by ArcherEmiya05** [comment]
> Oh, you need to run those in two separate builds or muck around with the task dependencies. If you use artifactDir, `publishBundle` will run immediately (without waiting for bundleRelease to finish).

You mean separate task?

`./gradlew clean :app:bundleRelease` // Keep the build artifacts for subsequent pipeline steps

` ./gradlew clean :app:publishBundle`

**Comment by SUPERCILEX** [comment]
Don't run clean: `./gradlew :app:publishBundle`

**Comment by ArcherEmiya05** [comment]
> Don't run clean: `./gradlew :app:publishBundle`

My bad

**Comment by ArcherEmiya05** [comment]
Hi, just want to raise this issue again. I actually tried this

First step
```
Build Bundle (Release)
...
./gradlew clean :app:bundleRelease"
          artifacts: # Keep these artifacts for subsequent pipeline steps
            - app/build/outputs/** # Artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
```

Second step
```

Deploy to PlayStore (Internal)
...
"./gradlew :app:publishBundle"
```

But it does not work, the task is successful but no bundle was uploaded to the store.

![image](https://user-images.githubusercontent.com/38008900/182365077-fe56fb40-27a7-401f-ac75-0f37675cb9f6.png)

Artifacts from previous pipeline build was downloaded so I am pretty sure it not empty
![image](https://user-images.githubusercontent.com/38008900/182365919-52a7ef52-1f97-411a-bc3c-cfb641dcc26a.png)

**Comment by ArcherEmiya05** [comment]
Do I need to include the actual AAB file name in this path?
`artifactDir.set(file("app/build/outputs/bundle/release"))`

Like this
artifactDir.set(file("app/build/outputs/bundle/release/app-release.aab"))

**Comment by SUPERCILEX** [comment]
No, that shouldn't be necessary. I would add an `ls -R` step to see what files are present.

**Comment by ArcherEmiya05** [comment]
> No, that shouldn't be necessary. I would add an `ls -R` step to see what files are present.

Shouldn't we start at build folder like this?  `artifactDir.set(file("build/outputs/bundle/release"))` since `build.gradle` is inside the app module already?

**Comment by ArcherEmiya05** [comment]
I tried to download the artifact and its directory is this `app\build\outputs\bundle\release`

**Comment by SUPERCILEX** [comment]
Oh yeah, you're right. `artifactDir.set(file("build/outputs/bundle/release"))` should work.

**Comment by ArcherEmiya05** [comment]
> Oh yeah, you're right. `artifactDir.set(file("build/outputs/bundle/release"))` should work.

Thanks will try this

**Comment by ArcherEmiya05** [comment]
> > No, that shouldn't be necessary. I would add an `ls -R` step to see what files are present.
> 
> Shouldn't we supposed to start at build folder like this? `artifactDir.set(file("build/outputs/bundle/release"))` since `build.gradle` is inside the app module already?

Solved, closing the issue now.
