### ISSUE TITLE
Ability to automatically grab screenshots

### ISSUE THREAD

**Issue by keunes** [Triple-T/gradle-play-publisher#1057]
### Problem description
We're currently thinking of adding automated, localized screenshots of our app (https://github.com/AntennaPod/AntennaPod/issues/4044). This way we would be able to improve our play store listings and save ourselves some work of manually creating the images. Following a quick web search I found Fastlane's [screengrab](https://docs.fastlane.tools/actions/screengrab/). However, the main developer @ByteHamster noted that we're using Triple-T to create builds and push metadata to Google.

Would it somehow be possible to integrate automatic screenshot processes in Triple-T somehow?

### Potential solutions/workarounds
Use fastlane's tools - can it peacefully live alongside Triple-T?

### Additional context
n/a

**Comment by SUPERCILEX** [comment]
Thanks for the suggestion, but something like this isn't ever going to be integrated directly into GPP. You can instead use a different tool and wire up the tasks to do the right thing.

**Comment by keunes** [comment]
Thanks @SUPERCILEX for the reply. Would you happen to know, then, if screengrab/Fastlane can live alongside Triple-T?

**Comment by SUPERCILEX** [comment]
I don't see why not, but I also haven't tried it. If you run into specific issues, feel free to post them.
