### ISSUE TITLE
why is "Manage Production APKs" permission always required ?

### ISSUE THREAD

**Issue by k2s** [Triple-T/gradle-play-publisher#106]
I want to publish only to beta track, without enabling "Manage Production APKs"  permission I am getting message "401 Unauthorized".

**Comment by bhurling** [comment]
That's required by the Google Play Developer API. I am afraid we can't do anything about it. I already filed an issue in the Google APIs project (see or discussion in #20). But the issue has not been very popular.

Please enable all the permissions as explained in the readme
