### ISSUE TITLE
This app has no data safety declaration

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#1064]
With plugin

        classpath 'com.android.tools.build:gradle:7.2.2'
        classpath 'com.github.triplet.gradle:play-publisher:3.7.0'

I suddenly run into this

> A failure occurred while executing com.github.triplet.gradle.play.tasks.CommitEdit$Committer
   > 400 Bad Request
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/info.audio.analyse/edits/13033420723244839709:commit?changesNotSentForReview=false
     {
       "code": 400,
       "errors": [
         {
           "domain": "global",
           "message": "This app has no data safety declaration.",
           "reason": "badRequest"
         }
       ],
       "message": "This app has no data safety declaration.",
       "status": "INVALID_ARGUMENT"
     }

Does someone knows what's wrong here ?

**Comment by SUPERCILEX** [comment]
https://support.google.com/googleplay/android-developer/answer/10787469?hl=en
