### ISSUE TITLE
Missing support for Subscriptions API

### ISSUE THREAD

**Issue by vlad-roid** [Triple-T/gradle-play-publisher#1067]
gradle-play-publisher 3.7 only supports legacy subscription products created last year or earlier, not new ones from this year which are not returned at all by the In-App Products API and have a very different structure
![image](https://user-images.githubusercontent.com/26101312/194789804-50bb71da-1c2c-4da7-9797-17cb7c28f034.png)

Please add support for the Subscriptions API, otherwise there's no way to use the library for those as they're not even generating by `bootstrapListing --products`.

**Comment by vlad-roid** [comment]
@SUPERCILEX sorry do you know if this is coming soon? InApp Products API is pretty much deprecated, there's no turning back to it unfortunately and `bootstrapListing --products` isn't returning the subscription products.

**Comment by SUPERCILEX** [comment]
That's a bummer, but I don't actively maintain this plugin anymore. That said, I'm happy to review PRs.

**Comment by vlad-roid** [comment]
Got it, thank you. Hopefully you'll see a PR from me for this soon then ;) Unsure how much effort the migration to the new API would be, Google I guess is known for overcomplicating things.
