### ISSUE TITLE
Update Android Gradle Plugin to 7.30

### ISSUE THREAD

**Issue by tanman2391** [Triple-T/gradle-play-publisher#1068]
### Problem description
upgrade request to be compatible with latest Android Gradle Plugin

**Comment by andreimesina** [comment]
Hey, any updates on this one? Lots of projects will soon be on Android Gradle Plugin 7.3.+

**Comment by SUPERCILEX** [comment]
I'm no longer actively maintaining this project, so someone else will need to take this on. There was an attempt, but it got stalled because gradle broke things as usual: https://github.com/Triple-T/gradle-play-publisher/pull/1069.
