### ISSUE TITLE
Improve missing language support

### ISSUE THREAD

**Issue by johnhearn** [Triple-T/gradle-play-publisher#107]
I am managing a growing number of application variants (and this plugin is a godsend, thanks!) however one of the differences between them is the languages that they support. For example there are variants with en-GB or en-US depending on the location, and others which support local languages like Catalan. I would like to define a `whatsnew` file for every possible language in the `src/main/play` folder but if I do that then I get a `apkRecentChangesAddedForMissingLanguage` error for any language not defined for a particular app. 

```
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Tried to set recent changes text for APK version 179 for language en-GB. Language is not associated with the app.",
      "reason" : "apkRecentChangesAddedForMissingLanguage"
    } ],
    "message" : "Tried to set recent changes text for APK version 179 for language en-GB. Language is not associated with the app."
  }
```

Is there a workaround for this error? Could it be skipped for apps which don't support a given language? I would like to avoid having to define specific language folders for every variant because that would mean having to maintain `whatsnew` files for each one, which is exactly what I'm trying to avoid.

**Comment by bhurling** [comment]
The plugin merges resources from main and the actual build variant. Perhaps you can drop your whatsnew files into a central folder somewhere at a higher level and then symlink the files you want to provide for each build variant. I Haven't tested this, but if you'r using git and your dev and ci machines are Unix-based, this should work.

**Comment by SUPERCILEX** [comment]
We should probably just handle edge cases where this plugin and the Play Store disagree on languages.
