### ISSUE TITLE
`3.8.1` and `3.8.0` don’t show up in GitHub Releases

### ISSUE THREAD

**Issue by chimbori** [Triple-T/gradle-play-publisher#1079]
https://github.com/Triple-T/gradle-play-publisher/releases only lists releases up to `3.7.0`

Releases `3.8.1` and `3.8.0` are both available as Tags, but not marked as Releases, so they’re not listed under Releases.

Is this somehow intentional? Thank you!

**Comment by SUPERCILEX** [comment]
Done: https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.8.1. 3.8 was botched and broke backcompat, so I'm only publishing 3.8.1.

**Comment by chimbori** [comment]
Thanks for taking care of this so quickly, I appreciate it!
