### ISSUE TITLE
Configuration Cache issue with Gradle 8.1

### ISSUE THREAD

**Issue by eygraber** [Triple-T/gradle-play-publisher#1083]
After updating to Gradle 8.1 I'm getting a configuration cache error:

```
Task `:commitEditFor<my package>` of type `com.github.triplet.gradle.play.tasks.CommitEdit`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

There was no error when using Gradle 8.0

**Comment by eygraber** [comment]
Bump

**Comment by SUPERCILEX** [comment]
PRs welcome, but I don't work on this project anymore.

**Comment by ydanneg** [comment]
any plans to release it?

**Comment by gmazzo** [comment]
Reponing since #1084 was not a fix at all.

**Comment by gmazzo** [comment]
This issue should be reopned since #1084 was not a fix at all. I'm taking a look at it

**Comment by SUPERCILEX** [comment]
@gmazzo Can you confirm the fix with the snapshot builds? If not, no worries I'll just publish.

**Comment by gmazzo** [comment]
> @gmazzo Can you confirm the fix with the snapshot builds? If not, no worries I'll just publish.

Give me a couple of days and I'll report back
cc: @rolgalan

**Comment by gmazzo** [comment]
> > @gmazzo Can you confirm the fix with the snapshot builds? If not, no worries I'll just publish.
> 
> Give me a couple of days and I'll report back cc: @rolgalan

I can confirm it worked successfully with CC on for `publishReleaseBundle` and `promoteArtifact` 🚀 

![image](https://user-images.githubusercontent.com/513566/236841344-c5d34392-b0ff-418c-9fb0-f70bf227f31c.png)
![image](https://user-images.githubusercontent.com/513566/236841835-9537b8a5-3e9f-4ec9-88e3-88b32799c946.png)

**Comment by gmazzo** [comment]
> > @gmazzo Can you confirm the fix with the snapshot builds? If not, no worries I'll just publish.
> 
> Give me a couple of days and I'll report back cc: @rolgalan

I can confirm it worked successfully with CC on for `publishReleaseBundle` and `promoteArtifact` 🚀 

![image](https://user-images.githubusercontent.com/513566/236841344-c5d34392-b0ff-418c-9fb0-f70bf227f31c.png)
![image](https://user-images.githubusercontent.com/513566/236841835-9537b8a5-3e9f-4ec9-88e3-88b32799c946.png)
