### ISSUE TITLE
Consider shading Google API client dependencies

### ISSUE THREAD

**Issue by tadfisher** [Triple-T/gradle-play-publisher#1091]
### Problem description

I have Google API client dependencies on the build classpath from [`com.google.firebase.testlab:testlab-gradle-plugin`](https://maven.google.com/web/index.html#com.google.firebase.testlab:testlab-gradle-plugin:0.0.1-alpha03). That plugin needs version 1.x of `google-api-client`, and this plugin wants version 2.x, which are not compatible:

```
Exception java.lang.IllegalStateException: You are currently running with version 2.2.0 of google-api-client. You need at least version 1.15 of google-api-client to run version 1.22.0 of the Cloud Testing API library.
```

### Potential solutions/workarounds

Ideally, both plugins would shade their dependencies, for example by using the [`shadow` plugin](https://github.com/johnrengelman/shadow); this is because Gradle doesn't isolate classpaths between plugins, so it ends up resolving the larger of the two library versions per its normal dependency resolution rules. 

I will also open a report on Google's issue tracker.

**Comment by SUPERCILEX** [comment]
The only thing that changed in 3.8.4 was the dependency update, so feel free to keep using 3.8.3.
