### ISSUE TITLE
A gradle task for uploading native debug symbols

### ISSUE THREAD

**Issue by pfieffer** [Triple-T/gradle-play-publisher#1092]
### Problem description

Every time an app bundle is uploaded to the play console. We are having to:
1. Zip the contents of:
`app/build/intermediates/merged_native_libs/release/out/lib/` (excluding mips/ and mpis64/ if they are present)
2. Upload them manually to **App Bundle Explorer > Specific Bundle > Downloads > Native debug symbols**

I have no idea if theres a better way to get things done or if this step is even important at all. But play console warns that the crash reports may not be that great if this step is skipped

### Potential solutions/workarounds
A script to zip the contents of `app/build/intermediates/merged_native_libs/release/out/lib/` and upload them to the play console.
Sorry I have no idea if that is even possible

### Additional context
None

**Comment by xxfast** [comment]
Anyone found any workaround for this?
