### ISSUE TITLE
Publish to Wear OS only?

### ISSUE THREAD

**Issue by PRosenb** [Triple-T/gradle-play-publisher#1108]
Thanks for your work on this useful project.
I'm wondering if it's possible to publish to `Phones, Tablets, Chrome OS` as well as to the `Wear OS Only` track on Google Play (see screenshot below)? It exists for `Internal Testing`, `Closed Testing`, `Open Testing` and `Production`.

<img width="398" alt="Screenshot 2023-11-11 at 15 22 51" src="https://github.com/Triple-T/gradle-play-publisher/assets/8108165/cf7b6456-4f4c-4b6a-8b93-f67b7e12b550">

**Comment by PRosenb** [comment]
@SUPERCILEX, do you know about this?

**Comment by SUPERCILEX** [comment]
No, someone else would have to look into this.

**Comment by maxrimmer** [comment]
Is this the same case for Android Automotive?

**Comment by PRosenb** [comment]
Yes it is. In the screenshot Wear OS isn't shown because I added it already.
<img width="209" alt="Screenshot 2023-12-09 at 16 40 01" src="https://github.com/Triple-T/gradle-play-publisher/assets/8108165/288b0e3e-6dd9-4b65-8f95-eee83de5f7f3">

**Comment by kubovy** [comment]
+1
