### ISSUE TITLE
Build fails on the version conflict with ResolutionStrategy.IGNORE

### ISSUE THREAD

**Issue by dmitrytavpeko** [Triple-T/gradle-play-publisher#1109]
### Describe the bug
When you try to upload a new bundle with the same version code and `resolutionStrategy.set(ResolutionStrategy.IGNORE)` set, the build still fails with the following message:
`
           {
             "code": 403,
             "errors": [
               {
                 "domain": "global",
                 "message": "Version code 1 has already been used.",
                 "reason": "forbidden"
               }
             ],
             "message": "Version code 1 has already been used.",
             "status": "PERMISSION_DENIED"
           }
`
Looks like Google Play has changed the error message, and the lib can't recognise the error anymore.
See [this line](https://github.com/Triple-T/gradle-play-publisher/blob/67e8f2e5fbc2f6a6db88485f4d2a5ea91a6c5beb/play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/internal/DefaultEditManager.kt#L219C24-L219C24):
`m.contains("version code") || m.contains("Cannot update", ignoreCase = true)`.

I believe we can fix it with the following change:
`m.contains("version code", ignoreCase = true) || m.contains("Cannot update", ignoreCase = true)`

### How To Reproduce
Set `resolutionStrategy.set(ResolutionStrategy.IGNORE)` and try to upload a bundle with the same version code.

- Gradle Play Publisher: [Gradle Play Publisher 3.8.4](https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.8.4)

### Expected behavior

The task should not fail.

**Comment by oliverlockwood** [comment]
Thanks @dmitrytavpeko for the fix and @SUPERCILEX for merging.

@SUPERCILEX if there's any possibility of a release being issued soon to include this, that would be great.  Many thanks.

**Comment by oliverlockwood** [comment]
Update: I found it is already released in 3.8.6 (see https://github.com/Triple-T/gradle-play-publisher/commits/master).

(I had originally been looking at https://github.com/Triple-T/gradle-play-publisher/releases which doesn't yet mention the new release.)

**Comment by SUPERCILEX** [comment]
Added the release notes. I tend to wait a bit in the hopes that someone will catch any introduced bugs before it's announced to everybody.
