### ISSUE TITLE
ResolutionStrategy.AUTO: appears not to respect track

### ISSUE THREAD

**Issue by Chuck-Townsend** [Triple-T/gradle-play-publisher#1127]
I would like som clarification of the ResolutionStrategy.AUTO feature behavior. It appears that the versionCode chosen when this feature is enabled is one more than the greatest versionCode among all tracks of the app being published. Is that the intended behavior? I was expecting it to us a value of one more than the versionCode of the app being published on the specified track.

**Comment by Chuck-Townsend** [comment]
I would like som clarification of the ResolutionStrategy.AUTO feature behavior.  It appears that the versionCode chosen when this feature is enabled is one more than the greatest versionCode among all tracks of the app being published.  Is that the intended behavior?  I was expecting it to us a value of one more than the versionCode of the app being published on the specified track.

**Comment by SUPERCILEX** [comment]
Yes, that's intended behavior. You can't upload an app with a duplicate version code, hence why the auto strategy is valuable in the first place.
