### ISSUE TITLE
Release v3.10.1 is missing from releases dashboard

### ISSUE THREAD

**Issue by JamalSharif** [Triple-T/gradle-play-publisher#1132]
### Describe the bug

We are utilizing Renovate for automatic library updates. Today, it detected a new release, v3.10.1. However, when I checked the release notes [here](https://github.com/Triple-T/gradle-play-publisher/releases), I could not find the release v3.10.1 .

### How To Reproduce
Go to [releases section](https://github.com/Triple-T/gradle-play-publisher/releases)

### Expected behavior

**We should be able to see the release notes for latest release v3.10.1**

**Comment by SUPERCILEX** [comment]
https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.10.1
