### ISSUE TITLE
Add support for Managed Publishing

### ISSUE THREAD

**Issue by phcannesson** [Triple-T/gradle-play-publisher#1136]
### Problem description
We're using [managed publishing ](https://support.google.com/googleplay/android-developer/answer/9859654?hl=en) on our app, which means that we control exactly when the app is served to user, after review.
It's the only action we need to do manually on the Google Play console.

### Potential solutions/workarounds
I tried to look into the documentation of the Publishing API, but it's unclear for me if we can automate the publishing.
If it's the case, it would be great to add the functionality to this plugin.

**Comment by SUPERCILEX** [comment]
If it can be done, if be happy to accept a PR.
