### ISSUE TITLE
Support deploying to multiple tracks at the same time

### ISSUE THREAD

**Issue by avalanchas** [Triple-T/gradle-play-publisher#1140]
### Problem description

I would like to have one build (one version code) be deployed to multiple tracks at the same time so that I don't have to promote a release manually later (in case I want multiple tracks to have the same content).

### Potential solutions/workarounds

I am a beginner at this so please forgive any ignorance, but from the API docs (if I have the correct ones), it looks like this should be possible in a loop:
https://developers.google.com/android-publisher/tracks#apk_workflow_example
> Call the [Edits.tracks: update](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/update) method for each track that you want to release APKs on

I imagine a solution where I would write something like this:
```
gradle app:publishReleaseBundle --track=beta,alpha

play {
    track.set("alpha,beta") 
}
```
### Additional context

Current state: the plugin tries to find a track called "alpha,beta"
![image](https://github.com/user-attachments/assets/71e3b683-1a6b-4f96-b21e-e092f9858dde)

**Comment by SUPERCILEX** [comment]
The way the plugin works, you have to first publish and then promote: https://github.com/Triple-T/gradle-play-publisher?tab=readme-ov-file#promoting-artifacts

**Comment by avalanchas** [comment]
Uh ok so this is already possible with the plugin as it is? Can add something like this to my gradle file?
```
play {
    // ...
    promoteTrack.set("alpha")
    promoteTrack.set("beta")
}
```
If so, how would this be written on the command line?

**Comment by SUPERCILEX** [comment]
If you swap out the promote statement between two builds so it first first goes to alpha and then beta, then sure. See https://github.com/Triple-T/gradle-play-publisher?tab=readme-ov-file#promoting-artifacts

Also you're probably making this too complicated. Just publish directly to beta? Like I don't see the point of filling all the tracks.

**Comment by avalanchas** [comment]
Haha yeah I get how this probably sounds. But after 1 or 2 years Google sends you notifications that your artifacts in some tracks (even paused ones) are outdated and threatens consequences if you don't update soon. So I'd like to update all tracks regularly without having to think about it every year

**Comment by SUPERCILEX** [comment]
Well that's dumb about google, thanks for the context.
