### ISSUE TITLE
Release v3.11.0 is missing from releases dashboard

### ISSUE THREAD

**Issue by david-allison** [Triple-T/gradle-play-publisher#1142]
Similar to: 

* https://github.com/Triple-T/gradle-play-publisher/issues/1132

We are using Dependabot to propose dependency updates. Changelogs on GitHub should be auto-linked by Dependabot, but this did not occur, as the releases page did not contain the latest release

----

* https://github.com/Triple-T/gradle-play-publisher/releases
  * as-of writing, [releases/latest](https://github.com/Triple-T/gradle-play-publisher/releases/latest) is [`3.10.1`](https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.10.1)
* ref: https://github.com/ankidroid/Anki-Android/pull/16959

----

Thank you for the publisher! I understand this project is in maintenance mode and issues may not be seen

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/1088#issuecomment-2309346073. I'm waiting to hear back.

**Comment by SUPERCILEX** [comment]
Ok I published some release notes under a pre-release since there's not much reason to upgrade: https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.11.0
