### ISSUE TITLE
Option to use the same Title for all Languages

### ISSUE THREAD

**Issue by Nutomic** [Triple-T/gradle-play-publisher#115]
I don't want to use different app titles for each language, and I don't want to copy the title file to each folder.

It would be convenient to have a setting so that a single, hardcoded title is used for all languages. Alternatively, a title file directly in the play folder could be used for languages without an explicit title.

**Comment by shiraji** [comment]
Check this [comment](https://github.com/Triple-T/gradle-play-publisher/issues/107#issuecomment-152180124).

Please share the result. The comment says about `whatsnew` but it shoule work with `title`, too.

**Comment by Nutomic** [comment]
So I can just put the file in `src/main/play`? 

Unfortunately, I can't really test because I'm getting an error "Daily save quota exceeded." all the time. Is there a know solution to that, or should I open a new issue?

**Comment by shiraji** [comment]
If I understand correctly, you need a symlink for each directory.

For `Daily save quota exceeded`, check Google's official documentation https://developers.google.com/android-publisher/quotas . I don't think that is the problem with this library.

**Comment by SUPERCILEX** [comment]
Closing in favor of #107
