### ISSUE TITLE
GoogleJsonResponseException: 500 Internal Server Error

### ISSUE THREAD

**Issue by Nutomic** [Triple-T/gradle-play-publisher#120]
I'm getting this error whenever I run `gradle publishListingRelease`. I've tried multiple times within the last few days, but no change. The problem happens with the exact same descriptions that I could upload before.

Error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishListingFatRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
  {
    "code" : 500,
    "message" : null
  }

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
```

Full output of `gradle publishListingFatRelease --info`:
http://paste.ubuntu.com/14567088/

Edit: Permissions in Google Play are granted as described in the Readme.

**Comment by krishan711** [comment]
I have the same issue. Did you find a fix for it?

**Comment by bhurling** [comment]
Did you try to run the task without uploading the images?

**Comment by Nutomic** [comment]
I just tried with uploadImages = false, but I get the exact same error.

**Comment by bhurling** [comment]
I found something suspicious in that output file. You are trying to upload your images to a locale called `en-UK`. Your descriptions go into `en-GB` and you want to set `en-US` as the default language. `en-UK` doesn't exist on the Play Store and you don't provide descriptions for `en-US`. 

Can you reorganise your metadata so you only use `en-GB` everywhere?

**Comment by Nutomic** [comment]
Right, looks like I got something mixed up there. I fixed it by deleting my local files and running `./gradlew bootstrapFatReleasePlayResources` again. 

Would be nice if this plugin could print a clear warning in this case.

**Comment by hannesa2** [comment]
I fixed it in Play console. It shows me some errors with pricing for some countries. After I fixed it, the job was successful

**Comment by SUPERCILEX** [comment]
Since 500 is a server error and we don't know what the exact issue is either, there's not much more we can do.
