### ISSUE TITLE
Don't break if lowering the userFraction

### ISSUE THREAD

**Issue by rocboronat** [Triple-T/gradle-play-publisher#125]
Usually, we launch a version to 0.05% of the target and check them daily using Crashlytics. And we increase that porcentage daily. Usually, we're at 10%, and we decide to launch a hotfix to Google Play.

In that case, the publisher breaks, 'cause we're trying to lower the userFraction.

It's possible to only use this value when the rollout process is new? I mean, if we're at 10%, it's ok that the .APK goes to 10% instead of 0.05% of the target.

**Comment by EsteveAguilera** [comment]
+1

**Comment by SUPERCILEX** [comment]
This isn't something the plugin controls. However, v2.0 will support halting a release which is all the Play Store allows. Addressed in #291.
