### ISSUE TITLE
Is there a way to test the API manually?

### ISSUE THREAD

**Issue by bhargavms** [Triple-T/gradle-play-publisher#128]
Google has this hideous daily usage quota of only 1, I have done this 3days straight now make some change try to publish using the gradle task, I keep getting the 401 unauthorized error unfortunately the task doesnt report the google's json error, just 401 unauthorized is shown, Now I need to debug this manually using Curl or something but how to get around the daily usage quota to test this?

**Comment by bhurling** [comment]
Did you create your service account as described in https://developers.google.com/android-publisher/getting_started?

Maybe this ridiculous quota only kicks in for unauthorized requests from the same IP. I never had issues running multiple requests a day using proper authentication. I would suggest to reassure that all the permissions are set up correctly and you are using valid credentials.

There is also the API Explorer you could use to run some tests: https://developers.google.com/apis-explorer/#p/androidpublisher/v2/

**Comment by bhargavms** [comment]
Oops sorry I fixed this problem, my boss hadn't provided the Manage store listing permission, hence the publishListing task always failed with 401, I thought it was a problem with the gradle task configuration, he heard an earful from me though, I am going to close this issue now.

**Comment by bhargavms** [comment]
oh and thanks for the api explorer link!
