### ISSUE TITLE
Publishing multiple flavors

### ISSUE THREAD

**Issue by aexmachina** [Triple-T/gradle-play-publisher#129]
It's not clear to me what I need to do to get `publishApkPaidRelease` working. The [docs](http://tools.android.com/tech-docs/new-build-system/user-guide) indicate that I need to specify a `signingConfig` for the various `productFlavor`s, which I'm doing like so:

```gradle
  buildTypes {
    release {
      // loop over all flavors to set default signing config
      productFlavors.all { flavor ->
        flavor.signingConfig signingConfigs.release
      }
    }
```

But this still doesn't give me a `publishApkPaidRelease` task. I've tried a variety of different approaches, but it's still not working. Furthermore, `./gradlew assemblePaid` does work and produces both debug and release APKs.

I understand that that "In case you are using product flavors you will get one of the above tasks for every flavor. E.g. publishApkPaidRelease or publishListingPaidRelease", but it's not clear to me what the criteria are that need to be satisfied in order to be able to publish an APK. Maybe some more detail should be added to this statement?

Any advise would be greatly appreciated. Thanks.

**Comment by aexmachina** [comment]
I've just removed the flavours to try to get something working, and I still don't have a `publishApkRelease` task, only `publishListingRelease`.

**Comment by aexmachina** [comment]
I've just solved this issue. My `build.gradle` gets the `storePassword` and `keyPassword` from the environment (`storePassword System.getenv('KEYSTOREPWD')`) and I hadn't defined these environment variables. Maybe it would be better to generate an error in this case to indicate that the keystore couldn't be opened, rather than just not providing the tasks?

**Comment by bhargavms** [comment]
So if you were to hard code the passwords instead of getting from env variables, do you get the publishApkRelease task?

**Comment by aexmachina** [comment]
I'd say so. Once o defined the environment vars properly it all worked.

What I'm suggesting is that the plugin should provide some indication if it can't open the keystore.

**Comment by bhurling** [comment]
First of all, you usually don't have to run the loop to assign the signingConfigs to all flavors. BuildTypes and ProductFlavors are an orthogonal concept so it should be enough to just say

```
buildTypes {
    release {
        signingConfig signingConfigs.release
    }
}
```
That will affect all the flavors you defined.

As for the issue at hand: The plugin does not use the keystore itself nor should it be the plugin's task to validate the passwords. This is done by the `packageRelease` task during the regular build of the release APK. Without providing the proper passwords even `assembleRelease` would have failed in that setup, I guess.

In fact, the plugin even prints a warning during the configuration phase (before all the tasks are executed) if no signingConfig is set. This behaviour is mentioned in the readme as well.

There are a few special cases, though, where this approach reaches its limits. Let's assume your build script has some logic to only create a valid signingConfig once the password env variables are properly set. And if you don't specify the passwords the release build will just create an unsigned APK. To the plugin this looks as if there is no signingConfig at all. Thus, we don't create the publishApk task.

We could of course create all the publisher tasks and just don't care whether or not a signingConfig has been defined. But I am afraid that people will just try to upload unsigned APKs.

Do you have an idea of how to make the docs a bit more clear about this behaviour?

**Comment by aexmachina** [comment]
Right, okay that makes sense. Sounds like it's not simple to provide indication of this. Maybe just adding some text to the README that describes specifically what conditions might result in the `publish` tasks not being created - e.g. "`packageRelease` can't open the keystore" etc.
