### ISSUE TITLE
Support for merging play resources

### ISSUE THREAD

**Issue by jurenovic** [Triple-T/gradle-play-publisher#130]
Currently plugin supports merging of flavors, but if you have a multi dimensional flavors like `stagingFree`, `stagingPaid`, `productionFree` and `productionPaid`, then folders like `src/staging/play` or `src/production/play` are ignored.

**Comment by ivanove** [comment]
I had also 2 flavours but I put just **one** folder play in the main so even I change the build variant, the folder play is not ignored.

**Comment by SUPERCILEX** [comment]
We don't have plans to add support for dimensions. However, [multiple flavors](https://github.com/Triple-T/gradle-play-publisher#sample-tasks) are supported.

**Comment by SUPERCILEX** [comment]
Whoops, I misunderstood this feature request. We'll add support for more general play folders without needing to fully qualify the flavor.

**Comment by gtcompscientist** [comment]
I think we should allow for an alternate root for the files, right now the 'src/' part of the path is hardcoded. Thoughts?

**Comment by gtcompscientist** [comment]
Looking at how I would actually approach this, I think we should actually use the `variant.sourceSets` to build this list.

**Comment by SUPERCILEX** [comment]
Screenshot of what properties are available to us:
![image](https://user-images.githubusercontent.com/9490724/41070669-eefa3972-69a8-11e8-8a0e-8d5920ca1812.png)

**Comment by gtcompscientist** [comment]
What about multi-dimensional flavors?

**Comment by SUPERCILEX** [comment]
This issue is poorly named: the variants don't actually care about dimensions. Here's the code for that first case:
```groovy
project.android {
    flavorDimensions 'pricing'

    productFlavors {
        free {
            dimension 'pricing'
        }
        paid {
            dimension 'pricing'
        }
    }

    buildTypes {
        dogfood.initWith(buildTypes.release)
    }
}
```

**Comment by gtcompscientist** [comment]
No, that's a single `flavorDimension` with multiple `flavors`. What happens when you have more than one dimension to your `flavors`?

That's the case I'm trying to handle better, because if you have the following:
```
project.android {
    flavorDimensions 'pricing','server'

    productFlavors {
        free {
            dimension 'pricing'
        }
        paid {
            dimension 'pricing'
        }
        staging {
            dimension 'server'
        }
        prod {
            dimension 'server'
        }
    }
}
```

That's and the multiple source locations are the two big things I'm trying to understand and solve.

**Comment by SUPERCILEX** [comment]
Some thoughts so I don't forget them:
- Need to build two mappings:
  1. Build type -> list of flavors
  2. Flavor -> build types
- Incremental file changes in a node invalidates all children

If `main` changes, we need to invalidate everything. If something changes in the build type folder or flavor, we'll look at the mappings to find which children need to be invalidated. And of course, if the most specific folder changes, we just incrementally copy whatever changed.

Sample tree:
```
                                        main
              _ _ _ _ _ _ _ _ _ _ _ _ _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
            /                             |                              \
           |                              |                              |
         debug                         release                        dogfood
       _ _ | _ _                    _ _ _ | _ _ _                  _ _ _ | _ _ _
     /            \                /             \               /               \
    |              |               |              |              |               |
<paid, debug> <free, debug> <paid, release> <free, release> <paid, dogfood> <free, dogfood>
```

**Comment by SUPERCILEX** [comment]
@gtcompscientist Well lol, I guess that invalidates my thoughts above. Sigh. Here's what your mess looks like (that looks so damn painful):
```
variant.name=paidProdDebug, paidProdRelease, paidProdDogfood, paidStagingDebug, paidStagingRelease, paidStagingDogfood, freeProdDebug, freeProdRelease, freeProdDogfood, freeStagingDebug, freeStagingRelease, freeStagingDogfood
variant.baseName=paid-prod-debug, paid-prod-release, paid-prod-dogfood, paid-staging-debug, paid-staging-release, paid-staging-dogfood, free-prod-debug, free-prod-release, free-prod-dogfood, free-staging-debug, free-staging-release, free-staging-dogfood
variant.dirName=paidProd/debug, paidProd/release, paidProd/dogfood, paidStaging/debug, paidStaging/release, paidStaging/dogfood, freeProd/debug, freeProd/release, freeProd/dogfood, freeStaging/debug, freeStaging/release, freeStaging/dogfood
variant.flavorName=paidProd, paidProd, paidProd, paidStaging, paidStaging, paidStaging, freeProd, freeProd, freeProd, freeStaging, freeStaging, freeStaging
variant.versionName=1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
sources=
    [main, prod, paid, paidProd, debug, paidProdDebug],
    [main, prod, paid, paidProd, release, paidProdRelease],
    [main, prod, paid, paidProd, dogfood, paidProdDogfood],
    [main, staging, paid, paidStaging, debug, paidStagingDebug],
    [main, staging, paid, paidStaging, release, paidStagingRelease],
    [main, staging, paid, paidStaging, dogfood, paidStagingDogfood],
    [main, prod, free, freeProd, debug, freeProdDebug],
    [main, prod, free, freeProd, release, freeProdRelease],
    [main, prod, free, freeProd, dogfood, freeProdDogfood],
    [main, staging, free, freeStaging, debug, freeStagingDebug],
    [main, staging, free, freeStaging, release, freeStagingRelease],
    [main, staging, free, freeStaging, dogfood, freeStagingDogfood]
```

**Comment by SUPERCILEX** [comment]
So I've been thinking about this some more, and it looks like it should be somewhat manageable. A product flavor can only have one dimension which means this is the craziest possible combination:
```
[main, buildType1, flavor3, flavor1, flavor1Flavor3, flavor1Flavor3BuildType1]
```

So in the end, that means we cascade merges for that entire tree, except where `flavor1` and `flavor3` are concerned. If those to have two files that conflict, we'll have to blow up and say that we don't know which one should take precedence.

**Comment by SUPERCILEX** [comment]
Ok, I've got a [branch going](https://github.com/Triple-T/gradle-play-publisher/tree/muli-diem-merge) which is ready for me to do some TDD if anyone's curious.

**Comment by SUPERCILEX** [comment]
Hold up, all of the tests are passing!!!??? (Except for the throw on conflict one of course.) I'm trying to understand why I magically made this work, and I belive it comes from the changes I made the incremental PR. Because the AGP gives us sources in the correct cascading order and I'm using Gradle's copy task, everything is already taken care of for us. They did all the hard work! Now I just need to figure out if I magically made #107 work too. 😆

@gtcompscientist TL;DR: our work is done here! My [incremental PR](#308) takes care of this as a side effect. That just goes to show Gradle's API is pure brilliance if it automatically does this kind of stuff.

**Comment by gtcompscientist** [comment]
@SUPERCILEX Added one set of tests for multiple source sets, and the logic to handle it.
