### ISSUE TITLE
Support for uploading Proguard mapping files

### ISSUE THREAD

**Issue by peterhav** [Triple-T/gradle-play-publisher#132]
In the Google Play developer console it's now possible to upload a Proguard De-obfuscation Mapping File for apps in order to have readable stacktraces. This is currently a manual step to be performend which requires a lot of administration (for each APK version a separate dedicated mapping file is needed). It would be great if the gradle-play-publisher task would upload the mapping file together with the APK automatically (in my opinion this would not require any end-user input configuration, since it's known if pro-guard has been used and where the generated files are located).

_update_ Please star this issue in order to make this possible:  https://code.google.com/p/android/issues/detail?id=203432

**Comment by Alexander--** [comment]
This is a killer feature, managing those have always been a huge pain for me. Just storing somewhere all those multiple-Mb files is already a problem on it's own and one have to keep them up to date as well!

**Comment by ChristianBecker** [comment]
We have to check if the API supports this. Unfortunately, I don't have time right now, but feel free to file a PR :)

@bhurling FYI

**Comment by peterhav** [comment]
PR has been issued: https://code.google.com/p/android/issues/detail?id=203432

**Comment by radzio** [comment]
+1

**Comment by ChristianBecker** [comment]
Unfortunately we can't do anything without an API for this. So please star the referenced android issue ;)

**Comment by bhurling** [comment]
Starred it. Would be very helpful, indeed.

**Comment by ismail-s** [comment]
@Alexander-- In the meantime, you could store the mapping files as build artifacts in whatever CI you use. I know circleci support this, as I use this. Don't know about other ci providers.

**Comment by supercairos** [comment]
Hi, can this API be used ? https://developers.google.com/android-publisher/api-ref/edits/deobfuscationfiles

**Comment by clhols** [comment]
I have implemented it and added a pull request here:
https://github.com/Triple-T/gradle-play-publisher/pull/179

**Comment by madsthom** [comment]
Support the community! - Thanks @clhols.

**Comment by bobvanderlinden** [comment]
For anyone that wants to use this right now see https://github.com/Triple-T/gradle-play-publisher/pull/179#issuecomment-271300562

**Comment by hardysim** [comment]
I'm having a relating problem uploading the mappings to Firebase Crash Reporting. Maybe we can combine the two needed mapping-uploads!?

See #186

**Comment by bhurling** [comment]
This is available now in version `1.2.0-beta2`. Let me know if you run into issues
