### ISSUE TITLE
The content of defaultLanguage is not trimmed

### ISSUE THREAD

**Issue by RazZziel** [Triple-T/gradle-play-publisher#143]
A lot of text editors (i.e. vim) automatically append a newline at the end of a file. This makes `./gradlew publishListingRelease` fail after editing `defaultLanguage` with this error:

```
:app:publishListingParkappStageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishListingParkappStageRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "The default language for your application is not currently supported.",
      "reason" : "invalidDefaultLanguage"
    } ],
    "message" : "The default language for your application is not currently supported."
  }
```

How to reproduce:
- `echo "es-ES" > app/src/main/play/defaultLanguage; ./gradlew publishListingRelease` **fails**
- `echo -n "es-ES" > app/src/main/play/defaultLanguage; ./gradlew publishListingRelease` **works**

**Comment by bhurling** [comment]
Next release
