### ISSUE TITLE
Grade android ionic build crashes when app is launched

### ISSUE THREAD

**Issue by nnadig123** [Triple-T/gradle-play-publisher#152]
Hi, I have an ionic android application where Uing the cradle play publisher to build and publish the app to the google play store  by using the puplicApkreleae command. Everything builds fine on the Mac machine and uploads it the Google play store. When I launch the app on the phone it crashes. It happens on the debug build too? And idea as to how I can debug the issue? Thabks

**Comment by nnadig123** [comment]
Any help will be appreciated.

**Comment by bhurling** [comment]
Did you try to manually upload the APK. Or even to just `adb install` your APK? Do you see the same issue?

**Comment by nnadig123** [comment]
Yes it crashes .. I am using a different plugin now

Nandini

On Aug 9, 2016, at 1:53 AM, Bj?rn Hurling <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you try to manually upload the APK. Or even to just adb install your APK? Do you see the same issue?

-
