### ISSUE TITLE
Add to Gradle Plugins Repository

### ISSUE THREAD

**Issue by jaredsburrows** [Triple-T/gradle-play-publisher#154]
Please add to https://plugins.gradle.org.

**Comment by jaredsburrows** [comment]
@bhurling Any update on this?

**Comment by jaredsburrows** [comment]
And update?

**Comment by jmfayard** [comment]
You don't need necesarily to publish to the gradle plugins repository. 

`Plugins fetched from a source other than the Gradle Plugin Portal may or may not be usable with the plugins {} block. It depends on how they have been published.`

See https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#declarative-scripts

What I care is that I can use the better syntax with the kotlin DSL, not where there are published

**Comment by SUPERCILEX** [comment]
Just letting you guys know that the plugin can already be used with the better DSL syntax: declare the classpath and then the ID in the `plugins` block without a version.

**Comment by eriwen** [comment]
Let me know if you need any further help with this folks.

**Comment by SUPERCILEX** [comment]
@bhurling didn't you say something about not getting credentials in our internal discussion? @eriwen might be able to speed the process along.

**Comment by SUPERCILEX** [comment]
Drum roll 🥁🥁🥁... This has finally been implemented! The first release on the plugins repo is [v2.0.0-rc2](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-rc2).
