### ISSUE TITLE
ResponseException: 401 Unauthorized

### ISSUE THREAD

**Issue by viniciusoh** [Triple-T/gradle-play-publisher#155]
Hello, 

I've started to used this plugin today and I'm currently having this issue when I try to use any command (publishApkRelease, bootstrapReleasePlayResources) from this plugin:
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized

It looks like something from google, but I've followed the Getting Started steps and everything went as described. The only issue was that, currently, the permission page looks a bit different, but the itens are the same. 
I've also tried to authenticate with both JSON and P12 files, but neither seemed to work.
Even with --stacktrace or --debug I could't find any relevant information.

Does anyone knows what might be causing it? Or maybe any way to check where might be the problem?

Thanks in advance,

**Comment by knzwats** [comment]
Im not trying to be a dick, but did you add your application to your publisher account?

Check "Settings -> User accounts & rights -> Users with access", click the gear icon, "Change permission -> Add an app".

I made the same mistake and it got me for a while.
Hope it helps!

**Comment by bhurling** [comment]
Looks like they added a new permission called "Visibility". Maybe that one has to be enabled as well.

We should update the README btw.

**Comment by bhurling** [comment]
This is what I have enabled:

<img width="580" alt="permissions" src="https://cloud.githubusercontent.com/assets/242983/17809992/95ea4eaa-661a-11e6-9879-521df4f14735.png">

**Comment by bhurling** [comment]
Readme is updated with the latest screenshot
