### ISSUE TITLE
Upload different flavours of my app to the store

### ISSUE THREAD

**Issue by pixelbendr** [Triple-T/gradle-play-publisher#156]
Hello, I have 3 flavours of my app beta, dev and prod. I want to have my users install both beta and prod on their phones via play store. How can I achieve this?

**Comment by bhurling** [comment]
1. Your flavours should have different application ids. Usually, this is done by specifying the `applicationId` parameter in your build flavour
2. If you want to provide different metadata per flavour you can drop it into `src/{flavourName}/play`. If you don't need that, drop everything into `src/main/play`
3. The plugin creates separate tasks for publishing the flavours called `publish{flavourName}ApkRelease` and `publish{flavourName}ListingRelease`

That should be all you need. Let me know if you need more help

**Comment by pixelbendr** [comment]
Thanks for this.
