### ISSUE TITLE
Publish APK without listing - FileNotFoundException

### ISSUE THREAD

**Issue by Dean79000** [Triple-T/gradle-play-publisher#163]
I publish APK only (without listing)

```
apply plugin: 'com.github.triplet.play'
play {
    serviceAccountEmail = 'myemail'
    pk12File = file("path-to-mycert")
    track = 'production'
}
```

When i run task `"publish<Flavor>Release"`, the build fail

```
:app:publish<Flavor>Release
:app:publishListing<Flavor>Release FAILED  
java.io.FileNotFoundException: [...]app/build/outputs/play/<Flavor>Release
```

But if i create empty folder "src/main/play" build is successful. I expect to have successful build without create this folder.

Tested in version 1.1.5

**Comment by bhurling** [comment]
You could only run publishApk<Flavor>Release to work around that issue.
That way the listing task won't be executed. But you have a point there. An
non-existing play folder should be treated the same as an empty one.

**Comment by damianpetla** [comment]
I also have this error but I checked that APK was successfully uploaded to GooglePlayConsole

**Comment by RyotaMurohoshi** [comment]
I failed publishListingRelease task with FileNotFoundException in CI environment.

I think this issue may be related to this issue.

https://github.com/Triple-T/gradle-play-publisher/issues/180

**Comment by clhols** [comment]
Created pull request here:
https://github.com/Triple-T/gradle-play-publisher/pull/184
