### ISSUE TITLE
publishApkRelease task missing (using com.android.tools.build:gradle:2.2.0-rc2)

### ISSUE THREAD

**Issue by yukuku** [Triple-T/gradle-play-publisher#166]
It's similar to #157 but now Android Studio 2.2 is already at RC2.

I also want to thank you for your library, this has been very useful.

**Comment by outlying** [comment]
It seems that it happened after buildToolsVersion upgrade. I was able to release my app yesterday but today, after some tweaks and version upgrades, I am missing release task

**Comment by vonox7** [comment]
I can confirm that the gradle update from 2.1.3 to 2.2.0 (as the now released Android Studio 2.2 suggests) removes the two tasks:

### Gradle 2.1.3
bootstrapReleasePlayResources
generateReleasePlayResources
publishApkRelease
publishListingRelease
publishRelease

### Gradle 2.2.0
bootstrapReleasePlayResources
generateReleasePlayResources
publishListingRelease

**Comment by sasvarizoli** [comment]
+1

**Comment by christianlanz** [comment]
+1

**Comment by papauschek** [comment]
+1

**Comment by ShagunParikh** [comment]
+1
Solved by updating 'com.github.triplet.gradle:play-publisher:1.1.4' to **1.1.5**.
Gradle version is **2.2.0**

**Comment by doubleo2** [comment]
I think this is a dupe of #145
