### ISSUE TITLE
Upload only if Local App version is higher than app version in Play Store

### ISSUE THREAD

**Issue by tridib** [Triple-T/gradle-play-publisher#168]
I want to automate the App upload to Play store through Jenkins. I was wondering if this plugin can upload only if there is a version upgrade. Right publish tasks fail if version is same. If there a way to configure the plugin to check the version in play store and upload if current version is higher than that of play store?

**Comment by SUPERCILEX** [comment]
Question for the community: should not uploading the APK if there's a conflict be the default or should automatically upgrading the version code be the default?

**Comment by gtcompscientist** [comment]
I would say not uploading is better. And how the task is managed after that is what becomes important. But, it could easily be a configuration
Options of:
- fail task (default)
- warn (log a warning for the user to see, but continue)
- ignore (skip the task entirely)

**Comment by gtcompscientist** [comment]
As a follow-up, the idea of a warning, with no upload would have a good use case for batching uploads where something fails halfway through (lost internet, whatever) and you have to restart.
