### ISSUE TITLE
Unable to install this plugin in android studio

### ISSUE THREAD

**Issue by stevenshichn** [Triple-T/gradle-play-publisher#170]
Hi,

I am working on the publisher and follow the steps. However, when I try to install plugin with gradle-play-publisher-master.zip file in Android Studio. It fail and following is the screen shot. Can someone help me work out this issue? Thank you.
![fail to install plugin](https://cloud.githubusercontent.com/assets/22338923/18700008/4d2b6044-8007-11e6-8860-0444e6644625.png)

**Comment by chrissd23** [comment]
You haven't got to do that. 
Look at the readme under point Usage. Hope it helps.

**Comment by stevenshichn** [comment]
Thank you very much. But when I add the "apply plugin" and classpath. Android studio can't compile. It says no cache version of the "com.github." Anything I need to do before I add those statement in build.gradle?

**Comment by chrissd23** [comment]
Check you android studio settings ... ? Preferences -> Build Tools -> Gradle 

There is a point where you can enable or disable offline work ...try to disable it

**Comment by stevenshichn** [comment]
I disabled offline work. But it still throw this error and compilation is very slow

**Comment by ChristianBecker** [comment]
@stevenshichn : Can you post your `build.gradle`? If it contains sensible data, remove it first. It's also a good idea to remove all other plugins / custom tasks, too, to reduce the scope.

**Comment by ChristianBecker** [comment]
It's working for me.
