### ISSUE TITLE
How to use this plugin in android studio

### ISSUE THREAD

**Issue by stevenshichn** [Triple-T/gradle-play-publisher#171]
Hi there,

Sorry, I am new in android development. May I ask anyone can tell me how to use this useful plugin into android studio? Because I add in the classpath and try to compile, it fail and said: 

Error:No cached version of com.github.triplet.gradle:play-publisher:1.1.5 available for offline mode.

How to solve it?

Thank you

**Comment by ValiDraganescu** [comment]
I guess you need to be connected to internet while building

**Comment by ChristianBecker** [comment]
If you don't have a (cached) version in your local maven repo, it will fail with this exact error. Try switching to "normal" (online) mode and try again.
