### ISSUE TITLE
Pre-launch report didn't start

### ISSUE THREAD

**Issue by dzinek** [Triple-T/gradle-play-publisher#173]
It seems that after publish my APK to Alpha channel, pre-launch tests didn't starter.

Every previous versions published via WebConsole started the tests, but when I used gradle task - there were no tests.

**Comment by gabrielittner** [comment]
That's not an issue with the plugin 

> If you uploaded your alpha or beta APK with the Publishing API, you won't receive a pre-launch report.
https://support.google.com/googleplay/android-developer/answer/7002270

**Comment by dzinek** [comment]
Ok, I didn't know that.
Thanks.
