### ISSUE TITLE
Error trying to publish apk for alpha

### ISSUE THREAD

**Issue by thalissondev** [Triple-T/gradle-play-publisher#175]
I'm trying to send my apk for alpha but I am in error, when there is a apk on google play console with a particular versionCode and try to upload the same versionCode works, but when I increase the versionCode does not work. Following error:

```
Total time: 38.713 secs
Build step 'Invoke Gradle script' changed build result to SUCCESS
Found APK file with version code 8: app/build/outputs/apk/app-release.apk
Authenticating to Google Play API...
- Credential:     Credencials Google Play
- Application ID: br.com.thalisson.dagger
Assigning 1 APK(s) with application ID br.com.thalisson.dagger to alpha release track
Could not assign APK(s) 8 to alpha, as these APKs do not exist: 8
ERROR: APK assignment failed
Skipping upload to Google Play due to build result
Finished: FAILURE
```

In this case, I'm trying to send a new version of the alpha, I just incrementei the versionCode and tried to publish.

**Comment by bhurling** [comment]
@thalissondev do you still see this issue? Can you explain how you are using the plugin? These log lines do not look like they are generated by this gradle plugin.

**Comment by SUPERCILEX** [comment]
Closing due to lack of response. Feel free to reopen if you're still running into this issue.
