### ISSUE TITLE
Invalid JWT Signature.

### ISSUE THREAD

**Issue by razzium** [Triple-T/gradle-play-publisher#176]
Hi,

I've made all steps but when I launch "./gradlew publishApkRelease" the response is : 

com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
  {
    "error" : "invalid_grant",
    "error_description" : "Invalid JWT Signature."
  }

Could you say me what I do wrong ?

Thanks.

**Comment by butterklopsi** [comment]
got the same problem, too.

**Comment by razzium** [comment]
Hey,

I solved my problem but forget to post solution here and closed this issue...
Unfortunately i don't remember how but here is my working gradle config : 

//APP
buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.github.triplet.gradle:play-publisher:1.1.5'
    }
}
...
...
...
apply plugin: 'com.github.triplet.play'
play {
    jsonFile = file('../publishKey.json')
    track = 'production'
}
(end of file)

//Project
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

Hope it helps.

**Comment by butterklopsi** [comment]
later i solved it, too. i thing the problem was that i took the wring was to get the json file. folowing the described way it worked. i also had to put the singingConfigs bevor the buildscrpit.release config.

**Comment by razzium** [comment]
Ok cool.
I close the issue.
