### ISSUE TITLE
[feature request] upload apk skip build

### ISSUE THREAD

**Issue by qiyulan** [Triple-T/gradle-play-publisher#177]
I meet some problem that build server does not have internet accsee,and pulish server dose not have Android SDK(and less of memory & disk).
The CI server will transfer apks(and all other files) from builder to publisher.But this plugin does require building again.
Can you add a gradle task that  accept signed apks and just upload it to Google play?

**Comment by johnhearn** [comment]
This would also be useful in a continuous delivery pipeline where the build sequence is divided into separate stages - build, test, publish, etc.

**Comment by giovannicandido** [comment]
I'm on the same use case. My project is not a full gradle project, is build with Nativescript, one case is to build the signed apk and use this plugin just to upload the file

**Comment by punksta** [comment]
you can use https://github.com/fastlane/fastlane/tree/master/supply for it.

**Comment by bhurling** [comment]
Yep, @punksta. In fact, fastlane is a great toolset and it should perfectly fit this use case. As this plugin serves a different purpose I am closing this issue.
