### ISSUE TITLE
Only one apk from splited is uploaded to Google Play

### ISSUE THREAD

**Issue by MastAvalons** [Triple-T/gradle-play-publisher#178]
Plugin uploads only apk with version 760154 but I have 5 different abis. All configs same as for default sample similar to this https://developer.android.com/studio/build/configure-apk-splits.html
may be you can provide advice or idea what I'm doing wrong

**Comment by dcvz** [comment]
It was added in 1.2.0-beta1, you can see it in a previous thread: https://github.com/Triple-T/gradle-play-publisher/issues/39

**Comment by MastAvalons** [comment]
Thank you!
