### ISSUE TITLE
Support image downloading in bootstrap task

### ISSUE THREAD

**Issue by bhurling** [Triple-T/gradle-play-publisher#18]
This is a leftover from #14. Currently the API only supports downloading thumbnail versions of the play store graphics. We should file a feature request somewhere (maybe [here](https://code.google.com/p/google-api-java-client/)). 

As soon as we get the original-sized images via the API we can enable this feature.

**Comment by ChristianBecker** [comment]
The feature request moved to GitHub: google/google-api-java-client#916

**Comment by gtcompscientist** [comment]
Investigated this on v3, and it's still downloading adjusted images (scale varies based on the image).

**Comment by SUPERCILEX** [comment]
Gonna close this since there really isn't anything we can do. The [API](https://developers.google.com/android-publisher/api-ref/edits/images/list#response) simply doesn't offer any alternatives.

**Comment by ChristianBecker** [comment]
Fine by me, we can always reopen this issue once the feature request google/google-api-java-client#916 is implemented.
