### ISSUE TITLE
upload mappings.txt to Firebase Crash Reporting

### ISSUE THREAD

**Issue by hardysim** [Triple-T/gradle-play-publisher#186]
I'm using Firebase Crash Reporting and want to upload the `mappings.txt` automatically on each publish to the PlayStore.

https://firebase.google.com/docs/crash/android#uploading_proguard_mapping_files_with_gradle

---

When I get it right, the mappings are always re-generated when a `gradlew build` is performed, right? So I cannot use `./gradlew :app:firebaseUploadReleaseProguardMapping` (because this would generate an othe mapping as the one used on the APK uploaded to the Play Store).

There is `firebaseUploadArchivedProguardMapping` which allows to set `FirebaseCrashMappingFilePath` which seems like a good idea (let gradle-play-publisher generate the APK + mapping and use this mapping for firebase as well) but it seems that I **must** provide `FirebaseCrashVersionCode` and `FirebaseCrashPackageName` as well.

As I'm using the GitLab CI Runner where the actual gradle-call is defined in its yml-file, I have no idea how to get these values dynamically (especially the versionCode which is using a environment-variable from the build-system (`versionCode System.getenv("CI_BUILD_ID")`).

---

Is there any way to combine gradle-play-publisher and Firebase Crash Reporting?

**Comment by bhurling** [comment]
Have you tried to set up task dependencies? You can add something like at the end of your gradle file:

```groovy
publishApkRelease.dependsOn firebaseUploadReleaseProguardMapping
```

That way the build task should only be run once. There will only be one APK with one mapping that will be used both for uploading to the Play Store and for firebase.

Maybe it's even enough to just run both tasks in the same gradle shell command:

```
./gradlew firebaseUploadReleaseProguardMapping publishApkRelease
```

gradle makes sure that within one command tasks are only run once.

**Comment by hardysim** [comment]
In the meantime I've discovered that the `mapping.txt` does not change when no `gradle clean` is involved. So build + publish via gradle-play-publisher and build + mapping-upload via firebase work fine together.

It would be great to have just one command though...

**Comment by bhurling** [comment]
Then you should try the `.dependsOn` trick. When it is set up correctly, you should be able to just call `publishApkRelease` and it will push the mapping file and upload the APK in one go.
