### ISSUE TITLE
`dependsOn` wrong task

### ISSUE THREAD

**Issue by chrisjenx** [Triple-T/gradle-play-publisher#189]
I'm not sure if this is a bug or intentional. When working with split apk's and the 1.2.0-beta1 build, it will build and upload all the varients (great! 👍 ). But the problem is, the task depends on the individual assemble commands, for example:

```
Pub Deps: task ':controller:assembleAmcrestProdX86_64Release'
Pub Deps: task ':controller:generateAmcrestProdReleasePlayResources'
Pub Deps: task ':controller:assembleAmcrestProdX86Release'
Pub Deps: task ':controller:assembleAmcrestProdArm64-v8aRelease'
Pub Deps: task ':controller:assembleAmcrestProdArmeabi-v7aRelease'
```

Now this would be fine, but other plugins that are looking for `assemble(${flavour})Release` tasks are broken. Again for example Fabric looks for:

```
Upload Deps: task ':controller:assembleAmcrestProdRelease'
```

It could be argued this is an issue with other plugins. But it's weird for anyone when doing a release/publish to only upload one ABI.

If you can point me to where the plugin is doing the `dependsOn` I can tweak this (Haven't done any gradle plugin development).

(Potentially related to: #186 )

**Comment by gabrielittner** [comment]
Here's the line :) https://github.com/Triple-T/gradle-play-publisher/blob/master/src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy#L103

**Comment by chrisjenx** [comment]
yeah so this:
```
 variant.outputs.each { output -> publishApkTask.dependsOn output.assemble }
```

Should simply be:
```
publishApkTask.dependsOn (variant.assemble)
```

Should be no need to depend on each output as the android-plugin will handle assembling all of the abi's for you.

**Comment by ChristianBecker** [comment]
This is fixed in the latest master and will be released with the next beta release
