### ISSUE TITLE
Error:ProductFlavor with name 'XXX' not found.

### ISSUE THREAD

**Issue by gdemiollis** [Triple-T/gradle-play-publisher#193]
Hi,

Since beta3, I have this Error :

```Error:ProductFlavor with name 'remoteProd' not found.```

In my project, I use different flavors dimension

```groovy
flavorDimensions "mock", "server"

    productFlavors {
        mock {
            dimension "mock"
        }
        remote {
            dimension "mock"
        }
        local {
            dimension "server"
        }
        preprod {
            dimension "server"
        }
        prod {
            dimension "server"
        }
    }
```

My variants are
   - remoteProdRelease
   - remoteProdDebug
   - remotePreprodRelease
   - remotePreprodDebug
   - mockLocalDebug

I don't have this error in beta2

**Comment by bhurling** [comment]
Looks like it's related to having multiple flavor dimensions. I'll write some tests to see what's going on

**Comment by bhurling** [comment]
@brp-david looks like `project.android.productFlavors[variant.flavorName].playAccountConfig` can't handle multiple flavor dimensions. Any idea how to fix that?

**Comment by brp-david** [comment]
I'll look into it, but a quick guess the playAccountConfig has to be stored on the composite flavor name somehow.

**Comment by bhurling** [comment]
I added a failing test: https://github.com/Triple-T/gradle-play-publisher/tree/fix-service-accounts-for-dimensions

**Comment by bhurling** [comment]
@gdemiollis If you don't need multiple service accounts you might want to fall back to beta2 in the meantime

**Comment by gdemiollis** [comment]
Thank you, that's what I will do.

**Comment by ChristianBecker** [comment]
This is fixed in the latest `master` and will be released with the next `beta` release
