### ISSUE TITLE
Support setting google play track using environment variable

### ISSUE THREAD

**Issue by ireneduke** [Triple-T/gradle-play-publisher#198]
I'm hoping to set the Google Play track to publish the apk to using an environment variable. This would allow me to configure CI to publish to the alpha track on commits to an alpha branch and to publish to beta track on commits to a beta branch. When I try doing this currently, I get an error which says `Track has to be one of 'alpha', 'beta', 'rollout' or 'production'.`

**Comment by bhurling** [comment]
Looks like Gradle is not picking up your environment variable. Can you post how you're setting it? Especially in Jenkins it can be a bit tricky to have environnent variables available in your scripts

**Comment by ireneduke** [comment]
I have the following in my build.gradle:
```
play {
  track = System.getenv("PUBLISHER_TRACK")
  serviceAccountEmail = System.getenv("PUBLISHER_EMAIL")
  pk12File = file('publisher_key.p12')
}
```
I'm not using Jenkins. I use CircleCI. I started by using an environment variable for just the email and  that worked great. The environment variable for the email is picked up on CircleCI. But since I added an environment variable for the track, the code doesn't compile locally.

**Comment by ireneduke** [comment]
@bhurling I got the project to compile locally by executing `launchctl setenv PUBLISHER_TRACK alpha` in a command line, but I don't want to require other developers to set this environment variable on their machines when it is only required on our CI server.

**Comment by bhurling** [comment]
I see. You can do the following trick:

```groovy
play {
    track = System.getenv("PUBLISHER_TRACK") ?: 'alpha'
}
```

It's the groovy way of saying: use the environment variable or just set alpha if it's empty.

**Comment by ireneduke** [comment]
@bhurling Thanks for the response and all your work on this code.
