### ISSUE TITLE
Specify in README which permissions must be given in API access

### ISSUE THREAD

**Issue by hzsweers** [Triple-T/gradle-play-publisher#20]
Preferably we would like to only use the permissions we need, but currently we only ever get `401 Unauthorized` failures. Could you provide any insights regarding to this? Specifically which permissions are necessary and maybe consider specifying them in the README for future users.

**Comment by bhurling** [comment]
The issue on Google Code has been moved to Done. I don't think there is anything left we can do about it so I updated the README with the required permissions.

**Comment by hzsweers** [comment]
yeah I guess we'll just have to hope they improve this in the future.
Thanks for looking into it and filing for he issue!
