### ISSUE TITLE
Remove the check for debuggable flag

### ISSUE THREAD

**Issue by Alexander--** [Triple-T/gradle-play-publisher#206]
Your plugin has the [following check](https://github.com/Triple-T/gradle-play-publisher/blob/cf7d893bba10/src/main/groovy/de/triplet/gradle/play/PlayPublisherPlugin.groovy#L33):

    if (variant.buildType.isDebuggable()) {

It might have bee added with good intentions, but please remove it: Google Play does much better job communicating with people than this plugin.

I have spent a lot of time debugging issues with non-existing publish tasks, until finding this line in your source code. Writing to log with disabled-by-default debug level certainly does not help.

**Comment by SUPERCILEX** [comment]
This check is intentional and here to stay since the Play Store won't let you upload debug builds anyway.

Sorry about not being responsive, we're working to fix that. 😊
