### ISSUE TITLE
whatsnew file ignored, not updating in Google play store

### ISSUE THREAD

**Issue by dmsierra11** [Triple-T/gradle-play-publisher#213]
I have the file structure as it says in the documentation, and everything uploads fine but the `whatsnew`. What could be happening?

I've tried 
`publishApkRelease`
`publishListingRelease`
`publishRelease`

<img width="734" alt="screen shot 2017-05-11 at 11 55 47 pm" src="https://cloud.githubusercontent.com/assets/2533919/25973738/b2717d76-36a5-11e7-8119-ff7318c421bc.png">

<img width="962" alt="screen shot 2017-05-12 at 12 00 06 am" src="https://cloud.githubusercontent.com/assets/2533919/25973820/174aca5e-36a6-11e7-85a8-bb3c7ab3ec05.png">

**Comment by 07steven01** [comment]
Same here. This has been the case since the release of the new developer play store console.

**Comment by Ilaeria** [comment]
I have found that if I'm replacing an existing pending APK (e.g. if I already have a pending Alpha release and I try to publish a new one) the whatsnew doesn't update. If it is creating a brand new release, the whatsnew will update.

**Comment by claucookie** [comment]
In my case it doesnt update even if it is a brand new beta/alpha. 
Is it something you are looking into?

**Comment by VictorJava** [comment]
Hi, I have the same issue...

**Comment by claucookie** [comment]
Is this gonna be investigated? Please, in my company we are depending on this and if the new google play store not gonna be supported, please let us know in order to choose another plugin.

**Comment by bhurling** [comment]
@VictorJava @claucookie Is this still an issue? I haven't been able to reproduce it

**Comment by SUPERCILEX** [comment]
Closing due to lack of response.
