### ISSUE TITLE
Publish fails but the build is actually published

### ISSUE THREAD

**Issue by modislaszlox2** [Triple-T/gradle-play-publisher#214]
Hello,

I get the following error when trying to publish an app:
```json
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "This app does not have a default language set.",
      "reason" : "noDefaultLanguage"
    }, {
      "domain" : "androidpublisher",
      "message" : "This app does not have a contact email address set.",
      "reason" : "noEmail"
    } ],
    "message" : "This app does not have a default language set."
  }
```

The apk is actually published and both default language and contact email is set correctly. I'm using the latest version(1.2.0).

Plugin configuration:

```gradle
play {
    track = 'production'
    untrackOld = true
    uploadImages = true
    jsonFile = file(".." + File.separator + "certificate" + File.separator + "zzz.json")
}
```

**Comment by daniele-athome** [comment]
I solved that by adding defaultLanguage and contactEmail files.

**Comment by Tapchicoma** [comment]
@daniele-athome can you close this issue then?

**Comment by daniele-athome** [comment]
My solution is actually a workaround, besides I don't have the permissions to close the issue.

**Comment by SUPERCILEX** [comment]
@modislaszlox2 Are you still running into this issue?

**Comment by modislaszlox2** [comment]
@SUPERCILEX I don't remember what was the issue or how I fixed it but it's working now so issue can be closed.

**Comment by gtcompscientist** [comment]
Let us know if it resurfaces.
