### ISSUE TITLE
Need a way to block targetSdkVersion upgrade

### ISSUE THREAD

**Issue by alexanderkjeldaas** [Triple-T/gradle-play-publisher#215]
Upgrading targetSdkVersion has mostly devastating effects on the application.  I publish all PR builds to the alpha channel, but I need a way to block any change to this field by accident.

Is there a way I can check this before publishing?

**Comment by SUPERCILEX** [comment]
No, the plugin doesn't check for that. Since you have to manually change the `targetSdkVersion`, I don't see a need for this plugin to add that kind of feature. Feel free to reopen if you have other concerns.
