### ISSUE TITLE
Support Wear 2.0 Apk uploads

### ISSUE THREAD

**Issue by danh32** [Triple-T/gradle-play-publisher#217]
We have a Wear 2.0 apk that we have to upload along with each regular phone apk release we do. I'm not sure the best way to support this case, as these apks are generated from different modules in our project. I've configured the plugin for each module, but what seems to happen is the second apk upload deactivates the previous one:

![screen shot 2017-05-25 at 1 15 22 pm](https://cloud.githubusercontent.com/assets/447085/26475089/25b76060-416a-11e7-9cca-804645777c4e.png)

So in my case, `gradlew publishApkRelease` runs `wear:publishApkRelease` first and successfully uploads version code `23612`. Right after this, `app:publishApkRelease` runs and uploads version code `23611`, deactivating the wear apk.

**Comment by saschpe** [comment]
Same here, would like to see a solution as well

**Comment by rocboronat** [comment]
+1 here... A link for newcomers (like us): https://developer.android.com/training/wearables/apps/packaging.html

**Comment by EsteveAguilera** [comment]
+1!

**Comment by SUPERCILEX** [comment]
I see a few options here:
- With the current plugin, you could create product flavors and split your app out into wear and app folders.
- Once v2.0 comes out, there will be support for creating drafts that aren't published right away. The wear module could be in draft mode and the app module could finish up the publishing:
  ```groovy
  play {
      // ...
      releaseStatus = "draft"
  }
  ```
  In the meantime, [snapshot builds](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#snapshot-builds) are available.

**Comment by ItsCalebJones** [comment]
@SUPERCILEX - can you give an example of how to configure this use case? In my case there is a :mobile and :wear module that both have bundles generated with bundleRelease.

**Comment by SUPERCILEX** [comment]
@ItsCalebJones To be completely honest, I have a very limited understanding of how Wear OS artifacts are built and published. If I recall correctly, the idea is follow [this guide](https://github.com/Triple-T/gradle-play-publisher#combining-artifacts-into-a-single-release). You want to set the `commit` property to false for one of your artifacts and true for the other. That tells GPP to append artifacts to the current play store edit instead of wiping everything out and starting fresh. Please let me know how that goes!

**Comment by ItsCalebJones** [comment]
@SUPERCILEX - so here's how it works.

In one project directory I have multiple modules for simplicity i'll combine most into a :common library thats shared between both of the main app modules, there is a :mobile module and a :wear module. When I go to create a release bundle/apk from the root of the project I usually simply run `./gradlew assembleBundle' this in essence runs both './gradle :mobile:assembleBundle' and './gradle :wear:assembleBundle'.

In each corresponding module/build/output there will be a mobile.aab and a wear.aab that I then sign and upload. For now i've found that I can do the following.

wear/build.gradle
```
play {
    serviceAccountCredentials = rootProject.file("publisher-key.json")
    track = "internal"
    releaseStatus = "completed"
    commit = false
}
```

mobile/build.gradle
```
play {
    serviceAccountCredentials = rootProject.file("publisher-key.json")
    track = "internal"
    releaseStatus = "completed"
    commit = true
}
```

And then invoke in order like this -> `./gradlew :wear:publishBundle :mobile:publishBundle --track=internal` ... its not the cleanest to look at but it works.

Source: https://github.com/ItsCalebJones/SpaceLaunchNow-Android/tree/build/SLN-A_Play_Publisher

**Comment by SUPERCILEX** [comment]
@ItsCalebJones Yup, that's the idea. To ensure things work properly, you'll want this stuff in the root project build file:
```kt
gradle.projectsEvaluated {
    project(":mobile").tasks.matching { it.name.startsWith("publish") }.configureEach {
        mustRunAfter(project(":wear").tasks.matching { it.name.startsWith("publish") })
    }
}
```

Then you can just run `./gradlew publishBundle` and it should work.

**Comment by hannesa2** [comment]
Has someone a running example to publish a wear and a mobile apk together to play store ?
I publish with
`./gradlew :wear:assembleRelease :wear:publishApk :app:publishBundle -Dorg.gradle.project.track=alpha`
I do this commit work:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/3314607/218327765-cf77fe10-650f-439e-b5fd-d96efe1613b2.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/3314607/218327799-495c61e6-7dfb-463f-86c1-00c959444066.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/3314607/218327817-b8ff2fda-226f-412a-b1d0-3e4e8263991d.png">

Both are successful uploaded to PlayStore, but when I install and run app, nothing happens on wear. On wear nothing appears.
Here https://developer.android.com/training/wearables/packaging#distribution this never happens. Both are using same signing and versionCode differs.
Does someone has an idea what I'm missing ?
