### ISSUE TITLE
Better warning when attempting to uploading debuggable builds

### ISSUE THREAD

**Issue by sebirdman** [Triple-T/gradle-play-publisher#219]
I recently changed my flavors and buildtypes around and accidently left "debuggable true" on the release builds, when i typed

./gradlew tasks

the release builds still showed up in the list and i was left wondering why actually running the task led to a message that the task didn't exist.

It would be nice to have a message that lets us know why the task fails to run.

**Comment by sebirdman** [comment]
if i have some time i'll dig into this myself and see if there's any way to fix it.

**Comment by SUPERCILEX** [comment]
Moving discussion to #206.
