### ISSUE TITLE
Improve support for 3P translation tools

### ISSUE THREAD

**Issue by eighthave** [Triple-T/gradle-play-publisher#227]
We've been using Weblate and Transifex to work with translators for our app strings for years now.  It can really make it dead simple to work with translators in many languages.  We've also been trying out techniques for doing the same with the app store descriptive materials, like what gradle-play-publisher manages.  The big problem is that the gradle-play-publisher file layout is quite difficult to integrate with translation tools:

* they expect a single file for source strings (not _title_, _fulldescription_, _shortdescription_, etc.)
* they work much better with real file formats like .po .xliff .json .yaml .xml rather than unstructured plain text
* char limits, notes to translators, etc. need to be in the source file (e.g .xliff)

Have there been any thoughts about how to integrate with standard translation workflows like these?  What are people using for translation when using gradle-play-publisher?

So far, the best "solution" I've seen feels like a workaround: managing the translations in a separate tree of XLIFF files, then having those files converted using a plugin.  This is a plugin for Fastlane Supply which handles these files in basically the same way as gradle-play-publisher:
https://github.com/danielkiedrowski/fastlane-plugin-onesky

**Comment by ypaiag** [comment]
Please add support also for lokalise.co

**Comment by SUPERCILEX** [comment]
Would supporting a standard-ish `strings.xml` file work? Something like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name" id="title">...</string>
    <string name="desc" id="shortDescription">...</string>
    <string name="long_desc" id="fullDescription">...</string>
    <string name="video_url" id="video">...</string>
</resources>
```

The directory structure would then look like this:
```
play/listings/
├── en-US/
│   ├── graphics/...
│   └── strings.xml
└── fr-FR/
    ├── graphics/...
    └── strings.xml
```

This [wouldn't be too hard](http://www.mkyong.com/java/how-to-read-xml-file-in-java-dom-parser/) actually, but supporting both the text files and the strings might be unpleasent.

@eighthave @peterhav what do you think?

**Comment by peterhav** [comment]
The above proposed looks good to me. But, if possible, I would prefer a hard convention for the string names, instead of a separate id field: a separate ID field will still require manual work since not all translations service allow to add extra custom field to the produced XML file.

**Comment by SUPERCILEX** [comment]
Ohhhhh, didn't think about that. I'm worried about ids conflicting though: `title` could be very common... I guess it's up to the translation services to figure that out.

**Comment by SUPERCILEX** [comment]
Huh, XLIFF looks way more complicated than what we have now so definitely not something for v2.0. Would be worth looking into though for a later release since our updated directory structure would support adding this in a backwards compatible manner.

**Comment by eighthave** [comment]
XLIFF works fine in its most basic state, so you could easily convert _strings.xml_ to XLIFF with only keys and values.  That means this:

```xml
<resources>
    <string name="app_name" id="title">Checkey: info on local apps</string>
    <string name="desc" id="shortDescription">utility for getting information about the APKs that are installed on your device</string>
</resources>
```

becomes this for the source file (e.g. English):
```xml
<xliff version="1.2">
  <file datatype="plaintext" original="source.xlf" source-language="en_US">
      <trans-unit id="app_name">
        <source>Checkey: info on local apps</source>
      </trans-unit>
      <trans-unit id="shortDescription">
        <source>utility for getting information about the APKs that are installed on your device</source>
      </trans-unit>
  </file>
</xliff>
```
And this for the translations:
```xml
<xliff version="1.2">
  <file datatype="plaintext" original="source.xlf" source-language="en_US"  target-language="de">
      <trans-unit id="app_name">
        <target>Checkey: Info über lokale Apps</target>
      </trans-unit>
      <trans-unit id="shortDescription">
        <target>genutzt um Informationen über die APKs zu bekommen auf deinem Gerät installiert</target>
      </trans-unit>
  </file>
</xliff>
```

The whole XLIFF standard is more complicated because it actually supports the whole translation workflow.  But there are lots of libraries and tools to work with it.  So handling it is not complicated, even when all the features are in use.  For example https://github.com/matecat/MateCat-Filters

**Comment by eighthave** [comment]
Or strip it down even more by using a simpler, static header: `<file datatype="plaintext">`

**Comment by SUPERCILEX** [comment]
Yeah, I mean the tough part is going to be getting an XML pipeline setup since we don't support that at all yet. We'll have to pull in some XLIFF parser library and process the listings differently depending on whether or not XLIFF is being used.

**Comment by eighthave** [comment]
You don't need an XLIFF parser library unless you want to do things with the extra data for the translator workflows.  You just need to parse the most basic XML elements to match `id="app_name"` then fetch `<target>` or `<source>` for the source file.

**Comment by eighthave** [comment]
This has some simple code to do that: https://github.com/lyncode/xliff-translate  I'd probably just take the little bit of needed code and include it directly in your code base.  It seems too small to deal with the hassle of adding a library dependency.

**Comment by eighthave** [comment]
@SUPERCILEX turns out I'm also starting work on this exact topic.  I see that you added this to a milestone.  I'm available for real time discussions as needed _hc on freenode/oftc and eighthave:matrix.org on Matrix/Riot

**Comment by eighthave** [comment]
Turns out that @nijel has implemented direct support in Weblate for having the source strings across multiple files, like Triple-T Gradle Play Publisher does.  So in theory, it should be possible to use the existing Triple-T file layout. https://github.com/WeblateOrg/weblate/issues/1525#issuecomment-463770130  Supporting XLIFF there would still give lots of extra features, like developer notes to translators, custom character limits, etc.

**Comment by SUPERCILEX** [comment]
@eighthave Glad to hear that!

In general, I don't think we want to go towards custom formats long-term. Maybe we'd reconsider in the future, but for now, we want to stay as close to the publishing API as possible while providing hooks for you the developer to map whatever you have into our simple format with your own tools.

**Comment by eighthave** [comment]
Makes sense to keep things as they are if they are working.  I just have to add that [XLIFF](https://en.wikipedia.org/wiki/XLIFF) is pretty much the opposite of a custom format.  It is a widely implemented standard (ISO 21720:2017 and others).  Basically every translation tool supports it, free or proprietary, web or desktop. iOS and other platforms use XLIFF as its core format, and on, and on.
