### ISSUE TITLE
App Store title limit is wrong

### ISSUE THREAD

**Issue by henningvs** [Triple-T/gradle-play-publisher#229]
When building and uploading the application the following error occus:

```
* What went wrong:
Execution failed for task ':app:publishListingRelease'.
> File 'pt-BR -> title' has reached the limit of 30 characters

```
When going to the webinterface it is possible to input 50 characters instead of the named 30.

**Comment by ChristianBecker** [comment]
Duplicate of #224 . Fixed by #225 . Release: tba.
