### ISSUE TITLE
Support for different build types

### ISSUE THREAD

**Issue by lucasmacielc** [Triple-T/gradle-play-publisher#231]
Why is not support for different buildTypes?

I use buildType like this:

`

     buildTypes {

        alpha {
            applicationIdSuffix '.alpha'
            debuggable true
            signingConfig signingConfigs.release
            versionNameSuffix '-ALPHA'
            play {
                track = 'alpha'
                userFraction = 1
            }
        }

        beta {
            applicationIdSuffix '.beta'
            debuggable true
            signingConfig signingConfigs.release
            versionNameSuffix '-BETA'
            play {
                track = 'beta'
                userFraction = 1
            }
        }

        release {
            signingConfig signingConfigs.release
            applicationIdSuffix '.release'
            debuggable false
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            play {
                track = 'production'
                userFraction = 1
            }
        }
    }

`

**Comment by Shusshu** [comment]
Is this supported?

**Comment by SUPERCILEX** [comment]
Yes: https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#using-multiple-service-accounts

**Comment by Shusshu** [comment]
I tried that but it doesn't work with only build types...

**Comment by SUPERCILEX** [comment]
Just use the build type name (e.g. `release`).

**Comment by Shusshu** [comment]
Did that... 

`publishQaBundle` wasn't available. Only `publishReleaseBundle`

**Comment by SUPERCILEX** [comment]
Hmmm, I'm confused. Please file a new issue with your build.gradle and the output of `./gradlew app:dependencies`.

**Comment by SUPERCILEX** [comment]
@Shusshu whoops, I meant `./gradlew tasks --group publishing`.
