### ISSUE TITLE
Need custom commands to upload my generated apk file

### ISSUE THREAD

**Issue by ShreyashPromact** [Triple-T/gradle-play-publisher#233]
Hi,

I want to use Facebook-Redex to optimize the APK file before uploading it. I know that the Triple-T tasks will make APK and will upload that to play store. But I want to make the APK file on my own and then want to optimize it with redex and then want to upload the optimise APK file to play store.

Is it possible to do with using a Triple-T plugin?
If yes then please guide me the command to use to achieve same.

Thanks.
Sincerely,
Shreyash

**Comment by ferhimedamine** [comment]
Any help on this one.

**Comment by michaelaubert** [comment]
would also be good for use with tools like Arxan

**Comment by ShreyashPromact** [comment]
I am waiting for this updates. Thanks.

**Comment by ShreyashPromact** [comment]
Can anyone guide me if this is possible to do now?

**Comment by SUPERCILEX** [comment]
@ShreyashPromact Is this a gradle plugin too? If so, you could just have the publish task depend on that plugin's task. Otherwise, you'll probably have to write a gradle task that runs the tool yourself and then have our publish task depend on that one.

**Comment by gtcompscientist** [comment]
@SUPERCILEX - Neither of these tools is a Gradle plugin. Their both generating/modifying apks out of the build tools.

**Comment by SUPERCILEX** [comment]
@gtcompscientistp thanks for the info! So yeah, that means that a custom task will have to run a shell script. I'll add that to the list of things we need to clarify in the README.

**Comment by gtcompscientist** [comment]
I suggest taking a folder as a command-line argument that would bypass the `assemble` step, and uploads it. The API result gives us everything we need to perform the rest of the process (version code). It also means not having to add any other configuration options, but we can use the existing configuration information to drive the uploads.

**Comment by gtcompscientist** [comment]
The previous suggestion would also allow for the configuration to solve #244

**Comment by SUPERCILEX** [comment]
Documentation will be available for v2.0. In the meantime, you can find it [here](https://github.com/Triple-T/gradle-play-publisher/blob/dev-docs/README.md#using-external-tools-from-gradle).

**Comment by henriquenfaria** [comment]
Is this possible? could not find any info about this in the README.
