### ISSUE TITLE
Publish All Multiple Apk (Product Flavor) in One Touch

### ISSUE THREAD

**Issue by abdymm** [Triple-T/gradle-play-publisher#234]
Halo, i have product flavors that implement multiple apk and i already set up for all google play publish config and then wehn i run `./gradlew task` just show each of product flavors like
`
publishApkProductFlavors1Release
publishApkProductFlavors2Release
publishApkProductFlavors3Release
`
is that possible if I want to publish all at once  ?

**Comment by abdymm** [comment]
@bhurling

**Comment by Gopinathp** [comment]
I think this will be a killer feature and saves tons of hours of labour for our fellow  #AndroidDev

**Comment by brp-david** [comment]
It's pretty easily solved by writing your own gradle task for it.
See https://github.com/Triple-T/gradle-play-publisher/issues/117

**Comment by SUPERCILEX** [comment]
Closing as duplicate of #117.
