### ISSUE TITLE
Validate service account auth keys and improve error message

### ISSUE THREAD

**Issue by SupzRao** [Triple-T/gradle-play-publisher#238]
## Execution failed for task ':app:publishApkRelease'.

com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized

``java        
play {          
        track = 'alpha'              
    }               
    signingConfigs {               
        debug {               
            storeFile file('app.jks')             
            keyAlias KEY_ALIAS               
            keyPassword KEY_PASSWORD                
            storePassword KEYSTORE_PASSWORD                    
        }
        release {               
             storeFile file('app.jks')                 
            keyAlias KEY_ALIAS                    
            keyPassword KEY_PASSWORD                  
            storePassword KEYSTORE_PASSWORD                  
        }                
    }
``

**Comment by nscherer** [comment]
I don't know if you're having the same problem I did: 

https://github.com/Triple-T/gradle-play-publisher/issues/221

**Comment by SUPERCILEX** [comment]
Please read the [authentication section](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#authentication), though I do agree that we should validate this stuff before trying to publish the APK and give a better error message.
