### ISSUE TITLE
Does this work with Google Play App Signing (presented Google I/O '17)

### ISSUE THREAD

**Issue by nilsi** [Triple-T/gradle-play-publisher#246]
Google Play now allows developers to add their signing key to google play store and upload APKs with an upload key to be signed by Google. Like this:
https://www.youtube.com/watch?v=PuaYhnGmeEk

This eliminates the risk of losing their signing key and allows Google to make smaller APKs made for a specific device.

Is this method possible with this library? So instead of signing the APK the old fashion way it's signed using the upload key and Google Play is doing the real signing?

**Comment by diareuse** [comment]
Hey @nilsi,
from my understanding the library has nothing to do with this signing behavior.
Set it up in the developer console and in your `build.gradle` replace signing config with your upload signing config and that's it. Google play will take care of the rest.

**Comment by synman** [comment]
It works fine with google app signing.  I'm maintaining alpha, beta, and production streams with google signing enabled.  The only difference is the keystore you reference locally.

**Comment by GabrielGil** [comment]
Yes, it does works perfectly. I also manage different channels with the plugin with no issue.

**Comment by bhurling** [comment]
Thanks for clarifying @diareuse @synman @GabrielGil
