### ISSUE TITLE
upload mapping to google play not working on ver 1.2.0 

### ISSUE THREAD

**Issue by Tilium** [Triple-T/gradle-play-publisher#251]
when I try to execute task `./gradlew publishApkRelease --info` , the cradle make mapping file in build directory, and I see in console success upload mapping file:
`-------------- REQUEST  --------------
POST https://www.googleapis.com/upload/androidpublisher/v2/applications/packageName/edits/06264314702457476215/apks/1246/deobfuscationFiles/proguard?uploadType=resumable
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: gradle-play-publisher Google-API-Java-Client Google-HTTP-Java-Client/1.22.0 (gzip)
x-upload-content-type: application/octet-stream
x-upload-content-length: 6596934
Content-Length: 0

curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: gradle-play-publisher Google-API-Java-Client Google-HTTP-Java-Client/1.22.0 (gzip)' -H 'x-upload-content-type: application/octet-stream' -H 'x-upload-content-length: 6596934' -d '@-' -- 'https://www.googleapis.com/upload/androidpublisher/v2/applications/packageName/edits/06264314702457476215/apks/1246/deobfuscationFiles/proguard?uploadType=resumable' << $$$
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
Server: UploadServer
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-GUploader-UploadID: AEnB2Ur4ZeZb-7T5vU2u8HZDMIaP0BrTnv_dbfhpmkJpqizLX6-rrSE9meTqRJowEWwuWOLw70kN4M-XxJEXmugTR-w6N62dHZYun_ZI4K5pVdedooLQudQ
Vary: X-Origin
Vary: Origin
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Content-Length: 0
Date: Tue, 27 Feb 2018 13:16:54 GMT
Content-Type: text/html; charset=UTF-8
Location: https://www.googleapis.com/upload/androidpublisher/v2/applications/packageName/edits/06264314702457476215/apks/1246/deobfuscationFiles/proguard?uploadType=resumable&upload_id=AEnB2Ur4ZeZb-7T5vU2u8HZDMIaP0BrTnv_dbfhpmkJpqizLX6-rrSE9meTqRJowEWwuWOLw70kN4M-XxJEXmugTR-w6N62dHZYun_ZI4K5pVdedooLQudQ

-------------- REQUEST  --------------
PUT https://www.googleapis.com/upload/androidpublisher/v2/applications/packageName/edits/06264314702457476215/apks/1246/deobfuscationFiles/proguard?uploadType=resumable&upload_id=AEnB2Ur4ZeZb-7T5vU2u8HZDMIaP0BrTnv_dbfhpmkJpqizLX6-rrSE9meTqRJowEWwuWOLw70kN4M-XxJEXmugTR-w6N62dHZYun_ZI4K5pVdedooLQudQ
Accept-Encoding: gzip
Authorization: <Not Logged>
Content-Range: bytes 0-6596933/6596934
User-Agent: Google-HTTP-Java-Client/1.22.0 (gzip)
Content-Type: application/octet-stream
Content-Length: 6596934

curl -v --compressed -X PUT -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'Content-Range: bytes 0-6596933/6596934' -H 'User-Agent: Google-HTTP-Java-Client/1.22.0 (gzip)' -H 'Content-Type: application/octet-stream' -d '@-' -- 'https://www.googleapis.com/upload/androidpublisher/v2/applications/packageName/edits/06264314702457476215/apks/1246/deobfuscationFiles/proguard?uploadType=resumable&upload_id=AEnB2Ur4ZeZb-7T5vU2u8HZDMIaP0BrTnv_dbfhpmkJpqizLX6-rrSE9meTqRJowEWwuWOLw70kN4M-XxJEXmugTR-w6N62dHZYun_ZI4K5pVdedooLQudQ' << $$$
Total: 6,596,934 bytes (logging first 16,384 bytes)
android.arch.core.internal.FastSafeIterableMap -> android.arch.a.a.a:
    java.util.HashMap mHashMap -> a
    35:37:void <init>() -> <init>
...
    105:109
-------------- RESPONSE --------------
HTTP/1.1 200 OK
Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
Server: UploadServer
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
ETag: "TG0uzr2VJapy2vqOc_tPsCT_gpo/rYZYCEG3_xOkke8bEt0Yc7WrRmk"
X-GUploader-UploadID: AEnB2Ur4ZeZb-7T5vU2u8HZDMIaP0BrTnv_dbfhpmkJpqizLX6-rrSE9meTqRJowEWwuWOLw70kN4M-XxJEXmugTR-w6N62dHZYun_ZI4K5pVdedooLQudQ
Vary: X-Origin
Vary: Origin
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Content-Length: 58
Date: Tue, 27 Feb 2018 13:16:57 GMT
Content-Type: application/json; charset=UTF-8

Total: 58 bytes
{
 "deobfuscationFile": {
  "symbolType": "proguard"
 }
}

Total: 23 bytes
{"versionCodes":[1246]}`

but when I open goole play dev console I can't see mapping file
![screenshot at feb 27 17-32-33](https://user-images.githubusercontent.com/5947396/36731437-3bc3f850-1be4-11e8-81b5-ac19c80a64c3.png)

**Comment by murkle** [comment]
We have an automatic upload each day, seems to have gone wrong around 20th Feb
![image](https://user-images.githubusercontent.com/814957/37097057-6e6358da-2212-11e8-8311-556dfb70807f.png)

**Comment by murkle** [comment]
Working again today, maybe Google fixed something?

**Comment by ChristianBecker** [comment]
We haven't changed anything with regards to the mapping file. So it must be something on Google's side.
