### ISSUE TITLE
Upload APK to make a draft?

### ISSUE THREAD

**Issue by vanlooverenkoen** [Triple-T/gradle-play-publisher#252]
Is it possible to upload the apk to the play console but only to make a draft?

**Comment by bhurling** [comment]
Sounds interesting. I'm not sure if Google's API allows it. If it does we could add a configuration flag

**Comment by gtcompscientist** [comment]
It looks like the Tracks API which requires a change to the "What's New" data includes this ability:
https://developers.google.com/android-publisher/api-ref/edits/tracks

<img width="430" alt="screen shot 2018-05-18 at 2 51 48 pm" src="https://user-images.githubusercontent.com/230875/40252655-0409b5a2-5aab-11e8-9014-7a3bc627c213.png">

**Comment by bhurling** [comment]
Fixed via #291
