### ISSUE TITLE
Add internal testing track

### ISSUE THREAD

**Issue by tonidero** [Triple-T/gradle-play-publisher#253]
Google just released internal test as a new track besides alpha, beta and production. Would be nice to add support for that

https://support.google.com/googleplay/android-developer/answer/3131213

**Comment by jacek-marchwicki** [comment]
I'm afraid that currently, this is not available via Google Play Publisher API: https://developers.google.com/android-publisher/tracks

I see only: `alpha`, `beta, `rollout` and `production`

**Comment by drjunior** [comment]
@jacek-marchwicki it might not be documented but already available... ;)

**Comment by jacek-marchwicki** [comment]
@drjunior you are right
https://developers.google.com/apis-explorer/#search/Google%20Play%20Developer%20API/androidpublisher/v2/androidpublisher.edits.tracks.update

there is `internal` track :)

**Comment by drjunior** [comment]
cool ;) Would this plugin continue working if we simply change the track to 'internal' in the build.gradle file like this:

play {
    jsonFile = file('dev.json')
    track = 'internal'
}

?

**Comment by jacek-marchwicki** [comment]
And also there were pull request for this: https://github.com/Triple-T/gradle-play-publisher/pull/254

**Comment by drjunior** [comment]
Ah ok, the plugin validates the tracks and it's not dynamic. Thanks.

**Comment by jacek-marchwicki** [comment]
@drjunior you can try use jitpack build from master

`maven { url 'https://jitpack.io' }`

`classpath 'com.github.Triple-T:gradle-play-publisher:4bb0bd9203'`

**Comment by visyan** [comment]
When will this be available in an 'official' release?

**Comment by ChristianBecker** [comment]
@visyan : No specific ETA but we're trying to push one release out soon.

**Comment by romshiri** [comment]
@ChristianBecker Thank you!

**Comment by jrchew88** [comment]
Thank you for the great library. I too would also greatly appreciate being able to publish to an internal track.

**Comment by prolificcoder** [comment]
Ping.. can we get this track please!

**Comment by bhurling** [comment]
Released in version 1.2.1-beta1
