### ISSUE TITLE
Is it possible to release to the 'Internal test' track?

### ISSUE THREAD

**Issue by HarshMindera** [Triple-T/gradle-play-publisher#259]

**Comment by huytran0605** [comment]
same question

**Comment by burntcookie90** [comment]
https://github.com/Triple-T/gradle-play-publisher/commit/4bb0bd9203c3337affffa9ae95d971826ec910c2 looks like this was merged recently, so yes.

**Comment by fearlessforhim** [comment]
Any ETA on when this change goes out?

**Comment by jonneymendoza** [comment]
Any info on how to build an internel release using 1.2.1-beta1?

**Comment by bhurling** [comment]
Just set the track to internal

```
play {
    track = 'internal'
}
```

**Comment by thekekc** [comment]
When i checkout 1.2.1-beta1 version and try to build project i get this error:"minimum supported Gradle vesion is 4.4. Current is 4.1".  Still works with 1.2.0.

**Comment by bhurling** [comment]
@ChristianBecker This is probably due to updating our android plugin dependency to 3.1.0 in #256 Apparently this change is not backwards compatible. Might make sense to temporarily revert that change for a proper version 1.2.1.

**Comment by bhurling** [comment]
Fixed in 1.2.1
