### ISSUE TITLE
GoogleJsonResponseException: 500 Internal Server Error

### ISSUE THREAD

**Issue by PShchahelski** [Triple-T/gradle-play-publisher#27]
Hi,

First of all thanks for plugin. I am using your plugin to upload apk to google play and faced a problem. I run publishApk task with debug mode. In log I see that all of the request are returned with Http.Ok response (200). But when the plugin tries to commit the changes in Edit by sending request https://www.googleapis.com/androidpublisher/v2/applications/...:commit it gets the response

[com.google.api.client.http.HttpTransport] {
 "error": {                                                
  "code": 500,                                             
  "message": null                                          
 }                                                         
}  

I do not understand what can be the reason of it? Maybe you have some ideas?

Thanks in advance.

**Comment by bhurling** [comment]
Did you have any success yet?

I tried with several misconfigurations but none of them results in that strange 500 error. I tried with a recent changes file with too many characters and with unsupported locales.

Are you sure your APK is correctly signed? Do you use a custom APK name as described in the README?

**Comment by migore** [comment]
I have the same problem in my CI environment, if I run the task from my local machine I can upload the APK normally.

**Comment by bhurling** [comment]
Could not reproduce

**Comment by mdenissov** [comment]
I have same problem:

Execution failed for task ':mobile-client:publishListingProductionRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
  {
    "code" : 500,
    "message" : null
  }

This is my content to upload:

<img width="222" alt="screenshot 2015-11-02 11 41 36" src="https://cloud.githubusercontent.com/assets/5848117/10874933/bcf3c1ba-8156-11e5-868b-cc68c18cb4d2.png">

Could it be a problem in file coding? I use UTF-8 encode and Russian text in files.

**Comment by mdenissov** [comment]
I found mistake in logo file. I replaced icon/512x512.jpg to 512x512.png with aplha, but it did not help.
