### ISSUE TITLE
Add `modifyRelease[Flavor]` task

### ISSUE THREAD

**Issue by gtcompscientist** [Triple-T/gradle-play-publisher#284]
Add a new task to promote releases. Looking for input on the task and manner of promotion.

My suggestion:
- Command-line input would be `fromTrack` and `toTrack` [optional]
- `toTrack` must be the same or "higher"
- Defaults to the plugin configured `status` of a release
- Releases status can also be overridden with any of the possible statuses

Available statuses:
- `completed`
- `draft`
- `halted`
- `inProgress` w/`rollout` %

The `modifyRelease` task would also have an "all" task for all `variants`.

Would solve #104, coincide with #252 and #274. And probably respect whatever logic is used for #125.

**Comment by SUPERCILEX** [comment]
Making some internal discussion public: it might be better to add a builder to the `play` block so that devs can choose where their values come from:
```kotlin
play {
    // ...
    releaseModifiers {
        fromTrack = properties["fromTrack"] // Could also be hardcoded, retrieved from the network, or even randomly generated to create an "I'm feeling lucky" button 😁
        toTrack = properties["toTrack"]
        status = properties["status"]
    }
}
```

Then the same way of passing args via the CLI would work:
```sh
./gradlew modifyReleasePaid -PfromTrack=internal -Pstatus=completed | ./gradlew modifyReleasePaid -PfromTrack=production -Pstatus=draft
```

**Comment by gtcompscientist** [comment]
Also allows for easier unit testing.

**Comment by gtcompscientist** [comment]
More discussion:
- Should "What's New" be updated from disk? Or should that be only for publishing?
- When updating, what should happen to the old Track? (Just set to empty?)
- Should we allow naming of Track Releases, to allow for multiple, and/or promoting a single release?
- If allowing multiple, what do we put in the new Track, the promoted release? Search/replace based on name? Add to what exists?

Multiple Track Releases would require research on how the API works with those. (What tracks can have multiple?)

**Comment by gtcompscientist** [comment]
Named releasees are specifically for Alpha channel, from my research, and they MUST be named. So we'll need a way to distinguish them, and know which track to modify.
