### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by maaudrana** [Triple-T/gradle-play-publisher#309]
Hallo 
I am Md Masud Rana 
Want to make a logo for this projects if you have any requirements then let me know.its free for any open source projects 
Thank you

**Comment by SUPERCILEX** [comment]
I don't see why not. 😄 It should probably look like a blend of the Play Console icon with the Gradle icon. I dunno, do something cool and we'll most likely add it to the README. 👍

**Comment by maaudrana** [comment]
![gradle play publisher-01](https://user-images.githubusercontent.com/34313493/41088101-6ca3734a-6a60-11e8-85ee-92f778dd00e4.jpg)

**Comment by bhurling** [comment]
Awesome. This thing looks great. I would love to put it into the readme file. What would you like us to reference. Any website or dribbble account we can link to?

**Comment by SUPERCILEX** [comment]
@maaudrana Wow, those look amazing! I personally like the middle one. Can you send us SVGs so we get crystal clear quality? 😁

**Comment by maaudrana** [comment]
@bhurling its enough to add to readme file. i don't need to reference any websites.
@SUPERCILEX sure.I am making all the editable file of this logo.So that you can use this as your wish.

**Comment by maaudrana** [comment]
check pull request #328
