### ISSUE TITLE
I want i can set proxy to this plugin

### ISSUE THREAD

**Issue by googolmo** [Triple-T/gradle-play-publisher#31]
my server need set proxy can connect to google, so if it's can set proxy will perfect!
thx

**Comment by googolmo** [comment]
@bhurling  I had set system variables like this but it's not work

**Comment by bhurling** [comment]
Do you know of another plugin that allows setting a proxy? That might serve as an example?

**Comment by googolmo** [comment]
i doesn't know, but now i migrate my deploy server, and it's can use this plugin
