### ISSUE TITLE
Collision with latest kotlin gradle script

### ISSUE THREAD

**Issue by hzsweers** [Triple-T/gradle-play-publisher#312]
After updating to Gradle 4.8, the following conflict occurs when using play publisher

```
e: /Users/pandanomic/.gradle/caches/4.8/gradle-kotlin-dsl-accessors/rek2a72n8v7nmfkjktfsds14/src/org/gradle/kotlin/dsl/accessors.kt:104:150: Platform declaration clash: The following declarations have the same JVM signature (getExt(Lorg/gradle/api/NamedDomainObjectContainer;)Lorg/gradle/api/plugins/ExtraPropertiesExtension;):
    fun NamedDomainObjectContainer<BaseVariantOutput>.<get-ext>(): ExtraPropertiesExtension defined in org.gradle.kotlin.dsl in file accessors.kt
    fun NamedDomainObjectContainer<PlayAccountConfig>.<get-ext>(): ExtraPropertiesExtension defined in org.gradle.kotlin.dsl in file accessors.kt
```

**Comment by SUPERCILEX** [comment]
Is this with v1.2.2?

**Comment by hzsweers** [comment]
Is that released? I only see the latest release as 1.2.1

**Comment by SUPERCILEX** [comment]
Nevermind, I mostly wanted to know if this was a snapshot build or not. Anyway, for now, you'll have to downgrade to Gradle 4.7 until something comes out of https://github.com/gradle/kotlin-dsl/issues/905.

**Comment by hzsweers** [comment]
Can do, thanks!

**Comment by p-schneider** [comment]
- [x] a fix for the issue was merged to the `develop` branch on gradle/kotlin-dsl#936
- [ ] now we wait for a [kotlin-dsl release (0.18.x)](https://github.com/gradle/kotlin-dsl/releases)
- [ ] after that we wait for that kotlin-dsl release to make it into a [gradle release (4.9? 4.10?)](https://github.com/gradle/gradle/releases)

Until then we stay on gradle 4.7 (kotlin-dsl 0.16.3) (or use gradle 4.8.x without kotlin-dsl)

**Comment by p-schneider** [comment]
The fix now made into the kotlin-dsl 0.18.4 release which you can test in gradle 4.9 RC1
(You can update your gradlew with `./gradlew wrapper --gradle-version=4.9-rc-1`.)

**Comment by SUPERCILEX** [comment]
@p-schneider Thanks for the update! Since there's nothing we can do on our end and a fix is now available, I'm going to close this issue. Feel free to keep posting updates for those subscribed to this issue. 😊

**Comment by p-schneider** [comment]
With the stable release of [Gradle 4.9](https://github.com/gradle/gradle/releases/tag/v4.9.0) it is now working again like it was with Gradle 4.7.
