### ISSUE TITLE
Remove `uploadImages` documentation

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#315]
It's no longer a thing

**Comment by bhurling** [comment]
Closing as duplicate of #314

**Comment by SUPERCILEX** [comment]
@bhurling this one is different. We need to remove references to that flag in the README. Your issue is about creating a migration guide.

**Comment by gtcompscientist** [comment]
I would suggest we adjust this issue to have a task list of 2.0.0 README updates

**Comment by SUPERCILEX** [comment]
I'm going to submit a PR soon. That's why we have that the dev docs branch, then we can close this issue whenever it goes into that branch

**Comment by SUPERCILEX** [comment]
Fixed in #316
