### ISSUE TITLE
Question: Versioning with splits plugin

### ISSUE THREAD

**Issue by pvasa** [Triple-T/gradle-play-publisher#359]
@bhurling @ChristianBecker @SUPERCILEX @gtcompscientist I am using splits plugin for different system architecture and screen sizes. Does this plugin support auto unique versioning of the splits?

**Comment by bhurling** [comment]
The current stable version of the publisher plugin (1.2.2) doesn't mess with version codes. We leave that up to the developer as they might have their own workflows in place. With splits, most people use some simple calculation to determine the final version code as described [here](https://developer.android.com/studio/build/configure-apk-splits#configure-APK-versions). The publisher plugin will then just pick up all your splits and try to upload them (without touching the version code again). 

Be aware that the upload for one or many APKs might fail if there is an error in your version code calculation. If any of the resulting APKs has a lower version code than what's already in the play store you might end up in a weird state where only half of your users would receive the update.

On our way towards 2.0.0, however, we're introducing a feature where you can apply your own resolution strategy (one of which would be automatically upgrading all version codes). See #301 for details.

Hope this answers your question

**Comment by pvasa** [comment]
Yes, that clears my doubt. Thank you.
