### ISSUE TITLE
use other buildTypes

### ISSUE THREAD

**Issue by falkorichter** [Triple-T/gradle-play-publisher#36]
I find it currently not possible to specify another buildType to be uploaded to play. 
Is that correct? 
Would a pull-request for such a feature be considered?

We have a buildType "playStore" that is used for the playStore and release is used for hockeyApp releases...

**Comment by bhurling** [comment]
Yes, you're right. I hardcoded the release buildType. Everything else currently won't get the publish tasks. There's a PR that might help (once the tests pass). See #37

**Comment by falkorichter** [comment]
sound like a plan for the weekend...

**Comment by bhurling** [comment]
Fixed in 1.0.1
