### ISSUE TITLE
Unable to generate / upload Android App Bundle

### ISSUE THREAD

**Issue by jaideepl** [Triple-T/gradle-play-publisher#377]
Hi,
I am not able to find any option for generating and uploading Android bundle files to playstore. Nowhere it is documented.
Please help me on this issue.

My Email Id : jaideepl1984@gmail.com

Thanks.
Jaideep L

**Comment by SUPERCILEX** [comment]
This will be available in the upcoming v2.0 release. See https://github.com/Triple-T/gradle-play-publisher/issues/262#issuecomment-402048034 for instructions on how to try it out.

**Comment by jaideepl** [comment]
Thank you for the update.
