### ISSUE TITLE
overriding the last version of store

### ISSUE THREAD

**Issue by andrefigas** [Triple-T/gradle-play-publisher#385]
When a haven't a alpha version for instance, i can send a alpha version, but if i alread have a alpha version, my app is stored just in artifacts. Tha same happens with all track options.

**Comment by SUPERCILEX** [comment]
The Play Store doesn't let you upload an artifact with the same version code as one you've already uploaded. There's nothing we can do on our end.

**Comment by SUPERCILEX** [comment]
Which version of the plugin are you using? And what track are you trying to upload to?
