### ISSUE TITLE
Documentation for Conditional Plugin use

### ISSUE THREAD

**Issue by kohenkatz** [Triple-T/gradle-play-publisher#387]
Some of my projects have contract developers who are not allowed to upload to the Play Store.  Because of that, we use a `.properties` file to determine whether to register the `play { ... }` configuration.

I think that it would be good to document a few points that I had to figure out along the way, because I'm sure I'm not the only one who wants this.

- You can enclose the `play { ... }` configuration section in an `if` block that checks whether the key file exists. You must also include the `apply plugin: 'com.github.triplet.play'` line only inside that `if`, and it must be before the `play { ... }` block.

```
def playKeyFile = file('your-key.json')
if (playKeyFile.exists()) {
    apply plugin: 'com.github.triplet.play'

    play {
        serviceAccountCredentials = playKeyFile
        track = 'internal'
    }
}
```

- If you are using `flavors` with a single common `play` configuration, the `play { ... }` block must come *before* the `android { ... }` block. Otherwise, Gradle will try to load the `play` configuration for each flavor before the `play` configuration has been created.

**Comment by SUPERCILEX** [comment]
@kohenkatz Yup, you're right about the first point. However, that's applicable to any Gradle plugin so I'm not sure about documenting it for this one.

As for the second point, I'm not quite sure what you mean. We only validate that credentials exist when variants are added and then that they are valid when you run a task. Here's how I address your issue in my project:
- Always apply and configure the plugin
- For my trusted builds, use a valid JSON file
- For 3P builds, the creds JSON file is specified but it doesn't exist. This doesn't matter unless you try to run a publishing task.
- If you're using the automatic conflict resolution strategy, add this code to skip metadata processing and allow release builds to work:
  ```kt
  project.gradle.taskGraph.whenReady {
      val creds = myFile
      val metadataTasks = allTasks.filter { it.name.startsWith("process") && it.name.endsWith("Metadata") }

      if (metadataTasks.isNotEmpty() && !creds.exists()) {
          metadataTasks.forEach { it.enabled = false }
      }
  }
  ```

Does that all make sense?

**Comment by kohenkatz** [comment]
@SUPERCILEX Here is a complete example of what didn't work that made me open this issue.

**`build.gradle` (with names changed and `dependencies` removed for brevity)**

```
apply plugin: 'com.android.application'
apply plugin: 'net.ltgt.errorprone'
apply plugin: 'com.github.triplet.play'

def keystorePropertiesFile = project.file("keystore.properties")
def keystoreProperties = null
if (keystorePropertiesFile.exists()) {
	keystoreProperties = new Properties()
	keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
	compileSdkVersion 28
	buildToolsVersion '28.0.2'
	useLibrary 'org.apache.http.legacy'

	defaultConfig {
		applicationId 'com.example.app'
		minSdkVersion 21
		targetSdkVersion 28
		versionCode 84
		versionName '3.8.2'
	}

	signingConfigs {
		release {
			storeFile     keystoreProperties == null ? null : file(keystoreProperties['storeFile'])
			storePassword keystoreProperties == null ? null : keystoreProperties['storePassword']
			keyAlias      keystoreProperties == null ? null : keystoreProperties['keyAlias']
			keyPassword   keystoreProperties == null ? null : keystoreProperties['keyPassword']
		}
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			signingConfig signingConfigs.release
		}
		debug {
			applicationIdSuffix '.dev'
		}
	}

	flavorDimensions 'skin'
	productFlavors {
		app1 {
			dimension 'skin'
		}
		app2 {
			dimension 'skin'
			applicationId 'com.example.app2'
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

	lintOptions {
		abortOnError false
	}
}

def playStorePropertiesFile = project.file("google-play-publisher.properties")
if (playStorePropertiesFile.exists()) {
	def playStoreProperties = new Properties()
	playStoreProperties.load(new FileInputStream(playStorePropertiesFile))

	play {
		serviceAccountEmail = playStoreProperties['serviceAccountEmail']
		serviceAccountCredentials = file(playStoreProperties['pk12FilePath'])
		track = playStoreProperties['track']
	}
}
```

This gives the error:

```
Could not find playAccountConfig on com.android.build.gradle.internal.api.ReadOnlyProductFlavor@95fd817
```

**Note that the README [says](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#authenticating-the-plugin) to put the `play` block *after* the `android` block:**

> ```
> android { ... }
>
> play {
>     jsonFile = file('your-key.json')
> }
> ```

This works fine without flavors but gives the error above with them, so I figured I would document that.

**Comment by SUPERCILEX** [comment]
@kohenkatz I can't reproduce your error, but either way, it would be a bug. Are you using the latest snapshot build? If you can create a failing test in `PlayPublisherPluginTest` after checking out [groovy-tests](https://github.com/Triple-T/gradle-play-publisher/tree/groovy-tests), that would be awesome! Otherwise, I was suggesting you use fake values:
```groovy
def playStoreProperties = new Properties()

def playStorePropertiesFile = project.file("google-play-publisher.properties")
if (playStorePropertiesFile.exists()) {
	playStoreProperties.load(new FileInputStream(playStorePropertiesFile))
} else {
    playStoreProperties['pk12FilePath'] = 'not-found'
    playStoreProperties['track'] = 'internal'
}

play {
    serviceAccountEmail = playStoreProperties['serviceAccountEmail']
    serviceAccountCredentials = file(playStoreProperties['pk12FilePath'])
    track = playStoreProperties['track']
}
```

**Comment by dlew** [comment]
I'm running into a very similar problem of trying to conditionally run based on whether the credentials are present.

The issue I'm running into is that `assembleRelease` is depending on the `processReleaseMetadata` task, which is when the plugin tries to grab `serviceAccountCredentials` (which may not be present).

It seems to me that the `processReleaseMetadata` task should only execute if you explicitly call `publishReleaseApk`, not if you're just assembling the release APK.

**Comment by dlew** [comment]
My workaround has been what was suggested above - provide a dummy JSON file when not actually calling the `publish` task.

That leads me to an alternative thought: since `processReleaseMetadata` doesn't actually validate the JSON file at all (my dummy file isn't even JSON), why validate that it even exists at that point? That, too, could be deferred until `publish`.

**Comment by SUPERCILEX** [comment]
@dlew That's a good point. Just to clarify, are you using the `auto` resolution strategy? Or are you saying `processReleaseMetadata` always fails without credentials? (It shouldn't.)

**Comment by dlew** [comment]
I'm not sure what you mean by the `auto` resolution strategy - could you clarify?

What I am saying is that `processReleaseMetadata` fails without credentials - if I don't define `serviceAccountCredentials`, then I get a "No credentials provided" error. If I define `serviceAccountCredentials` but the file doesn't exist, I get a "File does not exist" error. The only way I've made it work is to define a dummy file which has invalid content but that's not checked during `processReleaseMetadata`.

**Comment by dlew** [comment]
Sure, here's a [stacktrace](https://github.com/Triple-T/gradle-play-publisher/files/2450993/stacktrace.txt) for when the credential file is provided but doesn't exist.

**Comment by SUPERCILEX** [comment]
Ohhhhh, right. Ok, I think I have a fairly simple fix. 👍

**Comment by tasomaniac** [comment]
Oh nice. I will try tomorrow. For now, I fixed the build by putting an if condition over the env variable.
