### ISSUE TITLE
jsonFile or serviceAccountCredentials?

### ISSUE THREAD

**Issue by Queatz** [Triple-T/gradle-play-publisher#394]
Readme says to use jsonFile, found a comment on an issue and tried serviceAccountCredentials and it worked (v2.0.0-snapshot)

**Comment by SUPERCILEX** [comment]
Yeah, our documentation doesn't include any of the v2.0 changes. However, we've got a [changelog going](https://github.com/Triple-T/gradle-play-publisher/blob/master/CHANGELOG.md#200---to-be-released).
