### ISSUE TITLE
Can I upload a new project to an existing account?

### ISSUE THREAD

**Issue by SegaWeb** [Triple-T/gradle-play-publisher#395]
Hello! Thanks for the plugin.
I have an account in the google play console, there are already applications.

Question:
I created another new application, can I put it on the Play market with this plugin? Or must first manually upload it?

Thanks!

**Comment by SUPERCILEX** [comment]
You have to upload at least one APK/Bundle:
> You can only use this API to make changes to an existing app (that has at least one APK uploaded); thus, you will have to upload at least one APK through the Play Console before you can use this API. Furthermore, you cannot use this API to change an app's state from "published" to "unpublished", or to fill out the legal consents required for publishing. To publish the app, you have to use the Play Console.

Details: https://developers.google.com/android-publisher/edits/
