### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by AndroidGecko** [Triple-T/gradle-play-publisher#40]
Did everything as described in readme

after running `gradle publishApkRelease` I get

`java.io.FileNotFoundException: .... /app/build/outputs/play/release`

why it is looking by default inside play folder instead off apk?
I'm not running any other plugins, custom tasks

**Comment by AndroidGecko** [comment]
this can be solved by adding an empty `play` directory next to `java` directory however I don't think that should be required

**Comment by bhurling** [comment]
The plugin looks for a file called `whatsnew` inside the play folder that contains a summary of recent changes for the APK. Shouldn't be required though, you're right. Going to fix it this weekend
