### ISSUE TITLE
Cannot publish to custom closed track

### ISSUE THREAD

**Issue by nikedlab** [Triple-T/gradle-play-publisher#402]
### Describe the bug

In Google play is possibility to create Closed track with any name. If name of it set as destination track will be an error 

> Track must be one of 'internal', 'alpha', 'beta', 'rollout', 'production'

### To Reproduce

Login to Google Play Console, go to App releases, push CREATE CLOSED TRACK and complete action. Try to publish APK to new track

#### Versions

 - Gradle Play Publisher: 2.0.0
 - Gradle Wrapper (if applicable): 4.9
 - Android Gradle Plugin (if applicable): 173.4301.25

### Expected behavior

Application should be published to custom track

**Comment by SUPERCILEX** [comment]
Use `alpha`. Please let me know if that doesn't work.

**Comment by nikedlab** [comment]
It is no my case. I need six closed tracks for deploying ) It is two OEM with three environments for each

**Comment by gtcompscientist** [comment]
You have more than one named `alpha` `track`?

**Comment by nikedlab** [comment]
Yes. Six for now

**Comment by SUPERCILEX** [comment]
@nikedlab so you can upload different APKs for each closed track?

**Comment by SUPERCILEX** [comment]
Ah, well I don't think the API supports that yet so we're kinda stuck for now

**Comment by nikedlab** [comment]
Not different app, different flavors, different version codes

**Comment by gtcompscientist** [comment]
@nikedlab - @SUPERCILEX is correct that the publishing API doesn't support this currently. I have submitted a bug/feature request, but don't have a public link for anybody to star yet.

**Comment by gtcompscientist** [comment]
For reference: https://developers.google.com/android-publisher/api-ref/edits/tracks#resource

Notably that the there is no place for a named track, and `track` only accepts the standard values, which is what we accept.

**Comment by nikedlab** [comment]
Your issue about impossibility to specify custom track

**Comment by nikedlab** [comment]
Got it. Thank you
