### ISSUE TITLE
Deploying to alpha instead of beta

### ISSUE THREAD

**Issue by nikedlab** [Triple-T/gradle-play-publisher#403]
### Describe the bug

Probably it is misunderstanding of Google Play logic. Correct me if I wrong..
I have created two productFlavors
```
classpath 'com.github.triplet.gradle:play-publisher:1.2.2'

productFlavors {
        beta {
            play.track = "beta"
        }

        alpha {
            play.track = "alpha"
        }
    }

play {
    serviceAccountEmail = 'apk-publisher@api-1031236-227013.iam.gserviceaccount.com'
    pk12File = file("account.p12")
    untrackOld = true
}

```

and when I run publishApkBetaRelease it deployed to alpha. On Beta already exist application with versionCode less than current
My aim is to provide to QA two versions of application for different environments. Manually I can do this, but through plugin not

**Comment by SUPERCILEX** [comment]
Yeah, that's not how flavors work (also, 2 flavors shouldn't generate the same artifacts). Instead, we're adding a feature to promote releases so you can ship it to alpha and then bump it to beta: #389
