### ISSUE TITLE
 500 Internal Server Error

### ISSUE THREAD

**Issue by hrushie** [Triple-T/gradle-play-publisher#408]
### I am getting om.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
   {
     "code" : 500,
     "message" : null
   }
at the end of the build, do we know any specific reason for this error?

**Comment by SUPERCILEX** [comment]
Yeah, I got this too yesterday. Just rerun the build until it works (that did the trick for me).

PS: We can't do anything about Google's API dying, sorry! 😊

**Comment by hrushie** [comment]
Hey @SUPERCILEX, How many times you reran the build before it started working fine?

**Comment by SUPERCILEX** [comment]
To clarify, it was working before and just stopped randomly? You'll probably just have to wait. Otherwise, I would use the help icon in the play console to file a bug report.

**Comment by hrushie** [comment]
It was working fine 4 days ago and I tried it today and suddenly it is not working.
