### ISSUE TITLE
Gradle com.android.tools.build:gradle:3.2.0 error

### ISSUE THREAD

**Issue by nielsz** [Triple-T/gradle-play-publisher#411]
I updated my build plugin from `com.android.tools.build:gradle:3.1.0`
 to  `com.android.tools.build:gradle:3.2.0`, but since then I've received `500 Internal Server Error`  

```09:13:45 :app:publishApkRelease FAILED
09:13:45 
09:13:45 FAILURE: Build failed with an exception.
09:13:45 
09:13:45 * What went wrong:
09:13:45 Execution failed for task ':app:publishApkRelease'.
09:13:45 > com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
09:13:45   {
09:13:45     "code" : 500,
09:13:45     "message" : null
09:13:45   }
```
This happened both yesterday and today. I highly doubt that Google's backend has been down for 24 hours. Now I went back to version 3.1.0, and it works again. I suspect there's something weird going on when using the `3.2.0` version.

I'm running on version gradle-play-publisher `1.2.2`.

**Comment by hrushie** [comment]
I am getting the same error since yesterday and my gradle version is 2.3.3. I am trying to upload the app manually as well but it is not working, any solution for me @nielsz and @SUPERCILEX. I am hitting blocker here and need to resolve it immediately.

**Comment by nielsz** [comment]
@hrushie You can always go to https://play.google.com/apps/publish/ and upload it manually.

@SUPERCILEX While I agree that 500 means it's an error from Google's side, it might (theoretically) be getting in that state if the API is getting wrong data.
I didn't dare to try the 2.0 snapshots, as the process to get this gradle task to run amounts to a JIRA issue, QA testing, and PR review. Didn't dare to update to a major new release.

**Comment by SUPERCILEX** [comment]
@nielsz Yeah, I kinda agree. The main problem is that we don't have the bandwidth to investigate old releases, and 500 means it could be anything. If it would at least tell us what went wrong... 😞

Again, if someone can repro with 2.0, I'll definitely investigate. The old releases are written in a completely different language and are more than 100 commits behind... it's just not feasible with @bhurling's availability.

**Comment by SUPERCILEX** [comment]
Would one of you mind checking to see if the error changed? It might be #413 if Google fixed their crash.

**Comment by larsgrefer** [comment]
I've had the same error with AGP 2.3.0 and GPP 1.2.2. Updating to GPP 2.0.0-SNAPSHOT solved the problem.

**Comment by hrushie** [comment]
Yes it is working fine for me @SUPERCILEX @nielsz

**Comment by SUPERCILEX** [comment]
Ok, then closing 👍

**Comment by echorebel** [comment]
when can we expect the 2.0 release?

**Comment by SUPERCILEX** [comment]
Maybe next Monday. The beta is already out.
