### ISSUE TITLE
[Question] Is Google App Signing supported

### ISSUE THREAD

**Issue by claucookie** [Triple-T/gradle-play-publisher#412]
Hi,

We are considering start using the google app signing process released in 2017 by google and I was wondering if the plugin supports that.

As far as I know, what we need to do on our side (app side) is to sign the apk with a new upload key. So my question is, have you tested this already? is there any difference in terms of api usage to support?

Thanks so much in advance!

Claudia.

**Comment by knordbo** [comment]
Yup, that works just fine. There is no difference between signing with the 'real' key and the 'upload' key.

**Comment by claucookie** [comment]
Thanks so much for the quick reply!
