### ISSUE TITLE
whatsnew ignored in 2.0.0 

### ISSUE THREAD

**Issue by kawaiiDango** [Triple-T/gradle-play-publisher#414]
I put the file in play/listings/en-US/whatsnew.
After publishing to beta track, play console has no whatsnew.

**Comment by SUPERCILEX** [comment]
Yup, file names changed. See the [migration guide](https://github.com/Triple-T/gradle-play-publisher/blob/master/CHANGELOG.md#breaking-changes).

**Comment by alexfdz** [comment]
@SUPERCILEX There is no reference to the new `whatsnew` file name in https://github.com/Triple-T/gradle-play-publisher#directory-structure

**Comment by kawaiiDango** [comment]
It's called release notes or something similar, which is present in the new dir structure
