### ISSUE TITLE
Allow to supply JSON private key via ENV variable

### ISSUE THREAD

**Issue by NikolayManzhos** [Triple-T/gradle-play-publisher#415]
As far as i understand right now only way to provide private key is to store it as file in the same repo. Which is not really great if you wanna upload open source app from any free CI service (e.g. Travis CI, Circle CI). I suggest to provide an additional way of doing so by specifying env variable and storing credentials there.
WDYT?

**Comment by SUPERCILEX** [comment]
We're not going to do that because you can fairly easily support it yourself: https://github.com/Triple-T/gradle-play-publisher#encrypting-service-account-keys.
