### ISSUE TITLE
String resources not updated

### ISSUE THREAD

**Issue by fillobotto** [Triple-T/gradle-play-publisher#420]
### Describe the bug

Changing any string in translation xml files won't reflect in the final APK once published with "publishApkRelease" task. It looks like changes are not detected if the string resource was already there but some of its content changed between builds. Using Android Studio "Clean Project" and performing build solves the issue, but it's still annoying to remember of it every single time.

### To Reproduce

- Add a new string both for the main and any secondary language you support
- Build and publish the app using this plugin
- Change string value (content of translated string) for the secondary language
- Run task publighApkRelease

Running the app on a device that uses secondary language will not reflect the newer string value. 

#### Versions

 - Gradle Play Publisher: 1.2.2
 - Gradle Wrapper (if applicable): 4.6
 - Android Gradle Plugin (if applicable): 3.2

**Comment by SUPERCILEX** [comment]
1.x versions of the plugin are no longer supported. I would guess that you need to make the publishing task depend on assemble: `publishApkRelease.dependsOn(assemble)`.

Please migrate to v2.0: https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-beta1#breaking
