### ISSUE TITLE
Syntax: plugins {  id "xxx" version "xx"}

### ISSUE THREAD

**Issue by jmfayard** [Triple-T/gradle-play-publisher#421]
Gradle has a best practice of using the new `plugins { ... }` syntax over the "old" `buildscript { ... } / apply ....}` that we are most familiar with. 

This is especially important now that the Kotlin DSL is reaching maturity, since it makes for a much better user experience. 

```
Applying plugins

Just like with the Groovy DSL, there are two ways to apply Gradle plugins:
- declaratively, using the plugins {} block,
- imperatively, using the apply(..) functions.

(See https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#applying_plugins )

We strongly recommend that you use the plugins {} block in preference to the apply() function.
The declarative nature of the plugins {} block enables the Kotlin DSL to provide type-safe accessors 
to the extensions, configurations and other features contributed by the applied plugins, 
which makes it easy for IDEs to discover the details of the plugins' models 
and makes them easy to configure.

```

https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#applying_plugins

Is there a way to do this with your plugin and can you update the README about it?

**Comment by ChristianBecker** [comment]
This is already tracked in #154 .
