### ISSUE TITLE
Release notes not uploaded with draft status

### ISSUE THREAD

**Issue by paulVulog** [Triple-T/gradle-play-publisher#422]
Here is my context : 

My gradle configuration:
`        classpath 'com.github.triplet.gradle:play-publisher:2.0.0-beta1'`
```
play {
	serviceAccountEmail = 'myapp....@....gserviceaccount.com'
	serviceAccountCredentials = file('my_file.p12')
	track = "internal"
	releaseStatus = "draft"
	resolutionStrategy = "auto"
}
```

My release note file location: 
`...\app\src\main\play\release-notes\en-US\internal.txt`

-----------------
Issue:
Using that, the release note for the internal test is not correctly pushed. I still have the default text on my developer console.

-----------------

Additional info : 
- All the file hierarchy was created using the gradlew bootstrap task. The interal.txt file was correctly created with the expected content.
- I would like to know if this issue only affect Draft version or will also affect Completed version

**Comment by SUPERCILEX** [comment]
What happens if you upload it not as a draft?

**Comment by paulVulog** [comment]
I didn't try yet. Can you give me the choices I have regarding the upload possibilities ?
I will try tomorrow.

**Comment by SUPERCILEX** [comment]
`completed` is the default.

**Comment by paulVulog** [comment]
Just tested. Using the "completed" parameter it's fine. 
This is still a bug, but not  a critical one.
Thanks !

**Comment by SUPERCILEX** [comment]
@paulVulog This is an Android Publisher API bug. 😢

I will try to let you know when they fix it. Since GPP can't do anything about it, I'm going to close this issue.
