### ISSUE TITLE
Short circuit image uploads when hashes are the same

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#423]
We currently upload images anytime the task runs, but this comes with issues if different machines who aren't sharing a Gradle cache try publishing. The same images will be uploading twice! This is bad because the Play Store cache is invalidated and forces app users to re-download those assets.

I don't think short circuiting text based uploads is worth it.

**Comment by bhurling** [comment]
Makes a lot of sense

**Comment by SUPERCILEX** [comment]
I'm gonna count this a bug, so moving to 2.0.
