### ISSUE TITLE
maven-publish plugin task clash

### ISSUE THREAD

**Issue by markchristopherng** [Triple-T/gradle-play-publisher#427]
### Describe the bug
I am also using the maven-publish plugin and get the following error;

A problem occurred evaluating script.
> Failed to apply plugin [class 'org.gradle.api.publish.plugins.PublishingPlugin']
   > Cannot add task ':app:publish' as a task with that name already exists.
apply plugin: 'maven-publish'

### To Reproduce

Add `apply plugin: 'maven-publish'`

#### Versions

 - Gradle Play Publisher: 2.0.0.beta 1
 - Gradle Wrapper (if applicable):
 - Android Gradle Plugin (if applicable):

### Expected behavior

I was able to use both the gradle-play-publisher 1.x version with the maven plugin in my gradle builds. When i upgrade to 2.0.0 beta 1 there is a clash.

**Comment by SUPERCILEX** [comment]
Why are you publishing to Maven? GPP is mean for apps, not libraries.

**Comment by markchristopherng** [comment]
Hi,

We also publish our app binaries to our Nexus repository for history.

Regards
Mark

**Comment by SUPERCILEX** [comment]
Alright, that seems like a somewhat valid use case. This will be fixed before v2.0 GA.

**Comment by SUPERCILEX** [comment]
@markchristopherng Note: for the fix to work, you will have to apply the GPP plugin _after_ `maven-publish`. Then, the `publish` task's name will be diverted to `gppPublish`.

**Comment by gtcompscientist** [comment]
@SUPERCILEX I guess if you apply GPP first, then the `maven-publish` plugin is the one that would fail! ;)

**Comment by mmueller-abacus** [comment]
I still have this issue with version 2.1.0.

Here my test build.gradle file:

`buildscript {
    repositories {

        google()
    //    jcenter()
    
        // Repository for triplet.play plugin

        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
    }
}

plugins {

    id 'com.android.application'

    id 'maven-publish'

    // Gradle plugin to upload your App Bundle or APK and
    // other app details to the Google Play Store

    // Clashes with maven-publish task publish
    // https://github.com/Triple-T/gradle-play-publisher/issues/427

    id "com.github.triplet.play" version "2.1.0"

}

android {
    compileSdkVersion 28
}`
