### ISSUE TITLE
Cannot upload new apks

### ISSUE THREAD

**Issue by victorantos** [Triple-T/gradle-play-publisher#43]
Is it possible to upload brand new apks? And I don't mean updates, but the initial apk?

**Comment by bhurling** [comment]
You cannot upload brand new apps using this plugin. You have to at least upload the first APK through the play store UI. This is a restriction of the Google Play Developer API: https://developers.google.com/android-publisher/edits/overview
> You can only use this API to make changes to an existing app (that has at least one APK uploaded); thus, you will have to upload at least one APK through the Developer Console before you can use this API.
