### ISSUE TITLE
PKCS12 credentials must also specify a Service Account email

### ISSUE THREAD

**Issue by mehdiraza** [Triple-T/gradle-play-publisher#430]
I am running the `publishReleaseBundle` task and gradle build fails with the following error message, even though I've specified the `serviceAccountEmail` (was working before on version 1.2.1-beta1)

> PKCS12 credentials must also specify a Service Account email

This is my config:
``` 
play {
    track = 'internal'
    serviceAccountEmail = System.getenv("google_play_service_account")
    serviceAccountCredentials = file("[filename].p12")
}
```

#### Versions

 - Gradle Play Publisher: 2.0.0-beta1
 - Gradle Wrapper (if applicable): 4.6
 - Android Gradle Plugin (if applicable): 3.2.0

**Comment by SUPERCILEX** [comment]
`System.getenv("google_play_service_account")` is null.

**Comment by mehdiraza** [comment]
`google_play_service_account` was an encrypted environment variable in my Travis job. So I had to do `"${System.getenv("google_play_service_account")}"` to make gradle pass locally. Thanks.

**Comment by SUPERCILEX** [comment]
Awesome!
