### ISSUE TITLE
Getting error when upgrading to new 2.0 beta.

### ISSUE THREAD

**Issue by vegetablesalad** [Triple-T/gradle-play-publisher#432]
I followed the setup and upgraded to new beta. I get this error when running any publishing task.
Gradle version is *4.1*

> Error:Could not determine the dependencies of task ':app:publishApk'.
>  Cannot convert value: task ':app:publishReleaseApk' to a task.
>   The following types/formats are supported:
>     - A String or CharSequence task name or path
>     - A TaskReference instance
>     - A Task instance
>     - A Buildable instance
>     - A TaskDependency instance
>     - A Closure instance that returns any of the above types
>     - A Callable instance that returns any of the above types
>     - An Iterable, Collection, Map or array instance that contains any of the above types

```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.github.triplet.gradle:play-publisher:2.0.0-beta1'
    }
```

```
apply plugin: 'com.github.triplet.play'
play {
    serviceAccountCredentials = file('../../../keys/google-service-key.json')
    track = 'internal'
}
```

**Comment by bhurling** [comment]
@SUPERCILEX I also noticed this happening with 4.4. I updated the compatibility test to show that it's failing: https://github.com/Triple-T/gradle-play-publisher/commit/1498e4f02cecded5f4c898d588ba5ff45a390aee

**Comment by vegetablesalad** [comment]
@SUPERCILEX sorry this been a busy week, haven't had time to check it. I just reverted to previous version for now

**Comment by SUPERCILEX** [comment]
Well I was going to be lazy and just bump our minimum Gradle version to whatever works, but fine, y'all convinced me to fix it. 😆 See #443
