### ISSUE TITLE
Question: How to configure upload of mapping.txt

### ISSUE THREAD

**Issue by claudiu-accenture** [Triple-T/gradle-play-publisher#433]
Hi,
I've been going back and forward and could not find any info about how to upload the mapping.txt. I saw that this was implemented in version 1.2.0, and that it was a closed issue, but I could not find any info on how to actually use/configure this feature.
Any help will be highly appreciated!
Thank you.

**Comment by SUPERCILEX** [comment]
It's gets automatically uploaded to the Play Console on every build so you don't have to worry about it.
