### ISSUE TITLE
Question: Using the new version code conflict feature

### ISSUE THREAD

**Issue by thepizzagui** [Triple-T/gradle-play-publisher#437]
Hey there, really love the plugin so far. Been looking forward to using the new version code conflict feature however when using the example provided in the docs my build fails and I'm met with this error message:

 `Could not set unknown property 'versionNameOverride' for object of type com.github.triplet.gradle.play.PlayPublisherExtension.`

Full disclosure, I'm not super experienced with gradle, so it might be something simple that I'm missing, perhaps I need to define `verionNameOverride` elsewhere? I'm currently using gradle version 4.6 using Groovy syntax. Thanks in advance!

**Comment by SUPERCILEX** [comment]
Ah, gotya. Yeah, if you're using Groovy, I think this is the syntax:
```groovy
```

PS: I believe [this PR](https://github.com/Triple-T/gradle-play-publisher/pull/435) will fix that issue

**Comment by SUPERCILEX** [comment]
Ah, gotya. Yeah, if you're using Groovy, I think this is the syntax:
```groovy
outputProcessor = { output ->
    output.versionNameOverride = output.versionNameOverride + "." + output.versionCode
}
```

PS: If that doesn't work, I believe [this PR](https://github.com/Triple-T/gradle-play-publisher/pull/435) will fix that issue when GA is released.

**Comment by SUPERCILEX** [comment]
Awesome!
