### ISSUE TITLE
Add support for updating app's details

### ISSUE THREAD

**Issue by AlexTrotsenko** [Triple-T/gradle-play-publisher#44]
Google Publishing API provides ability to set:
- Default language of the app
- Contact Phone
- Contact mail
- Contact website

Necessity of setting the language from script is obvious. Meanwhile phone, main and website are required information in Google Play Dev Console and could speed up 1st publishing of the app.

Here is example of passing this data to Google API:

````.Java
            final AppDetails newDetails = new AppDetails();
            newDetails.setContactEmail("someone@domain.com")
            		.setContactPhone("+49777777777")
            		.setContactWebsite("http://somesite.com")
            		.setDefaultLanguage(Locale.GERMANY.toString());

            Update updateAppsDetailsRequest = edits
                    .details()
                    .update(ApplicationConfig.PACKAGE_NAME,
                            editId,
                            newDetails);
            AppDetails updatedAppsDetails = updateAppsDetailsRequest.execute();

````

**Comment by ChristianBecker** [comment]
@bhurling What do you think? Seems reasonable…

**Comment by bhurling** [comment]
Wouldn't be too complicated to add.

On the other side those are one-time-steps that are not likely to change afterwards. I don't really see the benefits of automating those steps. Especially, since first time APK upload has to be done through the web interface anyway

**Comment by bhurling** [comment]
@ChristianBecker What's your opinion? One file for each contact detail as we did for the title and the description? Or should we go with a `.properties` approach for those one-liners?

**Comment by ChristianBecker** [comment]
Jeah, it could get messy over time with separate files for each one-liner. On the other hand, `video` and `title` are one-liners, too, but they are living in their own files.

It's up to you to decide…

**Comment by bhurling** [comment]
Hey Guys, what do you think about the change? contactEmail, contactPhone and contactWebsite have to lie in their own files next to the locale dirs like so

```
- [src]
  |
  + - [main]
      |
      + - [play]
          |
          + - [en-US]
          |   |
          |   + - [listing]
          |       |
          |       + - ...
          |
          + - [de-DE]
          |   |
          |   + - [listing]
          |       |
          |       + - ...
          |
          + - contactEmail
          |
          + - contactPhone
          |
          + - contactWebsite
```
This is because the contact details are not translated.

Additionally, this all only works if we provide a default language. Seems a little strange why contact details are mingled with the default language in the API request. But that's how it is.

I added a new bean for the `play` block, called `defaultLanguage`. Then, the contact details are only updated if there is a `defaultLanguage` set.

**Comment by bhurling** [comment]
As an alternative we could just drop the default language into it's own file next to the others

**Comment by AlexTrotsenko** [comment]
@bhurling thank you a lot for implementing this.

As for me, `defaultLanguage` could be both in `play` block and inside separate file. 
Keeping it inside `play` block may be good enough because it's global per app and could be used separately from  `e-mail`\`phone`\`website`.

**Comment by AlexTrotsenko** [comment]
@bhurling  could you please tell if you are going to merge this changes to the master before next release?

**Comment by bhurling** [comment]
Released in 1.1.1

**Comment by AlexTrotsenko** [comment]
Thanks a lot for release this feature.

I am getting following error now:
`
Caused by: org.gradle.internal.UncheckedException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "androidpublisher",
    "message" : "Invalid contact phone number specified for this app.",
    "reason" : "invalidAppContactPhone"
  } ],
  "message" : "Invalid contact phone number specified for this app."
}
`

I see, that when you fill contact details you set phone and then set "contact web" to the same phone property instead of setting it to "contact web" property.

I will create pull request for this.

**Comment by AlexTrotsenko** [comment]
Here is the pull request, that should fix issue from previous message: https://github.com/Triple-T/gradle-play-publisher/pull/82
