### ISSUE TITLE
Release notes not uploaded

### ISSUE THREAD

**Issue by abredykhin** [Triple-T/gradle-play-publisher#440]
### Describe the bug

I can't figure out how to upload release notes to our internal track. Our Android project consists of an app module with two library modules. There is only one flavorDimension: `appType` and one productFlavor: 
```
    productFlavors {
        mobile {
            dimension "appType"
        }
    }
```
I'm publishing APK with `publishApkMobileRelease` and it successfully uploads the build, but not release notes.  I've tried to place them in the following folders: 

```
mobile/src/main/play/release-notes/en-US/default.txt
mobile/src/mobileRelease/play/release-notes/en-US/default.txt
mobile/src/release/play/release-notes/en-US/default.txt
[root]/src/mobileRelease/play/release-notes/en-US/default.txt
[root]/src/mobile/release/play/release-notes/en-US/default.txt
```

What am I missing?

**Comment by SUPERCILEX** [comment]
Are you using v2.0? It won't work otherwise.

**Comment by abredykhin** [comment]
Oh, that's right! I was using 1.2.2 .... Upgrading to 2.0 alpha helped to resolve this, thank you!

**Comment by SUPERCILEX** [comment]
Awesome!
