### ISSUE TITLE
Provide Gradle Kotlin DSL examples in documentation

### ISSUE THREAD

**Issue by eriwen** [Triple-T/gradle-play-publisher#445]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As a [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl) adopter, I'd like to know how to configure this plugin using the Kotlin DSL.

**Describe alternatives you've considered**
N/A

**Additional context**
[This plugin was identified](https://github.com/gradle/gradle/issues/6790) as one of the most useful Gradle plugins. With Kotlin DSL 1.0 approaching shortly, it'd be wonderful if the documentation provided Kotlin and Groovy DSL samples. [Blog post with suggestions](https://blog.gradle.org/groovy-kotlin-dsl-samples).

Here are a couple additional resources:

 * [Migrating build logic from Groovy to Kotlin guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
 * [Exemplar for automated samples testing](https://blog.gradle.org/documentation-samples-testing-exemplar)
 * [Join #kotlin-dsl channel in Gradle Community Slack for personalized help](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE)

Thank you for providing a great Gradle plugin! —The Gradle Team

**Comment by SUPERCILEX** [comment]
Part 1: #446
Part 2: #447

**Comment by eriwen** [comment]
Very nice!
