### ISSUE TITLE
Add dependency for gradle-play-publisher's tasks from client's app script.

### ISSUE THREAD

**Issue by AlexTrotsenko** [Triple-T/gradle-play-publisher#45]
We have our store data stored separately from our source code.

I want to have task **`loadStoreListing`**, that loads resources from remote server and put them inside `'src/release/play'` (as it's required by `gradle-play-publisher` plug-ing). 
I want to make this task executing before `generateReleasePlayResources` (*`GeneratePlayResourcesTask`*).

Here is part of my script to build my project called `app`

````.Java
...
preBuild.dependsOn applySettings

/**
 * Loads listing data and resources
 */
task loadStoreListing << {
     //load store listing and images and put them to 'src/release/play' for "play" plug-ing
}

generateReleasePlayResources.dependsOn loadStoreListing

...
````

First dependency (`preBuild.dependsOn applySettings`) works fine for me. But when I add 2nd dependency for the task from `"play"` plug-in I am getting error:

````
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'generateReleasePlayResources' on project ':app'.
````

How can I achieve my goal? Any ideas what I am doing wrong?

**Comment by AlexTrotsenko** [comment]
I am not proficient user of gradle, but I see, that this has to work this way.
For example: http://stackoverflow.com/a/11105927

**Comment by ChristianBecker** [comment]
Can you post some more lines of your build file? How do you initialize the `generateReleasePlayResources` property? It must be something like
```
def generateReleasePlayResources = project.tasks."generateReleasePlayResources"
```

**Comment by AlexTrotsenko** [comment]
I have tried few different way of initialisation. 

For example. For code, that you posted:

````.Java
def generateReleasePlayResources = project.tasks."generateReleasePlayResources"
generateReleasePlayResources.dependsOn loadStoreListing
````

I am getting:
````
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'generateReleasePlayResources' on task set.
````

Also, if I do something like this:

````.Java
def generateReleasePlayResources = project.tasks.getByName("generateReleasePlayResources")
````
I am getting:

````
> Task with name 'generateReleasePlayResources' not found in project ':app'.
````

So, I have a feeling, that tasks from "play" plug-ing are not visible to my script for some reason.


**But** at the same time this code 
````
gradle.taskGraph.whenReady {taskGraph ->
    def taskExists = taskGraph.hasTask(generateReleasePlayResources)
    println "generateReleasePlayResources exists: " + taskExists
}
````
produces
`generateReleasePlayResources exists: true`
So it's actually  visible some-how.

It's looks strange for me. Anyway, if you need any additional info - feel free to ask me.

**Comment by ChristianBecker** [comment]
Ok, can you try the following
```
project.afterEvaluate {
    def generateReleasePlayResources = project.tasks.getByName("generateReleasePlayResources")
    generateReleasePlayResources.dependsOn loadStoreListing
}
```

I think the tasks aren't initialized at the time you try to access them.

**Comment by AlexTrotsenko** [comment]
Thank you a lot for this suggestion. Now all working fine when I define dependencies this way.

Btw, previously I tried to do similar thing

````.Groovy
gradle.taskGraph.whenReady {taskGraph ->
    def generateReleasePlayResources = project.tasks.getByName("generateReleasePlayResources")
    generateReleasePlayResources.dependsOn loadStoreListing
}
````

But my code was silently doing nothing. 

Looks like `project.afterEvaluate` is called after **Initialisation** phase, while `gradle.taskGraph.whenReady` is called after **Configuration** phase and no changes to tasks' dependencies are really happening.

Thanks a lot, that you took care of this issue so quickly.

Also, it's definitely your responsibility, but I highly suggest adding this info somewhere to first "readme.md" page. For example, to "Configuration" section or just to the end of the page.

**Comment by ChristianBecker** [comment]
Pull Requests are always welcome, if you want to add such section yourself.

**Comment by AlexTrotsenko** [comment]
Sounds good, I will make it today-tomorrow.

**Comment by AlexTrotsenko** [comment]
As I promised, I have added this info to `readme` section (together with some more info concerning adding additional dependencies for tasks from "play" plug-in).

Here is pull request: https://github.com/Triple-T/gradle-play-publisher/pull/51
