### ISSUE TITLE
Add an Enable/Disable feature per variant

### ISSUE THREAD

**Issue by Tc2r1** [Triple-T/gradle-play-publisher#452]
In our build process, we build for 40 different variants, only half of those are able to publish to the playstore (which we want). How would we filter the ones that are not able to publish to the play store, yet still have the ability to build all the apks for manual publishing later?

example: 

MusicTestAppRelease - AutoPublish
HiistoryTestAppRelease - AutoPublish
SportsTestAppRelease - not setup to auto publish
- 37 more of these. 

We'd like to run a publish all command that only publishes the ones that have an account configuration, yet still builds all 40 variants. And doesn't fail due to this.

_Originally posted by @Tc2r1 in https://github.com/Triple-T/gradle-play-publisher/issues/431#issuecomment-435447105_

Currently we use a task such as: 

task publishApkAll(group: 'util') << {}
publishApkAll.dependsOn {
    tasks.findAll { it.name.startsWith('publishApk') && it.name.endsWith('Release') }
}

However this runs the publish task for literally every variant we have, including those not set to actually publish. We would like a way to only run for those that have credentials.

**Comment by SUPERCILEX** [comment]
@Tc2r1 My only concern is that new devs setting up the library won't get a crash if they forgot to configure the service account (and silent failures are bad UX). I think maybe we can keep track of every registered variant and fail only if _none_ have configured the service account.

Anyway, I agree that this will make life easier. Adding to the v2.1 milestone.

**Comment by SUPERCILEX** [comment]
Moving to #461
