### ISSUE TITLE
Problem with SSL-certificates when using behind corporate http(s)-proxy

### ISSUE THREAD

**Issue by NiciDieNase** [Triple-T/gradle-play-publisher#455]
### Describe the bug

This could possibly be related to #31 

We are running our build in a corporate environment behind a http(s)-proxy. The proxy is configured via gradle.properties (systemProp.http(s).proxyHost, etc.). 
We have also configured a custom trust store via the systemProp.javax.net.ssl.trustStore-property that includes our internal (self-signed) CA that the https-proxy is using.

Nevertheless the release fails with a javax.net.ssl.SSLHandshakeException.

When running with systemProp.javax.net.debug=ssl we get the following:

> 10:29:38.055 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Up-to-date check for task ':_ourProject_:publishStoreReleaseApk' took 0.004 secs. It is not up-to-date because:
  No history is available.
10:29:38.055 [DEBUG] [org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter] Ensuring directory exists for property outputDir (OUTPUT) at _directory redacted_
10:29:38.055 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':_ourProject_:publishStoreReleaseApk'.
10:29:38.056 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute publishApks for :_ourProject_:publishStoreReleaseApk' started
10:29:38.056 [INFO] [org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs] All input files are considered out-of-date for incremental task ':_ourProject_:publishStoreReleaseApk'.
10:29:38.086 [QUIET] [system.out] adding as trusted cert:
10:29:38.086 [QUIET] [system.out]   Subject: CN=Starfield Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US
10:29:38.086 [QUIET] [system.out]   Issuer:  CN=Starfield Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US
10:29:38.086 [QUIET] [system.out]   Algorithm: RSA; Serial number: 0x0
10:29:38.086 [QUIET] [system.out]   Valid from Tue Sep 01 02:00:00 CEST 2009 until Fri Jan 01 00:59:59 CET 2038
10:29:38.086 [QUIET] [system.out]
10:29:38.086 [QUIET] [system.out] adding as trusted cert:
10:29:38.086 [QUIET] [system.out]   Subject: CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
10:29:38.086 [QUIET] [system.out]   Issuer:  CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
10:29:38.086 [QUIET] [system.out]   Algorithm: RSA; Serial number: 0x83be056904246b1a1756ac95991c74a
10:29:38.086 [QUIET] [system.out]   Valid from Fri Nov 10 01:00:00 CET 2006 until Mon Nov 10 01:00:00 CET 2031
10:29:38.086 [QUIET] [system.out]
10:29:38.086 [QUIET] [system.out] adding as trusted cert:
10:29:38.086 [QUIET] [system.out]   Subject: CN=Equifax Secure eBusiness CA-1, O=Equifax Secure Inc., C=US
10:29:38.086 [QUIET] [system.out]   Issuer:  CN=Equifax Secure eBusiness CA-1, O=Equifax Secure Inc., C=US
10:29:38.086 [QUIET] [system.out]   Algorithm: RSA; Serial number: 0x4
10:29:38.086 [QUIET] [system.out]   Valid from Mon Jun 21 06:00:00 CEST 1999 until Sun Jun 21 06:00:00 CEST 2020
10:29:38.086 [QUIET] [system.out]
10:29:38.086 [QUIET] [system.out] adding as trusted cert:
10:29:38.086 [QUIET] [system.out]   Subject: CN=thawte Primary Root CA, OU="(c) 2006 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
10:29:38.086 [QUIET] [system.out]   Issuer:  CN=thawte Primary Root CA, OU="(c) 2006 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US

The list of 'adding as trusted cert' continues, but definitly does not include our internal CA.

To me this looks like, as if for the playstore upload not the keystore defined in gradle.preferences is used but another one is created which does not include the same certificates.

I would greatly appreciate any help or hints to what could be the cause of this.

### To Reproduce
run
`/gradlew --debug publishApkStoreRelease`
with the environment and config described above (which I realize is propably not that simple)

#### Versions

 - Gradle Play Publisher: same behavior with 1.2.2 and 2.0.0-rc2
 - Gradle Wrapper (if applicable): 4.4
 - Android Gradle Plugin (if applicable): 3.1.1

### Expected behavior

Plugin works normally when using an https-proxy with a custom CA included in a custom trust store.

**Comment by SUPERCILEX** [comment]
Interesting use case. We currently don't have plans to support this, but we'd surely welcome a contribution if you can get it working! Here's where we create our transport: https://github.com/Triple-T/gradle-play-publisher/blob/998af84fb8cdb781570d246155bfe02907ae270b/plugin/src/main/kotlin/com/github/triplet/gradle/play/internal/Constants.kt#L18

**Comment by NiciDieNase** [comment]
I got the plugin to work behind our proxy, but I haven't tested yet if these changes affect anything else.
