### ISSUE TITLE
Cannot publish rollout with 2.0.0: releasesRolloutTrackNotAllowed

### ISSUE THREAD

**Issue by Sloy** [Triple-T/gradle-play-publisher#456]
After updating to version 2.0.0-rc2 we're having issues publishing a rollout release.

We have the configuration like:
```
    play {
        serviceAccountCredentials = file(...)
        track = 'rollout'
        userFraction = 0.05
        releaseStatus = "inProgress" //Tried with and without this parameter, same results
    }
```
and running the task `./gradlew publishReleaseApk --info` throws the following error:
```
  {
    "code" : 400,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Releases in ROLLOUT track is not supported. You can create a staged rollout by using a partial release in the PRODUCTION track.",
      "reason" : "releasesRolloutTrackNotAllowed"
    } ],
    "message" : "Releases in ROLLOUT track is not supported. You can create a staged rollout by using a partial release in the PRODUCTION track."
  }
```

According to the log, the error is thrown when sending a PUT request to `https://www.googleapis.com/androidpublisher/v3/applications/..../edits/..../tracks/rollout` with body 
```
{
  "releases": [
    {
      "status": "inProgress",
      "userFraction": 0.05,
      "versionCodes": [
        "1600293003"
      ]
    }
  ],
  "track": "rollout"
}
```

I also tried making a release to the "internal" track and it worked fine.

Is there something wrong in our configuration? O is it an issue with the plugin?

 - Gradle Play Publisher: 2.0.0-rc2
 - Android Gradle Plugin: 3.2.1

**Comment by SUPERCILEX** [comment]
Looks like they killed the `rollout` track without bothering to tell anyone. 😒 It's gone from the API reference: https://developers.google.com/android-publisher/api-ref/edits/tracks#resource

**Comment by SUPERCILEX** [comment]
Oh wait, nvm, was looking in the wrong place. Either way, we shouldn't need the rollout track anymore because any track can be `inProgress`.

**Comment by SUPERCILEX** [comment]
Yeah, no, Google killed the `rollout` track. Nothing is working for me either and the error message is pretty clear. Path forward:
- Kill `rollout` on our side
- When an `inProgress` status is published, get the existing releases and add the new one to the existing set so they can coexist. Current behavior is to overwrite which makes `inProgress` pointless.
