### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ssubramanian** [Triple-T/gradle-play-publisher#47]
Hi,

I have followed the documentation on the gradle-play-publisher and Google API but seem to be getting this error. 

> com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
  {
    "code" : 404,
    "errors" : [ {
      "domain" : "global",
      "location" : "packageName",
      "locationType" : "parameter",
      "message" : "No application was found for the given package name.",
      "reason" : "applicationNotFound"
    } ],
    "message" : "No application was found for the given package name."
  }

There was a similar issue reported before and the suggestion was to link a package name to the project but I did not find such a step in the documentation. Clearly, I am missing something. Can you point me in the right direction?

Thanks!

**Comment by ssubramanian** [comment]
Looks like a new app cannot be uploaded via API. It can only be modified. Am I right?

**Comment by ChristianBecker** [comment]
I think so, too. If I'm not mistaken the initial APK upload has to be done through the web interface…

/cc @bhurling

**Comment by bhurling** [comment]
That's right. The initial set up of your app has to be done through the Web Interface. You have to at least upload your APK once. Aftwerwards, you can update and modify the APK and the listing through this plugin.
