### ISSUE TITLE
Plugin doesn't generate upload tasks for flavors

### ISSUE THREAD

**Issue by FilenkovMaxim** [Triple-T/gradle-play-publisher#474]
I have product flavors, but plugin doesn't generate tasks for them. 

Version 1.2.0 did it well.

Tasks generated with v1.2.0
```
publishApkDemoRelease - Uploads the APK for the DemoRelease build
publishApkDevelRelease - Uploads the APK for the DevelRelease build
publishApkProdRelease - Uploads the APK for the ProdRelease build
publishApkTstRelease - Uploads the APK for the TstRelease build
publishDemoRelease - Updates APK and play store listing for the DemoRelease build
publishDevelRelease - Updates APK and play store listing for the DevelRelease build
publishListingDemoRelease - Updates the play store listing for the DemoRelease build
publishListingDevelRelease - Updates the play store listing for the DevelRelease build
publishListingProdRelease - Updates the play store listing for the ProdRelease build
publishListingTstRelease - Updates the play store listing for the TstRelease build
publishProdRelease - Updates APK and play store listing for the ProdRelease build
publishTstRelease - Updates APK and play store listing for the TstRelease build
```

Tasks generated after upgrade to v2.0.0
```
publish - Uploads APK or App Bundle and all Play Store metadata for every variant.
publishApk - Uploads APK for every variant.
publishBundle - Uploads App Bundle for every variant.
publishListing - Uploads all Play Store metadata for every variant.
publishProducts - Uploads all Play Store in-app products for every variant.
```

After upgrade I move
```
playAccountConfigs {
    defaultAccountConfig {
        serviceAccountEmail = 'my_service_email'
        pk12File = file('upload-key.p12')
     }
}
playAccountConfig = playAccountConfigs.defaultAccountConfig
```
from android section to play section:
```
play {
    serviceAccountEmail = 'my_service_email'
    serviceAccountCredentials = file('upload-key.p12')
    track = 'alpha'
}
```
because it didn't work.

Should I do any other actions to upgrade correctly?

**Comment by SUPERCILEX** [comment]
Hmmm, if you run `./gradlew help` what's printed out? Any warnings from GPP?

**Comment by FilenkovMaxim** [comment]
./gradlew help
Configuration on demand is an incubating feature.

> Configure project :dubsapp 
Observed package id 'ndk-bundle' in inconsistent location '/home/maxf/workspace/android-sdk/ndk-bundle18' (Expected '/home/maxf/workspace/android-sdk/ndk-bundle')
Already observed package id 'ndk-bundle' in '/home/maxf/workspace/android-sdk/ndk-bundle'. Skipping duplicate at '/home/maxf/workspace/android-sdk/ndk-bundle18'
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :help 

Welcome to Gradle 4.6.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

**Comment by FilenkovMaxim** [comment]
I haven't nothing warnings from GPP, because publish cannot start, because task is absent.
`[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Task 'publishApkDevelRelease' not found in root project `

**Comment by SUPERCILEX** [comment]
Huh, and if you run it with `--info`?

**Comment by FilenkovMaxim** [comment]
Yes, because we need it for debug native code.
```
productFlavors {
        prod {
            applicationId 'com.dubsapp.prod'
            signingConfig signingConfigs.prod
            dimension 'default'

            externalNativeBuild.cmake {
                // enable verbose logging for tst
                cppFlags += '-DLOG_LEVEL=plog::info'
            }
        }
devel {
            applicationId 'com.dubsapp.devel'
            signingConfig signingConfigs.debug
            dimension 'default'

            externalNativeBuild.cmake {
                // enable verbose logging for dev
                cppFlags += '-DLOG_LEVEL=plog::verbose'
            }
        }
    }

buildTypes {
        release {
            externalNativeBuild {
                cmake {
                    // compile flags for native release build
                    cppFlags += '-DNDEBUG=1'
                }
            }
            jniDebuggable true
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

Actually we have different applications (for each flavor), and 3 from 4 are debug or test application, but release type.

**Comment by SUPERCILEX** [comment]
You can't do that. The play store won't let you publish a debuggable build. Make only the `devel` flavor debuggable.

**Comment by FilenkovMaxim** [comment]
"devel" flavor is a independent application on GP (com.dubsapp.devel) published only to closed alpha for testing. "Tst" is the same. "Demo" too.
They all are need to be debuggable.
And only "prod" is real app.

**Comment by FilenkovMaxim** [comment]
Can I solve this any other way?

**Comment by FilenkovMaxim** [comment]
I tried to set 
```
jniDebuggable false
debuggable false
```
for release, but it didn't fix the problem.

**Comment by SUPERCILEX** [comment]
Setting `debuggable false` should have fixed the problem. Make sure to check your manifest too for that flag.

**Comment by FilenkovMaxim** [comment]
Thanks for help. It solved the problem.

**Comment by mochadwi** [comment]
If there's anyone wondering the above method still doesn't works. 

Don't enable the test coverage in `release` buildType as well. E.g: 
```
        getByName("release") {
            isTestCoverageEnabled = true // this will always made GPP failed

            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true
            isDebuggable = false
            isJniDebuggable = false
        }
```

It will keep the `GPP cannot configure variant 'release' because it is debuggable` thrown.
