### ISSUE TITLE
Publishing listings error: Unknown file 

### ISSUE THREAD

**Issue by FilenkovMaxim** [Triple-T/gradle-play-publisher#480]
Execution failed for task ':dubsapp:generateDevelReleasePlayResources'.
[11:16:41]W:	 [Step 4/6] 11:16:41.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Unknown file: /home/.../src/main/play/en-US/listing/title.txt

### To Reproduce

run
./gradlew publishReleaseApk

#### Versions

 - Gradle Play Publisher: 2.0.0-SNAPSHOT
 - Gradle Wrapper (if applicable): 4.6
 - Android Gradle Plugin (if applicable): 3.2.1

### Additional context

Also tasks ./gradlew :app:generateDevelReleasePlayResources give errors like
Unknown file: /home/.../app/src/main/play/en-US/listing/full-description.txt

With publisher 1.2 this worked (without .txt extensions)

**Comment by SUPERCILEX** [comment]
Use the final 2.0.0 version (not snapshot).

**Comment by FilenkovMaxim** [comment]
There is no final version in Maven.
See [issue 473](https://github.com/Triple-T/gradle-play-publisher/issues/473)

```
Could not find com.github.triplet.gradle:play-publisher:2.0.0.
Searched in the following locations:
    https://jcenter.bintray.com/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://jcenter.bintray.com/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
    https://repo.maven.apache.org/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://repo.maven.apache.org/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
    https://dl.google.com/dl/android/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://dl.google.com/dl/android/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
    https://oss.sonatype.org/content/repositories/snapshots/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://oss.sonatype.org/content/repositories/snapshots/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
```

**Comment by SUPERCILEX** [comment]
We're not on maven. See the README for installation instructions.

**Comment by SUPERCILEX** [comment]
Oh, check your settings.gradle file and make sure you aren't overwriting the repositories. Or if you are, add the `pluginsPortal()` repo.

**Comment by FilenkovMaxim** [comment]
There is only one line in my settings.gradle
`include ':app'`

**Comment by SUPERCILEX** [comment]
Huh, well that's weird. Can you show me your root build.gradle file?

**Comment by FilenkovMaxim** [comment]
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        // You need to add the following repository to download the new gradle plugin.
        google()
        maven{url 'https://oss.sonatype.org/content/repositories/snapshots'}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.2.0' // google-services plugin
        classpath 'com.github.triplet.gradle:play-publisher:2.0.0-SNAPSHOT'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven{
            url "http://api.genymotion.com/repositories/releases/"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by SUPERCILEX** [comment]
Remove the classpath declaration.

**Comment by FilenkovMaxim** [comment]
Or another run
[19:26:31]
[Step 4/6] 19:26:31.713 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':dubsapp:generateDevelReleasePlayResources'.
[19:26:31]
[Step 4/6] 19:26:31.713 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Unknown file: /home/ubuntu/TeamCityBuildAgents/buildAgent-0/work/Dev-cluster/android-app/dubsapp/src/main/play/en-US/listing/title.txt

**Comment by SUPERCILEX** [comment]
Please pretend like you haven't used GPP before and go through the whole README like that. It will save us a lot of back and forth.

For your example, the path should be `listings/en-US/...`.

**Comment by FilenkovMaxim** [comment]
I see.
You changed folders order
I need to use play/listings/[language]

**Comment by SUPERCILEX** [comment]
Here's the bit about directory structures: https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#directory-structure

**Comment by FilenkovMaxim** [comment]
Yes, it saves. But not when I already had a ready-made file structure, and then I need to notice any small changes in the path or something like that. It is really difficult.
But thank you very much for your help and for the good plugin, it's pretty good thing!

**Comment by SUPERCILEX** [comment]
Yeah, we tried to be as clear as possible in the release notes, but I will admit that we broke a lot of stuff. 😊
