### ISSUE TITLE
We have a device that is proprietary and it is running Android 9.0.  It has no user interface.  How can we continually push new versions using gradle.  This APK is the first thing that starts after the operating system starts up.  There is no screen just responds to voice commands.  Could we use gradle to push new versions of this APK to users?  It also has some external libraries that we push to the SD memory card which would not need to be updated regularly.  I cant find a good solution for this anywere.  If you have this ability in gradle that would be awesome. thank you! Mark

### ISSUE THREAD

**Issue by roninstar** [Triple-T/gradle-play-publisher#482]
**Is your feature request related to a problem? Please describe.**
We have a device that is proprietary and it is running Android 9.0.  It has no user interface.  How can we continually push new versions using gradle.  This APK is the first thing that starts after the operating system starts up.  There is no screen just responds to voice commands.  Could we use gradle to push new versions of this APK to users?  It also has some external libraries that we push to the SD memory card which would not need to be updated regularly.  I cant find a good solution for this anywere.  If you have this ability in gradle that would be awesome. 
**Describe the solution you'd like**
from the command line be able to push new versions of this APK so that when the device is restarted or the next time the APK launches it would get updated without prompting the user.

**Describe alternatives you've considered**
A custom bootstrap that checks the version on a server location and automatically updates the APK and files on start up.

**Additional context**
Add any other context about the feature request here.

**Comment by NiciDieNase** [comment]
This plugin pushes apps to the playstore, sounds like you would like to push directly to a device.

Maybe something like [gradle-android-command-plugin](https://github.com/novoda/gradle-android-command-plugin) could be what you are looking for.

**Comment by SUPERCILEX** [comment]
Yeah, your request isn't clear. @NiciDieNase's response sounds fair.
