### ISSUE TITLE
Release version 2.0.0 not available in mavenCentral

### ISSUE THREAD

**Issue by ramack** [Triple-T/gradle-play-publisher#485]
### Describe the bug
When I add
`classpath 'com.github.triplet.gradle:play-publisher:2.0.0'`
in my build.gradle

I get the error
```
Could not find com.github.triplet.gradle:play-publisher:2.0.0.
Searched in the following locations:
    https://jcenter.bintray.com/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://jcenter.bintray.com/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
    https://repo.maven.apache.org/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://repo.maven.apache.org/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
    https://maven.google.com/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://maven.google.com/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
    https://dl.google.com/dl/android/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.pom
    https://dl.google.com/dl/android/maven2/com/github/triplet/gradle/play-publisher/2.0.0/play-publisher-2.0.0.jar
```

#### Versions
 - Gradle Play Publisher: 2.0.0
 - Gradle Wrapper (if applicable):
Gradle 4.6
Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Linux 3.16.0-7-amd64 amd64

 - Android Gradle Plugin (if applicable):
2.0.0

### Expected behavior
I would expect that everything works fine, as 2.0.0 is released, I get it working only if I change to:
`classpath 'com.github.triplet.gradle:play-publisher:2.0.0-rc1'`
in my build.gradle

**Comment by SUPERCILEX** [comment]
This is normal, we aren't on maven central anymore. See #480.

**Comment by SUPERCILEX** [comment]
And the release notes: https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-rc2

**Comment by ramack** [comment]
Thanks for the pointer. I did not get the point about how to make the plugin stuff work. I always got errors about "plugin" begin unknown.

After I moved 
```
plugins {
    id("com.android.application")
    id("com.github.triplet.play") version "2.0.0"
}
```
to the very beginning of my app/build.gradle it works. I also was doubting what to do because in the Readme you mention only Kotlin and Groovy, which I both do not use...
