### ISSUE TITLE
Plugin not found when added via "apply plugin"

### ISSUE THREAD

**Issue by cachapa** [Triple-T/gradle-play-publisher#491]
I contacted on of the developers via email and he asked me to create a bug report.

Gradle can't find the plugin when added via the `apply plugin` keyword unless `plugins.gradle.org` is explicitly added to the repository list.

The following works, but removing `maven { url "https://plugins.gradle.org/m2/" }` causes the build to fail:

Project build.gradle:
``` groovy
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.github.triplet.gradle:play-publisher:2.0.0'
    }
}
(...)
```

App module build.gradle:
``` groovy
apply plugin: 'com.android.application'
apply plugin: 'com.github.triplet.play'
(...)
```

**Comment by cachapa** [comment]
I emailed @ChristianBecker regarding adding that to the project's readme since it wasn't clear how to do it, and he suggested it was a bug.

In this case I would renew my proposal to add this to the documentation since it took me a while to figure it out and I think it could help others.

**Comment by SUPERCILEX** [comment]
Normally, you use the `plugins` block and _not_ `classpath`. The maven thing isn't required with the `plugins` block. Do you have a reason for using `classpath`?

**Comment by cachapa** [comment]
Essentially for familiarity and coherence with the rest of the code.

I'm not very familiar with the plugins block so please excuse me if I'm wrong but it seems the block can only be applied on the project's build file. We have multiple modules and the classpath method allows us to only apply the plugin in the app module.

Also, according to [this documentation](https://docs.gradle.org/4.10.2/userguide/plugins.html#sec:plugins_block) it seems that block is still an incubating feature.

**Comment by cachapa** [comment]
I'll look into using the plugins block. In any case it's comforting to know that the classpath method works even if it's not recommended.

In any case thanks for the help.

**Comment by calvarez-ov** [comment]
I would like to be able to put all our config regarding publishing inside a `publish.gradle` file. 

Our app `build.gradle` has:

```gradle
apply from: file('publish.gradle')
```

It looks like it won't be possible to isolate everything inside `publish.gradle`. The plugin declaration must be inside `app.gradle`. Is that right?
