### ISSUE TITLE
publishListing shouldn't fail when other files apart from locale folders exist

### ISSUE THREAD

**Issue by carstenhag** [Triple-T/gradle-play-publisher#493]
**Is your feature request related to a problem? Please describe.**
The `publishListing` job fails, when there are non-locale folders/files in the `listings` folder.

```
> Task :app:generateReleasePlayResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateReleasePlayResources'.
> Invalid locale: feature-graphic.psd

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

Relevant folder structure:
```
carst@DESKTOP-S6HS89M MINGW64 ~/Documents/git/dhbw/android-mosbach-map/app/src/main/play (master)
$ find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
.
 |-listings
 | |-de-DE
 | | |-full-description.txt
 | | |-graphics
 | | | |-feature-graphic
 | | | | |-1.png
 | | | |-icon
 | | | | |-icon.png
 | | | |-phone-screenshots
 | | | | |-1.png
 | | |-short-description.txt
 | | |-title.txt
 | |-feature-graphic.psd
 | |-icon-orange.png
 | |-icon-teal.png
 | |-icon.png
 | |-icon.psd
```

**Describe the solution you'd like**
Ignore files from the folders.

**Describe alternatives you've considered**
Keep it as is now and force the user to remove existing files, eg for me:

```
 | |-feature-graphic.psd
 | |-icon-orange.png
 | |-icon-teal.png
 | |-icon.png
 | |-icon.psd
```

**Comment by SUPERCILEX** [comment]
> Keep it as is now and force the user to remove existing files

That's the idea. Do you mind me asking why you want to put other files there? We just added a commit to ignore hidden files, not sure if that helps: #471.

Here's the philosophy behind the `play` folder: _everything_ in it is uploadable material that can be committed to the Play Store. If we start letting people put whatever they want in there, I feel like it will turn into a mishmash of random files and no one will know what's actually being uploaded to the Play Store.

**Comment by SUPERCILEX** [comment]
The reason we crash if it's _invalid_ as specified by the README is for UX purposes. Imagine you accidentally type `full-desription.txt`... did you catch the typo? I forgot the `c` after the `s`. Without crashing, you would get grumpy thinking the plugin isn't working or file an issue we have to spend time debugging. With the crashes, it's quite clear that something is amiss with that file.

PS: Once `v2.1.0` is released, you will be able to create a `.raw-graphics` folder (or any other hidden one) to put your photoshop files in.

**Comment by carstenhag** [comment]
Ah I see, yes. With hidden folders everything stays great! Thanks!
