### ISSUE TITLE
Instructions for migrating to v2.0.0

### ISSUE THREAD

**Issue by orionlee** [Triple-T/gradle-play-publisher#496]
Instructions for migrating from v1.2.x to v2.0.0 seems to be a tad scattered, especially for developers not terribly familiar with gradle.

It'd be great if it's included in `README`

**Comment by orionlee** [comment]
The following is what I have to do. It'd be great to have something similar included.

1. In project root `build.gradle`, remove `classpath "com.github.triplet.gradle:play-publisher:1.2.0"` from `buildscript { dependencies {` block. 

2. In each `com.android.application` module where you want to use GPP, 
  2a. remove `apply plugin: 'com.github.triplet.play'`, and 
  2b. apply it with `plugins {}` DSL
```
plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '2.0.0'
}
```

3. If you supply credentials with PKCS12 key, change `pk12File` to `serviceAccountCredentials` in `play{}` block: 
```
play {
    serviceAccountEmail = 'your-email-address'
    serviceAccountCredentials = file('your-key.p12') 
}
```

**Comment by SUPERCILEX** [comment]
Yeah, sorry about that. Here they all are: [beta1](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-beta1#breaking) -> [beta2](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-beta2#breaking) -> [rc1](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-rc1#breaking) -> [rc2](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0-rc2#breaking) -> [release](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.0.0#breaking). The main problem is that we kinda broke everything (sorry! 😊). I would personally recommend pretending like you haven't used GPP before and starting fresh by following the README. Does that help?

**Comment by SUPERCILEX** [comment]
Whoa, we posted at the same time!

**Comment by SUPERCILEX** [comment]
Yeah, that goes back to my point of kinda breaking everything. We really weren't happy about it, but we felt it was necessary to modernize the plugin. So I think my recommendation to start fresh makes sense. WDYT?

**Comment by orionlee** [comment]
I think either suggesting starting fresh or provide instruction, as long as it is stated in README. 

It is too tempting to simply change the version in `dependencies { classpath ` based on current README.

**Comment by AndreSand** [comment]
Thanks for opening issue, I also had problem following README.md for migrating from v1.2.x to 2.1.0. It looks like below code has to go on the top of file build.gradle.
Line 1:
`plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '2.1.0'
}`

**Comment by cosic** [comment]
When I used instruction from README for v2.1.0 I've got error:
 ```> Could not find com.github.triplet.gradle:play-publisher:2.1.0``` 

In https://mvnrepository.com/artifact/com.github.triplet.gradle/play-publisher/2.1.0 I found new repo url:
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}
```
It works.

**Comment by SUPERCILEX** [comment]
@cosic You shouldn't be using `classpath`. See the README for correct usage.

**Comment by SUPERCILEX** [comment]
I'm going to close this since it's been several months and I've kinda forgotten the old way of doing things. If someone still wants to write a guide, I'd be happy to review it.
