### ISSUE TITLE
doesn't work with testCoverageEnabled true

### ISSUE THREAD

**Issue by MHPtweidinger** [Triple-T/gradle-play-publisher#498]
First of all, thank you for the nice plugin. Today, unfortunately we just discovered a potential bug.  If you set `testCoverageEnabled true` in the release flavor of the app, the plugin doesn't work anymore and doesn't throw an error. Is there something we can do about this?

**Comment by SUPERCILEX** [comment]
What's the error?

**Comment by MHPtweidinger** [comment]
there is no error in terms of an exception. the task execution for `gradle publish` simply does nothing and finishes within 1 second. 
also tasks like `gradle publishRelease` are not available anymore when we activate testCiverage on the  release buildType.

**Comment by SUPERCILEX** [comment]
`testCoverageEnabled true` is invalid for release builds:
- https://stackoverflow.com/a/40084149/4548500
- https://github.com/paveldudka/JacocoEverywhere/issues/7#issuecomment-197455000

**Comment by MHPtweidinger** [comment]
okay, didn't know that. thanks for the heads up. but some sort of log entry or exception would be nice and might safe others hours of investigation, like it took us today to find the root cause of the plugin not working anymore. but still, nice plugin. we appreciate it.

**Comment by SUPERCILEX** [comment]
We do log it at the `info` level (so you'd have to run `./gradlew ... --info`). We can't change that otherwise all debug builds would be logging warnings. 😢

**Comment by SUPERCILEX** [comment]
Actually, you know what!? We can check to see if the name contains "release" and log it as a warning then. Doing that rn.

**Comment by MHPtweidinger** [comment]
yeah, thanks. and congrats on the 500th pull request ;)

**Comment by SUPERCILEX** [comment]
Hehe, thanks 😁
