### ISSUE TITLE
build error use gradle 2.3

### ISSUE THREAD

**Issue by googolmo** [Triple-T/gradle-play-publisher#50]
now i use gradle version 2.3
android build gradle version 1.1.3
play-publisher version 1.0.2

the error is 

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method play() for arguments [build_b6dp6swbwb3sfm4ofhfloa9zh$_run_closure4@477c7b19] on project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

but use gradle version 2.2.1 it's can work perfact!

**Comment by bhurling** [comment]
I've tried with gradle 2.3 and get the exact same error. It seems they changed how plugin extensions are handled.

The extension is registered through `project.extensions.create()` in the `PlayPublisherPlugin`

@hzsweers: Any idea how we might solve this? Do we need a setter for the plugin extension?

**Comment by hzsweers** [comment]
I have no idea :frowning:. Does the android gradle plugin officially support 2.3 yet? I don't see any mention of it [here](http://tools.android.com/tech-docs/new-build-system)

**Comment by emanuelet** [comment]
There is definetely some breaking changes in [2.3](https://gradle.org/docs/current/release-notes). 
I tried also with the 1.2.0-beta1 plugin version and it didn't worked. Rolled back to 2.2.1 and it ffinally did. 

Android Studio was giving the following error:
`Gradle DSL: couldn't find the plugin play()`; the funny thing is that it was happening only with the `play { ... }` block present and not with the line `apply plugin: 'play'` alone.

**Comment by emanuelet** [comment]
If I can make a suggestion, an example build.gradle file in the readme will be very helpful to have a reference. It took various attempts, for instance, to understand if the classpath goes into the main project gradle on in the app module one

**Comment by tasomaniac** [comment]
I have exact the same problem. Does anyone know anything how we fix that? Thank you.

**Comment by blundell** [comment]
bump

**Comment by tasomaniac** [comment]
I've confirmed today that it gives the same error with gradle2.4

I saw a new feature branch here uses gradle2.4 itself. Is it going to be fixed soon? How can we help?

**Comment by bhurling** [comment]
A little explanation: gradle 2.3 brings an internal plugin called `org.gradle.play.plugins.PlayPlugin` that is registered for the plugin id `play`. This is why our plugin is no longer loaded and that causes all the issues we have seen like missing tasks and missing methods.

The solution: I renamed the plugin and use reverse domain naming like most other plugins out there. This is a breaking change so we should consider a major version bump.

**Comment by tasomaniac** [comment]
oh I see. Can you push a SNAPSHOT version for us to use the fixed version before the release.

**Comment by bhurling** [comment]
Done. Version 1.1.0-SNAPSHOT

Said Tahsin Dane <notifications@github.com> schrieb am Fr., 8. Mai 2015
23:17:

**Comment by hzsweers** [comment]
Wonderful, good to see this is resolved! Been wanting to try out gradle 2.4
since it has a vastly improved configuration time

**Comment by tasomaniac** [comment]
Working great with 1.1.0-SNAPSHOT version. Thank you. 

Although, I didn't see any performance improvement with gradle 2.4
