### ISSUE TITLE
Customize 'Release name' in playstore

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#502]
After uploading apk to play store there is possible to put own **Release name**, it is by default fill with versionCode.

I was originally expected that

    outputProcessor { // this: ApkVariantOutput
        versionNameOverride = 'pokus'
    }

will do this works, but it looks that it does nothing.

Is there any way how to modify it by the plugin?
Or there is a limitation on Google Play API side?

Plugin version 2.0.0

**Comment by tprochazka** [comment]
There is some name
https://developers.google.com/android-publisher/tracks#specifying_release_notes
{
  "releases": [{
      "name": "My draft release",
      "versionCodes": ["88"],
      "status": "draft"
  }]
}

Hard to say if it is the same like in UI.

**Comment by SUPERCILEX** [comment]
The `versionName` and its override apply to the APK (that's what appears in system settings). The Play Store name is just for you, the developer, to identify one specific APK out of the shapeless artifact sea.

I've personally never seen the point. What's your use case? Also, if give every APK the same codename, then it's kinda pointless.

**Comment by tprochazka** [comment]
"The Play Store name is just for you, the developer, to identify one specific APK out of the shapeless artifact sea." yes and this is exactly the point why I want to change it.  When we want to release for example version 1.0.0, we need to have several RC version released to beta groups, before we handle all the bugs. VersionCode is, of course, different for every build, but it very unfriendly for us. So we always change the release name to 1.0.0 RC1, 1.0.0 RC2, etc. And when we found that 1.0.0 RC8 is really stable we release it from beta channel to production. So now we deploying the app automatically, but we still need to put the version suffix there manually.  Our build plugin knows the version suffix, so would great make it really fully automatic, if it is possible.

**Comment by SUPERCILEX** [comment]
I'm not quite sure I understand: when I release a new version, the Play Store name is whatever I set as the app's version name. Ex:
![image](https://user-images.githubusercontent.com/9490724/51498755-92598000-1d7c-11e9-8c81-a2abf544896a.png)

Where do you want the name to come from?

**Comment by tprochazka** [comment]
My versionName inside of apk is just 1.0.0, I cannot change it to something different, because it is used in many backend systems like analytics, from the marketing point of view there is just one version 1.0.0.
But for us, there are several RC version which we need to distinguish in play store.

So I need someting like:

   play {
       customReleaseName versionProvider.getInternalName()
   }

**Comment by SUPERCILEX** [comment]
Gotya. 👍

**Comment by SUPERCILEX** [comment]
This will be available in v2.2.0. While waiting for that to ship, please let me know what you think by trying a [snapshot build](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#snapshot-builds).

Lightning docs:
Add an `app/src/main/play/release-names` folder. In there, place `[track-name].txt` files with the text for your release. Ex:
```
[alpha.txt]
My custom release name (max 50 chars)
```

**Comment by tprochazka** [comment]
Thanks. 
Is there any way how to change it programmatically? I don't need it in the file.

I need to setup it dynamically in the build script as I mentioned it here:
https://github.com/Triple-T/gradle-play-publisher/issues/502#issuecomment-456198672

**Comment by SUPERCILEX** [comment]
Nope, you can only do it through the file for a few reasons:
1. Consistency: the `play` block is for configuring the plugin, not the content it uploads
1. We need ways to differentiate between the tracks

Reasoning aside, it's super easy to write to the file. Just add this wherever you're setting the release name:
```
file('app/src/main/play/release-names/alpha.txt') << versionProvider.getInternalName()
```

Or you could do something like this if you don't know when the value is being updated:
```gradle
task prepAppUpload() {
    doLast {
        file('app/src/main/play/release-names/alpha.txt') << versionProvider.getInternalName()
    }
}
tasks.getByName("publishReleaseApk") { dependsOn('prepAppUpload') }
```

**Comment by tprochazka** [comment]
I don't need to differentiate between tracks. Why? Release name is still the same name since I upload it to internal track and then push it to alpha, beta, release. Why do you think that somebody will need to have different name base on tacks where it is uploaded? I'm uploading just to the internal stage (developer builds) or alpha (release candidate builds) and then move them to beta or release if they pass QA without changing the name. But since this plugin always upload just to one track in one run, it is really easy to change the name based on track. Like:

```
play {
    track = isInternalBuild() ? 'internal' : 'alpha'
    releaseStatus = = 'completed'
    customReleaseName = isInternalBuild() ? 'internal build name : 'alpha build name'
    defaultToAppBundles = true
}

```

It is even harder in my situation. Because of our build plugin check that local copy is not modified against GIT commit and forbid to create release build if there is some modification. We want to be sure that build exactly match the source in the repository. The second way should work because it will be after this check, but it is super ugly

**Comment by SUPERCILEX** [comment]
Currently, everything is file based. Maybe in some distant future we'll start adding configuration options that specify content to be uploaded, but that's unlikely since it will make Gradle caching and up-to-date checks harder, incur memory costs, make versioning harder, etc.

And yeah, I know it doesn't fit your use case perfectly, but unfortunately, this plugin can't be targeted at a specific developer. ¯\_(ツ)_/¯ And I don't think it's _that_ bad:
```gradle
task prepAppUpload {
    mustRunAfter 'taskThatChecksForUncommittedChanges' // Or just add the file to the .gitignore

    doLast {
        file('app/src/main/play/release-names/${play.track}.txt') << isInternalBuild() ? 'internal build name : 'alpha build name'
    }
}
tasks.getByName("publishReleaseBundle") {
    dependsOn 'prepAppUpload'
    doLast { project.delete('app/src/main/play/release-names/${play.track}.txt') }
}
```

But I would actually think about how you're setting up the internal version name. If you're manually hardcoding it, why not simply commit the name to that play file? Or if you're generating it on the fly in that custom plugin of yours, why not have the plugin handle generating the file? You shouldn't need the hack above once you figure where all your data is coming from.

**Comment by tprochazka** [comment]
The internal version name is based on GIT tag. I Just tag some commit with a version like 1.0.0-RC1.
And build server automatically build it. 1.0.0 is the versionName of APK and 1.0.0-RC1 is internal version name. So I don't know it in the commit time.

I'm not sure if caching and up-to-date check is really issue for setting some non-file input. I think that gradle can handle also string/number as input parameter, not only file. 

But I understand. I will do it by creating a file during build time. Managing own fork is definitely more complicated that this. Thanks.

**Comment by tprochazka** [comment]
I did this quite a nice solution:

```
    project.afterEvaluate {
        def file = file("src/main/play/release-names/${play.track}.txt")
        def tsk = tasks.findAll { task -> task.name.startsWith('publish') }
        tsk*.doFirst {
            file.parentFile.mkdirs()
            file.write(versionProvider.getVersion())
        }
        tsk*.doLast {
            file.delete()
        }
    }
```

But it looks that it is not enough, the file is created probably too late and your task probably read the file.

To have API for that would be really much better.

**Comment by SUPERCILEX** [comment]
Yeah, not bad! This will work:
```
    project.afterEvaluate {
        def file = file("src/main/play/release-names/${play.track}.txt")
        def tsk = tasks.findAll { task -> task.name.startsWith('generate') && task.name.endsWith('PlayResources') }
        tsk*.doFirst {
            file.parentFile.mkdirs()
            file.write(versionProvider.getVersion())
        }
        tsk*.doLast {
            file.delete()
        }
    }
```

**Comment by SUPERCILEX** [comment]
PS: I'm also considering adding a property to the task itself. Follow #590 for updates.

**Comment by tprochazka** [comment]
Great news!

I ended with this solution, which works

```
    project.afterEvaluate {
        def file = file("src/main/play/release-names/${play.track}.txt")
        def tsk = tasks.findAll { task -> task.name.startsWith('publish') }
        def createTask = project.tasks.register("createProjectVersion") {
            doLast {
                file.parentFile.mkdirs()
                file.write(versionProvider.getVersion())
            }
        }
        tsk*.dependsOn createTask
        tsk*.doLast {
            file.delete()
        }
    }

```

**Comment by tprochazka** [comment]
Your solution works! Thanks.

**Comment by SUPERCILEX** [comment]
With #599, you'll be able to do this:
```kt
tasks.withType<PlayPublishArtifactBase>().configureEach {
    releaseName = versionProvider.getVersion()
}
```

> Note: this isn't an official API and it could break at any time

**Comment by tprochazka** [comment]
I just updated to 2.3.0 and previous hacky way with files stops working, so I switch to this much better solution. And it looks that its works. Thanks a lot!!!

**Comment by tprochazka** [comment]
It's OK. The only important thing is that it will still work somehow. Doesn't matter how. 
Maybe some days in the future it will end up with something like ;-)
```
play {
    customReleaseName versionProvider.getInternalName()
}
```

**Comment by tprochazka** [comment]
It looks that 
> tasks.withType<PlayPublishArtifactBase>().configureEach {
>     releaseName = versionProvider.getVersion()
> }

It doesn't work in 2.6.0 :-(

**Comment by SUPERCILEX** [comment]
@tprochazka yup, it's been promoted! I gave in and there's now a [`play.releaseName`](https://github.com/Triple-T/gradle-play-publisher/blob/abddfe9addb74eb41c25b84669c1849d0935e69d/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherExtension.kt#L199) property. Looks like I forgot to update the docs though.

**Comment by SUPERCILEX** [comment]
Docs updated: https://github.com/Triple-T/gradle-play-publisher#uploading-developer-facing-release-names

**Comment by tprochazka** [comment]
Thanks a lot! I stay with accessing PlayPublishArtifactBase until now when I'm converting everything to Kotlin DSL.
So I will try to use this way. I hope that it is enough to change this property any time before the upload task start.
