### ISSUE TITLE
Limit publishing to subset of all build variant

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#503]
I have something like 20 different build variants, but only 3 of them are published to Google Play. I did not found any way how to limit create publish task to some subset of all build variant. I can publish only explicitly name build variant, but much better would be some way how to limit it.

For example in a similar way like you can limit multidimensional flavor combinations:

    variantFilter { VariantFilter variant ->
                ... some logic ...
          if (something) {    
                variant.setIgnore(true)
          }
    }

I mean with some callback.
But simply list of all enabled buildVariant would be enough, like
  
    play {
         limitToBuildVariants ['customer1FullRelease', 'customer1DemoRelease']
    }

plugin version 2.0.0

**Comment by SUPERCILEX** [comment]
We've had similar requests before, but I don't understand the use case yet. So you have 20 release builds? And why are only 3 published? Do you use setIgnore on them? Why are you applying your release signing configs to them?

In general, I'm trying to understand this type of use case.

**Comment by SUPERCILEX** [comment]
K, that makes sense. 👍

**Comment by tprochazka** [comment]
Thanks a lot! I'm just testing it, but it is weird. I updated plugin to 2.2.0 and I'm getting this error:

`> Could not set unknown property 'isEnabled' for object of type com.github.triplet.gradle.play.PlayPublisherExtension.`

Maybe It is my fault.

I have this setup
```
play {
    track = isSnapshotBuild() ? 'internal' : 'internal'
    releaseStatus = track == isSnapshotBuild() ? 'draft' : 'completed'
    defaultToAppBundles = true
    isEnabled = false
}

    playConfigs {
        a {
            serviceAccountCredentials = file('play/a_play_developer_api.json')
            isEnabled = true
        }

        b {
            serviceAccountCredentials = file('play/b_play_developer_api.json')
            isEnabled = true
        }

        c {
            serviceAccountCredentials = file('play/c_play_developer_api.json')
            isEnabled = true
        }

    }
```

**Comment by tprochazka** [comment]
It looks that it's working as expected.
At least it trying to upload just enabled variant.
It always end with

```
  {
    "code" : 500,
    "message" : null
  }

```
But I hope that it is just some temporary issue on Google side.

**Comment by SUPERCILEX** [comment]
Man, you really have been unlucky with those 500s. Can you try running the Gradle task again with --stacktrace so I can see which API call failed?

**Comment by tprochazka** [comment]
Yes. Now 5 hours later it's working.
