### ISSUE TITLE
Reliability of publishing

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#504]
After some time I found that reliability of publishing is quite bad. It is probably not a problem of the plugin itself, but it quite often ends with an error like

```
Execution failed for task ':app:publishDefaultReleaseBundle'.
[13:07:27]	> java.net.SocketTimeoutException: Read timed out

```
or
```
Execution failed for task ':app:publishDefaultReleaseBundle'.
[14:32:12]	> com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
[14:32:12]	  {
[14:32:12]	    "code" : 500,
[14:32:12]	    "message" : null
[14:32:12]	  }

```

And if you run it on TC it always fails the whole build just because of that.
Would be great to have possible to configure that it will not stop whole Gradle build if it fails.
And the possibility to repeat the whole action if the success of publishing is really important.
Especially in temporary error like like in this case, in case of a network error

Something like
```
play {
  failOnPublishFailed false
  repeatUploadCount 3
}
```

Plugin version 2.0.0

**Comment by tprochazka** [comment]
Maybe also SocketTimeoutException is too low.

**Comment by bhurling** [comment]
In version 2.1.0 we bumped up the socket timeout from less than 2 minutes to 5 minutes (see #479). Would you mind trying that version to see if it improves your situation?

**Comment by tprochazka** [comment]
Of course. I'm just testing it.

**Comment by tprochazka** [comment]
Sorry for delay, here is full stacktrace
https://gist.github.com/tprochazka/3c47909b0c1b035880170449cf1992ca

And after update to 2.1.0 it looks much better!

**Comment by SUPERCILEX** [comment]
Interesting, it's the [mapping file upload](https://github.com/Triple-T/gradle-play-publisher/blob/3e86503431794792dc63dd6b5bb51e03493f1ed7/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/internal/PlayPublishPackageBase.kt#L153) that fails. Since that's fairly low priority, we can retry 3 times and then just ignore the 500 error if it keep crashing.

**Comment by tprochazka** [comment]
Great. I was recently curious if is possible to upload mapping wile automatically. Now I know that plugin is already able to do that!

**Comment by tprochazka** [comment]
Now very often happen this
https://gist.github.com/tprochazka/2a61457f3cad980c36aa6f56b43c5124

The main issue is that we have a chain of jobs on TeamCity and if the build fails just because of publishing everything relying on it also fail. Maybe a possibility to set up these tasks to not fail the whole build if upload fail would be really the best way.

**Comment by SUPERCILEX** [comment]
v2.2.0 should fix the timeout issues (#540), but I'm going to hold off on the retry stuff. If you run into another 500 error, please send me the stack trace. I want to know if it's always one API failing or a mix.

**Comment by SUPERCILEX** [comment]
I'm going to close this for now, but please do share a stack trace if another error occurs.

**Comment by tprochazka** [comment]
Thanks!
