### ISSUE TITLE
Gradle task to publish Release notes?

### ISSUE THREAD

**Issue by AndreSand** [Triple-T/gradle-play-publisher#507]
It's not a bug: I noticed that to publish "release notes" I need to run the gradle task: $`./gradlew publishBundle`, is it possible to run a task to update only the Release notes? Seems like updating the bundle and release notes go together? thanks.

**Comment by SUPERCILEX** [comment]
Yeah, use `./gradlew promoteArtifact --from-track beta --track beta`. Currently, `default.txt` is ignored but that will be fixed in #506.

**Comment by AndreSand** [comment]
Oh okay got it, thanks! 👍
