### ISSUE TITLE
Release notes are not uploaded/publishListing doesn't run at all

### ISSUE THREAD

**Issue by carstenhag** [Triple-T/gradle-play-publisher#509]
### Describe the bug

`publishListing` does not upload Release Notes. I can't see them anywhere on the Play Console, at least. Tried 2.0.0 and 2.1.0. Play Console says that there are no release notes. "Previous release notes" also doesn't contain any new ones.

<img width="1008" alt="bildschirmfoto 2019-01-28 um 22 54 54" src="https://user-images.githubusercontent.com/3776997/51869036-c1a95780-234f-11e9-93bc-27dc6441de0d.png">

My play config is the following. The app was uploaded to the alpha track, but there are no alpha tasks, so I ran `publishListing`.

### To Reproduce

```groovy
play {
    serviceAccountCredentials = file("../playstoreapi.json")
    track = "alpha"
    defaultToAppBundles = true
    resolutionStrategy = "auto"
}
```

Also: `publishListing` doesn't seem to register file-changes inside the release notes directory.  
After being run once, it just exits immediately the second time it has been ran.

#### Versions

 - Gradle Play Publisher: 2.1.0
 - Gradle Wrapper (if applicable): 5.1.1
 - Android Gradle Plugin (if applicable): 3.3.0
 
### Expected behavior

Release notes (be it alpha.txt, default.txt) should upload.

### Additional context

```
app/src/main/play/release-notes/de-DE/alpha.txt
app/src/main/play/release-notes/de-DE/default.txt
app/src/main/play/release-notes/de-DE/internal.txt
```

```
Publishing tasks
----------------
app:bootstrap - Downloads the Play Store listing metadata for all variants.
app:bootstrapReleasePlayResources - Downloads the Play Store listing metadata for Release.
app:promoteArtifact - Promotes a release for every variant.
app:promoteReleaseArtifact - Promotes a release for Release.
app:publish - Uploads APK or App Bundle and all Play Store metadata for every variant.
app:publishApk - Uploads APK for every variant.
app:publishBundle - Uploads App Bundle for every variant.
app:publishListing - Uploads all Play Store metadata for every variant.
app:publishProducts - Uploads all Play Store in-app products for every variant.
app:publishRelease - Uploads APK or App Bundle and all Play Store metadata for Release.
app:publishReleaseApk - Uploads APK for Release.
app:publishReleaseBundle - Uploads App Bundle for Release.
app:publishReleaseListing - Uploads all Play Store metadata for Release.
app:publishReleaseProducts - Uploads all Play Store in-app products for Release.
```

Possibly related to #440 but I'm using the newest version. Actually, there are many related issues.

**Comment by SUPERCILEX** [comment]
`publishListing` has nothing to do with release notes. The listing is about your app name, graphics, description, etc. It doesn't necessarily change with each app update. To upload release notes to an existing artifact, see https://github.com/Triple-T/gradle-play-publisher/issues/507#issuecomment-458291682. Otherwise, use `publish[Bundle/Apk]`.

**Comment by carstenhag** [comment]
That seems to be it. Thanks!
