### ISSUE TITLE
Get current version code and version name

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#511]
Is there a way to get current version codes and version names of all tracks. eg. release, beta, alpha, ... from Playstore

If it's possible, please can you provide an example how to do so ?

Thank you !

**Comment by SUPERCILEX** [comment]
Nope. We're not trying to duplicate the play console—rather, we want to make publishing apps as easy as possible. If you're trying to see how your app is doing, the visual console is a much better medium.
