### ISSUE TITLE
Replace apk in draft

### ISSUE THREAD

**Issue by dmytro-ostapovets** [Triple-T/gradle-play-publisher#512]
Hello. I'd like to have possibility to replace apk  in draft for alpha track.
For Example:
I sent apk-1 to draft in alpha track.
Then we found a bug and sent apk-2 to alpha track.
Default behavior is: 
apk-1 is pushed to beta track, apk-2 - to alpha track.
Is it possible to just replace apk-1 by apk-2 in alpha track?

**Comment by SUPERCILEX** [comment]
I'm not sure I understand. Can you share your `play` block and the exact tasks you executed?

**Comment by dmytro-ostapovets** [comment]
Here is our play block:

`play {`
    `track = 'alpha'`
    `serviceAccountCredentials = file("publish.json")`
    `releaseStatus = "draft"`
`}`

I'll try to explain question again.
Let's assume that we already have apk in alpha track draft. Then we upload another apk with some fixes. And my problem is that previous apk is promoted to beta track, but I don't need that, I just want to replace apk  in alpha track.

**Comment by SUPERCILEX** [comment]
What tasks are you executing?

**Comment by SUPERCILEX** [comment]
@dmytro-ostapovets I'm going to close this issue for now, but please do let me know if you're still running into it.
