### ISSUE TITLE
How To Increase Rollout Percentage

### ISSUE THREAD

**Issue by sdoward** [Triple-T/gradle-play-publisher#515]
Apologies for opening an issue for support but I don't see another channel.

It's unclear how I can increase a rollout percentage. Do I need to use the `promoteArtifact` task?

The readme doesn't show how this is possible so perhaps the readme can be improved? Happy to send a PR once this is clarified

**Comment by SUPERCILEX** [comment]
You're right, our README is lackluster. Let me know if this is what you're looking for: https://github.com/Triple-T/gradle-play-publisher/pull/523/files

**Comment by christxph** [comment]
I didn't want to create a new ticket, but according to the @sdoward's original description he wants to increase the roll-out percentage of an existing track and _not_ promote a release from `alpha` to `beta` like in the PR you linked (#523)

So is there a way to increase the roll-out percentage of an existing track? E.g. can I do the followin to increase the roll-out percentage of the `production` track to 50% and the percentage of the `beta` track to 10%:
```
./gradlew promoteArtifact \
  --track production \
  --release-status inProgress --user-fraction .5
```

```
./gradlew promoteArtifact \
  --track beta \
  --release-status inProgress --user-fraction .1
```

**Comment by SUPERCILEX** [comment]
Yup, if you use `from-track` and `track` with the same track, that updates it. Do you think it would be worth adding a `--update track` CLI param to make this easier?

**Comment by christxph** [comment]
@SUPERCILEX Such a parameter would be super helpful and definitely clear up some confusion.

**Comment by SUPERCILEX** [comment]
Dope, I thought so too and actually already added it a few days ago: #567. Should be part of 2.3.0. 👍
