### ISSUE TITLE
Breaking bundle file naming in AGP 3.5.0 alpha 04

### ISSUE THREAD

**Issue by knordbo** [Triple-T/gradle-play-publisher#516]
### Describe the bug

Android Gradle Plugin 3.5.0-alpha04 changed bundle file names to include variant, similar to apks.

So what would previously be 'app.aab' is now 'app-release.aab' for 'release' variant

I suspected this was a bug all when AGP introduced bundles since the naming convention wasn't consistent with apks, sadly since they fixed it so late, it now breaks this plugin.

### To Reproduce

Run publish task (using bundles):

* What went wrong:
A problem was found with the configuration of task ':app:publishReleaseBundle'.
> File '../app/build/outputs/bundle/release/app.aab' specified for property 'bundle' does not exist.

#### Versions

 - Gradle Play Publisher: 2.1.0
 - Gradle Wrapper (if applicable): 5.2.1
 - Android Gradle Plugin (if applicable): 3.5.0-alpha04

**Comment by gpx1000** [comment]
Annoying bug, tried to help, will downgrade gradle version used until it's fixed elsewhere.

**Comment by SUPERCILEX** [comment]
Yeah, sorry again for shutting the PR down so fast. 😟 Adding new configurations options is almost never the answer. 🙂

**Comment by knordbo** [comment]
Yeah I think the fact that google changed the path should not be exposed. Look for the file in the new path and fall back to the old way seems fine to me, and that piece of code can be deleted in the future.

**Comment by gpx1000** [comment]
No worries, I agree that's probably not the best approach.  The first approach was to simply fix the bug by the if check (first commit).  Just simply do the if check.

**Comment by gpx1000** [comment]
if the idea is to simply not have the option (completely agreed), should have just taken the first commit via cherry-pick or reverted the second commit.  It at least solves the immediate issue without waiting on a more elegant solution.  It's no worse then the already hard coded solution in code.

**Comment by SUPERCILEX** [comment]
This will be fixed in v2.2.0.

**Comment by SUPERCILEX** [comment]
Since v2.2.0 might be a ways away, I've decided to release a hotfix [v2.1.1](https://plugins.gradle.org/plugin/com.github.triplet.play/2.1.1) release.
