### ISSUE TITLE
Disable plugin for developers

### ISSUE THREAD

**Issue by sereden** [Triple-T/gradle-play-publisher#518]
As far as I understand `serviceAccountCredentials` requires a valid file. But quite often a regular developers do not publish application to Play Market and often CI is responsible for this.

Could you add a possibility to disable a plugin or ignore play credentials?

**Comment by SUPERCILEX** [comment]
This is planned in #503. 👍

**Comment by foal** [comment]
Possible workaround:

add to the root (project) module the following 
```groovy
plugins {
    id 'com.github.triplet.play' version '2.1.0' apply false
}

ext {
    ci = System.env['CI_ENV'] != null
}

subprojects { subproject ->
    if (ci) {
        apply plugin: 'com.github.triplet.play'
    }
}
```
`CI_ENV` is some enviroment variable defined only on CI server. Or some another way to initialize `ci` variable (`true` for CI server and `false` for developers workstations)

Suround `play` section with `if` in each individual `com.android.application` module
```groovy
if (ci) {
    play {
        serviceAccountCredentials = file("your-key.json")
        //.....
    }
}

```
