### ISSUE TITLE
Unable to update listing details

### ISSUE THREAD

**Issue by ssubramanian** [Triple-T/gradle-play-publisher#52]
Hi,

I am trying to upload listing details such as title, fulldescription and shortdescription with a folder structure as mentioned in the documentation. For some reason, only "whatsnew" is updated and everything under the listing directory is ignored. Any thoughts or suggestions on this?
 
![screen shot 2015-03-12 at 9 24 29 am](https://cloud.githubusercontent.com/assets/1056836/6619632/9ea00b68-c899-11e4-8d60-7db9c5b016ca.png)

**Comment by ssubramanian** [comment]
Never mind again :) Looks like you have a separate task to publish listing details.

**Comment by ctsdevmumbai** [comment]
I have the same structure but it only uploads apk file, the play store listings are not updated.
