### ISSUE TITLE
maven-publish plugin task clash

### ISSUE THREAD

**Issue by mmueller-abacus** [Triple-T/gradle-play-publisher#520]
### Describe the bug

Using gradle-play-publisher plugin together with the maven-publish plugin clashes with the publish task.

ERROR: Cannot add task 'publish' as a task with that name already exists.

### To Reproduce

```
buildscript {
    repositories {
        google()

        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath "com.android.tools.build:gradle:3.3.1"
    }
}

plugins {
    id "com.android.application"
    id "maven-publish"
    id "com.github.triplet.play" version "2.1.0"
}

android {
    compileSdkVersion 28
}
```

#### Versions

 - Gradle Play Publisher: 2.1.0
 - Gradle Wrapper (if applicable): 5.2.1
 - Android Gradle Plugin (if applicable): 3.3.1

### Expected behavior

I was able to use both the gradle-play-publisher 1.2 version with the maven-publish plugin in my gradle builds. When i upgrade to 2.1.0 there is a clash.

### Additional context

It seems, that the maven-publish plugin clashes with the publish task of the triplet play plugin. But how can you change the plugin order?

**Comment by SUPERCILEX** [comment]
Huh, can you share the full stacktrace? (Use `-s`) I thought we had fixed that issue. Also, can you try making sure the `play` block appears _after_ maven stuff? It might be lazily evaluated.

**Comment by mmueller-abacus** [comment]
How can make sure the play block appears after maven stuff?

I saw the Note in the issue #427:
for the fix to work, you will have to apply the GPP plugin _after_ `maven-publish`. Then, our `publish` task's name will be diverted to `gppPublish`.

How can you do that? Why not rename the publish task always to gppPublish? Why just in this situation?

**Comment by SUPERCILEX** [comment]
In your build file, move the `play { ... }` block to the end of the file.

Yeah, it should work if you apply GPP after maven so I don't know what's going on.

And we don't want to rename it always because. `gppPublish` is ugly and doesn't follow task naming conventions.

**Comment by mmueller-abacus** [comment]
Thank you! Now everything works fine.
