### ISSUE TITLE
Support for a additional resource directory

### ISSUE THREAD

**Issue by quittle** [Triple-T/gradle-play-publisher#521]
**Is your feature request related to a problem? Please describe.**
I generate my icons from an SVG so my Play Store High-Res icon cannot be available in `src/main/play`. I instead have a folder in the build, where I generate my resources, e.g. `build/custom-res/mipmap-hdpi/ic_launcher.png`. I am currently struggling to get the publisher to also upload an icon not checked in to my source, but located somewhere like `build/custom/play/listings/en-US/graphics/icon/icon.png`.

**Describe the solution you'd like**
Ideally, I'm missing something and you can provide here (and maybe in the README) instructions on how to do what I want with the way the plugin is currently designed.

**Describe alternatives you've considered**
If not, then adding support for additional `srcDirs` would be really helpful for this or even just being able to explicitly set the single `srcDir` so I can copy all my files to the build directory and point the plugin at that one.

In the meantime, I've been trying to copy my image into `build/generated/gpp/release/res/...` but it won't pick up my image.

**Additional context**
The project I'm struggling with is https://github.com/quittle/a11y-ally if you want to look at how I consume your plugin.

**Comment by SUPERCILEX** [comment]
The plugin uses the [Android Gradle Plugin's source dirs](https://developer.android.com/studio/build/build-variants#sourceset-build). Unless you plan on changing your icon very frequently, I'm not sure I see the value in generating the icons on every build.

About the generated folder, you could theoretically inject stuff in there, but it's definitely not supported. You'd want to make `publishReleaseListing` depend on your task (say `injectGeneratedIcons`) run after the generate one because it wipes the dir.

Something like this:
```kt
tasks.named("publishReleaseListing").configure { dependsOn("injectGeneratedIcons") }
tasks.named("injectGeneratedIcons").configure { mustRunAfter("generateReleasePlayResources") }
```

**Comment by quittle** [comment]
I see what you mean by using the Android plugin's source directories, however you guess the source directories [in GenerateResources here](https://github.com/Triple-T/gradle-play-publisher/blob/ff329f9c9d9924916346406537676e51c880b675/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/GenerateResources.kt#L41-L46) by assuming there is only one `res` dir located in `src/$flavorName/res` instead of using the [variant's source set provided res directories](https://android.googlesource.com/platform/tools/build/+/ef84df96b7b1a26a96a37506d95e3d427ee830ed/builder-model/src/main/java/com/android/builder/model/SourceProvider.java#84).

Android variants can have multiple sources, which is what I was trying to leverage with my above change. If in the `GenerateResources` task, you did something like the following, I would be able to leverage the multiple folders for my generated files without resorting to intercepting the build.

```groovy
protected val resSrcDirs by lazy {
        variant.sourceSets.flatMap { it.resDirectories }
}
```

What do you think?
