### ISSUE TITLE
Manual publish

### ISSUE THREAD

**Issue by ssubramanian** [Triple-T/gradle-play-publisher#53]
Hi,

I have noticed that the plugin uploads all the content - like APK and metadata. But it only gets it to the "Read to Publish" state. I had to manually publish the app to get it to the play store. Is this not supported by the plugin or am I missing something here?

Thanks!

**Comment by bhurling** [comment]
You can publish your APK directly to production using the `track` property in the `play` closure. See the Readme for details.

**Comment by ssubramanian** [comment]
Hi,

Thanks for your response @bhurling . Just so I understand this clear, are you saying that the publish to playstore will only work for production or are you suggesting the idea of using the track property. The reason I ask is because, I did use the "track" property as mentioned in Readme and I was trying to publish the app in the "beta" channel. What it does is that it uploads the apk, updates the description, whatsnew, screenshots and everything, but it only takes the app to the "Ready to publish" status. That meant I had to manually go and click on the publish button to publish the app to the play store.

Thanks!

**Comment by bhurling** [comment]
I will run some tests and get back to you. Perhaps there is another API request necessary in order to actually release the uploaded APK. I have to admit I never actually released in another track than alpha before.

**Comment by bhurling** [comment]
I just published my app to the beta track and it worked as expected. It is the one version that is currently available for beta with only one giant button to promote it to production. Do you use some kind of Multi-APK-Setup or the expert mode in the Web UI? I don't use any of those.

**Comment by ssubramanian** [comment]
@bhurling , I have multiple flavors if that's what you mean but I do not use an expert mode. I have attached a screenshot to be clear on what I mean. Notice that the app is in the "READY TO PUBLISH" state and has a button to the right, meaning it has all the info needed to push it to the playstore. This is what happens when I execute the command "publish[flavor]Release". Just to be clear you are saying you were able to skip this manual step when you execute the command and directly put the app in the playstore? Again, your plugin is already awesome that it eliminates all the manual steps for us but I just want to make sure I am not missing out on a capability of the plugin or the google API.
![store listing daxko google play developer console](https://cloud.githubusercontent.com/assets/1056836/6854344/a874b3a2-d3be-11e4-9b57-37876e81a924.png)

**Comment by bhurling** [comment]
I see. Am I right that your app has never been published before? I mean it has never been available in the Play Store? Unfortunately, this one step is not possible via the plugin. This is a restriction of the API. The initial release has to be done through the web interface. Once your App has been published, though, you can upload (and release) APK updates with the plugins (to any track you like)

**Comment by ssubramanian** [comment]
ohhh..Yes I have not released this app to the playstore before but I have had the apk and metadata uploaded before. You are saying this is similar to not being able to upload apk automatically, until you have done it once through the UI. So if I release the app to playstore manually at least once, then from the next time I can run the command and I would not have to go through this step, correct?

**Comment by bhurling** [comment]
Correct

**Comment by ssubramanian** [comment]
Thanks @bhurling .
