### ISSUE TITLE
Cant upload APK

### ISSUE THREAD

**Issue by tshank30** [Triple-T/gradle-play-publisher#532]
### Describe the bug

I have around 20 flavours in my code with diffrent application ids for each client. All client's APK are in same Playstore account. I need to publish all the apks with gradle script. I followed this article , but I am not able to upload apk for any flavour and getting the error below : 

Executing tasks: [publishApkTfstrackerRelease]

> Task :app:preBuild UP-TO-DATE
> Task :app:preTfstrackerReleaseBuild UP-TO-DATE
> Task :app:compileTfstrackerReleaseAidl NO-SOURCE
> Task :app:compileTfstrackerReleaseRenderscript UP-TO-DATE
> Task :app:checkTfstrackerReleaseManifest UP-TO-DATE
> Task :app:generateTfstrackerReleaseBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateTfstrackerReleaseSources UP-TO-DATE
> Task :app:javaPreCompileTfstrackerRelease UP-TO-DATE
> Task :app:mainApkListPersistenceTfstrackerRelease UP-TO-DATE
> Task :app:generateTfstrackerReleaseResValues UP-TO-DATE
> Task :app:generateTfstrackerReleaseResources UP-TO-DATE
> Task :app:mergeTfstrackerReleaseResources UP-TO-DATE
> Task :app:createTfstrackerReleaseCompatibleScreenManifests UP-TO-DATE
> Task :app:processTfstrackerReleaseManifest UP-TO-DATE
> Task :app:processTfstrackerReleaseResources UP-TO-DATE
> Task :app:compileTfstrackerReleaseJavaWithJavac UP-TO-DATE
> Task :app:compileTfstrackerReleaseNdk NO-SOURCE
> Task :app:compileTfstrackerReleaseSources UP-TO-DATE
> Task :app:lintVitalTfstrackerRelease
> Task :app:mergeExtDexTfstrackerRelease UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForTfstrackerRelease UP-TO-DATE
> Task :app:mergeDexTfstrackerRelease UP-TO-DATE
> Task :app:mergeTfstrackerReleaseShaders UP-TO-DATE
> Task :app:compileTfstrackerReleaseShaders UP-TO-DATE
> Task :app:generateTfstrackerReleaseAssets UP-TO-DATE
> Task :app:mergeTfstrackerReleaseAssets UP-TO-DATE
> Task :app:validateSigningTfstrackerRelease UP-TO-DATE
> Task :app:signingConfigWriterTfstrackerRelease UP-TO-DATE
> Task :app:mergeTfstrackerReleaseJniLibFolders UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForTfstrackerRelease UP-TO-DATE
> Task :app:processTfstrackerReleaseJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForTfstrackerRelease UP-TO-DATE
> Task :app:packageTfstrackerRelease UP-TO-DATE
> Task :app:assembleTfstrackerRelease
> Task :app:bootstrapTfstrackerReleasePlayResources
> Task :app:generateTfstrackerReleasePlayResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:generateTfstrackerReleasePlayResources'.
> File '/Users/shashank.tiwari/StudioProjects/Rottweiler/app/src/main/play' specified for property '$1' is not a file.
> File '/Users/shashank.tiwari/StudioProjects/Rottweiler/app/src/tfstracker/play' specified for property '$2' is not a file.
> File '/Users/shashank.tiwari/StudioProjects/Rottweiler/app/src/release/play' specified for property '$3' does not exist.
> File '/Users/shashank.tiwari/StudioProjects/Rottweiler/app/src/tfstrackerRelease/play' specified for property '$4' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 49s
28 actionable tasks: 3 executed, 25 up-to-date
11:30:52 PM: Task execution finished 'publishApkTfstrackerRelease'.

### To Reproduce

I run command : ./gradlew publishApkTfstrackerRelease
(Tfstracker is flavour name)

below is my gradle file : 

apply plugin: 'com.android.application'

android {

    flavorDimensions "ftelematics"
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 3
        versionName "1.2"
    }

    signingConfigs {

        release {
             storeFile file(“****”)
            storePassword “****”
            keyAlias “***”
            keyPassword “*****”
        }
    }

    productFlavors {
        
…
…
…
       

        tfstracker {
            dimension "ftelematics"
            applicationId "com.fst.apps.tfstracker"
            resValue "string", "app_name", "24x7 Tracker"
            resValue "string", "parking", "disabled"
            resValue "string", "ac", "disabled"
            resValue "string", "fuel", "disabled"
            versionCode 4
            versionName "1.3"
        }
….
…
      
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false  //ADD THIS
            zipAlignEnabled true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        abortOnError false
    }

}

repositories {
    maven { url "https://jitpack.io" }
}

allprojects {
    buildDir = "/Users/shashank.tiwari/StudioProjects/Rottweiler/app/build/"
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:3.8.2'
    implementation('com.android.support:appcompat-v7:28.0.0')
            {
                exclude module: 'support-v4'
            }
    implementation 'com.android.support:support-v13:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.google.android.gms:play-services-gcm:10.2.1'
    implementation 'com.google.code.gson:gson:2.5'
    implementation 'com.google.android.gms:play-services-maps:10.2.1'
    implementation 'com.google.android.gms:play-services-places:10.2.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.joanzapata.iconify:android-iconify-fontawesome:2.1.1'
    implementation 'com.github.PhilJay:MPAndroidChart:v2.2.4'
    implementation("com.airbnb.android:lottie:2.5.1") {
        exclude group: 'com.android.support'
        exclude module: 'support-v4'
    }

}

apply plugin: 'com.github.triplet.play'

play {
    track = 'production'
    serviceAccountEmail = 'ftelematics-847@api-9216857070691207484-382697.iam.gserviceaccount.com'
    pk12File = file('/Users/shashank.tiwari/StudioProjects/Rottweiler/ftelematics.p12')
    //jsonFile = file('/Users/shashank.tiwari/StudioProjects/Rottweiler/ftelematics.json')

}

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:28.0.0'
    }
}

allprojects {
    project.afterEvaluate {
        generateTfstrackerReleasePlayResources.dependsOn bootstrapTfstrackerReleasePlayResources
    }
}

#### Versions

 - Gradle Play Publisher: 1.1.5
 - Gradle Wrapper (if applicable): 5.0
 - Android Gradle Plugin (if applicable): 3.3.1

### Expected behavior

Apk should get uploaded

**Comment by SUPERCILEX** [comment]
GPP v1.x is no longer supported. Please upgrade to [v2.1.1](https://github.com/Triple-T/gradle-play-publisher/issues/496#issuecomment-454985389).

**Comment by tshank30** [comment]
Thanks a lot. 💃 Works like charm. Finally, no pain in life 👯‍♂️

**Comment by SUPERCILEX** [comment]
:rofl: :sparkling_heart:
