### ISSUE TITLE
2.2.0-SNAPSHOT for java seem not to be available

### ISSUE THREAD

**Issue by nickyrabit** [Triple-T/gradle-play-publisher#534]
### Describe the bug
what i place
 classpath "com.github.triplet.gradle:play-publisher:2.2.0-SNAPSHOT" 

### To Reproduce

if you build it in an android (java) it gets things like

 {
errors: [
{
status: 404,
message: "Artifact not found: com/github/triplet/gradle/play-publisher/2.1.1-SNAPSHOT/play-publisher-2.1.1-SNAPSHOT.pom"
}
]
}

but classpath 'com.github.triplet.gradle:play-publisher:2.0.0-SNAPSHOT'   WORKS

i HOPE THIS IS HELPFUL

**Comment by SUPERCILEX** [comment]
2.1.1 snapshots are not available. 2.2.0 ones are though: https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#snapshot-builds.
