### ISSUE TITLE
Add option to split out the build and publish stages

### ISSUE THREAD

**Issue by g3kk0** [Triple-T/gradle-play-publisher#535]
It would be really useful if there was an option of splitting build and publish into separate tasks.

Without this there is no way of testing the build artefact before it is published.

e.g.
1) Create Android app bundle
2) Use `bundletool` to extract an APK for testing
3) Test the APK
4) All things being well publish the bundle to Google Play

**Comment by SUPERCILEX** [comment]
This use case will be addressed by https://github.com/Triple-T/gradle-play-publisher/issues/360.
