### ISSUE TITLE
Deferring applicationId retrieval to when the publishApkTask runs

### ISSUE THREAD

**Issue by hzsweers** [Triple-T/gradle-play-publisher#54]
Right now, the applicationId is captured at configuration and persisted throughout the `PlayPublishTask`'s lifetime, even though a build might dynamically change the applicationId after that. Retrieving the APK file would run into the same issue if the developer set custom APK names, but it doesn't run until the `PlayPublishApkTask` runs, and thus retrieves the correct final name after the app has been assembled. My proposal is to do the same with applicationId. I think it would be an easy change, since the variant instance is held in the `PlayPublishApkTask`. 

In [PlayPublishApkTask][0], instead of using the saved `applicationId` field, we can simply call `variant.applicationId`. I think this should work, though it might have to be `variant.mergedFlavor.applicationId` (I'm not entirely sure if they can ever be different).

If you're open to it, I'd be happy to send a pull request your way.

[0]: https://github.com/Triple-T/gradle-play-publisher/blob/master/src%2Fmain%2Fgroovy%2Fde%2Ftriplet%2Fgradle%2Fplay%2FPlayPublishApkTask.groovy

**Comment by bhurling** [comment]
Sounds good.

**Comment by hzsweers** [comment]
Great, I'll get started on it tomorrow!
