### ISSUE TITLE
Minimal service account permissions?

### ISSUE THREAD

**Issue by Diolor** [Triple-T/gradle-play-publisher#543]
Hey and first of thanks for this plugin! 

Do you know what are the minimal permissions for the service account ? Google is not telling us anything here: https://developers.google.com/android-publisher/getting_started#using_a_service_account

Is "project viewer" the minimum permission role level?

![image](https://user-images.githubusercontent.com/1686807/55295885-b5567f00-5412-11e9-820c-24c8a41b18c6.png)

We can add this in the read.me file (I guess I am not the only one here with this question).

**Comment by SUPERCILEX** [comment]
Are they forcing you to put a permission? You shouldn't have to. Things are configured on the Play Console side.

**Comment by Diolor** [comment]
If the service account, on the Google Cloud Console, doesn't have a minimum permission of "Project Viewer", that cloud project/service account will not be visible for linking on the Google Play Console. 

This under the scenario of using an existing cloud project.

**Comment by SUPERCILEX** [comment]
Then viewer perms should do.

**Comment by Diolor** [comment]
Cool, thanks!
