### ISSUE TITLE
Trouble using `isEnabled`

### ISSUE THREAD

**Issue by ScottPierce** [Triple-T/gradle-play-publisher#544]
### Describe the bug

I'm getting the following error:
```
Could not set unknown property 'enabled' for object of type com.github.triplet.gradle.play.PlayPublisherExtension.
```

### To Reproduce
I have the following code:
```
play {
    serviceAccountCredentials = playCredentialsFile
    track = 'beta'
    releaseStatus = 'completed'
    defaultToAppBundles = true
    isEnabled = isCi
}
```

which yields the following error:
```
Could not set unknown property 'enabled' for object of type com.github.triplet.gradle.play.PlayPublisherExtension.
```

#### Versions

 - Gradle Play Publisher: 2.1.0
 - Gradle Wrapper (if applicable): 5.2.1
 - Android Gradle Plugin (if applicable): 3.3.2

### Expected behavior

That it wouldn't crash my gradle script, and would properly enable and disable the app.

**Comment by SUPERCILEX** [comment]
Oops, I didn't mean to publish those docs. 😳 But since you're here, would you mind trying a [snapshot build](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#snapshot-builds) and seeing if it fits your use case?

**Comment by ScottPierce** [comment]
Someone from my team tried the snapshot and still had the same issues I believe.

**Comment by jschnall** [comment]
Yes, I tried the "2.2.0-SNAPSHOT" and had the same issue with isEnabled not working

**Comment by SUPERCILEX** [comment]
Ohhh, since you're using Groovy I think it has to be `enabled = isCi`. Groovy's boolean stuff is always confusing to me.

**Comment by ScottPierce** [comment]
you might want to update the groovy docs for that then.

**Comment by SUPERCILEX** [comment]
Did it work? If so, I'll definitely update the docs.

**Comment by ScottPierce** [comment]
We found a workaround using environment variables, and are no longer trying
to use the `isEnabled` flag.
