### ISSUE TITLE
Add option to set service account credentials from environment variable

### ISSUE THREAD

**Issue by ivoberger** [Triple-T/gradle-play-publisher#546]
**Is your feature request related to a problem? Please describe.**
in CI secrets are usually supplied using environment variables. Currently a step to write the variable containing the service account credentials to a file before publishing

**Describe the solution you'd like**
an option to supply service account credentials with a simple string so it's possible to do `serviceAccountCredentials = System.getenv("PLAY_CREDENTIALS")` instead of
`serviceAccountCredentials = file("play_credentials.json")` with a bash command like `echo $PLAY_CREDENTIALS > play_credentials.json` as a preceding step.

**Comment by SUPERCILEX** [comment]
You shouldn't be storing your secrets in an environment variable (it's a very _lonnng_ string). If you really want to use environment variables, what you're currently doing is correct. From a technical perspective, the Google library we use under the hood only accepts files so we'd just be doing exactly what you wrote above anyway.

**Comment by IIIuminator** [comment]
If you don't mind be asking, where do I put it then to have it available in CI? It's credentials after all so it shouldn't be in the repository (right?)

**Comment by SUPERCILEX** [comment]
I personally encrypt the file and commit it to my repo, but anywhere that's safe is fine. We actually have some guides on this: https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#encrypting-service-account-keys

**Comment by IIIuminator** [comment]
Thanks!

**Comment by gnarea** [comment]
I really wish this were supported, consider how common this pattern is. Anyone using GitHub actions will be forced to implement this workaround, for example.

**Comment by SUPERCILEX** [comment]
@gnarea Agreed, I'm going to reconsider this for v3.0 when I get to nuke the PKCS12 auth support and use Google's new auth lib.
