### ISSUE TITLE
Release Status

### ISSUE THREAD

**Issue by Abhishekqwerty** [Triple-T/gradle-play-publisher#547]
Hi,
I have published an app to **alpha track** using **GPP** with **release status as inProgress**.
Now I got two options on alpha track google play console:
**Halt Rollout** and **Update Rollout**.
Now If I want to halt the release through GPP how to achieve it?
If I release an app with **halted** status using GPP, I got 
Execution failed for task ':app:publishReleaseApk'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
  {
    "code" : 400,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Cannot halt release, no matching in progress release found.",
      "reason" : "releaseToHaltNotFound"
    } ],
    "message" : "Cannot halt release, no matching in progress release found."
  }

Can someone explain me the process in details.
Hoping for co-operation
Thanks

**Comment by SUPERCILEX** [comment]
Yeah, you can't upload a new artifact. See the docs to [update an existing release](https://github.com/Triple-T/gradle-play-publisher/tree/771b2a58ad0faf5298e096b9dc2282d08c862929#promoting-artifacts). You could do this:
```sh
./gradlew promoteArtifact --from-track alpha --track alpha --release-status halted
```
