### ISSUE TITLE
android.playConfigs extension merges null values on top of play extension

### ISSUE THREAD

**Issue by tadfisher** [Triple-T/gradle-play-publisher#548]
### Describe the bug

If values are configued in `play` but not in `android.playConfigs.$variant`, the default `null` value overrides fields in `play`.

This means configuration fields must be duplicated across extensions registered in `android.playConfigs` extensions, and is not what I expect when configuring both `play` and `android.playConfigs`.

If one such field is `serviceAccountCredentials`, the build will succeed but skip the `publish$variantApk` task with no error output.

### To Reproduce

Config snippet:

```kotlin
android {
    playConfigs {
        register("devRelease") {
            isEnabled = true
            track = "production"
        }
        register("prodRelease") {
            isEnabled = true
            track = "beta"
        }
    }
}

play {
    isEnabled = false
    serviceAccountCredentials = file("path/to/credentials.json")
    resolutionStrategy = "auto"
}
```

#### Versions

 - Gradle Play Publisher: 2.20.0
 - Gradle Wrapper (if applicable): 5.3.1
 - Android Gradle Plugin (if applicable): 3.3.2

### Expected behavior

In the example configuration, I would expect `serviceAccountCredentials` and `resolutionStrategy` for `publishDevReleaseApk` and `publishProdReleaseApk` to inherit from the fields in `play`, but they remain at their default values (`null` and `"fail"` respectively).

**Comment by SUPERCILEX** [comment]
Can you share a sample build output with the command you ran and `--console plain`.
