### ISSUE TITLE
Publish tasks should fail for missing configuration

### ISSUE THREAD

**Issue by tadfisher** [Triple-T/gradle-play-publisher#549]
### Describe the bug

Related to #548 

If `serviceAccountCredentials` is missing for a given configuration, publish tasks for that configuration will be skipped instead of failing. If running from CI which depends on the return code of Gradle to mark a task as successful, one could assume the publish task succeeded in publishing its artifact when in fact it did not attempt to do so.

### To Reproduce

- Configure the `play` extension but do not enter a value for `serviceAccountCredentials`.
- Run a `publish` task for the configuration.
- In the log output, note the publish task is `SKIPPED` and the build succeeds with a `0` return code.

#### Versions

 - Gradle Play Publisher: 2 20.0
 - Gradle Wrapper (if applicable): 5.3.1
 - Android Gradle Plugin (if applicable): 3.3.2

### Expected behavior

I would expect the publish task to fail for any case where an artifact was not actually published.

In addition, I would appreciate clear error logs as to why the task failed, including a description of missing or invalid configuration fields.

**Comment by SUPERCILEX** [comment]
This was actually intentional: https://github.com/Triple-T/gradle-play-publisher/issues/461. Since we can now explicitly disable variants I'm wondering if we should go back to failing the build at configuration if we don't find credentials.
