### ISSUE TITLE
Plugin is not initializing correctly

### ISSUE THREAD

**Issue by Gopinathp** [Triple-T/gradle-play-publisher#550]
Plugin is not getting initialized correctly and it is while creation of Google client. Tried with 2.2.0 and 2.3.0-snapshot

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bootstrapReleasePlayResources'.
> com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;

#### Versions

 - Gradle Play Publisher: 2.2.0/2.3.0-snapshot
 - Gradle Wrapper (if applicable): gradle-5.3.1
 - Android Gradle Plugin (if applicable): 3.5.0-alpha11

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/344#issuecomment-447917493
