### ISSUE TITLE
--artifact-dir doesn't work as expected

### ISSUE THREAD

**Issue by ScottPierce** [Triple-T/gradle-play-publisher#551]
I'm using the latest build, which I believe is 2.2.0 at the current time.

I applied `--artifact-dir` to my build, but it didn't work, and it tried to start building my project. I didn't realize it at the time, but the directory I was pointing too was a relative path from the root project, not from the android module that I had the `play-publisher` plugin applied. It probably wasn't able to find it the directory, or the bundle I was trying to have it find, and instead of erring like I'd expect, instead it tried to build it.

I wasn't able to see an error, and actually understand what was happening until I tried `artifactDir`.

This behavior is unexpected. If I supply the `--artifact-dir` param, I'd expect it to behave the exact same as the `artifactDir` parameter.

**Comment by SUPERCILEX** [comment]
Would you mind elaborating a little bit on what behavior is different? The path stuff for the CLI arg is intentional: it should be relative to the directory you're in right now, like any other CLI tool. That way, standard paths like `~/foo/bar` work as expected.

**Comment by ScottPierce** [comment]
So the `--artifact-dir` param wasn't erroring out when it didn't find the file. Instead, it seemed like it was trying to build it. I had to switch to using the `artifactDir` to get the behavior I was expecting.

**Comment by SUPERCILEX** [comment]
Oh, can you share the command you were running?

**Comment by ScottPierce** [comment]
I tried several. This was one:
```
./gradlew crashlyticsUploadDistributionInternalRelease crashlyticsUploadDistributionProductionRelease publishBundle --artifact-dir app/app-android/build/outputs/bundle/productionRelease
```

I tried a few other variations:
```
./gradlew publishProductionReleaseBundle --artifact-dir app/app-android/build/outputs/bundle/productionRelease
```

I didn't realize that I needed to be providing a relative path from the module that had the plugin applied, and not the root project. I was able to realize that when I swapped to specifying the `artifactDir`  in the gradle DSL. The error it gave me showed that I was looking in the `app/app-android/app/app-android/build/outputs/bundle/productionRelease` folder, which doesn't exist. I'm assuming that the `--artifact-dir` param wasn't finding the bundle, and then was trying to build it because of that, but instead I think it probably should have thrown an error just like the gradle DSL.

**Comment by SUPERCILEX** [comment]
Ok, thanks for all the information. I think this is a misunderstanding of how Gradle works. If you use `file(...)`, the file will be resolved relative to the module your DSL is applied to. With `--artifact-dir`, we resolved it relative to the directory you are executing the CLI command from. When you say it was building your project, that means it was working. I'm not sure why you didn't let it finish. To prove this to yourself, you can run some simple tests:
```sh
./gradlew publishBundle --artifact-dir fakeDir
```

This will print out the path it resolved.

**Comment by ScottPierce** [comment]
@SUPERCILEX If that's the case, then this seems like a bug, as the relative path to the folder my bundle was in was valid from the root project directory (the directory I was executing the command from).

>When you say it was building your project, that means it was working. I'm not sure why you didn't let it finish.

I was running it in a low memory environment on CircleCI, and gradle was crashing because it was running out of memory, as it was trying to build, which was something it shouldn't have been doing.

**Comment by ScottPierce** [comment]
I just tried your suggestion of providing a fake path, and it immediately fails. That's not what I was seeing.

To sum up, the path was valid, but now it seems that it was still building something, when it shouldn't have been.

**Comment by SUPERCILEX** [comment]
I'm very confused: if the path is valid, why wouldn't it build something? And the memory errors have nothing to do with this plugin.

**Comment by ScottPierce** [comment]
>if the path is valid, why wouldn't it build something

@SUPERCILEX Isn't the point of `--artifact-dir` to ensure that it doesn't build anything, but instead uploads an already existing artifact? From the docs in the `Uploading a pre-existing artifact` sections: `By default GPP will rebuild your project before every release. In advanced use cases, this might not be the desired behavior.` The entire reason why I'm using `--artifact-dir` is because I already built the bundle in a previous build step, and now I'm only uploading it in certain situations.

>the memory errors have nothing to do with this plugin.

I'm aware, I was just answering your question as to why the build didn't finish.

**Comment by SUPERCILEX** [comment]
Ohhhhhhhhhhhhhh, I think I finally understand what you mean. 👍 Here's what I think is going on:
- If you run
  ```sh
  ./gradlew publishBundle --artifact-dir app/app-android/build/outputs/bundle/productionRelease --console plain
  ```
  you'll see that only the publishing tasks will run (it won't do the whole assemble thing)
- But when you run other tasks like `crashlyticsUploadDistributionProductionRelease`, those will depend on completely building the app from scratch because they need that `mapping.txt` file. GPP won't actually upload the mapping file when you specify an artifact dir (ignoring a bug I just realized we have).

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/556

**Comment by ScottPierce** [comment]
@SUPERCILEX In order to conclude which command was causing the building, I separated them, and identified that the build was still happening even with

```
./gradlew publishBundle --artifact-dir app/app-android/build/outputs/bundle/productionRelease
```

**Comment by SUPERCILEX** [comment]
Can you please add `--console plain` and share the output?

**Comment by ScottPierce** [comment]
@SUPERCILEX I reproduced again.

Running
```
./gradlew publishBundle --artifact-dir app/app-android/build/outputs/bundle/productionRelease --console plain
```
ends up trying to build my app again.

I don't think I can show you the build output, as it details all our build steps, and modules, but it does in fact build my app instead of erroring or anything.

**Comment by ScottPierce** [comment]
In contrast, when we don't use `--artifact-dir`, and instead use `artifactDir`, the build output is like 40 lines, and it clearly doesn't build anything. It only runs 2 build steps:

```
> Task :app-android:generateProductionReleasePlayResources NO-SOURCE
> Task :app-android:publishProductionReleaseBundle
```

**Comment by SUPERCILEX** [comment]
Huh, ok. And what version of Gradle are you using? I'm wondering if the CLI params aren't resolved early enough on old Gradle versions.

**Comment by ScottPierce** [comment]
I'm using Gradle 5.4.

I also tried
```
./gradlew publishProductionReleaseBundle --artifact-dir app/app-android/build/outputs/bundle/productionRelease --console plain
```

It gave the same result as the previous command; trying to build my app.

**Comment by SUPERCILEX** [comment]
Wowwwww, well here's a sad story. If you run `publishBundle`, it works. If you run `publishProductionReleaseBundle`, it won't work. Feel free to use that workaround while I figure this out. And thank you so much for your patience while I tried understanding what was going on! :blush:

**Comment by SUPERCILEX** [comment]
Please give the [latest snapshot artifact](https://github.com/Triple-T/gradle-play-publisher#snapshot-builds) a try! If all goes well, I'll be cutting a `v2.2.1` release in a few days.

**Comment by ScottPierce** [comment]
I think my misunderstanding of how gradle path parameters work is what made this more complicated than it needs to be. Sorry about that :-P

Also, I explicitly tried `publishProductionReleaseBundle`, and `publishBundle` today, and several days ago, and in all cases I found that they all resulted in an undesired build.

What's funny is that `publishBundle` doesn't work with the Gradle DSL approach. I have to use `publishProductionReleaseBundle`, or it tries to upload an internal variant to the store and fails.

**Comment by SUPERCILEX** [comment]
Well I'm happy everything is set up to your liking, and thanks again for filing the bug!

PS: about the internal variant, [this](https://github.com/Triple-T/gradle-play-publisher#disabling-publishing) might come in handy.
