### ISSUE TITLE
Default JSON file won't be used in flavor specific configuration

### ISSUE THREAD

**Issue by vitorhugods** [Triple-T/gradle-play-publisher#552]
First of all, awesome project. Thank you for this amazing tool and the support you provide =)

### Describe the bug
My project structure:
7 flavors, one of them is `kia`
3 build types:
* debug
* release
* staging (release with staging server URL, for QA testing)

### Steps to To Reproduce

My config:
```kotlin
android{
    ...
    playConfigs {
        create("kiaStaging") {
// 			  no upload takes place by commenting the credential file
//            serviceAccountCredentials = file("./playstore.json")
            track = "alpha"
            isEnabled = true
        }
    }
}

play {
    serviceAccountCredentials = file("./playstore.json")
    isEnabled = false
    defaultToAppBundles = true
}
```

Outcome of `./gradlew publish`:
```sh
> Task :app:assembleKiaStaging
> Task :app:generateKiaStagingPlayResources UP-TO-DATE
> Task :app:publishKiaStagingApk SKIPPED
> Task :app:publishKiaStagingListing SKIPPED
> Task :app:publishKiaStagingProducts SKIPPED
> Task :app:publishKiaStaging UP-TO-DATE
> Task :app:publish UP-TO-DATE
```

#### Versions

 - Gradle Play Publisher: 2.2.0
 - Gradle Wrapper (if applicable): 5.1.1
 - Android Gradle Plugin (if applicable): 3.4.0

### Expected behavior

The default `.json` file should be used, no need to specify the same file in every flavor configuration.

**Comment by SUPERCILEX** [comment]
But the upload _does_ happen if you uncomment the credentials?

**Comment by vitorhugods** [comment]
Oops, forgot to mention.
Yes, it does.
If I uncomment the credentials, I can also remove the one line from the default configurations.
