### ISSUE TITLE
Version override not sync to BuildConfig

### ISSUE THREAD

**Issue by b95505017** [Triple-T/gradle-play-publisher#553]
It looks like outputProcessor only affect `AndroidManifest.xml` but `BuildConfig.VERSION_XXX`. Is there any possible to check version early?

**Comment by SUPERCILEX** [comment]
Looks like there's a bug on both ends. This will be fixed on our side in 2.3.0 and on the AGP side whenever this gets done: https://issuetracker.google.com/issues/131449903

**Comment by b95505017** [comment]
WOW thanks for quick fix!
