### ISSUE TITLE
Impact of Google play API migration to 3.0 on beta deployment[Android]

### ISSUE THREAD

**Issue by hrushie** [Triple-T/gradle-play-publisher#562]
Hello Team,

We are using gradle-play-publisher API since last year on our several markets to upload the beta builds on the Google play. Starting 12/1/19, Google will be deprecating Google Play Developer API versions 1 and 2. Our Android app needs to migrate to the latest API version 3 to avoid any impact. So is there any impact on the our use of gradle-play-publisher api if we migrate to version 3 of google play API?

**Comment by SUPERCILEX** [comment]
All versions in the 2.x range of the plugin use the latest publisher API.

**Comment by avalanchas** [comment]
Hi, so glad there is already a comment on this here. Quick question for clarification though: 
`gradle-play-publisher` uses [this artifact](https://mvnrepository.com/artifact/com.google.apis/google-api-services-androidpublisher/v3-rev86-1.25.0), the `google-api-services-androidpublisher`, which is v3. But that in turn has a dependency on the "`google-api-client` version 1.25, [here](https://mvnrepository.com/artifact/com.google.api-client/google-api-client/1.25.0) 

So is that not a problem? What is this "v3" that the Play Console complaining about in the end?

**Comment by SUPERCILEX** [comment]
Nope, not related. See [my answer](https://stackoverflow.com/a/57331205/4548500). We use v3 as you noticed. Also, your project doesn't use GPP as far as I can tell since you don't use CI.
