### ISSUE TITLE
Gradle tasks are not available

### ISSUE THREAD

**Issue by ivanarellano** [Triple-T/gradle-play-publisher#57]
Simply put, none of the gradle tasks are available in either command line or Android Studio (1.1.0 and 1.2 P4) and I do not know what to look for. I'm working with a barebones Android Studio project and have followed the Readme. When I get a chance, I'm going to try this process again on a separate PC.

I'm using:
Gradle 2.2.1
Android Tools Gradle 1.1.3
Play-Publisher 1.0.2
on OSX 10.10

**Comment by fpsscarecrow** [comment]
Having the same issue on the same set up as @ivanarellano  - tasks are not appearing

**Comment by bhurling** [comment]
You need to set up a singingConfig for the release build type. Otherwise, there won't be a releasable APK. I should add a note to  the README for that
