### ISSUE TITLE
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

### ISSUE THREAD

**Issue by ShreyashPromact** [Triple-T/gradle-play-publisher#570]
### Describe the bug

> WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
> Affected Modules: app

When I build my project after adding the plugin, I got this warning. When I remove it, my project works fine. Can you please let me know what is the problem here?

### To Reproduce

I have just added the plugin in my project and it shows me this error.

#### Versions

 - Gradle Play Publisher: **1.2.2**
 - Gradle Wrapper (if applicable): **5.1.1**
 - Android Gradle Plugin (if applicable): **3.4.0**

### Expected behavior

It should work as expected. It was working with the 1.2.0 Gradle Play Publisher and Android 26 version. When I update my build to latest 28 version, it starts showing me warning as mentioned above.

**Comment by SUPERCILEX** [comment]
1.x is not supported. Please upgrade to v2.2.1 by following installation instructions in the README.

**Comment by ShreyashPromact** [comment]
ok Thanks.
