### ISSUE TITLE
Double assets after second bootstrap

### ISSUE THREAD

**Issue by YuryPashkov** [Triple-T/gradle-play-publisher#572]
### Describe the bug

Screenshots for "phone-screenshots" and "tablet-screenshots" are duplicated.

### To Reproduce

Did bootstrap task for flavor. All screenshots was downloaded. 
Next day. I do the same task. Screenshots for phone-screenshots and tablet-screenshots are duplicated. So eventually it leads publish task fail because exceed max amount of screenshots.

#### Versions

 - Gradle Play Publisher: 2.2.1
 - Gradle Wrapper (if applicable): 4.10.2
 - Android Gradle Plugin (if applicable): 3.3.1

### Expected behavior

I've expected that they will be replaced.

**Comment by SUPERCILEX** [comment]
The bootstrap task isn't meant to be run daily, only when first setting up the plugin. Can you explain your use case a little bit more?

**Comment by SUPERCILEX** [comment]
Eh, I actually just went ahead and fixed it. It'll be available in v2.3.0.
