### ISSUE TITLE
Skip processing metadata on repo PRs

### ISSUE THREAD

**Issue by f4ww4z** [Triple-T/gradle-play-publisher#582]
### Describe the bug

When using this plugin in our repository, we found that the task `processReleaseMetadata` is running on regular debug builds and PRs, so as we don't provide keystore and service account on debug builds, [the json file doesn't exist](https://travis-ci.org/openmrs/openmrs-contrib-android-client/builds/540166597#L953), failing the build.

### How To Reproduce

1. Build the project in travis CI (debug), without `google_play.json` file.
2. CI build failed with `google_play.json` not found.

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 5.1.1
- Android Gradle Plugin: 3.4.1

#### Tasks executed

- `assembleDebug`
- `processReleaseMetadata`

### Expected behavior

We want to run this task on releases only, so there should be a way to skip this `processReleaseMetadata` task on non-release builds.

### Additional context (if a crash, provide stack trace)

We're publishing releases on [tagged builds](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/build.sh#L18).

**Comment by SUPERCILEX** [comment]
Yep, this change is intentional. The idea that if you don't have credentials, you should simply [disable all of GPP](https://github.com/Triple-T/gradle-play-publisher#disabling-publishing). It could something like this:
```
play {
    isEnabled = file("google_play.json").exists()
}
```

**Comment by f4ww4z** [comment]
That led me to reading [this section](https://github.com/Triple-T/gradle-play-publisher#disabling-publishing). Thanks.

**Comment by f4ww4z** [comment]
@SUPERCILEX the `processReleaseMetadata` task [is still running on CI](https://travis-ci.org/openmrs/openmrs-contrib-android-client/builds/540833456#L951) even though [I've disabled it by default](https://github.com/openmrs/openmrs-contrib-android-client/pull/602/files#diff-cc5437861bff23b3bb39d227f1f32eaeR176). We want [to use this](https://github.com/openmrs/openmrs-contrib-android-client/pull/602/files) as our current travis CI config. Is there something I'm missing?

**Comment by SUPERCILEX** [comment]
You haven't disabled it: you set `enabled = true` which is the default. As per my above comment, this should work:
```
play {
    enabled = rootProject.file('google_play.json').exists()
}
```

**Comment by f4ww4z** [comment]
Thanks again for the fast reply, the CI build is now passing.

**Comment by f4ww4z** [comment]
@SUPERCILEX 1 more question - the `publishRelease` [task is successful](https://travis-ci.org/openmrs/openmrs-contrib-android-client/builds/541046194#L1140), but I cannot see any changes in the Play store page. The page's still on the previous release. What do you suggest to do? Do we need to create a new, updated service account?

**Comment by SUPERCILEX** [comment]
My guess is that the app was published as a rollout release due to [this line](https://github.com/openmrs/openmrs-contrib-android-client/blob/d23c576f609d29bb7dad56fc78849c2a70b0a7e9/openmrs-client/build.gradle#L182). If you just remove it or change the value to `completed` you should be good.
