### ISSUE TITLE
Play extension not found

### ISSUE THREAD

**Issue by lordcodes** [Triple-T/gradle-play-publisher#584]
### Describe the bug

After the plugin is applied, the 'play' extension cannot be found and I instead have to configure the plugin using `configure<PlayPublisherExtension> {}` instead of `play {}`.

### How To Reproduce

Apply plugin to project, sync project and then try to add 'play {}' extension block to app/build.gradle.kts.

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: Gradle 5.4.1
- Android Gradle Plugin: 3.4.0

#### Tasks executed

No tasks executed

### Expected behavior

The play extension block works.

### Additional context (if a crash, provide stack trace)

Using Kotlin Gradle DSL.

**Comment by SUPERCILEX** [comment]
That's because you're using `apply(plugin = foo)` instead of `plugins { id(foo) }`.

**Comment by lordcodes** [comment]
Okay thank you. I had to use apply(plugin = foo) syntax in order to only apply the plugin conditionally if the Play credentials file was present. Thought I saw examples that did this using apply plugin syntax and then still used the 'play' extension so thought I should be able to.

Thank you very much for the explanation.

**Comment by SUPERCILEX** [comment]
Don't do that. Use `play { isEnabled = file("cred.json").exists() }`.

**Comment by lordcodes** [comment]
Even better, thank you very much. Sorry for wasting your time with my
issue. Appreciate the help.

**Comment by SUPERCILEX** [comment]
Lol, no worries. 😊
