### ISSUE TITLE
Support for more CLI options (for example release-name)

### ISSUE THREAD

**Issue by damian-burke** [Triple-T/gradle-play-publisher#590]
### Problem description

Our Play Store listing is managed by a couple different teams. The listing itself, the release notes (due to heavy need for localization), and the releases. 

We, the engineering team, take care of the releases and we'd like to utilize the release names. At the moment we are doing that manually since we didn't bootstrap the Play Store listing of our application with the gradle plugin (since there's no need to keep it in the repository due to different teams managing it outside of the repo's scope).

It would be nice to make CLI a viable option for more settings.

### Potential solutions/workarounds

Add CLI options for more options that are closer to the release. 
The dev-facing release name would make the most sense in my opinion, to be able to execute for example `./gradlew publishReleaseApk --release-name "Feature X" (...)`

Not sure for which options it'd make sense. I think for a non-localized release note it'd also be nice to be able to set it via CLI, especially for the internal track for example.

**Comment by tprochazka** [comment]
+1
I want to do the some from inside of the build script as mentioned in #502
There is also workaround solution for the current version.
