### ISSUE TITLE
Add task to receive current releases on selected tracks

### ISSUE THREAD

**Issue by damian-burke** [Triple-T/gradle-play-publisher#591]
### Problem description

Not sure if this is too far out of scope for the `gradle play publisher`: 

It would be nice to be able to query the current track setup / release stages. This would allow for a "state-less" release management, i.e. CI/CD or a dashboard could call the gradle task periodically and fetch the current release status.

For example a gradle trask `./gradlew queryRelease [--track internal|alpha|beta|production]`  that returns a list of tracks formatted in a certain way with the current `userFraction`, `trackIdentifier` as well as `versionCode`.

### Potential solutions/workarounds

AndroidPublisher's [Track](https://developers.google.com/resources/api-libraries/documentation/androidpublisher/v2/java/latest/com/google/api/services/androidpublisher/model/Track.html) API.

**Comment by SUPERCILEX** [comment]
I'm confused, what would you use it for? To rebuild the Play Console?

**Comment by SUPERCILEX** [comment]
Closing due to staleness, will reopen if you reply.

**Comment by damian-burke** [comment]
The use-cases I had in mind were to be able to for example automate the release pipeline - that means promoting artifacts between tracks after certain time-frames if there are no incidents, as well as notifying different stakeholders (who may not have access to the Play Console, thus need an update via different channel).

But yes, maybe a task just for that would be overkill. What is your opinion on having the publisher tasks respond / print / save the current track setup instead? That might make more sense from a pure publisher point of view, i.e. after publishing an APK/Bundle there'd be a `track status` update that can be parsed.

**Comment by SUPERCILEX** [comment]
I'm still a tad confused. We have the [promote task](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#promoting-artifacts) which will move a release from track to track. Is that not what you're asking for? And the console stuff is already available in the latest snapshot builds (see #593).

**Comment by damian-burke** [comment]
The promote task is what'd be used to execute the promotion itself, what I was thinking of was more a machine-readable track representation after executing the promotion / publishing. The logging in #593 is nice, what's missing is maybe a different output type (for example JSON). 

But that'd just print a success message for the currently executed task. 

Say for example I have the following tracks:

`production / v1.0 / completed`
`beta / v1.1 / completed`

And then I'd execute a `promote from beta to production with 25% rollout`, it'd be nice to have a complete representation of the track setup printed (machine readable), so here it'd be something like this (imagine this in a JSON format)

`production / v1.0 / completed`
`production / v1.1 / in_progress / 25%`

I could then take this response message, parse it, format it and share it with the stakeholders.

**Comment by SUPERCILEX** [comment]
Huh, interesting. That actually would be a piece of cake implementation wise because the response we get is already JSON. So what you want is a kind of audit log of the actions performed? I'm doing that with the Internal Sharing artifacts by writing out a file like `build/outputs/internal-sharing/bundle/[timestamp].json` which contains the response we received.

What if instead we had a folder that's dedicated to this stuff like `build/outputs/gpp/...`. But then that raises the question: is this not out of scope? The reason I'm doing it for the Internal Sharing artifacts is because they contain a link to the uploaded artifact which could be needed later. Writing out the tracks or Bundle upload response seems weird. Also, there wouldn't be a good way to define when and what will be saved to disk.

I almost feel like it would be easier for you to hit up the API yourself:
```kt
fun buildPublisher(): AndroidPublisher {
    val transport = GoogleNetHttpTransport.newTrustedTransport()
    val factory = JacksonFactory.getDefaultInstance()
    val credential = GoogleCredential.fromStream(file("creds.json").inputStream(), transport, factory)
                .createScoped(listOf(AndroidPublisherScopes.ANDROIDPUBLISHER))

    return AndroidPublisher.Builder(transport, JacksonFactory.getDefaultInstance(), null).setApplicationName(packageName).build()
}

val publisher = buildPublisher()
val editId = publisher.edits().insert(packageName, null).execute().id
val tracks = publisher.edits().tracks().list(packageName, editId).execute().tracks

// Do whatever you want
```

WDYT? Doesn't that seem easier and far more flexible?
