### ISSUE TITLE
Upload mapping file to cloud storage

### ISSUE THREAD

**Issue by MaTriXy** [Triple-T/gradle-play-publisher#592]
### Problem description
Publishing the artifacts does upload the mapping to the play store but if for some reason the file is gone - you can't recover and retrace issues

### Potential solutions/workarounds
Allow optional mapping upload
Allow creating a copy of the file

**Comment by SUPERCILEX** [comment]
I'm confused, we only consume the mapping file. It's located in `app/build/outputs/mapping/release/mapping.txt` and you can do whatever you want with it. We just upload it. Long term, I'd like to provide an API that lets you write custom publishing plugins.

**Comment by MaTriXy** [comment]
I know its not consumed but if the build machine somehow  reset the build or another build is triggered we lose the file.
So i thought we could have extra setting to allow keeping the file in cloud storage somewhere with versions.

**Comment by SUPERCILEX** [comment]
Yeah, that's out of scope for this plugin. Eventually, you'll be able to use our API to upload the files we process. Since it will be generalized and not specific to the mapping file, I'm going to close this issue. You can follow #583 to see progress on the generalized solution.
