### ISSUE TITLE
Gradle lifecycle logging during build

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#593]
Just small thing, nothing extra important.

But I notice that this plugin has a very great interactive output with the current state of upload, but at the end in the log is nothing. So for example on CI server when you check the logs is not mentioned that it was uploaded to play. I did not try --info or --debug log but I think that in normal build there should be at least name od the task and operation result, like for example 

```
> Task :app:shrinkDefaultAvastReleaseResources
Removed unused resources: Binary resource data reduced from 7139KB to 6955KB: Removed 2%
```

So in the case of this plugin
```
> Task :app:publishMyFlavorRelease
aab uploaded to internal stage of xyz playstore as draft with custom name 1.0.0-RC1
```

**Comment by SUPERCILEX** [comment]
That interactive stuff is going away and has already been replaced. The snapshot builds have the new behavior. Gotta check what info I included though.

**Comment by tprochazka** [comment]
I personally don't need to see all the percentages in the log.
Maybe for debugging with --debug it makes sense.
```
Uploading mapping file: 6% complete
Uploading mapping file: 11% complete
Uploading mapping file: 17% complete
Uploading mapping file: 23% complete
Uploading mapping file: 28% complete
Uploading mapping file: 34% complete
Uploading mapping file: 40% complete
Uploading mapping file: 45% complete
Uploading mapping file: 51% complete
Uploading mapping file: 57% complete
Uploading mapping file: 62% complete
Uploading mapping file: 68% complete
```
can stay interactive. I think.

But I'm missing information about target Play, target track and draft/completed

**Comment by SUPERCILEX** [comment]
Yeah, having that many logs is overkill (I think it logs after every MB uploaded). 5 MBs probably strikes a good balance.

The reason I'm not putting that in the rich output is because a CI job will appear stuck if nothing is logged on a large upload. I'm going to try and find an API that tells me if the rich console is enabled and dump the upload logs in there if it is enabled, otherwise put them in the console.

And yeah, I'll log that extra metadata (I thought I already was). What do you mean by `target Play`? Typo?

**Comment by SUPERCILEX** [comment]
Oh yeah, I remember the other reason the interactive stuff had to go: there's no way to get a `ProgressLogger` service from a Gradle Worker.

**Comment by SUPERCILEX** [comment]
It'll look like this: `Updating [completed] release (com.supercilex.test:[380135]) in track 'internal'`

**Comment by tprochazka** [comment]
>What do you mean by target Play? Typo?

Plugin support upload to multiple Google Play Developer accounts.
So by "play" I mean the name of "playConfigs".

**Comment by SUPERCILEX** [comment]
Gotya. The package name is the unique identifier so that's what will be logged.

**Comment by tprochazka** [comment]
Yes. This is true.
