### ISSUE TITLE
GPP ignore generated release notes 

### ISSUE THREAD

**Issue by rovkinmax** [Triple-T/gradle-play-publisher#600]
### Describe the bug
I configure plugin
```
play {
    serviceAccountCredentials = file("credentials/servise-account-google-play-automator.json")
    releaseStatus = 'draft'
    track = 'production'
}
```
And register task for generate release notes file from system environment

```
def generateReleaseNotes = tasks.register("generateReleaseNotes") {
    doFirst {
        //take release notes from system var and put in to new file
        def releaseNotes = System.getenv("RNOTES") ?: "olololololololololololololo"
        if (releaseNotes != null && !releaseNotes.isBlank()) {
            def file = new File("${projectDir.path}/src/main/play/release-notes/en-US", "production.txt")
            file.text = releaseNotes
        }
    }
}

afterEvaluate {
    if (project.hasProperty("publishProdReleaseApk")) {
        tasks.named("publishProdReleaseApk").configure {
            dependsOn generateReleaseNotes
        }
    }
}
```
Also I have `default.txt` file in dir `src/main/play/release-notes/en-US`
File generates before task `publishProdReleaseApk` executed, but in Google Play created draft with default release notes.

If execute task `publishProdReleaseApk` again, when `production.txt` already exist then all be okay.

#### Versions
- Gradle Play Publisher: 2.2.1
- Gradle Wrapper:  5.1.1
- Android Gradle Plugin: 3.3.2

#### Tasks executed

`./gradlew clean publishProdReleaseApk`

### Expected behavior
I want that generated file `production.txt` used as release notes

**Comment by SUPERCILEX** [comment]
It should be:
```
tasks.named("generateProdReleasePlayResources").configure {
    dependsOn generateReleaseNotes
}
```

**Comment by rovkinmax** [comment]
Thank you, that's what I needed
