### ISSUE TITLE
Jenkins build failed with “Task 'Play' not found in root project” error

### ISSUE THREAD

**Issue by Jaik** [Triple-T/gradle-play-publisher#605]
I'm trying to setup a continuous deployment to Google Play using Jenkins. I was able to test the publish part locally from Android Studio by running the command below -

./gradlew clean :app:publishBundle

### How To Reproduce
The same command fails when I add `Invoke Gradle script` step in Jenkins and chose `Use Gradle wrapper`. I get the following error -

`Task 'Play' not found in root project 'app-bundles'.`
Here is part of my app.build gradle file using play property from the library -

```
plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '2.2.1'
}

.
.
.

play {
        track = track
        userFraction = userFraction as Double
        serviceAccountEmail = serviceAccountEmail
        serviceAccountCredentials = file(serviceAccountCredentials)
}
```

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 3.3.2
- Android Gradle Plugin: 4.10.1

#### Tasks executed

What tasks did you run? `publishBundle`.

### Expected behavior

The app would have uploaded to the play store.

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
Please provide a stack trace. Also, we don't create a task named `Play` so I doubt this is related to GPP.

**Comment by Jaik** [comment]
That was happening because of a separate Jenkins plugin (used for storing secret files) which was changing the gradlew path for that step. 
Closing this issue.
