### ISSUE TITLE
Metadata for all flavors being packaged into the apk

### ISSUE THREAD

**Issue by ssubramanian** [Triple-T/gradle-play-publisher#61]
Hi,

I have noticed that when I have metadata for multiple flavors as shown below, the publishrelease command packages the metadata for all flavors into an apk irrespective of the flavor we try to build. This is causing the apk to exceed size restrictions. Any thoughts why it would not package only the metadata for the flavor that is being built?

- [src]
  |
  + - [Flavor1]
      |
      + - [play]
      |
      | ....[folders like screenshots and so on]
      |
  + - [Flavor2]
      |
      + - [play]
      |
      | ....[folders like screenshots and so on]
      |

**Comment by bhurling** [comment]
I did not even know that the data inside the `play` folder is packaged inside the APK. I don't see that behavior in my project

**Comment by bhurling** [comment]
This is all I see in my APK. No play folder:

![apk](https://cloud.githubusercontent.com/assets/242983/7303820/6a39b006-e9f3-11e4-9bc9-81fbd9ddb2a0.png)

**Comment by jaredsburrows** [comment]
This can be closed, it is not packaged into the app at all. The android gradle plugin handles the packaging anyways.
