### ISSUE TITLE
APK not visible after publishing

### ISSUE THREAD

**Issue by kalv179** [Triple-T/gradle-play-publisher#611]
### APK not visible in the internal track after updating from 1.2.0 to 2.2.1

We have been successfully publishing APKs with version 1.2.0. However after updating to 2.2.1 the publish seems to be successful, however the APK is never visible on the Play Console. I also get an email notification from the Play Console saying my update is live, but the version is not visible.

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 4.6
- Android Gradle Plugin: 3.1.4

#### Tasks executed

`publish[variant]Apk`.

### Expected behavior

APK should be visible in the internal test track

### Additional context (if a crash, provide stack trace)

There is no error. Play console sends a notification that update is live, however apk is not visible.

**Comment by SUPERCILEX** [comment]
Can you share you `play` block with me?

**Comment by kalv179** [comment]
```
 play {
        serviceAccountCredentials = file(project.playStoreAccountKey)
        userFraction = 1
        resolutionStrategy = "auto"
    }
```

also tried with -

 ```
play {
        serviceAccountCredentials = file(project.playStoreAccountKey)
        track = "internal"
        userFraction = 1
        resolutionStrategy = "auto"
    }
```
project.playStoreAccountKey is in gradle.properties and points to the path of the credential json file. Also tried to give the path directly there.

I also have some release notes located at src/main/play/release-notes/

It's a bit strange since something is getting uploaded since the Play Console does say update is live in an email.

**Comment by SUPERCILEX** [comment]
Hmmm, and what do you mean it isn't showing up? What's in the internal track? A screenshot might help me understand.

**Comment by kalv179** [comment]
The internal track just has the previous version that was successfully uploaded with 1.2.2. It doesn't update with the version code published with the new library.

**Comment by SUPERCILEX** [comment]
Hmmm, are you sure? Can you try with the [snapshot builds](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#snapshot-builds)? And then can you share the logs from executing the gradle task? If what you say is true, there's not much I can do on the GPP, so you'd have to contact play support (I can probably speed things along).
