### ISSUE TITLE
--artifact-dir with --resolution-strategy auto causes application to build then publish instead of using the app bundle provided to the plugin

### ISSUE THREAD

**Issue by ScottBishop** [Triple-T/gradle-play-publisher#612]
### Describe the bug

When using the `--artifact-dir` option, the application is still building the app bundle instead of just using the artifact provided to the plugin. This causes the publish to be ~20 minutes longer than necessary.

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 5.1.1
- Android Gradle Plugin: 3.4.0

#### Tasks executed

```
./gradlew --stacktrace publishProdReleaseBundle --artifact-dir outputs/bundle/prodRelease --default-to-app-bundles --resolution-strategy auto
```

### Expected behavior

I expected the plugin to skip the build step and publish the app bundle provided to the plugin. Is this an issue with using `--resolution-strategy auto`, does this option require the application to be built again?

**Note**: the app bundle is uploaded correctly after building the application, but I want to release the same artifact that we ran our automation and manual tests against.

### Additional context (if a crash, provide stack trace)

./gradlew --stacktrace publishProdReleaseBundle --artifact-dir outputs/bundle/prodRelease --default-to-app-bundles --resolution-strategy auto
build	27-Jun-2019 09:18:11	> Task :buildSrc:compileKotlin UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:compileJava NO-SOURCE
build	27-Jun-2019 09:18:11	> Task :buildSrc:compileGroovy UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:pluginDescriptors UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:processResources UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:classes UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:jar UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:assemble UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:compileTestKotlin NO-SOURCE
build	27-Jun-2019 09:18:11	> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
build	27-Jun-2019 09:18:11	> Task :buildSrc:compileTestJava NO-SOURCE
build	27-Jun-2019 09:18:11	> Task :buildSrc:compileTestGroovy NO-SOURCE
build	27-Jun-2019 09:18:11	> Task :buildSrc:processTestResources NO-SOURCE
build	27-Jun-2019 09:18:11	> Task :buildSrc:testClasses UP-TO-DATE
build	27-Jun-2019 09:18:12	> Task :buildSrc:test NO-SOURCE
build	27-Jun-2019 09:18:12	> Task :buildSrc:validateTaskProperties UP-TO-DATE
build	27-Jun-2019 09:18:12	> Task :buildSrc:check UP-TO-DATE
build	27-Jun-2019 09:18:12	> Task :buildSrc:build UP-TO-DATE
build	27-Jun-2019 09:18:12	Configuration on demand is an incubating feature.
build	27-Jun-2019 09:18:12	
build	27-Jun-2019 09:18:12	> Configure project :app

...
...

build	27-Jun-2019 09:40:25	> Task :app:packageProdRelease
build	27-Jun-2019 09:40:32	> Task :app:buildProdReleasePreBundle
build	27-Jun-2019 09:40:40	> Task :app:packageProdReleaseBundle
build	27-Jun-2019 09:40:52	> Task :app:signProdReleaseBundle
build	27-Jun-2019 09:40:52	> Task :app:bundleProdRelease
build	27-Jun-2019 09:40:52	> Task :app:publishProdReleaseBundleWrapper
build	27-Jun-2019 09:41:22	> Task :app:publishProdReleaseBundle
build	27-Jun-2019 09:44:07	BUILD SUCCESSFUL in 25m 56s

**Comment by SUPERCILEX** [comment]
There are two possibilities I can think of off the top of my head.

BTW, auto resolution will not work with prebuilt artifacts, but it should just ignore the option.

The first possibility is that you have a Gradle script which adds dependencies to the publishing task. Check your build files for `dependsOn` logic.

The second option is that there's some old bug I'm not remembering. Can you try the [snapshot](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#snapshot-builds) builds?

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/649#issuecomment-517969845
