### ISSUE TITLE
internalappsharingartifacts for bundle through play store

### ISSUE THREAD

**Issue by abhimaanmadhav** [Triple-T/gradle-play-publisher#617]
### Problem description
Could not find how to publish  an android app bundle through **internalappsharingartifacts** for internal testing. This track in play store helps to upload build without any signing or version code restriction.

Could not find documentation for this hence assumed this feature doesn't exist.

### Additional context
Attached is the link for better understanding of the feature

https://developers.google.com/android-publisher/api-ref/internalappsharingartifacts/uploadbundle

**Comment by SUPERCILEX** [comment]
See  #563

**Comment by SUPERCILEX** [comment]
The feature will be part of GPP 2.3 and will be released whenever AGP 3.5 is shipped.
