### ISSUE TITLE
Support uploading debuggable internal sharing artifacts

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#619]

**Comment by abhimaanmadhav** [comment]
cant we add this to 2.3 snapshot?

**Comment by SUPERCILEX** [comment]
No, I want to ship GPP 2.3 today.

The main issue is that we've made a lot of assumptions around only having to deal with release builds. I need some more time to think about how to properly create debug variant tasks.

**Comment by SUPERCILEX** [comment]
@abhimaanmadhav Also forgot to mention this trick: `./gradlew uploadReleasePrivateApk --artifact-dir app/build/outputs/apk/debug/`.

**Comment by abhimaanmadhav** [comment]
ah right thanks for the tip :)
