### ISSUE TITLE
Conflict with maven-publish plugin

### ISSUE THREAD

**Issue by ToxicBakery** [Triple-T/gradle-play-publisher#621]
### Describe the bug

GPP conflicts with the core Gradle `maven-publish` plugin. The cause is that GPP uses the task name `publish` for publishing all artifacts.

### How To Reproduce

```
plugins {
    id 'com.github.triplet.play' version '2.2.1'
    id 'maven-publish'
}
```

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 5.4.1
- Android Gradle Plugin: 3.5.0-beta05

#### Tasks executed

`publish`

### Expected behavior

To not throw an error message for an existing task.

### Additional context (if a crash, provide stack trace)

```
Gradle error:
Cannot add task 'publish' as a task with that name already exists.
```

**Comment by SUPERCILEX** [comment]
Apply the maven plugin first. GPP knows how to handle the conflicts.

**Comment by ToxicBakery** [comment]
Gotcha, that fixed it. Thanks

**Comment by SUPERCILEX** [comment]
Awesome! I've had several people run into this, so I'm going to add some docs about it.

**Comment by SUPERCILEX** [comment]
https://github.com/Triple-T/gradle-play-publisher/compare/7a230f5f0a2630798eeb71446f00c5aa9fdab316..571e3ee36e77e808f845cfe1cc5767286db9b81f
