### ISSUE TITLE
Option to retain APK/App Bundle from previous release

### ISSUE THREAD

**Issue by OnlyInly** [Triple-T/gradle-play-publisher#630]
### Problem description
Hi!
We have a build (apk/app bundle) for WearOS and a build for Mobile. We decide that we are going to release a new version for Mobile but not for WearOS version. We would then retain the WearOS version from previous release and replace the new version for Mobile only.
Is there any option to achieve desired with Triple-T plugin? 

### Potential solutions/workarounds
Maybe new 'retain' to resolutionStrategy

**Comment by SUPERCILEX** [comment]
I'm still a little confused. So you have your production track with 2 artifacts (WearOS + app) and you want to only upload a new version of your app and retain the WearOS artifact. Is that correct?

**Comment by OnlyInly** [comment]
Yes

**Comment by SUPERCILEX** [comment]
Gotya. A feature like that would be painful because retained artifacts are identified by their version code. So the GPP API would look something like `retainedArtifacts = [123, 456]`, which can't be automated. I'm not sure that would be useful since you'll probably have to go to the Play Store anyway to find the version code. WDYT?

**Comment by OnlyInly** [comment]
Now we use the plugin to create draft release and then go to the play console and manually retain the wearOS version. It's a solution but not ideal. In our development cycle, the wearOS version updated once every few months. At the same time, the application is updated several times a month.

I agree that `retainedArtifacts` feature a little bit tricky but it can help with a CI process. So any support for this functionality will be very useful.

**Comment by SUPERCILEX** [comment]
Ohhh, I get it. Yeah, that sounds like a super useful feature. 👍

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/pull/644#issuecomment-515816693
