### ISSUE TITLE
[action][Variant][Thing] not working

### ISSUE THREAD

**Issue by jonneymendoza** [Triple-T/gradle-play-publisher#634]
This library does not seem to be able to publish a specific varient in gradle despite the documentation saying it should in the form of : [action][Variant][Thing]

So i tried a simple "publishFlavourRelease " and it states that it cant find this task

**Comment by SUPERCILEX** [comment]
Run `./gradlew tasks --group publishing` to see the full list of tasks. If it's not there, please show me your build file.

**Comment by jonneymendoza** [comment]
Sure ok here it goes

` productFlavors {
    FlavourOne {
        applicationIdSuffix ".live"
        buildConfigField 'String', 'SERVER_BASE_URL', '"http://live.com"'

    }
    FlavourTwo {
        applicationIdSuffix ".demo"
        buildConfigField 'String', 'SERVER_BASE_URL', '"http://demo.com"'
    }

buildTypes {
        debug {
            minifyEnabled false
            // shrink code (remove unused classes and methods) - note that it falls back to experimental shrinker for Instant Run
            shrinkResources false // don't strip unused res files
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-rules-debug.pro'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules-test.pro'
        }
        release {
            minifyEnabled true // shrink code (remove unused classes and methods)
            shrinkResources false // don't strip unused res files
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debugDemo {
            applicationIdSuffix '.demo'
            versionNameSuffix '-DEMO'
            minifyEnabled false
            // shrink code (remove unused classes and methods) - note that it falls back to experimental shrinker for Instant Run
            shrinkResources false // don't strip unused res files
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-rules-debug.pro'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules-test.pro'
        }
        demo {
            applicationIdSuffix '.demo'
            versionNameSuffix '-DEMO'
            minifyEnabled true // shrink code (remove unused classes and methods)
            shrinkResources false // don't strip unused res files
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }`

None of the buildtypes work and when i do publishApk it finishes the task in 2 seconds and with it saying that there is nothing to do in that task?

When i run the task command you mentioned, it outputs this:

`Publishing tasks
----------------
bootstrap - Downloads the Play Store listing metadata for all variants.
promoteArtifact - Promotes a release for every variant.
publish - Uploads APK or App Bundle and all Play Store metadata for every variant.
publishApk - Uploads APK for every variant.
publishBundle - Uploads App Bundle for every variant.
publishListing - Uploads all Play Store metadata for every variant.
publishProducts - Uploads all Play Store in-app products for every variant.
`

**Comment by SUPERCILEX** [comment]
Ok, there are only 2 possibilities:
1. You've [disabled publishing](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#disabling-publishing)
1. Your builds are all debuggable (check the build logs for the word `debuggable`)
