### ISSUE TITLE
How to upload apk from different modules

### ISSUE THREAD

**Issue by nishithkhanna** [Triple-T/gradle-play-publisher#636]
Hi, Firstly thanks so much for such an awesome tool to upload apk automatically. I had a doubt. 
My project has 4 different modules like
1. Nougat
2. Oreo 8.0
3. Oreo 8.1 
4. Pie
When I do ./gradlew publishReleaseApk It only uploads apk from one of these modules and uploads it to the track mentioned. 
So only way to upload all apk's is to use ./gradlew publishApk and enter the folder name where all 4 apk's are there. It does the trick but the build fails and the error message for each module is 
```1: Task failed with an exception.
* What went wrong:
Execution failed for task ':Pie:publishReleaseApk'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 410 Gone
  {
    "code" : 410,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "This Edit has been deleted.",
      "reason" : "editDeleted"
    } ],
    "message" : "This Edit has been deleted."
  }
```
So is there a way to upload apk's from each module without build failing.
I am on v2.2.1 of gpp as am not using AS 3.5 right now which is required on v2.3.0 plugin.

Thanks in advance for your help.

**Comment by SUPERCILEX** [comment]
Right, this is where GPP struggles. I've written some new docs, please let me know if you're able to follow them: https://github.com/Triple-T/gradle-play-publisher/tree/commit-docs#combining-artifacts-into-a-single-release

**Comment by nishithkhanna** [comment]
Hi, Thanks for your reply. I would need to be on latest snapshot or this will work on 2.2.1 too?

**Comment by nishithkhanna** [comment]
Also I had one more doubt. For example I push my app to internal and would like to promote it to beta always. Is there anyway to do it? Or will have to use that cli command mentioned in readme. If there is any gradle changes that can be done to make it permanent that will be awesome.  Sorry this is not related to the main issue but thought to ask here instead of making another issue for it.

**Comment by nishithkhanna** [comment]
> Right, this is where GPP struggles. I've written some new docs, please let me know if you're able to follow them: https://github.com/Triple-T/gradle-play-publisher/tree/commit-docs#combining-artifacts-into-a-single-release

My case is a little different as its not a flavor but module so publishNougatReleaseApk will not work.
To explain in a better way to compile a particular module I do 
./gradlew :Nougat:assembleRelease

**Comment by SUPERCILEX** [comment]
Replying to each of your comments:
- The commit stuff has been around since `v2.1.0` so you should be fine without snapshots.
- Lol, I do that too. And no, GPP doesn't support that, but we should absolutely have an official solution, so I've created #638. PS: I have some [hacks I use](https://github.com/SUPERCILEX/Robot-Scouter/blob/f7145fa2608f72a12f6f1b72d26a87680319680c/buildSrc/src/main/kotlin/com/supercilex/robotscouter/build/RobotScouterBuildPlugin.kt#L87-L101), but they're really sad and ugly, especially considering I maintain GPP.
- Hmmm, haven't seen that one before. You *can* actually make it work, but you'll have to prefix all the task names with `:project:...` and move the ordering configuration to your root build script. Though, TBH, I don't understand the use case. Why not just use product flavors? That's what they were built for. 😜

**Comment by nishithkhanna** [comment]
Regarding why we use module is that because in android folder structure in studio they are pretty easily visible. 
![Screenshot_20190725_121237](https://user-images.githubusercontent.com/28793412/61851841-97d38680-aed5-11e9-95f0-6cc7ada3678c.png)

But flavors folder are not visible in android view and the only way to see them is by changing view to project which takes some time to navigate to particular sdk version. So it is sort of a hack to make navigating easier hehehe.

**Comment by SUPERCILEX** [comment]
Lol, ok. I can't justify supporting your use case, but you should be able to make it work with the changes I mentioned above.

I'm going to close this issue, but let me know if you run into any trouble.

**Comment by nishithkhanna** [comment]
Hi, I changed to flavors instead of modules and the new docs worked like a charm. Thanks for the help. I saw you did some changes for promoting apps. Thanks for that too. Will wait when android studio 3.5 is rolled  to stable and docs are updated then will use it.
Thanks again for all the help and your patience.

**Comment by SUPERCILEX** [comment]
Awesome!

**Comment by nishithkhanna** [comment]
Hey again, So as said above I shifted to product flavors. When trying to promote it from internal to production the build doesn't fail but the app is not being promoted.

I used 
```
./gradlew promoteArtifact \
  --from-track internal --track production \
  --release-status completed
```
using this in play configs as stated in the doc
```
playConfigs {
        nougat {
            commit = false
        }

        oreo26 {
            commit = false
        }
        oreo27 {
            commit = false
        }
        pie {
            commit = true
        }
    }
```
and used this
```
afterEvaluate {
    def intermediateTasks = [
            "publishOreo26ReleaseApk",
            "publishOreo27ReleaseApk"
    ]
    tasks.matching { intermediateTasks.contains(it.name) }.configureEach {
        mustRunAfter("publishNougatReleaseApk")
    }
    tasks.named("publishPieReleaseApk").configure {
        mustRunAfter(intermediateTasks)
    }
}
```
But promotion didn't work. Need to add anything else? Using v2.2.1
