### ISSUE TITLE
Receiving back the new versionCode updated by resolutionStrategy = auto

### ISSUE THREAD

**Issue by ishantsagar** [Triple-T/gradle-play-publisher#641]
### Problem description
Is there any way right now by which I can know the value of versionCode updated by `resolutionStrategy = "auto"`?

Basically I need to tag every release on Github, something like `android_v1.5(8)` where **8** is my `versionCode`. So to make it happen I need to get back the latest versionCode pushed on the Google Play Store.

### Potential solutions/workarounds

I believe, if we can update the `build.gradle` file with the new `versionCode`, that will be good enough, as one can read the value from it and proceed.

Let me know the suggestions over it.

**Comment by SUPERCILEX** [comment]
Yes, that's described [here](https://github.com/Triple-T/gradle-play-publisher#post-processing-outputs-sanitized-by-auto-resolution). You can do whatever you want with `versionNameOverride`.

**Comment by SUPERCILEX** [comment]
Oh, and note that `versionCode` inside the `outputProcessor` block is different than the `versionCode` from the `android.defaultConfig` block. I'd recommend just using `versionCodeOverride` if you want to be sure you're using the right one.

**Comment by ishantsagar** [comment]
@SUPERCILEX Oh, so I believe any versioncode that has been associated with the build(bundle/apk) generated is going to be assigned to `versionCodeOverride` variable. But I am just a beginner with `gradle`, could you please tell me how can I access/read `versionCodeOverride` value, after the `./gradlew publish` task has done its job?

**Comment by SUPERCILEX** [comment]
Look at the docs I linked above, they show how to use it. If you have a specific example in mind, you can post the code with a placeholder variable and I can take a look.

**Comment by ishantsagar** [comment]
@SUPERCILEX I managed to call a function inside `outputProcessor` block, which writes the `versionCode` value to a `gradle.properties` file, after which I used a `Fastlane` plugin to read this value and write back to the `versionCode` in `defaultConfig` block.
