### ISSUE TITLE
Update apk + bundle task dependencies on artifactDir change propagation

### ISSUE THREAD

**Issue by abhimaanmadhav** [Triple-T/gradle-play-publisher#649]
### Describe the bug

gradle task uploadReleasePrivateBundle does not honor  --artifact-dir /pathname instead it builds everything instead of using the given path argument

### How To Reproduce
 ./gradlew uploadReleasePrivateBundle --artifact-dir /Users/abhimaanmadhav/Android/work\ space/build/outputs/bundle/release/test-release.aab

#### Versions

Run this command to get all the version info you need: 5.4.1
+--- com.android.tools.build:gradle:3.5.0-rc02
|    |    +--- com.android.tools.build:gradle:3.0.0 -> 3.5.0-rc02 (*)

- Gradle Play Publisher:  2.4-shapshot
- Gradle Wrapper: 5.4.1
- Android Gradle Plugin: 3.5.0-rc02

#### Tasks executed

 ./gradlew uploadReleasePrivateBundle --artifact-dir /Users/abhimaanmadhav/Android/work\ space/build/outputs/bundle/release/test-release.aab

### Expected behavior

it should not build the artifact instead should take artifact given as a parameter

**Comment by SUPERCILEX** [comment]
I've heard this one before, but I can't repro unfortunately. Can you search your build files for `dependsOn` and see if there's anything related to GPP. If not, what other plugins are you applying?

**Comment by abhimaanmadhav** [comment]
der no depends on in the whoel project

below are all the plugin used by me in order of its applied

id("com.android.application")
    id("kotlin-android")
    id("kotlin-kapt")
    id("kotlin-android-extensions")
    id("com.github.triplet.play")
    id("io.fabric")
    id("newrelic")
    id("com.google.firebase.firebase-perf")

**Comment by abhimaanmadhav** [comment]
note :
another interesting thing is the artifacts work if you we add the artifact path in build.gradle file 
example 
play {
    serviceAccountCredentials = file("/data/dev/credentials/api-service account.json")
    track = "internal"
    defaultToAppBundles = true
    resolutionStrategy = "ignore"
    artifactDir = file("path/to/apk-or-app-bundle/dir")
}

**Comment by SUPERCILEX** [comment]
Oh, I got it. The issue is that you're calling some sort of [eager task configurator method](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview). In the short term, fix those issue (so no `tasks.all`, no `tasks.onEach`, etc).

Long term, I should be able to fix this issue by creating a callback for when the `artifactDir` property changes, wiping out all deps with `setDependsOn(null)`, and then re-adding deps without the full app build.

**Comment by abhimaanmadhav** [comment]
i believe i am not calling any eager task config methods.Maybe other plugins like playservice, firebase performance etc plugins.do we have a work around to try for this until we get a fix?

**Comment by SUPERCILEX** [comment]
- You can check which plugins are eagerly configuring your tasks with the `--scan` option. Here's an example build where you can see that the Kotlin plugin created a task immediately : https://scans.gradle.com/s/aacsk4ancfzby/performance/configuration?focused=15&openDependencies=WyJrb3RsaW4hOmJ1aWxkU3JjIl0&openScriptsAndPlugins=Wzhd
- The workaround would be this:
  ```
  $ ./gradlew foobar -Pdir=path/to/dir

  if (hasProperty("dir")) play.artifactDir = file(property("dir"))
  ```
- I have plans to fix this properly, but haven't found the time to do so yet

**Comment by SUPERCILEX** [comment]
Depends on #652
