### ISSUE TITLE
Use same directory structure as Fastlane

### ISSUE THREAD

**Issue by devgianlu** [Triple-T/gradle-play-publisher#650]
### Problem description
My open source apps are published on F-Droid which uses the same directory structure of Fastlane for the Play Store metadata. I'd like to use this plugin, but I don't see any easy way not to duplicate all of the files in my repo.

### Potential solutions/workarounds
Symlinks aren't an option, the process is too tedious. The only option I see is to add an option to use a different method to fetch this metadata. Changing each metadata directory isn't a solution either. [docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/)

I'm not very good at Kotlin, but I can work on this if needed.

**Comment by SUPERCILEX** [comment]
That's not going to happen for a few reasons:
1. It would break everybody already using GPP
1. I don't like the fastlane structure :stuck_out_tongue: 
   1. Version coded release notes don't make sense and don't scale. That's what version control is for.
   1. The file naming is super inconsistent. We went with dashes for everything to ensure consistency.
   1. The language structure is debatable. They organized it by type, we organized by feature.
   1. The fastlane structure doesn't support variants properly.
1. **There are other solutions:** you can write a script that maps your folder structure to GPP's and then dumps everything into `app/build/generated/gpp/release/res`.

There is one good idea I'll bring back: #651

**Comment by devgianlu** [comment]
Guess I'll write a script to convert from THIS format to Fastlane. Your arguments are quite true.

**Comment by devgianlu** [comment]
Turns out that F-Droid recognizes your directory structure:
> There are two options for including the app store materials in an app’s source repository: fastlane supply and Triple-T Gradle Play Publisher.
