### ISSUE TITLE
Propagate CLI properties to override extensions

### ISSUE THREAD

**Issue by nishithkhanna** [Triple-T/gradle-play-publisher#652]
Hey again, So as said in previous issue. I shifted to product flavors. When trying to promote it from internal to production the build doesn't fail but the app is not being promoted.

I used
```
./gradlew promoteArtifact \
  --from-track internal --track production \
  --release-status completed
```
using this in play configs as stated in the doc
```
playConfigs {
        nougat {
            commit = false
        }

        oreo26 {
            commit = false
        }
        oreo27 {
            commit = false
        }
        pie {
            commit = true
        }
    }
```
and used this
```
afterEvaluate {
    def intermediateTasks = [
            "publishOreo26ReleaseApk",
            "publishOreo27ReleaseApk"
    ]
    tasks.matching { intermediateTasks.contains(it.name) }.configureEach {
        mustRunAfter("publishNougatReleaseApk")
    }
    tasks.named("publishPieReleaseApk").configure {
        mustRunAfter(intermediateTasks)
    }
}
```
But promotion didn't work. Need to add anything else? Using v2.2.1
I have another app which has no product flavor and it is working fine.

**Comment by SUPERCILEX** [comment]
Sadly, you're going to have to do the `afterEvaluate` block again, but for promotion. So this:
```kt
afterEvaluate {
    def intermediateTasks = [
            "promoteOreo26ReleaseArtifact",
            "promoteOreo27ReleaseArtifact"
    ]
    tasks.matching { intermediateTasks.contains(it.name) }.configureEach {
        mustRunAfter("promoteNougatReleaseArtifact")
    }
    tasks.named("promotePieReleaseArtifact").configure {
        mustRunAfter(intermediateTasks)
    }
}
```

Please let me know if that doesn't work.

**Comment by nishithkhanna** [comment]
Hi, So I copied the above block but it didn't work. I was able to see one thing in output of gradle it said promoting internal -> internal.

**Comment by SUPERCILEX** [comment]
Ohhhh, crap. Can you try running this?
```
./gradlew promoteOreo26ReleaseArtifact promoteOreo27ReleaseArtifact promoteNougatReleaseArtifact promotePieReleaseArtifact \
  --from-track internal --track production \
  --release-status completed
```

**Comment by nishithkhanna** [comment]
Hey, I tried this from internal to alpha as couldn't push to production yet might do that tomorrow or something but promoting to alpha worked with the latest command. In gradle output it said internal -> internal but it worked anyhow.
So I guess it should be good now thanks again for your help.

**Comment by SUPERCILEX** [comment]
Cool beans! And about prod, make sure you've given the `Manage production releases` permission: https://github.com/Triple-T/gradle-play-publisher#service-account

**Comment by nishithkhanna** [comment]
Yes, that permission I have given. As my other apps without product flavors are working.

I have two doubts.
1. That after evaluate block is needed with this new command
2. Does the position of command matter as in like it started with Oreo26 and ended with pie. This should be followed or can use it any way.

**Comment by SUPERCILEX** [comment]
Yes, the after evaluate block is still needed. Gradle doesn't use the order of the tasks you specify to run the build. So `./gradlew task1 task2` vs `./gradlew task2 task1` does NOT imply different execution order.

PS: if https://github.com/Triple-T/gradle-play-publisher/issues/652#issuecomment-518093086 works but `promoteArtifact` doesn't, that would be a bug. Feel free to ping me if that's the case.

**Comment by nishithkhanna** [comment]
Hi, So I tested thoroughly today and ./gradlew promoteArtifact works on app which doesn't use flavors. But if flavors are used then it doesn't work.

```
./gradlew promoteOreo26ReleaseArtifact promoteOreo27ReleaseArtifact promoteNougatReleaseArtifact promotePieReleaseArtifact \
  --from-track internal --track production \
  --release-status completed
```
This works without any issues.

**Comment by SUPERCILEX** [comment]
Thanks for confirming, that's definitely a bug.
