### ISSUE TITLE
Flutter-App with firebase_analytics faild on publishReleaseApk FAILED

### ISSUE THREAD

**Issue by DagobertDokate** [Triple-T/gradle-play-publisher#656]
#### Versions

- Gradle Play Publisher: 
- Gradle Wrapper: 
- Android Gradle Plugin: 

#### Tasks executed

What tasks did you run? For example, `publishBundle`.

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
Please fill out the template
