### ISSUE TITLE
Flutter with firebase_analytics faild on publishReleaseBundle

### ISSUE THREAD

**Issue by DagobertDokate** [Triple-T/gradle-play-publisher#658]
I am developing an android app with flutter.
It can be built "normal" (assemble with gradle) and uploaded in the store. 
If I want to upload the app now with the Publisher-Plugin I get in step :app:publishReleaseBundle FAILED
"WARNING: This version of firebase_analytics will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated." and the plugin aborts.

This is a bit strange, isn't it? The build went through before oO
Is that a bug? Or can I force the plugin to continue?

best regards

pubspect.yaml dependencies:

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  firebase_analytics: ^4.0.2
  firebase_core: ^0.4.0+8
  firebase_crashlytics: ^0.1.0+2
  sentry: 2.2.0
  firebase_performance: ^0.3.0+4

Gradle Version: 5.4
PluginVersion 2.2.1

Run:
> Task :app:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
> Task :app:buildReleasePreBundle
> Task :app:collectReleaseDependencies UP-TO-DATE
> Task :app:configureReleaseDependencies UP-TO-DATE
> Task :app:packageReleaseBundle
> Task :app:validateSigningRelease UP-TO-DATE
> Task :app:signingConfigWriterRelease UP-TO-DATE
> Task :app:signReleaseBundle
> Task :app:bundleRelease
> Task :app:publishReleaseBundleWrapper
> Task :app:publishReleaseBundle
> Task :app:publishReleaseBundle FAILED
         *********************************************************
WARNING: This version of firebase_analytics will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
165 actionable tasks: 12 executed, 153 up-to-date
09:13:03: Task execution finished 'publishReleaseBundle'.

**Comment by SUPERCILEX** [comment]
Yeah, I don't think this is related to the plugin. Can you run the Gradle command with `--stacktrace` to get more details?

**Comment by DagobertDokate** [comment]
> > Configure project :app
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:processReleaseGoogleServices
Parsing json file: /Users/..../Projekte/.../app/google-services.json

> Task :app:publishReleaseBundle FAILED
         *********************************************************
WARNING: This version of firebase_analytics will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
201 actionable tasks: 18 executed, 183 up-to-date

output from  ./gradlew publishReleaseBundle -s

**Comment by SUPERCILEX** [comment]
Can you please share the actual stacktrace?
