### ISSUE TITLE
Android Studio 3.4 Unsupported

### ISSUE THREAD

**Issue by kristiyanP** [Triple-T/gradle-play-publisher#660]
### Describe the bug
The newest versions(2.3.0 & 2.2.1) of the plugin don't work with Android Studio 3.4 (Latest stable version)

### How To Reproduce
Include the plugin in Android Studio 3.4

#### Versions
Tested on 2.3.0 & 2.2.1

- Gradle Play Publisher: 2.3.0
- Gradle Wrapper: Gradle 5.5
- Android Gradle Plugin: 3.4.2

### Expected behavior

To compile with latest stable version of Android Studio.

Am I missing something?

**Comment by nishithkhanna** [comment]
Plugin 2.2.0 should work with Android Gradle Plugin as currently using it on Android Studio 3.4
Plugin 2.3.0 will not work on it as it is based android gradle plugin 3.5.0 which requires Android Studio 3.5 to work which is currently in beta right now. The error in studio will be 
```
This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.
```
which is normal as that gradle is not supported for current stable Android Studio.
You can run it via cli if you want that will work.
But 2.2.0 should work. As Supercilex said you need to provide log for it.

**Comment by SUPERCILEX** [comment]
Oh, I see. Yeah, that's normal. The [release notes](https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.3.0) have a section on it. Also, AGP 3.5 will be going stable soon (hopfully next week since it's in RC).

**Comment by kristiyanP** [comment]
Yes, exactly as @nishithkhanna analyzed.
Looks like I had some cache issues which did not enable me to get the 2.2.1 working.
I confirm that 2.2.1 works with Android Studio 3.4.

For those who encounter my problem clean all cache when downgrading from 2.3 to 2.2.1 of the plugin.
