### ISSUE TITLE
Publishing fails with 400 Bad Request

### ISSUE THREAD

**Issue by VasileUngureanu** [Triple-T/gradle-play-publisher#669]
### Describe the bug

Hi,

Everything was working perfectly for a long time until recently.
It fails with next main error:
```
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
  {
    "error" : "invalid_grant",
    "error_description" : "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems."
  }
```
### How To Reproduce

Task executed:
```./gradlew publishReleaseApk```

#### Versions

Versions:
- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 5.4.1
- Android Gradle Plugin: 3.4.2

Hope you will give me at least the direction where i need to look for the problem.

Thanks!

**Comment by SUPERCILEX** [comment]
Sadly, there's not much I can do. I would say just wait it out or contact support through the play console. Also, make sure nothing changed in your app recently and maybe try on another computer? Sorry I can't be more helpful.

**Comment by VasileUngureanu** [comment]
Hi,

Maybe it will be useful for those who encounter the same problem:
Clock on my MacBook was wrong for some unknown reasons...
