### ISSUE TITLE
Support hooking into publish tasks

### ISSUE THREAD

**Issue by bhurling** [Triple-T/gradle-play-publisher#67]
It would be nice to have some mechanism to hook custom code into the publisher tasks. The main object to expose here would be the current `Edits` instance. That way we allow developers to perform additional work on the API without implementing every feature request in the main plugin.

Who's interested in this feature?

Perhaps we can collect some use cases here.

**Comment by brp-david** [comment]
My use case (as in #62 ), albeit probably not very common, is that I need to know the current version of the production-apk to do pre-processing before the publish task. Apart from that I can't really see any other cases and even my own feels weird and not exactly something publishers in general need to worry about.

I'm still interested though, and exposing the Edits instance would be enough for me.

**Comment by bhurling** [comment]
No relevant use cases
