### ISSUE TITLE
xml instead of txt file for listing

### ISSUE THREAD

**Issue by inProjects** [Triple-T/gradle-play-publisher#676]
### Problem description
Hi,
Do you support XML format file instead of 'txt' for listing? I have a lot of flavors that have common text with small changes between each of them. For example, the title for each of them will be something like: [common text] by [app-name], which app-name is a value from unique string.xml for each flavor.
Thanks.

**Comment by SUPERCILEX** [comment]
No, because I want to stick to what the AndroidPublisher API does (which is just plain text).

There's been some discussion about this before: #227. Of course, if you want to write your own plugin that preprocesses stuff and writes it to a format that GPP can understand, that's totally doable.
