### ISSUE TITLE
Loading first bundle manually

### ISSUE THREAD

**Issue by inProjects** [Triple-T/gradle-play-publisher#677]
### Describe the bug
Hi,
I have a lot of flavors that their package name diff only with the suffix. I already upload one of the flavors manually. When trying to upload the rest with the library, I get message that I must upload each. 
Is it a correct flow? or there is a solution to upload the rest flavors automatically?
Thanks!

#### Versions

- Gradle Play Publisher: 
- Gradle Wrapper: 
- Android Gradle Plugin: 

#### Tasks executed

What tasks did you run? For example, `publishBundle`.

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
Yup, sadly that's how it works. I think it's to prevent spam or something: https://developers.google.com/android-publisher/edits/

> You can only use this API to make changes to an existing app (that has at least one APK uploaded); thus, you will have to upload at least one APK through the Play Console before you can use this API. Furthermore, you cannot use this API to change an app's state from "published" to "unpublished", or to fill out the legal consents required for publishing. To publish the app, you have to use the Play Console.
