### ISSUE TITLE
Where does uploadReleasePrivateApk upload to?

### ISSUE THREAD

**Issue by tomaszrykala** [Triple-T/gradle-play-publisher#678]
I have set up a service account as instructed and I use the json key. I am interested in publishing to the internal track only with the library.

```
play {
    serviceAccountCredentials file("......json")
    track "internal" // default, but specified for clarity
}
```

When I run `./gradlew publishReleaseApk` the apk is uploaded and immediately published.

I would like to upload but not immediately publish so I tried to run `./gradlew uploadReleasePrivateApk`. The script reports that the apk was uploaded and produces a url in the console. That url is a 404 and I can't see the APK anywhere in the Play Console.

Maybe the thing I'm really unclear on is what is the difference between `Internal Sharing APK` and `APK`? Sorry if that's a silly question.

**Comment by SUPERCILEX** [comment]
Publishing stuff and uploading a private release are two completely different APIs. The private releases are what the Play Store call ["Internal app sharing"](https://support.google.com/googleplay/android-developer/answer/9303479?hl=en). What you're probably looking for is a "draft" release that will be uploaded but not published. More info on available options [here](https://github.com/Triple-T/gradle-play-publisher#common-configuration).

**Comment by tomaszrykala** [comment]
You're right. Thank you for being so helpful and for the lib of course :)

**Comment by SUPERCILEX** [comment]
😊

**Comment by sachinsadhu11** [comment]
I have run this cmd for private bundle ./gradlew uploadReleasePrivateBundle,  but i am not able to find apk on console

Please check below Screenshot

![image_2022_03_02T06_48_23_354Z](https://user-images.githubusercontent.com/81043586/156310355-96c3ea16-6768-4d0c-8273-e161c949622f.png)
