### ISSUE TITLE
Run Play Bundle task

### ISSUE THREAD

**Issue by skimarxall** [Triple-T/gradle-play-publisher#680]
### Problem description
In order to test the full Internal Sharing flow, devs must build a bundle, upload it to Play Console internal sharing, copy the upload link and open it inside a device, then install the app and try it out.

This becomes more important for testing Dynamic Features since Internal Sharing is the only way to test the "user" flow of installing the app and installing a dynamic feature.

### Potential solutions/workarounds
Currently using the plugin with a simple Gradle tasks that depends on uploadReleasePrivateBundle and reads the output json to retrieve the URL and launch it via adb works. Although an integration directly in the plugin would be better.

### Additional context
Proposed task name: runPlayBundle
Challenge: how to handle multiple or no connected devices. 
Dependencies: Using the workaround to specify the folder works but having #619 implemented would be better

**Comment by SUPERCILEX** [comment]
Whoops, forgot to add the label.

**Comment by Whipsmith** [comment]
@skimarxall Could you give an example of how you extract the URL from the output json? I would like to automate sending that to my testers as part of my build process, but my gradle skills are a bit lacking.

**Comment by SUPERCILEX** [comment]
@Whipsmith Since this feature depends on the API response we get back from the AndroidPublisher and I don't want to guarantee compatibility across GPP versions, I haven't documented this feature. That means I won't feel bad breaking people. With that said, I have no plans to break stuff so you should feel pretty safe it.

Ok, so here are my lightning fast docs. When you run an Internal Sharing task, it will output the API response into a folder such as `app/build/outputs/internal-sharing/[bundle/apk]/[variant]/`. Each file will be named `[file creation timestamp].json`. For example, here's file `app/build/outputs/internal-sharing/bundle/release/1567900521492.json`:
```js
{
  "certificateFingerprint" : "SHA256: 3F:BD:02:C2:C7:58:FC:E9:3E:60:6F:F0:82:12:9B:A8:68:6A:52:4D:FE:C4:27:DA:39:EE:B6:BC:A8:36:A5:26",
  "downloadUrl" : "https://play.google.com/apps/test/RQfyunnt0Yk/ahAAvZMmhXICGYSObY05pAifC0laUwSoNzFQMxIYS7wXyjMrgKtCe-Vkn-ElhTquZpY3ROgcJJt-yPp369P55gxjkB",
  "sha256" : ""
}
```

The code is located here if you're curious: https://github.com/Triple-T/gradle-play-publisher/blob/b634da71fe0ffddd2b573247637d84b03f516fc5/plugin/play/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishInternalSharingBundle.kt#L57-L59

**Comment by Whipsmith** [comment]
Thanks!

**Comment by skimarxall** [comment]
@SUPERCILEX that's great! Thanks for implementing it. Using the DeviceProvider is great.

There is an issue or at least missing feature though.

The tasks does not depend on bundleVariant meaning that if I do changes in code and run the install tasks it won't rebuild the app and install the previous uploaded version.

To fix that I have to run './gradlew bundleDebug installReleasePrivateArtifact'

Shall we make this tasks depend on the build?

**Comment by SUPERCILEX** [comment]
Hmmm, it should build the bundle if you have `play.defaultToAppBundles = true` set to true. Otherwise it picks apks. Does that work?

**Comment by skimarxall** [comment]
Yes, I guess the issues is that I am redirecting the artifactDir to the debug folder since I want to run this for debug builds. 

This is my setup:

```
play {
    serviceAccountCredentials = file("service_account_credentials.json")
    artifactDir = file("build/outputs/bundle/debug")
    defaultToAppBundles = true
}
```

After modifying a file, if I run again installReleasePrivateArtifact it won't build again.

```
12:07:51 PM: Executing task 'installReleasePrivateArtifact'...

Executing tasks: [installReleasePrivateArtifact] in project ...

> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validateTaskProperties UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :app
Signing not ready. Be sure to specify a signingConfig for variant 'release'.

> Task :app:publishReleaseBundleWrapper UP-TO-DATE
> Task :app:uploadReleasePrivateBundle UP-TO-DATE
> Task :app:installReleasePrivateArtifact

BUILD SUCCESSFUL in 677ms
2 actionable tasks: 1 executed, 1 up-to-date
12:07:53 PM: Task execution finished 'installReleasePrivateArtifact'.
```

If I remove the artifactDir seems to work as expected. 

Are there plans to support installDebugPrivateArtifact?

**Comment by SUPERCILEX** [comment]
@skimarxall Right, cuz Gradle knows nothing about `build/outputs/bundle/debug`. Until #619 is resolved (which I'm planning on doing after I finish the [testing refactors](https://github.com/Triple-T/gradle-play-publisher/issues/709)), you'll have to manually wire up the tasks like so:
```kt
afterEvaluate {
    tasks.named("uploadReleasePrivateBundle").configure {
        dependsOn("bundleDebug")
    }
}
```

**Comment by skimarxall** [comment]
Correct. Thanks for the info.
