### ISSUE TITLE
Can't bump rollout percentage after updating to 2.4.1 when mapping.txt doesn't exist

### ISSUE THREAD

**Issue by christxph** [Triple-T/gradle-play-publisher#697]
### Describe the bug

I'm using the GPP plugin to bump the release rollout of a staged release. This worked fine with v2.2.1 but no longer works with v2.4.1 because the plugin is looking for the mapping.txt file, however it doesn't need the mapping if I'm bumping the rollout percentage of an already published artifact.

### How To Reproduce

The command I'm using:
`./gradlew promotePlayStoreReleaseArtifact -p . --from-track production --track production --release-status inProgress --user-fraction 0.02`

The product flavor is called `playStore`.

This command worked fine with GPP v2.2.1 but no longer works with v2.4.1 because of the missing mapping.txt

#### Versions

- Gradle Play Publisher: 2.4.1
- Gradle Wrapper: 5.6.2
- Android Gradle Plugin: 3.5.0

### Expected behavior

The command mentioned above should increase the rollout percentage to 2%

### Additional context (if a crash, provide stack trace)

Error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:promotePlayStoreReleaseArtifact'.
> File '/builds/android-app/app/build/outputs/mapping/playStore/release/mapping.txt' specified for property 'mappingFile$plugin' does not exist.
```

**Comment by SUPERCILEX** [comment]
Fixed by #711
