### ISSUE TITLE
Cannot download plugin from Maven repository

### ISSUE THREAD

**Issue by zawadz88** [Triple-T/gradle-play-publisher#698]
### Describe the bug
We are unable to use the plugin on our CI machines as it seems there's an issue with getting the plugin from Jitpack Maven repository:
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.triplet.gradle:play-publisher:2.2.0.
     Required by:
         project :
      > Could not resolve com.github.triplet.gradle:play-publisher:2.2.0.
         > Could not get resource 'https://jitpack.io/com/github/triplet/gradle/play-publisher/2.2.0/play-publisher-2.2.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/triplet/gradle/play-publisher/2.2.0/play-publisher-2.2.0.pom'. Received status code 401 from server: Unauthorized
```
This also happens for version 2.4.1

### How To Reproduce
Try to build the app with plugin added to your project e.g.
```
./gradlew assembleDebug --refresh-dependencies
```

#### Versions
- Gradle Play Publisher: 2.2.0 & 2.4.1
- Gradle Wrapper: 5.5.1
- Android Gradle Plugin: 3.5.0

#### Tasks executed
```
./gradlew assembleDebug --refresh-dependencies
```

### Expected behavior

The plugin should be fetched from Maven repo

### Additional context (if a crash, provide stack trace)
We use other artifacts from jitpack.io, but we only started having issues with this plugin.

**Comment by SUPERCILEX** [comment]
This is a bug with Jitpack, make sure to put it at the bottom of your list of repositories.

**Comment by zawadz88** [comment]
Hi @SUPERCILEX, putting at the bottom of the list doesn't change anything since it's the only repository with this artifact. I also have:
```
mavenCentral()
google()
jcenter()        
```
but it's not available there.
Is this plugin available at something other than Jitpack?

**Comment by SUPERCILEX** [comment]
It's not on Jitpack, please read the documentation: https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#installation

**Comment by MarcusWolschon** [comment]
Documentation in README.md is incomplete.
It listst how to install "2.7.0-SNAPSHOT" (rejected by proxy because if "Virus Found")
but not how to install any of the releases.

The 2.6.1 release on Github is not present on Sonatype.
https://oss.sonatype.org/#nexus-search;gav~com.github.triplet.gradle~play-publisher~~~
only lists releases up to 2.0.0-rc1 but not an of the later ones.
