### ISSUE TITLE
Add tasks for build types

### ISSUE THREAD

**Issue by nscherer** [Triple-T/gradle-play-publisher#699]
Unless I'm missing it, there is no task created such as "publishReleaseApk" or just "publishRelease", to publish all flavors of the release build type.  I have a bunch of flavors to publish, but I only want to publish the release variants, and it looks like I have to make a custom task to do them all at once.

**Comment by SUPERCILEX** [comment]
That's definitely not true, look for error/warning logs to see why nothing is being generated.

**Comment by SUPERCILEX** [comment]
Please open a new issue with the template filled out and a build log (aka copy the output of `./gradlew publish`).

**Comment by SUPERCILEX** [comment]
Sorry for the issue jumping, please follow these instructions: https://github.com/Triple-T/gradle-play-publisher/issues/700#issuecomment-533818829
