### ISSUE TITLE
Update to Google Play Developer API version 3

### ISSUE THREAD

**Issue by AndreSand** [Triple-T/gradle-play-publisher#702]
Hi, currently I'm getting this message on Google Console:
`We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date. Learn more`

I'm using GPP version 2.1.0, I found the commit "Upgrade to Android Publisher API v3'
https://github.com/Triple-T/gradle-play-publisher/commit/c0ca5088d920f66ca5094ec4c19d86b1e3642e09
So if I update to GPP version 2.4.1, it will fix the warning correct?

Thanks!

**Comment by SUPERCILEX** [comment]
Anything on 2.x is fine and uses v3 of the AndroidPublisher API.

**Comment by AndreSand** [comment]
Thanks for the info. I think it might be related to my android billing dependency version. Thanks!

**Comment by tobltobs** [comment]
First thanks a lot for this super useful tool. It saves me a ton of time.

I am using `id("com.github.triplet.play") version "2.5.0"`. 
My Google Play Dashboard showed me a big fat yellow banner today:

> ACTION REQUIRED: Your automated publishing to Google Play will stop working on December 1, 2019
> Your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. [read more ](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html )

@AndreSand I am also using billing. How might that cause this warning?

**Comment by SUPERCILEX** [comment]
@tobltobs billing shouldn't have anything to do with it. TBH, I think there's a bug in Google's API detection algorithm. As long as you:
- don't have use any other plugins or have your own server that interacts with the AndroidPublisher API
- Are on GPP v2.x

You can probably ignore the warning. You can also run `./gradlew buildEnv` to validate that v3 of the API is being used.

**Comment by scottyab** [comment]
Hey  @tobltobs and @AndreSand. We had the same warning and running  `./gradlew buildEnv` as @SUPERCILEX  suggests seesm to confirm we're using v3. 

See the 2nd line ` \--- com.google.apis:google-api-services-androidpublisher:v3-rev71-1.24.1`

```
+--- com.github.triplet.gradle:play-publisher:2.2.1
|    \--- com.google.apis:google-api-services-androidpublisher:v3-rev71-1.24.1
|         \--- com.google.api-client:google-api-client:1.24.1
|              +--- com.google.oauth-client:google-oauth-client:1.24.1
|              |    +--- com.google.http-client:google-http-client:1.24.1
|              |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|              |    |    \--- org.apache.httpcomponents:httpclient:4.5.3 -> 4.5.6 (*)
|              |    \--- com.google.code.findbugs:jsr305:3.0.2
|              +--- com.google.http-client:google-http-client-jackson2:1.24.1
|              |    +--- com.google.http-client:google-http-client:1.24.1 (*)
|              |    \--- com.fasterxml.jackson.core:jackson-core:2.9.2
|              \--- com.google.guava:guava:20.0 -> 27.0.1-jre (*)
```
