### ISSUE TITLE
GPP v3.0 tasks

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#710]
Root issue for stuff that needs to happen when we bump the plugin to v3.0.

**Comment by tobltobs** [comment]
First thanks a lot for this super useful tool. It saves me a ton of time.

My Google Play Dashboard showed me a big fat yellow banner today:

> ACTION REQUIRED: Your automated publishing to Google Play will stop working on December 1, 2019
> Your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. [read more ](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html )

Is there a release date scheduled for GPP v3.0?
As this is already in a few days, do we have to expect to live a few days or weeks without the help of the gradle-play-publisher?
