### ISSUE TITLE
Snapshot publish broken after exposing project deps

### ISSUE THREAD

**Issue by knordbo** [Triple-T/gradle-play-publisher#719]
### Describe the bug

After the change to expose some of the project dependencies (they are no longer compileOnly), these dependencies are now showing up in the pom with unspecified version which means it cannot be resolved.

https://github.com/Triple-T/gradle-play-publisher/commit/e31eb03ad2c8de08b864716d724abf776e7373ab#diff-8aabdb9422c92d947a3a6b3693a9f3aeL10

This could have been an accidental commit.

### How To Reproduce

Try to consume the snapshot from sonatype

Working POM: https://oss.sonatype.org/content/repositories/snapshots/com/github/triplet/gradle/play-publisher/2.5.0-SNAPSHOT/play-publisher-2.5.0-20191004.031631-10.pom
Broken POM:
https://oss.sonatype.org/content/repositories/snapshots/com/github/triplet/gradle/play-publisher/2.5.0-SNAPSHOT/play-publisher-2.5.0-20191004.034329-10.pom

At the bottom of the pom you can see the unspecified deps

#### Versions

Latest snapshot

**Comment by knordbo** [comment]
Put up PR to demonstrate it, that PR is actually blocked by the fact that the test app is trying to download the latest snapshot which doesn't work :P https://circleci.com/gh/Triple-T/gradle-play-publisher/110?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SUPERCILEX** [comment]
Whoops, my B. Thanks for catching that! 😻
