### ISSUE TITLE
Can't find title, fulldescription etc.

### ISSUE THREAD

**Issue by Allansk2** [Triple-T/gradle-play-publisher#72]
I'm not sure I am doing it right, I could do publishApkRelease task, upload a new apk, but I could't update the listing, I have the descriptions and title files in structure <project_name\app\src\main\play\<de-DE and en-US>\listing\<title.txt fulldescription.txt shortdescription.txt>, I got error The app has no title/short descripts. Below is the screenshots. Can anyone tell me what I am missing.

![1](https://cloud.githubusercontent.com/assets/6540316/7501351/8753ad66-f3f0-11e4-98db-38304ee5693f.PNG)

![2](https://cloud.githubusercontent.com/assets/6540316/7501362/92186ae8-f3f0-11e4-88e7-d98fecce672e.PNG)

![4](https://cloud.githubusercontent.com/assets/6540316/7501366/9bac3de6-f3f0-11e4-90c1-e31c21774367.PNG)

 Thanks.

**Comment by bhurling** [comment]
It's the .txt extension that is causing this. Please remove the extension and try again.

Of course, windows is hiding the extensions for known file types. Never knew why that would be useful, anyway.

**Comment by Allansk2** [comment]
Thanks, just try it, it's working.
