### ISSUE TITLE
Gradle 6.0 causes an error

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#738]
### Describe the bug

Using Gradle 6.0 causes this
![image](https://user-images.githubusercontent.com/3314607/68977929-c6b19780-07f9-11ea-8944-05fdcd0b09fe.png)

### How To Reproduce
<img width="641" alt="image" src="https://user-images.githubusercontent.com/3314607/68977942-d03aff80-07f9-11ea-931f-fd49e8b97177.png">

#### Versions
2.5.0

**Comment by hannesa2** [comment]
Maybe it's related to this: With Gradle 5.6.4 I run into this, but this is clear, what's wrong here
<img width="699" alt="image" src="https://user-images.githubusercontent.com/3314607/68978071-1728f500-07fa-11ea-8f28-c67b381beb32.png">

**Comment by pavlospt** [comment]
https://github.com/Triple-T/gradle-play-publisher/issues/734

**Comment by hannesa2** [comment]
Ok, I can wait for `2.5.1`

**Comment by SUPERCILEX** [comment]
Just published GPP 2.6. 🎉
