### ISSUE TITLE
Release multiple APKs

### ISSUE THREAD

**Issue by sonalbharavani14** [Triple-T/gradle-play-publisher#745]
Is there any feature for releasing multiple apks of product flavour with different playstore account? Like can i write multiple play{} block or anything?

**Comment by SUPERCILEX** [comment]
Yup: https://github.com/Triple-T/gradle-play-publisher#using-multiple-service-accounts

**Comment by SUPERCILEX** [comment]
I'd also recommend reading https://github.com/Triple-T/gradle-play-publisher#working-with-product-flavors to better understand how `playConfigs` work.

**Comment by sonalbharavani14** [comment]
Thanks @SUPERCILEX
