### ISSUE TITLE
New Gradle Sync is not supported due to containing Kotlin modules

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#747]
### Describe the bug

During  #746 I run into `New Gradle Sync is not supported due to containing Kotlin modules` first time open project

#### Versions
It's obsolete, I'm on 91902aa8e5e7196 in this repo

#### Tasks executed

`git clone https://github.com/Triple-T/gradle-play-publisher.git` now I'm on 91902aa8e5e7196

and first time open project in Android Studio

### Expected behavior

I don't want to see this 
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/3314607/70392213-cdd55b00-19dd-11ea-81a4-4a8b3cdbb11c.png">

**Comment by SUPERCILEX** [comment]
Disable the "Only sync active variant" setting (worded something like that).

**Comment by SUPERCILEX** [comment]
Found it:
![image](https://user-images.githubusercontent.com/9490724/70394486-7073e680-19aa-11ea-8bc9-2beda3c81564.png)
