### ISSUE TITLE
Json setup unclear

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#749]
I tried to prepare for version 3 and switch to json setup, but it's very confusing and at least not working. Maybe you have an advice for me ?

### A: I followed the Readme :

<img width="660" alt="image" src="https://user-images.githubusercontent.com/3314607/70415051-0d428c80-1a5c-11ea-89c7-48f25235089e.png">

### B: And run into ...
<img width="850" alt="image" src="https://user-images.githubusercontent.com/3314607/70415184-5bf02680-1a5c-11ea-96c3-109710b48f4c.png">

### C: My settings
![image](https://user-images.githubusercontent.com/3314607/70415320-a7a2d000-1a5c-11ea-8a6e-4627427b48f7.png)

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3314607/70415362-b8ebdc80-1a5c-11ea-8bde-4ce16ab579da.png">
########
<img width="380" alt="image" src="https://user-images.githubusercontent.com/3314607/70415624-57783d80-1a5d-11ea-8f9a-5658ad83c20c.png">

![image](https://user-images.githubusercontent.com/3314607/70415445-eb95d500-1a5c-11ea-97d7-db62267ecca6.png)

**Comment by hannesa2** [comment]
As a general feedback, but I know it's not your fault :

It's too complicated and confusion, too much click and create there an account , and click something again, click, click ...
I want to have here a script or similar, with much less interactions !

**Comment by SUPERCILEX** [comment]
Hmmm, everything looks correct. You sure the GCP project in the `Linked project` screenshot is the same one that owns the service account? And the credentials you're using really are the right ones? I'm pretty sure that last screenshot is fine. Also, is this API enabled? https://console.developers.google.com/apis/library/androidpublisher.googleapis.com?id=9e04125c-74ec-4b95-8ed6-adc2a682e82c

**Comment by hannesa2** [comment]
Yes, it's enabled
<img width="422" alt="image" src="https://user-images.githubusercontent.com/3314607/70416671-e423fb00-1a5f-11ea-92cb-76c6fc6ebf9c.png">

And all is the same account !

My wish is:
Please don't drop in 3.0 the current way !
If not, I've to setup >10 apps, and I've a huge fear about this

**Comment by SUPERCILEX** [comment]
Huh, I just checked my own config and it seems like the service account needs pubsub access for whatever reason. Can you try giving the service account the `Pub/Sub Viewer` permission? https://console.cloud.google.com/iam-admin/iam

**Comment by hannesa2** [comment]
Thank you to have a look on it !

Ok, I followed your suggestion
![image](https://user-images.githubusercontent.com/3314607/70497159-856b8980-1b12-11ea-847f-5fda8ac6ab4d.png)
 ```
 A failure occurred while executing com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
   > 403 Forbidden
    {
       "code" : 403,
       "errors" : [ {
         "domain" : "androidpublisher",
         "message" : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
         "reason" : "projectNotLinked"
       } ],
       "message" : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."
     }

```

Unfortunately it doesn't solve the issue.
Now, I extend a too much complex (and manual click) system, with more complexity. In my point of view this is not always the best way.
 
I don't know which problem is solved by removing current way of configuration and switch to json, but I vote strongly to not remove current way.
Why ?  Because it's working !

**Comment by SUPERCILEX** [comment]
> I don't know which problem is solved by removing current way of configuration and switch to json

JSON vs PKCS12 is irrelevant for the problem you're encountering since you still need to configure the service account and go through all that mumbo jumbo setup either way. BTW, I don't control any of that so there's not much I can do to improve the experience.

Rereading your error, I'm kinda convinced you linked the wrong GCP project. Open your `creds.json` and look for the `project_id` field. Now click on the [`Linked project`](https://play.google.com/apps/publish#ApiAccessPlace) and be 1000% sure the resolved `project` query param in the URL is the same as the `project_id` you found earlier. If they are the same, then you'll probably have better luck contacting support because I don't know what could have gone wrong.

**Comment by hannesa2** [comment]
Thank you for your help ! 
For me it looks right, but please confirm a valid setup, before I contact support

### Json

<img width="459" alt="image" src="https://user-images.githubusercontent.com/3314607/70598111-5f191d00-1bea-11ea-88f7-f73eaf8b3e50.png">

### Playstore
<img width="652" alt="image" src="https://user-images.githubusercontent.com/3314607/70598209-9be51400-1bea-11ea-820e-06648c2f34f1.png">

### Google API
<img width="617" alt="image" src="https://user-images.githubusercontent.com/3314607/70598257-b6b78880-1bea-11ea-9450-8f64e3395354.png">

**Comment by SUPERCILEX** [comment]
Yeah, that looks right to me. Last ditch effort: does [this](https://stackoverflow.com/a/52540746/4548500) happen to work for you?

**Comment by SUPERCILEX** [comment]
Gonna close this in favor of #751
