### ISSUE TITLE
Check to make sure an app exists first

### ISSUE THREAD

**Issue by jaredsburrows** [Triple-T/gradle-play-publisher#75]
It seems that you must upload an initial APK:

> com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
  {
    "code" : 404,
    "errors" : [ {
      "domain" : "global",
      "location" : "packageName",
      "locationType" : "parameter",
      "message" : "No application was found for the given package name.",
      "reason" : "applicationNotFound"
    } ],
    "message" : "No application was found for the given package name."
  }

**Comment by bhurling** [comment]
Perhaps we should wrap that exception into our own exception like we did for invalid locales - #33

**Comment by janni2** [comment]
Is it possible to upload a new apk, whose package name is not yet registered at google play store ? In the androidpublisher sample it seems not to be part of. And when I have a look at the insert method of Google's API, the call is "POST https://www.googleapis.com/androidpublisher/v2/applications/packageName/edits" so this would explain, why I get a 404 on unknown package names.

Update of app works nicely. But before this is possible, one has to upload the apk manual once.

**Comment by bhurling** [comment]
That is true. The first upload of an APK needs to be done through the web
interface.

janni2 <notifications@github.com> schrieb am Mo., 29. Juni 2015 15:07:

**Comment by jaredsburrows** [comment]
@janni2 Thanks for confirming you are seeing the same exception.
