### ISSUE TITLE
Wear APK support?

### ISSUE THREAD

**Issue by markchristopherng** [Triple-T/gradle-play-publisher#750]
What are you having trouble with and how can we help you?
 
Currently, we use the plugin to deploy a single APK to the play store and everything works great. our APK has an embedded Wear APK inside it so we only need to deploy a single artifact however we would like to remove the embedded Wear APK and have it as a separate artifact.
Please see the doco - https://developer.android.com/training/wearables/apps/packaging

My question is does this plugin support uploading multiple Apks - an APK for the phone and an APK for the wear? I couldn't find any documentation and i'm not sure how to configure the plugin to support this.

**Comment by SUPERCILEX** [comment]
Yup, we support this: https://github.com/Triple-T/gradle-play-publisher#combining-artifacts-into-a-single-release. You'll have two Gradle modules that are published together. Let me know how it goes.
