### ISSUE TITLE
commitEditForComDotApp_name FAILED

### ISSUE THREAD

**Issue by kdavdevs** [Triple-T/gradle-play-publisher#752]
### Describe the bug
publishBundle fails , here are the logs 
```
Uploading App Bundle: 42% complete
Uploading App Bundle: 84% complete
App Bundle upload complete
Updating [completed] release (com.app_name:[162]) in track 'internal'
> Task :app:publishBundle
> Task :commitEditForComDotApp_name FAILED
Committing changes
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':commitEditForComDotApp_name'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.CommitEdit$Committer
38 actionable tasks: 38 executed
   > 500 Internal Server Error
     {
       "code" : 500,
       "message" : null
     }

```
### How To Reproduce
Run ./gradlew app:publishBundle 
#### Versions
```
\--- com.github.triplet.play:com.github.triplet.play.gradle.plugin:2.6.1
     \--- com.github.triplet.gradle:play-publisher:2.6.1
Gradle 6.1-milestone-2
+--- com.android.tools.build:gradle:4.0.0-alpha06

```

- Gradle Play Publisher: 2.6.1
- Gradle Wrapper: 6.1-milestone-2
- Android Gradle Plugin: 4.0.0-alpha06

#### Tasks executed

`./gradlew app:publishBundle`

### Expected behavior

App should be uploaded and released on internal track on playstore

### Additional context (if a crash, provide stack trace)

```
play {
    serviceAccountCredentials = file("service-key.json")
    enabled = true
    resolutionStrategy = "auto"
    defaultToAppBundles = true
    track = "internal"
}
```

**Comment by SUPERCILEX** [comment]
Unfortunately, there's nothing I can do about that since it's a 500 error with no message. If this happens every time you attempt to publish, I would try reverting to a more stable AGP or contacting support. I would also try waiting a day or two because Google might fix stuff in the meantime.

**Comment by kdavdevs** [comment]
hello @SUPERCILEX ,
thanks for the reply...
it happens every time i try to publish ...
can you please help me out by suggesting versions of Gradle Wrapper , GPP and AGP i can use for now for a more stable build...

and just my 2 cents here... i think this might me causing issues
```failure occurred while executing com.github.triplet.gradle.play.tasks.CommitEdit$Committer```
although i have looked at and followed documentation ... i don't know if i am doing something wrong , or have missed something ....

**Comment by SUPERCILEX** [comment]
Hmmm, I don't think the Gradle version would matter, but try an AGP v3.6. The issue is caused because our request to the AndroidPublisher API is failing with the 500 error, hence why there's nothing on GPP's end to do.

**Comment by kdavdevs** [comment]
hii @SUPERCILEX ,
i just tried with AGP v3.6.0-rc01 and it is showing the same error as before :( 
i also tried changing gradle versions to 6.0 and 6.0.1 but got same result...

**Comment by SUPERCILEX** [comment]
:man_shrugging: Try contacting support. There's nothing I can do on my end.

**Comment by kdavdevs** [comment]
okay man thanks  :) 
and yes by support you mean contacting google play support team right...?

**Comment by SUPERCILEX** [comment]
Yeah, in the play console if you go to the help button, there should be a form you can fill out. I would link them to this issue and say that this endpoint is failing: https://developers.google.com/android-publisher/api-ref/edits/commit. Hopefully they'll be able to tell you why.

**Comment by kdavdevs** [comment]
Hello @SUPERCILEX , thanks for helping ...
i just had an screen sharing session with the admin guy who manages the account, turns out the release management was not checked... so in future if anyone faces this issue check if release management is checked for the service account...

**Comment by SUPERCILEX** [comment]
Lol, that's dumb. Very sad that that's a 500. Glad you solved it!
