### ISSUE TITLE
Could not find method playAccountConfigs() for arguments [build_...@...] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

### ISSUE THREAD

**Issue by sayederfanarefin** [Triple-T/gradle-play-publisher#753]
After upgrading to 2.6.1, when running in Gitlab CI pipeline error occurs: Could not find method playAccountConfigs() for arguments [build_aryhhwoafbk9ukshkjbcpyoh$_run_closure1$_closure5@11eb06a3] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

* Where:
> Build file '/builds/sayederfanarefin/android-meisterkoch/app/build.gradle' line: 12

* What went wrong:
> A problem occurred evaluating project ':app'.
> Could not find method playAccountConfigs() for arguments [build_aryhhwoafbk9ukshkjbcpyoh$_run_closure1$_closure5@11eb06a3] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

The following is the relevant Gitlab CI console output:

 Unzipping /builds/sayederfanarefin/android-meisterkoch/.gradle/wrapper/dists/gradle-6.0.1-all/99d3u8wxs16ndehh90lbbir67/gradle-6.0.1-all.zip to /builds/sayederfanarefin/android-meisterkoch/.gradle/wrapper/dists/gradle-6.0.1-all/99d3u8wxs16ndehh90lbbir67
82 Set executable permissions for: /builds/sayederfanarefin/android-meisterkoch/.gradle/wrapper/dists/gradle-6.0.1-all/99d3u8wxs16ndehh90lbbir67/gradle-6.0.1/bin/gradle
83 Welcome to Gradle 6.0.1!
84 Here are the highlights of this release:
85  - Substantial improvements in dependency management, including
86    - Publishing Gradle Module Metadata in addition to pom.xml
87    - Advanced control of transitive versions
88    - Support for optional features and dependencies
89    - Rules to tweak published metadata
90  - Support for Java 13
91  - Faster incremental Java and Groovy compilation
92  - New Zinc compiler for Scala
93  - VS2019 support
94  - Support for Gradle Enterprise plugin 3.0
95 For more details see https://docs.gradle.org/6.0.1/release-notes.html
96 Starting a Gradle Daemon (subsequent builds will be faster)
97 FAILURE: Build completed with 2 failures.
98 1: Task failed with an exception.
99 -----------
100 * Where:
101 Build file '/builds/sayederfanarefin/android-meisterkoch/app/build.gradle' line: 12
102 * What went wrong:
103 A problem occurred evaluating project ':app'.
104 > Could not find method playAccountConfigs() for arguments [build_aryhhwoafbk9ukshkjbcpyoh$_run_closure1$_closure5@11eb06a3] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
105 * Try:
106 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
107 ==============================================================================
108 2: Task failed with an exception.
109 -----------
110 * What went wrong:
111 A problem occurred configuring project ':app'.
112 > compileSdkVersion is not specified.
113 * Try:
114 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
115 ==============================================================================
116 * Get more help at https://help.gradle.org
117 Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
118 Use '--warning-mode all' to show the individual deprecation warnings.
119 See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
120 BUILD FAILED in 1m 2s
122
Running after script...
00:01
123 $ cp app/version.properties updatedVersion.properties
126 ERROR: Job failed: exit code 1

**Comment by SUPERCILEX** [comment]
Please upgrade cleaning to v2.x: https://github.com/Triple-T/gradle-play-publisher/issues/496#issuecomment-454985389

**Comment by SUPERCILEX** [comment]
`playAccountConfigs` comes from v1.x of GPP.

**Comment by sayederfanarefin** [comment]
Thanks!
