### ISSUE TITLE
Documentation does not contain path for changelogs

### ISSUE THREAD

**Issue by l-jonas** [Triple-T/gradle-play-publisher#759]
<https://github.com/Triple-T/gradle-play-publisher#directory-structure> shows the folder structure. The changelogs/ release notes are not mentioned there.

As far as I know, the path is ``play/release-notes/[locale]/[track].txt`` where track is in most cases ``production``.

**Comment by nishithkhanna** [comment]
Its mentioned above 
https://github.com/Triple-T/gradle-play-publisher#uploading-release-notes

**Comment by l-jonas** [comment]
Correct, I did not see that
