### ISSUE TITLE
Return upload url for Internal App Sharing

### ISSUE THREAD

**Issue by Onwa1kenobi** [Triple-T/gradle-play-publisher#760]
### Problem description
Return URL after publishing to play store.

### Potential solutions/workarounds
-

### Additional context
When an Internal App Sharing build is pushed, I would like to get the publish URL so that I can send a slack message with the link attached so a simple click would direct testers to download.

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/680#issuecomment-537790676
