### ISSUE TITLE
Support deployment of Wear APKs to Playstore

### ISSUE THREAD

**Issue by markchristopherng** [Triple-T/gradle-play-publisher#762]
### Problem description

the plugin only supports uploading different flavours of the same APK. If the APK is in a different module such as app and wear the plugin does not support this.

app\build\outputs\apk\debug\app-debug.apk

wear\build\outputs\apk\debug\wear-debug.apk

### Potential solutions/workarounds
a potential work around is to copy the wear APK to the app directory using a gradle task

**Comment by SUPERCILEX** [comment]
GPP does: https://github.com/Triple-T/gradle-play-publisher#combining-artifacts-into-a-single-release. Also, see https://github.com/Triple-T/gradle-play-publisher/issues/217.
