### ISSUE TITLE
ClassCastException on version 2.4.0 and up

### ISSUE THREAD

**Issue by avalanchas** [Triple-T/gradle-play-publisher#773]
### Describe the bug
I know, version 2.4.0 of September 2019 is quite some time ago 😁 But I only now got around to upgrading this wonderful plugin, which leads me straight into a crash.

As soon as the gradle Sync starts, I get two error messages in the "messages" tab of Android Studio, one "Gradle Import Error" and one "Project Resolve Error". They are as follows:
```
<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>C:\Users\Patrick\StudioProjects\Android-App\build.gradle<ij_nav><i><b>root project 'Android-App': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':generateEditForDeDotRadioDotAndroid'.<eol>Caused by: java.lang.ClassCastException: com.github.triplet.gradle.play.tasks.GenerateEdit_Decorated cannot be cast to com.github.triplet.gradle.play.tasks.GenerateEdit</i>
<ij_msg_gr>Project resolve errors<ij_msg_gr><ij_nav>C:\Users\Patrick\StudioProjects\Android-App\build.gradle<ij_nav><i><b>root project 'Android-App': Unable to resolve additional project configuration.</b><eol>Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':commitEditForDeDotRadioDotAndroid'.<eol>Caused by: java.lang.ClassCastException: com.github.triplet.gradle.play.tasks.CommitEdit_Decorated cannot be cast to com.github.triplet.gradle.play.tasks.CommitEdit</i>
```
The `Unable to build Kotlin project configuration` makes me most suspicious, I assumere there's a version conflict here or something?

However, the sync claims that it was `CONFIGURE SUCCESSFUL in 8s` and so I tried just running the app, the result is:
```
com.github.triplet.gradle.play.tasks.CommitEdit_Decorated cannot be cast to com.github.triplet.gradle.play.tasks.CommitEdit
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```
None of the two options make it work in the next go-around, however

This is 100% reproducible even without cleaning gradle or restarting the processes in some way. As soon as I set the plugin to ANY version of 2.4.0 or higher, it crashes. As soon as I go down to 2.3.0, it works immediately.

### How To Reproduce
Set Publisher Plugin to version 2.4.0 and click on "Sync Now" in Android Studio -> observe the messages

#### Versions
Confirmed in:
- Gradle Play Publisher: 2.4.0, 2.4.1, 2.5.0, 2.6.2
- Gradle Wrapper: 6.2
- Android Gradle Plugin: 3.5.3 

More Info:
- ext.kotlin_version = '1.3.61'
- play config: 
```
play {
    serviceAccountCredentials = file("...")
    track = "internal"
    defaultToAppBundles = true
}
```

#### Tasks executed
None yet

### Expected behavior
Gradle Sync and build successful

**Comment by SUPERCILEX** [comment]
Huh, well I've never seen that before. Can you try `./gradlew --stop` and then `./gradlew help --no-build-cache --rerun-tasks --refresh-dependencies` to see if that clears things up?

**Comment by SUPERCILEX** [comment]
Also, are you trying to configure GPP tasks somewhere in your build file?

**Comment by avalanchas** [comment]
Hi, thanks for getting back to me so quickly! :) 
Ok I did that, and now I'm even more confused than before. I executed the commands on the terminal, then also executed a "gradlew assembleRelease", and they both worked without the problems mentioned above. 

However, clicking on the "Sync Project", and clicking on the green "Run 'app'" button in Android Studio still procuces the problems. 

This feels like a bad hickup in the gradle instances, as you probably also suspected when telling me to execute those "cleaning" commands. Are the terminal and the buttons using different gradle installations or something?

> Also, are you trying to configure GPP tasks somewhere in your build file?
Sorry, aside from the config I posted in the OP, I don't know what to answer here

**Comment by SUPERCILEX** [comment]
Hmmm, what version of Android Studio are you using? And maybe you have a system-wide Gradle installation you're accidentally using? https://www.jetbrains.com/help/idea/gradle-settings.html make sure the "Use Gradle from" setting specifies your local wrapper.

**Comment by avalanchas** [comment]
I'm on Android Studio 4.0 Canary 9. I checked and I don't have an external `GRADLE_HOME` variable set or something like that. The Gradle page in the settings points to the jre from Android Studio, as does my `JAVA_HOME`

I'm quite confused about which commands the "Play" Button in AS actually executes. The "Run anything" dialog is no help, since it fails with 
```
Command-line arguments cannot be parsed: --version 
```
when trying to find out more... Well, anyway, thanks for your gracious help. I'm about 90% sure that this is something about my installation now. It's still mysterious, but I can't expect you to solve that for the 10% chance that it's actually coming from GPP 😁

**Comment by SUPERCILEX** [comment]
Oh wait, can you try running a GPP task from the command line (like bootstrap)? I'll bet you it will fail because Studio sync actually creates all the tasks. If I'm right, can you share your build scripts with me?

**Comment by avalanchas** [comment]
Oh man this is one of those rabbit holes...
Ok I did that, I (reproducibly) see this error
```
Execution failed for task ':automotive:bootstrapFreeAtRelease'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ListingsDownloader
   > There was a failure while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageFetcher
         > There was a failure while executing work items
            > A failure occurred while executing com.github.triplet.gradle.play.tasks.Bootstrap$ImageDownloader
               > Unable to create C:\...\src\freeAt\play\listings\es-419\graphics\phone-screenshots
```
I highly doubt that has anything to do with our problem here, right...?

But what's more stupid is... the original problem is now solved, it works! For whatever reason, some kind of mixture of the `no-build-cache`, the resets, my deleting all the `.gradle` cache and wrapper folders on my system, cleaning, rebuilding and letting the gradle wrapper run from a clean slate must have worked and must have resolved some kind of conflict that GPP 2.4.0 was having, but 2.3.0 was not. 

Thanks again, what an effort by you!

**Comment by SUPERCILEX** [comment]
😂 wait so are you still having the original issue? Like, can you publish stuff now? (I think your computer is glitching in and out of different dimensions.)

**Comment by avalanchas** [comment]
No I don't. As I said some combination of the "cleanup" steps seem to have worked and yes, I can publish now, even with version 2.4.0 and above (currently using 2.6.2). 

So if anybody ever sees  this problem again: remove ALL the gradle caches on your computer, clean everything you can, execute the commands from above and just try again

**Comment by SUPERCILEX** [comment]
Alright, gonna close the issue then. 👍

**Comment by SUPERCILEX** [comment]
Unless there's something that still doesn't work?
