### ISSUE TITLE
Support inAppUpdatePriority

### ISSUE THREAD

**Issue by b95505017** [Triple-T/gradle-play-publisher#776]
https://issuetracker.google.com/issues/133299031#comment14

So that we could use it in 0.6.5 play core to detect in app update.

**Comment by SUPERCILEX** [comment]
Can someone test this out with a [snapshot build](https://github.com/Triple-T/gradle-play-publisher#snapshot-builds)? Use `./gradlew publishThing --update-priority 5`.

**Comment by ArcherEmiya05** [comment]
> Can someone test this out with a [snapshot build](https://github.com/Triple-T/gradle-play-publisher#snapshot-builds)? I don't have an app that uses update priority.
> 
> Use `./gradlew publish[Bundle/Apk] --update-priority 5`.

Hello, just a question. I am assuming that this priority parameter is the one that mentioned [here](https://developer.android.com/guide/playcore/in-app-updates/kotlin-java#update-priority). If yes then does it mean we can either set the priority via gradle command like the above example or with the plugin task like this?
```
play {
    serviceAccountCredentials.set(file(PLAY_API_KEY_FILE))
    artifactDir.set(file("build/outputs/bundle/release"))
    updatePriority.set(2)
}
```
