### ISSUE TITLE
 "APK signature is invalid or does not exist."

### ISSUE THREAD

**Issue by AdityaAnand1** [Triple-T/gradle-play-publisher#780]
Getting the following error upon publishing a release apk 

```
"APK signature is invalid or does not exist. Error from apksigner: ERROR: JAR_SIG_NO_SIGNATURES: No JAR signatures"
```

Is there a way to specify that the apk should be built with JAR signature (both v1 and v2)

This:
![image](https://user-images.githubusercontent.com/13274079/75407990-7094da00-593a-11ea-8510-a1cd39d0a4bb.png)

**Comment by SUPERCILEX** [comment]
Creating an APK from Android Studio doesn't do anything. See here to about configuring this in Gradle: https://developer.android.com/studio/publish/app-signing#secure-shared-keystore. Or take inspiration from the test app:
