### ISSUE TITLE
Can't bump rollout percentage - 2.5.0 version

### ISSUE THREAD

**Issue by VictorAlbertos** [Triple-T/gradle-play-publisher#789]
### Describe the bug
We are using 2.5.0 `Gradle Play Publisher` version, where this [bug](https://github.com/Triple-T/gradle-play-publisher/issues/697) is supposed [to be fixed ](https://github.com/Triple-T/gradle-play-publisher/pull/711). But that's not the case for us, because when we run the command to bump the rollout to 100%:

`./gradlew promoteGlobalNoInstrumentationStandardReleaseArtifact --user-fraction 1 --release-status completed --from-track production --track production
`

we get this error:

```
* What went wrong:
A problem was found with the configuration of task ':cookpad:promoteGlobalNoInstrumentationStandardReleaseArtifact'.
> File '/bitrise/src/cookpad/build/outputs/mapping/globalNoInstrumentationStandardRelease/mapping.txt' specified for property 'mappingFile$plugin' does not exist.
```

### Versions 
- Gradle Play Publisher: 2.5.0
- Gradle Wrapper: 5.6.4
- Android Gradle Plugin: 3.6.1

Any suggestions will be really appreciated. Thanks!

**Comment by SUPERCILEX** [comment]
Please use GPP v2.7.2, it's been fixed in there.
