### ISSUE TITLE
Task :generateEditFor<project> FAILED -> AbstractGoogleJsonClient

### ISSUE THREAD

**Issue by leofirespotter** [Triple-T/gradle-play-publisher#795]
### Describe the bug

We have just updated to Android Gradle Plugin **3.6.0,** this meant that the gradle version had to go up to **5.6.4**. And now I can't publish using gpp. We were previously on 2.3.0, and everything has worked for a long time until it started failing today with:
```
java.lang.NoSuchFieldError: BUNDLE
	at com.github.triplet.gradle.play.tasks.internal.AgpKt.findBundleFile(Agp.kt:26)
	at com.github.triplet.gradle.play.tasks.PublishBundle.getBundle(PublishBundle.kt:38)
```
Some searching led me to #695 . So I increased the version of gpp to 2.5.0 and tried again (I even converted to json from p12 for my service account), have also tried 2.4.2, but now I am getting the following (with both 2.5.0 and 2.4.2):
```
Execution failed for task ':generateEditForComDotUberconference'
A failure occurred while executing com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
Could not create an instance of type com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
```

This AbstractGoogleClientBuilder error I have encountered before, but we already aren't using the firebase-perf plugin, because of this issue before.

#### Tasks executed

I've been testing in Android Studio just by running _gradlew bootstrap_

But also in Travis with _publishReleaseBundle_ (with stacktrace)

[gpp_crash.txt](https://github.com/Triple-T/gradle-play-publisher/files/4362436/gpp_crash.txt)

**Comment by SUPERCILEX** [comment]
Man, I hate that issue so much. :sob: Obviously, if you can, please upgrade to Gradle 6.x and GPP 2.7.2. Otherwise, I think you might be able to fix it by adding these dependencies to your root project classpath:

```gradle
classpath("com.google.api-client:google-api-client:1.30.9")
classpath("com.google.guava:guava:28.2-jre") // Not sure if this is needed
```

**Comment by leofirespotter** [comment]
Sorry, should have closed, another developer on the team was able to get around this. It turns out that we were on a very old version of firebase-perf plugin, updating that and moving to Gradle 6.2 and GPP 2.7.2 seems to have fixed all the issues (and enabled us to re-enable the plugin)

**Comment by SUPERCILEX** [comment]
Awesome possum!

**Comment by theunreal** [comment]
> Man, I hate that issue so much. 😭 Obviously, if you can, please upgrade to Gradle 6.x and GPP 2.7.2. Otherwise, I think you might be able to fix it by adding these dependencies to your root project classpath:
> 
> ```groovy-gradle
> classpath("com.google.api-client:google-api-client:1.30.9")
> classpath("com.google.guava:guava:28.2-jre") // Not sure if this is needed
> ```

Sadly, i'm unable to update my GPP and gradle, and this solution didn't work (same error)

Any idea?

Thanks!

**Comment by SUPERCILEX** [comment]
@theunreal have you tried this? https://github.com/Triple-T/gradle-play-publisher/issues/344#issuecomment-452277735

**Comment by sberg413** [comment]
I'm getting this error. I'm on Gradle 6.2.2 with the latest of the plugin (2.8.0). I do have the perf-plugin as mentioned in the previous comment and also tried adding the additional classpath entries. No luck. Any ideas?

**Comment by SUPERCILEX** [comment]
You can check your `./gradlew buildEnvironment` and look for dependencies being changed by other plugins. Maybe you have another plugin messing with `google-api-client`?

**Comment by sberg413** [comment]
The jackson parser doesn't seem to like any format of the ANDROID_PUBLISHER_CREDENTIALS using the default value. The workaround I found was to assign it directly.

`serviceAccountCredentials = file(System.getenv("ANDROID_PUBLISHER_CREDENTIALS"))`

**Comment by SUPERCILEX** [comment]
You're supposed to put JSON in the envvar. That code is trying make it a file path. You don't need an envvar for that.

**Comment by sberg413** [comment]
Just re-read the the doc "To circumvent this issue, put the contents of your JSON file in the ANDROID_PUBLISHER_CREDENTIALS environment variable and don't specify the serviceAccountCredentials property." I was putting the _path_ to the Google API creds json file into the ANDROID_PUBLISHER_CREDENTIALS.  This is how the Firebase App Distribution gradle plugin does it - the envvar is the PATH to the creds file and not the actual content. Doing it how I am will allow me to set it the same way for both plugins on my CI server.
