### ISSUE TITLE
PlayPublisherPlugin is defined as internal

### ISSUE THREAD

**Issue by dzwicker** [Triple-T/gradle-play-publisher#796]
### Describe the bug

It is common practise to define company plugins to configure other plugins in the same way for the hole company. In these plugins you apply other plugins in a type save way e.g. `apply<PlayPublisherPlugin>()` this is not possible as `PlayPublisherPlugin` is defined `internal`.

**Comment by SUPERCILEX** [comment]
Why can't you use the plugin ID?
