### ISSUE TITLE
Is there a way to automatically bump version code?

### ISSUE THREAD

**Issue by nishithkhanna** [Triple-T/gradle-play-publisher#804]
Hi, I wanted to know if there is a way to bump version code by a specified number if there is a conflict?
For example My version code in app is 356 and when I do ./gradlew publishApk it throws an error that version code already exists and the build fails. Is there a way to like bump version code by 1 so as to make it 357 and hence build doesn't fail. The version conflict documentation wasn't clear enough so wanted to ask that. Thanks in advance.
My GPP version is 2.7.5
AGP 3.6.1
Gradle wrapper 6.3

**Comment by SUPERCILEX** [comment]
https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#handling-version-conflicts
