### ISSUE TITLE
Postpone Signing not ready evaluation

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#806]
Would be possible to move this check
`Signing not ready for Gradle Play Publisher. Be sure to specify a signingConfig for variant 'defaultCcaDebuggableReleaseNoProguard'.
`
to `project.afterEvaluate {}` to be sure that setup of this is really done?

I have own plugin which setup custom signing, but I also need to do it in afterEvaluate , because I have custom setup for it, something like 

```
apply myplugin
apply gradle-play-publisher

myConfig{
  signBy ....
}
```

So I cannot setup it directly when my plugin is applied. And I not found a way how to react on the moment when myConfig is finished, so I'm waiting to `afterEvaluate`, but gradle-play-publisher meantime write this error and it is confusing for users.

**Comment by SUPERCILEX** [comment]
Do you think that warning is even necessary? It's there because it used to be an error, and we've just kind of carried it along. I'd be fine completely removing it.

**Comment by tprochazka** [comment]
I agree, that it is maybe not necessary. I think that the android build plugin directly will warn that it is missing.

**Comment by SUPERCILEX** [comment]
Killed. 👍
