### ISSUE TITLE
"bootstrap" task appends LF (new line character) to each downloaded text file

### ISSUE THREAD

**Issue by yvolk** [Triple-T/gradle-play-publisher#807]
Following README.md I configured the plugin for my AndStatus app ( https://github.com/andstatus/andstatus/tree/master/app )

I executed "bootstrap" task, and see that each text file inside https://github.com/andstatus/andstatus/tree/master/app/src/main/play folder has "new line" ( 0xA ) character appended. 

This commit shows configuration (without credentials that are stored separately) used for the task execution and results of this execution:
https://github.com/andstatus/andstatus/commit/45e66c322e7e96800981f00dfdc9f32fba9fd490

GitHub doesn't show the ending "new line" char in UI but downloading repo zip we still see this unwanted character that potentially may cause problems...

Not a big deal to edit 100 files manually :-) 
but it looks like this bug (even if it is actually Google's API bug...) could be fixed in your great plugin. So far I used the bootstrap only, but result already is worth the effort :-) Thank you for the plugin!

**Comment by SUPERCILEX** [comment]
That's [intentional](https://github.com/Triple-T/gradle-play-publisher/blob/bfbd435eaabe5068eb4f676651d3d15072d5fc14/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt#L222): source files should [always have a new line at the end](https://thoughtbot.com/blog/no-newline-at-end-of-file). Any reason not to have it?

**Comment by yvolk** [comment]
I'm afraid that:

1. My app "title" with a new line appended will look ugly. And "title" is not a "file" or "source" - it's a String, for which every character matters. Who / what will recognize this unneeded char and remove it before putting into Google Play's metadata (where it won't have any new line at the end...)?

2. This additional character will be counted and may cause problem where maximum number of chars is limited (e.g. 80 chars for description)

3. All text translations that I get from Crowdin don't have new line at the end. And this works good for years...

**Comment by yvolk** [comment]
@SUPERCILEX So this is conceptual mistake, not a programming bug.
I think that files with text strings should be treated like binary files, and copied without any modifications.

**Comment by SUPERCILEX** [comment]
You don't have to worry about it, we automatically strip any surrounding whitespace for you. If you notice that we don't, that would be a bug.

The current implementation is working as intended and follows Git conventions.

**Comment by yvolk** [comment]
Ok, thanks. Will try this.
