### ISSUE TITLE
Duplicate entry: META-INF/services/[...]PlayPublisher$Factory

### ISSUE THREAD

**Issue by chrisbanes** [Triple-T/gradle-play-publisher#813]
### Describe the bug
Plugin does not work with Gradle 6.5-milestone-1

#### Versions
- Gradle Play Publisher: 2.7.5
- Gradle Wrapper: 6.5-milestone-1
- Android Gradle Plugin: 4.1.0-alpha10

#### Tasks executed
`./gradlew assembleDebug`

### Additional context (if a crash, provide stack trace)

```
➜  tivi git:(cb/agp-4.1.0-alpha10) ✗ ./gradlew assembleDebug
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to create /Users/chrisbanes
/.gradle/caches/jars-8/94696ba2953bc23c4a2d926361936632/play-publisher-2.7.5.jar.
Duplicate entry: META-INF/services/com.github.triplet.gradle.androidpublisher.PlayPublisher$Factory
```

[Full stacktrace here](https://github.com/Triple-T/gradle-play-publisher/files/4688772/stacktrace.txt)

**Comment by SUPERCILEX** [comment]
Looks like the fat jar stuff finally caught up to us. We need to be properly publishing our submodules as separate dependencies: https://weibeld.net/java/publish-to-maven-central.html.

**Comment by chrisbanes** [comment]
Alternatively use can use https://github.com/vanniktech/gradle-maven-publish-plugin which automates a lot of the setup.

**Comment by SUPERCILEX** [comment]
Thanks for the tip! 👍

**Comment by SUPERCILEX** [comment]
Do you get to skip sonatype setup?

**Comment by chrisbanes** [comment]
Not sure what you mean? I assume that you already have Sonatype setup?

You still need to manually close and release via the web UI (although I think there's a command to do that with the plug-in).

**Comment by SUPERCILEX** [comment]
Ah, yeah that's the part I'm not looking forward to. Right now I'm only using Sonatype for snapshots, so I'll have to go learn how all the release artifact stuff works. Still, the plugin looks good. 💯

**Comment by gildor** [comment]
I don't think that gradle-maven-publish-plugin is needed, it was useful for Android before support of maven-publish plugin natively. It's quite straight forward for JVM library (and for Android too), configure.
Set artifact group, version:
https://docs.gradle.org/current/userguide/publishing_maven.html#sec:identity_values_in_the_generated_pom

And configure repository (but add login and password to be able to upload):
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories

**Comment by aipok** [comment]
I got exact same issue in my project. Do you have any ETA of fixing the issue? Or any way to work around it?
