### ISSUE TITLE
no track alpha issue

### ISSUE THREAD

**Issue by shbadawy** [Triple-T/gradle-play-publisher#816]
![222](https://user-images.githubusercontent.com/22125302/83527041-f1daaa80-a4ef-11ea-8ef1-880eab36cd00.png)
### Describe the bug

While trying to publish the APK file to the playstore using a BitBucket pipeline to track "alpha" , I get this error inspite of the fact that the track exists and I can manually publish to this track using Android Studio   

#### Versions

- Gradle Play Publisher: 2.8.0-SNAPSHOT
- Gradle Wrapper: 6.4.1
- Android Gradle Plugin: 4.0.0

[build.gradle.txt](https://github.com/Triple-T/gradle-play-publisher/files/4717447/build.gradle.txt)
[build.gradle2.txt](https://github.com/Triple-T/gradle-play-publisher/files/4717453/build.gradle2.txt)

#### Tasks executed

What tasks did you run?  `publishApk`.

### Expected behavior

Publish the APK file to the play store successfully.

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

[log.txt](https://github.com/Triple-T/gradle-play-publisher/files/4725012/log.txt)

**Comment by mwaked** [comment]
Same issue happened with me, can you please help me?

**Comment by SUPERCILEX** [comment]
Please provide the stack trace: `./gradlew publishApk --stacktrace`

**Comment by shbadawy** [comment]
@SUPERCILEX Thank you for your reply. I have uploaded a txt file with the stack trace

**Comment by SUPERCILEX** [comment]
@shbadawy oops, looks like you forgot to bump the APK version code. Can you set it to 101 and make sure the error you get is the same as in the screenshot?

**Comment by shbadawy** [comment]
@SUPERCILEX Oops, My bad. I have just updated the file

**Comment by SUPERCILEX** [comment]
@shbadawy You're using snapshot builds, right? Can you run `./gradlew --refresh-dependencies` and see if the fix works?

**Comment by shbadawy** [comment]
@SUPERCILEX I tried it and it worked. Thank you for your time. Could you provide a brief explanation of why the `--refresh-dependencies ` switch solved the problem ?

**Comment by SUPERCILEX** [comment]
Glad it works! For people not on snapshot builds, I'm hoping to make a release sometime this weekend.

@shbadawy As for [`--refresh-dependencies`](https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:refreshing-dependencies), it just tells Gradle to ignore the dependency cache. (This is necessary for snapshot builds because I'm overwriting the same `2.8.0-SNAPSHOT` release again and again.)
