### ISSUE TITLE
Could not set unknown property 'isEnabled' for PlayPublisherExtension

### ISSUE THREAD

**Issue by tkhduracell** [Triple-T/gradle-play-publisher#817]
Documentation states that `isEnabled` is to be used to disable/enable for variants/flavors, but does not accept this value.  
https://github.com/Triple-T/gradle-play-publisher#disabling-publishing

I get this error: 
`Could not set unknown property 'isEnabled' for PlayPublisherExtension`

This is the correct attributes. 
```
    playConfigs {
        register("prodRelease") {
            enabled = true
        }
    }
```
and 
```
play {
    enabled = false // Disable by default
    ...
 }
```

Version `id 'com.github.triplet.play' version '2.7.5'`

**Comment by SUPERCILEX** [comment]
Can you do a find f for `isEnabled`? Seems like you have an erroneous one.

**Comment by SUPERCILEX** [comment]
Oh, and you're using the groovy script, right?

**Comment by tkhduracell** [comment]
I use the default gradle build for Android.

**Comment by SUPERCILEX** [comment]
Ok. Do you have `isEnabled` anywhere in your file? The error message means you do as I understand it. Also, try this:
```gradle
playConfigs {
  prodRelease {
    enabled = true
  }
}
```

**Comment by Shusshu** [comment]
after using the snapshot 3.0.0 I have this problem....

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/827#issuecomment-651392330
