### ISSUE TITLE
Upgrade to new auth lib

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#819]
https://github.com/googleapis/google-auth-library-java

**Comment by pavlospt** [comment]
https://github.com/Triple-T/gradle-play-publisher/pull/736

**Comment by SUPERCILEX** [comment]
Yup! I can ping you when v3.0 code starts landing and we're ready for the switch.

**Comment by SUPERCILEX** [comment]
@pavlospt I thought it'd be easier to just write a new commit rather than resolve the merge conflicts on your PR, so I co-authored you on the commit: 8c3cf02b3a7b98eecd1d07c94a269d8f9d561c9a

**Comment by pavlospt** [comment]
> @pavlospt I thought it'd be easier to just write a new commit rather than resolve the merge conflicts on your PR, so I co-authored you on the commit: 8c3cf02b3a7b98eecd1d07c94a269d8f9d561c9a

Sure that sounds reasonable!
