### ISSUE TITLE
Release urls are wrong

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#820]
It's not important, but the urls in release are wrong https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.8.0

Please click on _docs_ or the other one.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3314607/84104706-93915880-aa16-11ea-8aab-54d287bda97d.png">

**Comment by SUPERCILEX** [comment]
Oh wait, are you not on Chrome? I'm using the new [URL fragments](https://github.com/WICG/scroll-to-text-fragment#tldr), but I guess those wouldn't work unless implemented. BTW, here's what it looks like for me:
![image](https://user-images.githubusercontent.com/9490724/84105320-cb73ae00-a9cc-11ea-8d8b-bef92121aeba.png)

And the AP article that brought this to my attention: https://www.androidpolice.com/2020/06/03/google-search-aims-to-make-ctrlf-a-thing-of-the-past-will-start-highlighting-relevant-text-on-actual-web-pages/

**Comment by hannesa2** [comment]
Indeed it's related to Firefox

**Comment by SUPERCILEX** [comment]
Well this makes me sad, but I removed the text fragments.
