### ISSUE TITLE
Disable publishing for specific variant doesn't work

### ISSUE THREAD

**Issue by tfcporciuncula** [Triple-T/gradle-play-publisher#822]
### Describe the bug

Based on the docs [here](https://github.com/Triple-T/gradle-play-publisher/#disabling-publishing), I wrote this to disable GPP by default and enable it only for release builds:

```groovy
android {
  ...

  playConfigs {
    release {
      enabled = true
    }
  }
}

play {
  enabled = false
}
```

But whenever I try to sync with Gradle, I get:

>No credentials specified. Please read our docs for more details:
>https://github.com/Triple-T/gradle-play-publisher#authenticating-gradle-play-publisher

I don't want to specify credentials because I'm planning to set the `ANDROID_PUBLISHER_CREDENTIALS` environment variable on my CI, as it's described in the docs [here](https://github.com/Triple-T/gradle-play-publisher#authenticating-gradle-play-publisher).

### How To Reproduce

- Disable GPP for release builds as it's described in the docs
- Do not specify credentials
- Click on `Sync Project with Gradle Files`
- Observe the sync fail because of the lack of credentials

#### Versions

- Gradle Play Publisher: 2.8.0
- Gradle Wrapper: 6.5
- Android Gradle Plugin: 4.0.0

#### Tasks executed

Just the Gradle sync.

### Expected behavior

No credentials required for the Gradle sync or for any `release` task.

**Comment by SUPERCILEX** [comment]
Yup, that's totally normal. You didn't configure a service account and we have no way of knowing that it will be configured by the time you try to run a Gradle task. The solution is a piece of cake though:

```kotlin
enabled = System.getenv("ANDROID_PUBLISHER_CREDENTIALS") != null
```

**Comment by SUPERCILEX** [comment]
And if you want to be compatible with the new configuration cache, do this:
```kotlin
enabled = providers.environmentVariable("ANDROID_PUBLISHER_CREDENTIALS").forUseAtConfigurationTime().present
```

**Comment by tfcporciuncula** [comment]
That makes sense, thanks! Just a quick follow up question on your last comment if you don't mind: what is this new configuration cache? Tried to find something about that on the readme here and on a few recent Gradle release notes but I'm still clueless to be honest.

**Comment by SUPERCILEX** [comment]
Yeah, it doesn't seem to be showing up in Google yet. Here are the docs: https://docs.gradle.org/nightly/userguide/configuration_cache.html

**Comment by tfcporciuncula** [comment]
Thank you!
