### ISSUE TITLE
How does promote track work with BuildType configs?

### ISSUE THREAD

**Issue by amngupta** [Triple-T/gradle-play-publisher#825]
My app is using different configs / API urls for different tracks. 

API Service is a Build Config variable that I set. 

| Track | Build Type |  API Service |
|-------|------------|---------------|
| Internal | Internal | UAT |
| Beta | Staging | Pre-Prod |
| Production |  Release | Prod |

If I promote beta to production, would the plugin promote the Beta APK with the Staging Build Type or would the production app use the release build type and Prod API service.

**Comment by SUPERCILEX** [comment]
I have no idea what that means. What APIs are you referring to?

**Comment by amngupta** [comment]
@SUPERCILEX by API I meant my applications backend services. I am running three different versions of backend services UAT / PREPROD & PROD. 

I need to be able to connect to a different backend for each Track... Would promotion of app from Track Beta to Track Release update the BuildConfig from Staging to Release?

**Comment by SUPERCILEX** [comment]
No. Just imagine you're pushing the button in the play console to promote a release, that's exactly what we do. If you need to rebuild your APK, you'll have to reupload stuff and then you can put it in the right track directly.
