### ISSUE TITLE
Unable to run task of uploadDebugPrivateBundle to upload an "internal sharing app" of "debug" buildType

### ISSUE THREAD

**Issue by mochadwi** [Triple-T/gradle-play-publisher#829]
### Problem description
If I set `isDebuggable = true` in `app/build.gradle`. The task for `:app:uploadDebugPrivateBundle` is throw this error:

```
Task 'uploadDebugPrivateBundle' not found in root project 'app-android.
```

Otherwise, `isDebuggable = false`, the task for  `:app:uploadDebugPrivateBundle` is exist

### Potential solutions/workarounds
Allow `isDebuggable = true` to generate task for any buildType e.g: `debug` & `release`, or custom build type in this for this gradle task `uploadPrivateBundle` or `uploadPrivateApk` 

### Additional context
I cannot find any issue related for internal sharing app (not internal tester). Please refer me if there's one already.

My current approach to allow the AAB/APK debuggable.

1. Runs: `./gradlew bundleDebug` with `isDebuggable = true`
1. Modify `isDebuggable = false`
1. Runs: `./gradlew uploadDebugPrivateBundle`

Does it possible to skip step 1 & 2, with `isDebuggable = true`.

"Internal sharing app" is allowing developer to install debug mode and to test Playstore environment, thus this feature (or bug) is I think necessary

Library Versions + AGP Versions:
```
+--- com.github.triplet.play:com.github.triplet.play.gradle.plugin:2.6.2
|    \--- com.github.triplet.gradle:play-publisher:2.6.2
Gradle 6.1.1
+--- com.android.tools.build:gradle:4.0.0
|    \--- com.android.tools.build:gradle:1.1.0 -> 4.0.0 (*)
```

**Comment by SUPERCILEX** [comment]
What version of the plugin?

**Comment by mochadwi** [comment]
> What version of the plugin?

My apologize, I've updated the description for plugin & AGP version @SUPERCILEX

**Comment by SUPERCILEX** [comment]
Update. This was adding in 2.7.0: https://github.com/Triple-T/gradle-play-publisher/releases/tag/2.7.0
