### ISSUE TITLE
Support `productFlavors` for different descriptions

### ISSUE THREAD

**Issue by jaredsburrows** [Triple-T/gradle-play-publisher#83]
Support `android.productFlavors` extension provided by the `Android` plugin. 

For instance, if you have a free and paid version of the application where the descriptions vary.

**Currently:**
<pre>
|-- play
|   |-- contactEmail
|   |-- contactPhone
|   |-- contactWebsite
|   `-- en-US
|       |-- listing
|       |   |-- fulldescription
|       |   |-- icon
|       |   |   `-- web_hi_res_512_square.png
|       |   |-- phoneScreenshots
|       |   |-- sevenInchScreenshots
|       |   |-- shortdescription
|       |   |-- tenInchScreenshots
|       |   |   |-- screen1437336847.png
|       |   |   `-- screen1437336856.png
|       |   `-- title
|       |-- whatsnew
|       `-- whatsnew-beta
</pre>

**It would be nice to have:**
<pre>
|-- play
|   |-- free flavor
|       |   |--contactEmail
|       |   |--contactPhone
|   |-- paid flavor
|       |   |--contactEmail
|       |   |--contactPhone
</pre>

etc...

**Comment by bhurling** [comment]
This is already supported and explained in a side note in the readme. Suppose you have a `free` and a `paid` flavor. Then you already have different source sets for your flavors. The plugin just merges several play folders into one like so:

```
- [src]
  |
  + - [main]
  |   |
  |   + - [play]
  |       |
  |       + // texts and images used in all flavors
  |
  + - [free]
  |   |
  |   + - [play]
  |       |
  |       + // texts and images used in your free flavor
  |
  + - [paid]
      |
      + - [play]
          |
          + // texts and images used in your paid flavor
```

This way you can even support different sets of languages in your flavors.

**Comment by jaredsburrows** [comment]
So if both `free` and `paid` share `source code` and `resources` from `main`, then what happens to the text? This setup only generates 2 `APK` files.

**Comment by bhurling** [comment]
Files in the flavour directories override files in the main source set just like your asp resources would

**Comment by jaredsburrows** [comment]
Good, thank you!
