### ISSUE TITLE
How to test / dry-run a publishApk task?|

### ISSUE THREAD

**Issue by erikhuizinga** [Triple-T/gradle-play-publisher#831]
I'm trying to test run / dry run a publishApk task.

What I want is that GPP runs all steps, except the actual upload to Google Play. Ideally, this dry run would succeed if all is well (everything required builds and is well-configured), but fails on any (build/config) issue. This is useful, for example to run a dry-run task on CI, to verify that the actual publishing task would succeed.

I found the `--no-commit` option for the publishApk tasks. However, I'm not sure if this is the exact option that I'm looking for.

How can I test/dry run a publishApk task?

**Comment by SUPERCILEX** [comment]
Yup, no commit is the one. It'll upload everything, but it won't actually show up in the play console or do anything.

**Comment by mochadwi** [comment]
what equivalent CLI argument in v3? @SUPERCILEX
