### ISSUE TITLE
userFraction not work

### ISSUE THREAD

**Issue by Volodar** [Triple-T/gradle-play-publisher#832]
### Describe the bug

I want to use **userFraction** feature to publish apk in production status on 50%
My config:
```
play {
    serviceAccountCredentials = file("...")
    track = "production"
    userFraction = 0.5
}
```
command **gradle publishApk** uploads apk to release status on 100%

#### Versions

classpath 'com.github.triplet.gradle:play-publisher:2.8.0-SNAPSHOT'

- Gradle Play Publisher: Gradle 6.5.1
- Gradle Wrapper: not used
- Android Gradle Plugin: 'com.android.tools.build:gradle:3.6.0'

#### Tasks executed

publishApk

**Comment by SUPERCILEX** [comment]
Yup, that's expected. You need to also specify that the release is in progress: `releaseStatus = "inProgress"`.
