### ISSUE TITLE
API 'ApkVariantOutput.getVersionNameOverride()' is obsolete and has been replaced with 'VariantOutput.versionName()'.

### ISSUE THREAD

**Issue by QUK-Pesiloman** [Triple-T/gradle-play-publisher#834]
What are you having trouble with and how can we help you?
> Task **:app:processReleaseMetadata** ### FAILED
WARNING: API 'ApkVariantOutput.getVersionNameOverride()' is obsolete and has been replaced with 'VariantOutput.versionName()'.
It will be removed in version 5.0 of the Android Gradle plugin.
Gradle Properties must be used to change Variant information.
For more information, see https://d.android.com/r/tools/use-properties.
To determine what is calling ApkVariantOutput.getVersionNameOverride(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by SUPERCILEX** [comment]
This has been fixed in the upcoming 3.0 release.
