### ISSUE TITLE
Google play store publishing error for Pro app

### ISSUE THREAD

**Issue by AndreSand** [Triple-T/gradle-play-publisher#837]
### Describe the bug

We have a Free and Pro app version. I didn't made any changes, and we started to see error when we publish the Pro version.

error:

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "The current user has insufficient permissions to perform the requested operation.",
    "reason" : "forbidden"
  } ],
  "message" : "The current user has insufficient permissions to perform the requested operation.",
  "status" : "PERMISSION_DENIED"
}

#### Versions
- Gradle Play Publisher:  id 'com.github.triplet.play' version '2.5.0'
- Gradle Wrapper: gradle-5.6.4
- Android Gradle Plugin:  classpath 'com.android.tools.build:gradle:3.6.3'

Thanks.

**Comment by SUPERCILEX** [comment]
Unfortunately this isn't related to the plugin. The best I can offer is to contact Play Support.
