### ISSUE TITLE
Remove your private key from the repository

### ISSUE THREAD

**Issue by Farix1337** [Triple-T/gradle-play-publisher#838]
### Problem description
I know it's your testapp but still you published your private key at https://github.com/Triple-T/gradle-play-publisher/blob/master/testapp/google-play-auto-publisher.json please remove that file and override your git history, so no one can steal your key and upload malicious apps in your name. 

### Potential solutions/workarounds

- remove https://github.com/Triple-T/gradle-play-publisher/blob/master/testapp/google-play-auto-publisher.json from git
- override your git history to remove the file from previous commits
- use your own recommend way of environment variables

**Comment by SUPERCILEX** [comment]
Thanks, but that's intentional. It only has access to test apps and unstable release channels. If people are developing the plugin, they're supposed to use the key to validate their changes.
