### ISSUE TITLE
Add option to keep going if there's an error in one of the flavours.

### ISSUE THREAD

**Issue by harshmandan** [Triple-T/gradle-play-publisher#841]
### Problem description
I have a lot of flavours to be published and there's a scenario where one of the flavour could fail to build. But I don't want that to prevent the publishing of the remaining flavours.

### Potential solutions/workarounds
A flag could be added to the command `gradlew publishBundle` like so:  `gradlew publishBundle --ignore-fail`.

### Additional context
Nope.

**Comment by SUPERCILEX** [comment]
This is built into Gradle: https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continue_build_on_failure. Any reason that doesn't work?

**Comment by harshmandan** [comment]
@SUPERCILEX I'll test that now. I have another problem, my VM on the cloud has very less space. And when I'm building a large number of flavours it fills up very fast. Is there any way where I can add a `graldlew clean` command after every, say 30 publishflavours?

**Comment by SUPERCILEX** [comment]
I don't think Gradle supports that, but storage is cheap, just buy some more. :)
