### ISSUE TITLE
Defining Application type, Category, Content rating, PRIVACY POLICY, PRICING & DISTRIBUTION

### ISSUE THREAD

**Issue by aqibmumtaz** [Triple-T/gradle-play-publisher#85]
How can I define missing attributes like Application type, Category, Content rating, PRIVACY POLICY, PRICING & DISTRIBUTION?

Is it even possible using gradle-play-publisher?

http://stackoverflow.com/questions/31675039/defining-missing-attributes-using-gradle-play-publisher

**Comment by bhurling** [comment]
Those attributes are not accessible through the Google Play Developer API. So they can't be changed from third party tools
