### ISSUE TITLE
What's the migration guide for 3.0.0-SNAPSHOT to post processing?

### ISSUE THREAD

**Issue by b95505017** [Triple-T/gradle-play-publisher#851]
https://github.com/Triple-T/gradle-play-publisher#post-processing-outputs-sanitized-by-auto-resolution

I want to do the same effect in 3.0.0-SNAPSHOT but `outputProcessor` is gone in 3.0.0-SNAPSHOT, I only saw [onVariantProperties](https://github.com/Triple-T/gradle-play-publisher/blob/354812b6d789abee4d2c22c598424f73962b54c5/play/plugin/src/test/kotlin/com/github/triplet/gradle/play/tasks/ProcessArtifactVersionCodesIntegrationTest.kt#L41-L48) but need more cleared guide.

**Comment by SUPERCILEX** [comment]
Do you have anything specific in mind? Here's a clearer version of that test:

```kotlin
android {
  onVariantProperties {
    for (output in outputs) {
      val processedVersionCode = output.versionCode.map { playVersionCode ->
        // Version names will look like `semantic.release.name.123`
        "semantic.release.name.$playVersionCode"
      }
      output.versionName.set(processedVersionCode)
    }
  }
}
```

**Comment by SUPERCILEX** [comment]
Closing in favor of #853

**Comment by b95505017** [comment]
@SUPERCILEX I found that it hard to replace some part of current versionName config (based on other config such as `versionNameSuffix`). Use `output.versionName.zip(output.versionCode)` seems not working.

Previously I could use `versionNameOverride.replace(...)`. How do I achieve this?

**Comment by SUPERCILEX** [comment]
Does using `output.versionName.get().replace(...)` not work?

**Comment by b95505017** [comment]
No, I tried `get()` or `map { }` both get `StackOverflowError`

**Comment by SUPERCILEX** [comment]
Ah, you're doing it inside the `versionCode.map`... You have to get the value before-hand or it will evaluate to `versionName.set` which is where you're trying to use, so then it goes back and yada yada yay recursion. :) Basically just move do this and it should work hopefully:

```
  for (output in outputs) {
      val initialVersionName = output.versionName.get()
      val processedVersionCode = output.versionCode.map { playVersionCode ->
        initialVersionName...
      }
      output.versionName.set(processedVersionCode)
    }
```

**Comment by SUPERCILEX** [comment]
Note that that's also wrong long-term, but I haven't figured out the solution yet: #858
