### ISSUE TITLE
Uploading new app bundle

### ISSUE THREAD

**Issue by uKL** [Triple-T/gradle-play-publisher#855]
### Describe the bug

My app is not published for the production yet. I do have published artifacts in internal tests and alpha channel. 

### How To Reproduce

./gradlew :app:bundleProduction uploadProductionReleasePrivateBundle 

```
   > 400 Bad Request
     PUT https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/internalappsharing/__app package is here__/artifacts/bundle?uploadType=resumable&upload_id=__ upload ID is here __
     {
       "code" : 400,
       "errors" : [ {
         "domain" : "global",
         "message" : "UploadException: NOT_PUBLISHED [[]] (__app package is here__)",
         "reason" : "failedPrecondition"
       } ],
       "message" : "UploadException: NOT_PUBLISHED [[]] (__app package is here__)",
       "status" : "FAILED_PRECONDITION"
     }

```
#### Versions
```
bash-3.2$ ./gradlew buildEnvironment app:buildEnvironment | grep 'com.github.triplet'
+--- com.github.triplet.gradle:play-publisher:2.8.0
|    +--- com.github.triplet.gradle:android-publisher:2.8.0
|    |    +--- com.github.triplet.gradle:common-utils:2.8.0
|    +--- com.github.triplet.gradle:common-utils:2.8.0
|    +--- com.github.triplet.gradle:common-validation:2.8.0
```
```
Gradle 6.2
```

```
bash-3.2$ ./gradlew buildEnvironment | grep 'com.android.tools.build:gradle:'
+--- com.android.tools.build:gradle:4.0.1
```

- Gradle Play Publisher: 2.8.0 and 3.0.0-SNAPSHOT
- Gradle Wrapper: 6.2 and 6.6-rc-6
- Android Gradle Plugin: 4.0.1 and newest alpha

Any ideas?

**Comment by SUPERCILEX** [comment]
Unfortunately, if the API says no, there's really not much we can do about it. I would check to make sure the package ID is correct and ditto with your service account. If you think everything looks good, the best I can offer is that you contact Play Support and hope they can fix it.

**Comment by alexandru-calinoiu** [comment]
Did you manage to fix this issue, I am running on the same issue when trying to publish to my internal track via `uploadReleasePrivateApk`

**Comment by camtthompson** [comment]
To future readers: 
The NOT_PUBLISHED response is referencing the fact the app you are trying to upload in not published to the App Store. From my understanding and contrary to the phrasing given by the Google play store if you "Unpublish" an app you are deleting it and supporting current installs. 

Google Play Store Console > 'Your App' > Setup > Advanced Settings > App Availability > Ensure your app is 'Published'

**Comment by PaulRudin** [comment]
I'm seeing this too. It Seems a bit odd that you can upload via the play store console web, but you can't upload programmatically.
I don't really know exactly what they mean for the app to be "published". I'm at the point where I'm making an app, so have only set up the "internal" track. For the time being it's no big deal to upload manually, but it doesn't partially defeat the purpose of having an api if there are things you can do through the web interface that are impossible via the api.

**Comment by srinath-ramanujan** [comment]
> Unfortunately, if the API says no, there's really not much we can do about it. I would check to make sure the package ID is correct and ditto with your service account. If you think everything looks good, the best I can offer is that you contact Play Support and hope they can fix it.

I'm really appreciative of the project in helping folks publish through command line without having to make use of APIs and do all the plumbing themselves. But it is a little counter-intuitive to close an issue when the cause of the issue is not known. I don't think "not understand" should be the same as "not supported". A useful response might be to explain what is the expected outcome and why such expected outcome is either Desirable, or Acceptable.

**Comment by mboudreau** [comment]
Has anyone found a solution for this or is it just that it needs to be published before I can use my CI to release it internally?

**Comment by aliasgarlabs** [comment]
What we ended up doing is release an APK in Closed Testing (Alpha) which triggers a review by Google. This review took about 3 days and after it was reviewed, we were able to upload APK and bundles using the API. 

Since the app is in closed testing, it cannot be accessible without an invite anyway.
