### ISSUE TITLE
minimum Android Gradle Plugin version is at least 4.1.0-beta01 and yours is 4.0.1.

### ISSUE THREAD

**Issue by EinSoldiatGott** [Triple-T/gradle-play-publisher#861]
Hi, I'm having this error.

Mi Gradle is updated to the newest version 6.6.1
Mi android studio is 4.

`Gradle 6.6.1

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_231 (Oracle Corporation 25.231-b11)
OS:           Windows 10 10.0 amd64`

When I run Gradle sync with this plugin at the top of my build.gradle:app
```
plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '3.0.0'
}
```

I get this error
```
Gradle Play Publisher's minimum Android Gradle Plugin version is at least
4.1.0-beta01 and yours is 4.0.1. Make sure you've applied
the AGP alongside this plugin. Find the latest AGP version and upgrade
instructions at https://developer.android.com/studio/releases/gradle-plugin.
For GPP installation docs, see here:
https://github.com/Triple-T/gradle-play-publisher#installation
Open File

```

**Comment by EinSoldiatGott** [comment]
Ok, sorry

Gradle and Android Gradle are different, with the new version of the android studio I found where to change it
![image](https://user-images.githubusercontent.com/11496215/93000255-cd2da000-f4ec-11ea-89c4-93cf917c59f9.png)

**Comment by prawen** [comment]
Hi. What is the stable version of Android Gradle Plugin ? Using alpha or 4.2.0+ is not recommended.

**Comment by SUPERCILEX** [comment]
https://maven.google.com/web/m_index.html?q=build#com.android.tools.build:gradle:4.1.0-rc03
