### ISSUE TITLE
Upload multiple APKs and mapping files

### ISSUE THREAD

**Issue by iNdieboyjeff** [Triple-T/gradle-play-publisher#863]
### Problem description
As part of the workflow we need to have, we sometimes need to upload multiple APKs (in this instance 1 for mobile version, 1 for TV version) as a single release to Google Play.  We can upload the APKs OK using the artifact-dir option to a folder containing all the APKs we want to upload.  However, how can we upload the mapping files?  From what I can see the plugin will search for a 'mapping.txt' file in the directory - but we cannot have two files with this name in the directory. 

### Potential solutions/workarounds
Possibly allow renamed mapping files in the artifact-dir.  Something like _apkfile-name.mapping.txt_ and upload these as mapping files to the relevant APK file.

_For example:_

- _apk-for-mobile-v.x.x.x.apk_
- _apk-for-mobile-v.x.x.x.mapping.txt_
- _apk-for-tv-v.x.x.x.apk_
- _apk-for-tv-v.x.x.x.mapping.txt_

Would this be possible?

**Comment by SUPERCILEX** [comment]
Is there a reason you aren't using this: https://github.com/Triple-T/gradle-play-publisher#combining-artifacts-into-a-single-release

Either way, this seems like a reasonable feature request.
