### ISSUE TITLE
Stable version (3.0.0) of GPP should probably not depend on beta version of the Android Gradle Plugin

### ISSUE THREAD

**Issue by ivanbartsov** [Triple-T/gradle-play-publisher#865]
### Problem description
In order to use the latest stable version `3.0.0` (which would be the go-to version for most new people)  of GPP, one has to also use Android Gradle Plugin `4.1.0-beta1` -- which in turn forces one to switch Android Studio update channel to Beta

### Potential solutions/workarounds
versions (3.0.0 incl.) should probably be in beta for as long as they depend on a beta AGP

**Comment by SUPERCILEX** [comment]
rc03 is available, so this problem will go away soon. See #864 and https://github.com/Triple-T/gradle-play-publisher/issues/839#issuecomment-669159610 for a bit more context.
