### ISSUE TITLE
Support Custom Mapping File Path

### ISSUE THREAD

**Issue by ccjernigan** [Triple-T/gradle-play-publisher#868]
### Problem description
I am specifying the app bundle path explicitly (`artifactDir.set`), rather than building it on the fly.  However, there is no option in the extension to support supplying the mapping file.  This means I cannot upload a mapping file automatically when specifying the app bundle path.

I would like something like `mappingDir.set` so that I can explicitly define where to upload the mapping from too.

### Potential solutions/workarounds
Currently, I have to upload the mapping file manually through the Play Store console after the automatic upload completes.

### Additional context
I have a quirky setup.  I'm integrated with DexGuard which post-processes my APK file.  However, I also need to run the Play Publisher plugin before DexGuard runs, in order to automatically increment the version code.  So on the command line my build happens in two steps:
`./gradlew :app:publishBundle -PPUBLISH_MODE=build`
`./gradlew :app:publishBundle -PPUBLISH_MODE=upload`

In my app's build.gradle, I provide different options to the Play Publisher based on `PUBLISH_MODE`.  The build mode uploads automatically but disables commits, so that a version code is generated.  After the fake "upload", the DexGuard plugin post-processes the app bundle and generates a new bundle and mapping file.

The upload mode is supplied the path to the app bundle, but there's no way to supply a path to the mapping file that I can see.

**Comment by SUPERCILEX** [comment]
2 things:
- You can upload a mapping file by putting a file named `mapping.txt` in the artifact dir. This will hopefully become more flexible as per #863, but the current method should be enough for your use case.
- If all you want to do is get the version code bump, you can simply make sure `processXXXVersionCodes` gets run where XXX is `Release` for example. Going through all of `publishBundle` should be unecessary. (BTW `processXXXVersionCodes` is the task name for v3.0, I think it was called something different in v2.x.)

**Comment by ccjernigan** [comment]
Cool, thank you for the reply.  It wasn't clear from the documentation that the first option would work, so I'll give that a try.  That should solve what I need for the time being.

**Comment by SUPERCILEX** [comment]
Oh wait, you're right. I thought I had docs for that.
