### ISSUE TITLE
Incorrect folder structure?

### ISSUE THREAD

**Issue by SteveEdson** [Triple-T/gradle-play-publisher#87]
When I ran the boostrap task, my `play` folder was created inside a new `release` folder, sat next to the `main` folder.

Is there a reason for this? From what I can see, I have set it up correctly. I don't have any productFlavours, only debug and release build variants.

Thanks.

**Comment by tasomaniac** [comment]
It puts the 'play' folder inside 'release' folder for me too. Before I had an alpha flavor and I remember it put the folder inside 'alpha' folder. That is weird. 

I think it would be good to have control over where to put the folder.

**Comment by tasomaniac** [comment]
Fixing my comment. It didn't give me 'alpha' folder because I've set alpha build type as debuggable. Debuggable types are not supported with the plugin. I think it should be documented somewhere. 

After I set it to `debuggable false` I could run
```
./gradlew publishApkAlpha
```

**Comment by bhurling** [comment]
You're right. With no flavors we bootstrap the play store data into the release folder (more specifically into the folder named after the current buildType). As soon as there are flavors, we do not honor the buildType anymore but only the flavor name. This is not really consistent. I will fix that.

**Comment by bhurling** [comment]
Fixed in 1.1.3
