### ISSUE TITLE
Two flavor dimensions configuration help request

### ISSUE THREAD

**Issue by volo-droid** [Triple-T/gradle-play-publisher#870]
Our project has 2 flavor dimensions: `region` and `distribution`.
The `region` dimension has 2 flavors: `europe` and `asia`, each defining its own `applicationId`: `com.example.app.europe`, `com.example.app.asia`.
The `distribution` dimension also has 2 flavors: `appCenter` and `googlePlay`. Those flavors don't define `applicaitonId` and are used to customize builds for different distribution channels (i.e. AppCenter and Google Play).  

We'd like to publish app bundles for the `europeGooglePlay` and `asiaGooglePlay` variants. For the time being an application for `asia` hasn't been created yet in the Google Play (this is not managed by the dev team) and it needs to be temporary disabled. Also in the future there will be more region flavors (e.g. `americas`), so we might assume we'd need to publish all `xxxGooglePlay` build variants.

My setup:

```groovy
android {
    flavorDimensions "region", "distribution"

    productFlavors {
        appCenter {
            dimension "distribution"
        }

        googlePlay {
            dimension "distribution"
        }

        europe {
            dimension "region"
            applicationId 'com.example.app.europe'
        }

        asia {
            dimension "region"
            applicationId 'com.example.app.asia'
        }
    }

    playConfigs {

        asia {
            enabled.set(false)
        }

        appCenter {
            enabled.set(false)
        }
    }
}
```

However `gradlew bootstrap` ends with an error:
```
> A failure occurred while executing com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
   > 404 Not Found
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/com.example.app.asia/edits
     {
       "code" : 404,
       "errors" : [ {
         "domain" : "global",
         "message" : "Package not found: com.example.app.asia.",
         "reason" : "notFound"
       } ],
       "message" : "Package not found: com.example.app.asia.",
       "status" : "NOT_FOUND"
     }
```

That's happening because `com.example.app.asia` has not been create yet in the Google Play, as I mentioned above. But why does the plugin query it at all, if I asked it to disable publishing for the `asia` flavor? That looks like a bug.

Interesting though, that if I remove `appCenter` block from `playConfigs`:
```
    playConfigs {
        asia {
            enabled.set(false)
        }
    }
```
then `gradlew bootstrap` completes normally, however it creates two folders under `app/src`:
* `europeAppCenter/play`
* `europeGooglePlay/play`

The first one there is redundant, so it would be good to get rid of it and to avoid unnecessary network requests.

Can you tell me, what I'm doing wrong with the configuration?

---

Plugin version: 3.0.0
AGP version: 4.1.0-beta05

**Comment by volo-droid** [comment]
I was able to make it work by disabling GPP by default:
```
android {
    playConfigs {
        europeGooglePlayRelease {
            enabled.set(true)
        }
    }
}

play {
    enabled.set(false)
}
```

**Comment by SUPERCILEX** [comment]
Yeah, yeah you'd have to disable every possible combination. It's better to simply disable everything and enable only the bits you want.
