### ISSUE TITLE
Option to skip some tasks

### ISSUE THREAD

**Issue by harshmandan** [Triple-T/gradle-play-publisher#875]
### Problem description
I have a project with many flavours. When I'm doing any batch task, say `gradlew bootstrap` to fetch metadata of all flavours and one flavour fails in between due to some error, the task stops. Now after fixing the cause of the error, running `gradlew bootstrap` runs from the start (as expected). I'd like to have an option to skip some tasks somehow.

### Potential solutions/workarounds
One solution is to never stop the batch tasks (by passing a param), just print the error and keep going on with the rest of the tasks. (this should be easier than the next solution I'm going to propose)

Another solution is to pass a paramter which allows to select the starting task, As all the tasks are sorted alphabetically, task name can be given so that all the tasks before the given task gets skipped.

**Comment by SUPERCILEX** [comment]
This should work: https://blog.mrhaki.com/2014/12/gradle-goodness-continue-build-even.html?m=1

**Comment by harshmandan** [comment]
@SUPERCILEX Yes it does work. Thank you.
