### ISSUE TITLE
create a task to retrieves channel names for a Google Play Store 

### ISSUE THREAD

**Issue by underwindfall** [Triple-T/gradle-play-publisher#878]
### Problem description
Here it the context , when I try to publish a `apk` from plugin I want to input an existed `channel name` from my current playstore. However I don't know what list of `channel names` already existed in my project. I think it would be better to expose a new task to display all releases channel name for this feature.

### Potential solutions/workarounds
1. Add a new method in `DefaultPlayPublisher` to get list of tracks and expose it the 
```kotlin
 override fun findListOfTrackName(): List<String> {
       return  publisher.tracks().map{ it }
    }
```
2. expose this function to the `gradle plugin` task

**Comment by SUPERCILEX** [comment]
I'm confused, do you want a task that prints out all the channel names? Or do you mean a programmatic API you'd use in the build script?

**Comment by underwindfall** [comment]
I want to have a that prints out all the channel names.

**Comment by SUPERCILEX** [comment]
Gotya, thanks for clarifying. I'll have to think about it, but I'm not sure that makes sense for this project. The goal is to enable automation, not provide a CLI for the play console.

**Comment by SUPERCILEX** [comment]
For now, I've decided to forgo an official implementation. That said, if more people want one, I might reconsider.

In the meantime, with GPP v3.1.0 you can use this hack (as a KTS script):

```kotlin
tasks.register("printPlayTracks") {
    val apiService = gradle.sharedServices.registrations
            .named("playApi-com.supercilex.test")
            .get().service.get()

    doLast {
        val publisher = apiService.withGroovyBuilder { "getPublisher"() }!!
        val editId = publisher.withGroovyBuilder { "insertEdit"() }!!
                .withGroovyBuilder { "getId"() }
        val tracks = publisher.withGroovyBuilder { "listTracks"(editId) } as List<Any>

        println(tracks.joinToString(",\n") {
            it.withGroovyBuilder { "toPrettyString"() } as String
        })
    }
}

**Comment by underwindfall** [comment]
thx agagin, very greatful you deal with it.
