### ISSUE TITLE
Replace "track" with multiple gradle tasks. 

### ISSUE THREAD

**Issue by tasomaniac** [Triple-T/gradle-play-publisher#88]
It is really common to use build type inside Gradle task names like `assembleFlavor1Alpha`

The plugin can also make use of these instead of "track" keyword. Which should be manually changed everytime you want to publish to a different track. 

Instead we can have tasks like this. 

if there is no flavor:
```
publishAlpha
publishBeta
publishRelease
```
if there is a flavor Flavor1
```
publishFlavor1Alpha
publishFlavor1Beta
publishFlavor1Release
```

What do you think? If it sounds ok, I can implement it and send you a PR.

**Comment by bhurling** [comment]
I'd rather stay with the current solution of manually changing the track (and perhaps even committing that change into version control). I don't want to introduce another dimension of gradle tasks.

You can still use gradle properties or command line arguments to fill the track property at runtime.

**Comment by tasomaniac** [comment]
Makes sense.
