### ISSUE TITLE
class com.android.build.gradle.internal.scope.InternalArtifactType$BUNDLE cannot be cast to class com.android.build.api.artifact.ArtifactType

### ISSUE THREAD

**Issue by mochadwi** [Triple-T/gradle-play-publisher#882]
### Describe the bug

```
Could not determine the dependencies of task ':legacy:uploadStagingDebugPrivateBundle'.
> class com.android.build.gradle.internal.scope.InternalArtifactType$BUNDLE cannot be cast to class com.android.build.api.artifact.ArtifactType (com.android.build.gradle.internal.scope.InternalArtifactType$BUNDLE and com.android.build.api.artifact.ArtifactType are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4129832e)
```

### How To Reproduce

Running `./gradlew :legacy:uploadStagingDebugPrivateBundle`

#### Versions

- Gradle Play Publisher: 3.0.0
- Gradle Wrapper: 6.6-all
- Android Gradle Plugin: 4.1

#### Tasks executed

What tasks did you run? For example, `./gradlew :legacy:uploadStagingDebugPrivateBundle`.

### Expected behavior

Succeed to upload onto internal sharing 

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
You probably have an extra AGP dependency somewhere that isn't 4.1.0. This was fixed: #824

**Comment by mochadwi** [comment]
ok, will try to search for it, I'm afraid this is due to my CI caches that still use the both the previous 4.0 & 4.1

**Comment by mochadwi** [comment]
solved, due to conflicting binary version of AGP
