### ISSUE TITLE
Fix documentation for Gradle Script Kotlin

### ISSUE THREAD

**Issue by ccjernigan** [Triple-T/gradle-play-publisher#883]
The docs here show using a `play {}` block which I can’t get working with kts+3.0.0 of the plugin.

The error is that val can’t be reassigned, so it looks like the switch to gradle properties doesn’t work nicely.

I looked at the [test app](https://github.com/Triple-T/gradle-play-publisher/blob/master/testapp/build.gradle.kts) and found `configure<PlayPublisherExtension> {}` syntax.

So it looks like the docs need to be updated to reflect this syntax difference.

**Comment by SUPERCILEX** [comment]
I'm guessing you're still doing stuff like `track = "foo"`? It should be `track.set("foo")`.

**Comment by ccjernigan** [comment]
I made the change for the gradle property API (`.set`).  There seems to be something else going on where the `play` block wasn't behaving properly but `configure<PlayPublisherExtension> {}` worked.

**Comment by SUPERCILEX** [comment]
Hmmm, that doesn't make much sense since `configure` and `play` should be the same. Are you using `.set` everywhere in the play block? Or maybe you put the `play` block inside something else that's messing it up? And are you using the `plugins { id(...) }` block up top?
