### ISSUE TITLE
Promote staged rollout to 100% requires to use completed status

### ISSUE THREAD

**Issue by rolgalan** [Triple-T/gradle-play-publisher#884]
Hi there!

We've been using this amazing plugin for a while, but today we got problem when trying to promote a staged rollout to 100%. This used to work fine with ` --release-status inProgress --user-fraction 1.0`, but since today Google API returns "User fraction must be lower than one". Which is consistent with their [documentation](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Track).

It might be interesting to improve the [Promoting Artifacts](https://github.com/Triple-T/gradle-play-publisher#promoting-artifacts) section in the Readme to highlight that `--release-status completed  --user-fraction 1.0` [should be used instead](https://developers.google.com/android-publisher/tracks#completing_a_staged_rollout).

Thanks!

**Comment by SUPERCILEX** [comment]
The user fraction can only be used with inProgress status. Marking the release as completed is the same as a full rollout so the user fraction param you're setting is just being ignored.

The plugin could maybe correct the inProgress release to completed if you set the user fraction to 0, but I feel like that might be too much magic.

**Comment by SUPERCILEX** [comment]
Oops, still need to decided on this.

**Comment by SUPERCILEX** [comment]
I'm not a huge fan of magic, so I decided to just add some docs instead of trying to correct the invalid combination.
