### ISSUE TITLE
Issues upgrading to 3.0.0

### ISSUE THREAD

**Issue by crysxd** [Triple-T/gradle-play-publisher#886]
### Describe the bug

I tried to upgrade to 3.0.0 as 2.8.0 does not seem to be compatible with Android gradle plugin 4.1+. I followed the instructions I found around the repo and replaced all `=` with `set` and looked up the example configurations in the readme.

I get two errors:

- `Cannot set the value of extension 'play' property 'userFraction' of type java.lang.Double using an instance of type java.math.BigDecimal.`
- `No such property: IGNORE for class: org.gradle.api.artifacts.ResolutionStrategy`

The first one is especially odd as I use `userFraction.set(1.0)` which for some reason is a `BigDecimal`. The second one is a missing import I guess but the readme does not state any import requirements.

Thanks for your support!

### How To Reproduce
The code is available here, configuration in `app/build.gradle`. 
https://gitlab.com/crysxd/octoapp/-/tree/235-upadte-google-play-publisher

```
play {
    serviceAccountCredentials.set(file("service-account.json"))
    track.set("beta")
    defaultToAppBundles.set(true)
    resolutionStrategy.set(ResolutionStrategy.IGNORE)
    updatePriority.set(2)
    userFraction.set(1.0)
}
```

#### Versions

- Gradle Play Publisher: 3.0.0
- Gradle Wrapper: 6.5
- Android Gradle Plugin: 4.1.1

#### Tasks executed

Failes to sync, so all tasks :)

**Comment by SUPERCILEX** [comment]
Yeah, see #885.

You'll want to `import com.github.triplet.gradle.androidpublisher.ResolutionStrategy` and slap a d on the number to make it work for whatever reason: `1.0d`. Sidenote: setting the user fraction to 1 is unnecessary.

**Comment by zhelanov** [comment]
Hi! :) 
For some reason I can't import `com.github.triplet.gradle.androidpublisher.*` classes because gradle can't resolve `androidpublisher` :/ 
Am I the only one who faced this problem?
