### ISSUE TITLE
ResolutionStrategy IGNORE is missing in 3.0.0

### ISSUE THREAD

**Issue by sophiataskova** [Triple-T/gradle-play-publisher#887]
Looks like these docs are out of date https://github.com/Triple-T/gradle-play-publisher#handling-version-conflicts -- I am on AGP 4.1.0 and the current release of the Gradle Play Publisher 3.0.0, and I get an error "> No such property: INGORE for class: com.github.triplet.gradle.androidpublisher.ResolutionStrategy" when I set the configs:
```
play {
        resolutionStrategy.set(com.github.triplet.gradle.androidpublisher.ResolutionStrategy.INGORE)
}
```

**Comment by SUPERCILEX** [comment]
The typo, common enemy of the people. :grin: `INGORE -> IGNORE`

**Comment by sophiataskova** [comment]
Yikes! Thanks you! And way to waste my opportunity to get your help 🤦

**Comment by SUPERCILEX** [comment]
Lol, no worries
