### ISSUE TITLE
contactEmail not updating the email in store listing

### ISSUE THREAD

**Issue by Shivam-Miglani** [Triple-T/gradle-play-publisher#89]
I have included contactEmail file under Play folder, and it's not updating it in the store listing. However, everything else is working fine.

**Comment by bhurling** [comment]
The API requires a defaultLanguage to be set when you want to update contactEmail, contactWeb or contactPhone. Please make sure to add a file called `defaultLanguage` right next to the `contactEmail` file. Drop in the language/region combination that should be the default for your store listing.

**Comment by Shivam-Miglani** [comment]
Adding defaultLanguage solved the issue.
