### ISSUE TITLE
Bugsnag upload task no longer invoked with 3.0.0

### ISSUE THREAD

**Issue by shashachu** [Triple-T/gradle-play-publisher#893]
### Describe the bug

We use Bugsnag for our crash reporting (https://github.com/bugsnag/bugsnag-android-gradle-plugin) which needs to upload mapping files to their servers in order to deobfuscate callstacks. After upgrading to 3.0.0 (and AGP 4.1), it appears that running the `publishXXXBundle` task no longer causes their plugin to add the `uploadXXX-mapping` task. 

### How To Reproduce

I haven't tried to build a minimal repro project, but prior to the upgrade, when running `./gradlew --dryRun publishProductionRelease` in our project, I see the following tasks:

```
:Pinterest:packageProductionReleaseBundle SKIPPED
:Pinterest:signProductionReleaseBundle SKIPPED
:Pinterest:uploadBugsnagProduction-releaseMapping SKIPPED
:Pinterest:bundleProductionRelease SKIPPED
:Pinterest:publishProductionReleaseBundleWrapper SKIPPED
:Pinterest:publishProductionReleaseBundle SKIPPED
:commitEditForComDotPinterest SKIPPED
```

After the upgrade, running the same command outputs:

```
:Pinterest:packageProductionReleaseBundle SKIPPED
:Pinterest:validateSigningProductionRelease SKIPPED
:Pinterest:signProductionReleaseBundle SKIPPED
:Pinterest:publishProductionReleaseBundle SKIPPED
:commitEditForComDotPinterest SKIPPED
```

Note the `uploadBugsnag` task is missing. I haven't looked carefully through their plugin code to see exactly how it's deciding when to add the upload task, but I suspect it's looking for the `bundleXXX` task. 

I'm unsure which side this should be fixed on, so we're just looking for some guidance on your end.

#### Versions

- Gradle Play Publisher: 3.0
- Gradle Wrapper: 6.6
- Android Gradle Plugin: 4.1

#### Tasks executed

`publishProductionReleaseBundle`

### Expected behavior

We expect the Bugsnag upload task to be invoked.

### Additional context (if a crash, provide stack trace)

We're using Bugsnag Gradle Plugin version 5.3.0

**Comment by shashachu** [comment]
In the Bugsnag plugin I do see this: 

```
/**
     * Whether or not a bundle task is going to be run for this variant
     */
    private fun isRunningBundleTask(project: Project,
                            variant: ApkVariant,
                            output: ApkVariantOutput): Boolean {
        return isRunningTaskWithPrefix(project, variant, output, BUNDLE_TASK)
    }
```

So this might be something better fixed on the Bugsnag side; but I'm also a little curious what happened to the `bundleXXX` task.

**Comment by SUPERCILEX** [comment]
Yeah, this is the same as #859. Those plugins are wrong in that they assume you'll call the public task names. Newer AGP versions don't run those lifecycle tasks when a plugin says that need to assemble the app because they're just there for a human to type.

**Comment by SUPERCILEX** [comment]
For now, you should manually call the bugsnag task, but I think I'll add some logic to depend on the bugsnag and crashlytics tasks on publish since that seems better than those plugins running on every assemble.

**Comment by shashachu** [comment]
> For now, you should manually call the bugsnag task, but I think I'll add some logic to depend on the bugsnag and crashlytics tasks on publish since that seems better than those plugins running on every assemble.

Thanks; yeah for now we added an explicit call to the upload task as a workaround.

**Comment by shashachu** [comment]
@SUPERCILEX if I wanted to put a PR up to fix this on the Bugsnag side; which task should be the right one for them to detect if a bundle or APK build were running? Or is the best fix still on your side vs Bugsnag/Crashlytics?

**Comment by SUPERCILEX** [comment]
Currently, I believe the task is `package${variantName}Bundle`, but that's supposed to be an implementation detail of AGP so it could change at any time. Feel free to send up a PR, though I'm not sure they'll want to merge it since the name could break.

**Comment by shashachu** [comment]
Yeah, I'm also in contact w/ the Bugsnag folks and they said they'd probably accept a PR looking for the package task but it's probably just buying us some additional time, and certainly not bullet-proof.
