### ISSUE TITLE
Nothing happend

### ISSUE THREAD

**Issue by ivanove** [Triple-T/gradle-play-publisher#90]
Hi all,

I use the Plugin to upload my APK and metadata to the Google Play Store, I follow the link
but nothing happen, when I check google play no APK found
this my play's task
play {
    serviceAccountEmail = 'agence.paperpad@gmail.com'
    pk12File = file('Paperpad-e7da3122bc6a.p12')
    errorOnSizeLimit = false
    track = 'production' // or 'rollout' or 'beta' or 'alpha'
    //userFraction = 0.1 // only necessary for 'rollout', in this case default is 0.1
   // uploadImages = true
}

What I did wrong ?

**Comment by bhurling** [comment]
I think you used the wrong email address. You have to use the service email address that is tied to your p12 file. Have a look into the Developer console. If everything is set up correctly, you should find another user with some numeric email address.

**Comment by ivanove** [comment]
thnk's for the respone, but where I can found this email address could you give more indication ?

**Comment by ivanove** [comment]
Hi 

How to know if the upload works or no ? I add my service email adresse with the generated p12 file, I generate my new signing apk but I don't receive any messages, so I must wait or what exactly to do ?

**Comment by ivanove** [comment]
Hi,
Can you please see my code, I respect all the rules in Readme, but nothing happen.
********************
**************
********
****
**
*
apply plugin: 'com.android.application'

buildscript {
    repositories {
        mavenCentral()
        maven { url 'http://download.crashlytics.com/maven' }
    }
    dependencies {
        classpath 'com.github.triplet.gradle:play-publisher:1.1.2'  /***publish***/
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'com.crashlytics.tools.gradle:crashlytics-gradle:1.+'

    }
}
apply plugin: 'android'
apply plugin: 'crashlytics'
apply plugin: 'com.github.triplet.play'  /***publish***/
repositories {
    mavenCentral()
    maven { url 'http://download.crashlytics.com/maven' }
}
  /***publish**/
play {
    serviceAccountEmail ='75389784733-2qt0qnjjcfvljum02kvop6d37uqvvgkg@developer.gserviceaccount.com'
    pk12File = file('Paperpad Business-31d706bc131f.p12')
    errorOnSizeLimit = false
    track = 'production' // or 'rollout' or 'beta' or 'alpha'
//    userFraction = 0.1 // only necessary for 'rollout', in this case default is 0.1
  uploadImages = true
}



android {

    //useOldManifestMerger false

    dexOptions {
        preDexLibraries = false
        javaMaxHeapSize "4g"
    }

    lintOptions {
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    signingConfigs {
        debug_config {
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            storeFile file('debug.keystore')
            storePassword 'android'
        }


        release_config {
            keyAlias 'euphor-paperpad'
            keyPassword 'paperpadeuphor2013'
            storeFile file('release.keystore')
            storePassword 'paperpadeuphor2013'
        }
    }
    compileSdkVersion 21
    buildToolsVersion '21.1.2'
    defaultConfig {
        applicationId 'com.euphor.paperpad'
        minSdkVersion 11
        targetSdkVersion 21
        versionCode 131
        versionName '0.8.4'
        signingConfig signingConfigs.debug_config
        // Enabling multidex support.
        multiDexEnabled true
    }

    buildTypes {
        release {
            debuggable false
            //runProguard false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            signingConfig signingConfigs.debug_config
            renderscriptDebuggable false
        }
    }
    productFlavors {
        Business {
            applicationId "com.euphor.paperpad"
            manifestPlaceholders = [activityLabel : "Business", gcmPackage : "com.euphor.paperpad"]
            minSdkVersion 11
            signingConfig signingConfigs.debug_config
            targetSdkVersion 21
            versionCode 131
            versionName '0.8.4'
            ext.enableCrashlytics = true
            set("crashlyticsApiKey", "023e7fe8a4a93f93ffe7510201929d081b125313")
            set("crashlyticsApiSecret", "fe4680d06d3dce0537bab77fc97ff48bb7803a6091c916ac0c285e50d9dd0fa5")
        }
        BusinessApps {
            applicationId "com.paperpad.GrandMonarque"
            minSdkVersion 11
            signingConfig signingConfigs.debug_config
            targetSdkVersion 21
            versionCode 131
            versionName '0.8.4'
            ext.enableCrashlytics = true
            set("crashlyticsApiKey", "023e7fe8a4a93f93ffe7510201929d081b125313")
            set("crashlyticsApiSecret", "fe4680d06d3dce0537bab77fc97ff48bb7803a6091c916ac0c285e50d9dd0fa5")
        }

        BusinessApp1 {
            applicationId "com.paperpad.TanteArlette"
            minSdkVersion 11
            signingConfig signingConfigs.debug_config
            targetSdkVersion 21
            versionCode 128
            versionName '0.8.1'
            ext.enableCrashlytics = true
            set("crashlyticsApiKey", "023e7fe8a4a93f93ffe7510201929d081b125313")
            set("crashlyticsApiSecret", "fe4680d06d3dce0537bab77fc97ff48bb7803a6091c916ac0c285e50d9dd0fa5")
        }

        BusinessApp2 {
            applicationId "com.paperpad.SuiteHome"
            minSdkVersion 11
            signingConfig signingConfigs.debug_config
            targetSdkVersion 21
            versionCode 134
            versionName '0.8.7'
            ext.enableCrashlytics = true
            set("crashlyticsApiKey", "023e7fe8a4a93f93ffe7510201929d081b125313")
            set("crashlyticsApiSecret", "fe4680d06d3dce0537bab77fc97ff48bb7803a6091c916ac0c285e50d9dd0fa5")
        }

        BusinessApp3 {
            applicationId "com.paperpad.fds"
            minSdkVersion 11
            signingConfig signingConfigs.debug_config
            targetSdkVersion 21
            versionCode 132
            versionName '0.8.5'
            ext.enableCrashlytics = true
            set("crashlyticsApiKey", "023e7fe8a4a93f93ffe7510201929d081b125313")
            set("crashlyticsApiSecret", "fe4680d06d3dce0537bab77fc97ff48bb7803a6091c916ac0c285e50d9dd0fa5")
        }

        BusinessApp4 {
            applicationId "com.paperpad.AperoChic"
            minSdkVersion 11
            signingConfig signingConfigs.debug_config
            targetSdkVersion 21
            versionCode 128
            versionName '0.8.1'
            ext.enableCrashlytics = true
            set("crashlyticsApiKey", "023e7fe8a4a93f93ffe7510201929d081b125313")
            set("crashlyticsApiSecret", "fe4680d06d3dce0537bab77fc97ff48bb7803a6091c916ac0c285e50d9dd0fa5")
        }
    }

    sourceSets {
/*        main {
            manifest.srcFile 'main/AndroidManifest.xml'
            java.srcDirs = ['main/java']
            res.srcDirs = ['main/res']
            assets.srcDirs = ['main/assets']
        }*/

/*        BusinessApps.java.srcDirs = ['src/BusinessApps/java']
        BusinessApps.res.srcDirs = ['src/BusinessApps/res']
        BusinessApps.assets.srcDirs = ['src/BusinessApps/assets']
        BusinessApps.manifest.srcFile = ['src/BusinessApps/AndroidManifest.xml']*/

        Business {
            manifest.srcFile 'Business/AndroidManifest.xml'
        }

        BusinessApps {
            manifest.srcFile 'src/BusinessApps/AndroidManifest.xml'
            assets.srcDirs 'src/BusinessApps/assets'
        }

        BusinessApp1 {
            manifest.srcFile 'BusinessApp1/AndroidManifest.xml'
            assets.srcDirs = ['BusinessApp1/assets']

        }

        BusinessApp2 {
            manifest.srcFile 'BusinessApp2/AndroidManifest.xml'
            assets.srcDirs = ['BusinessApp2/assets']

        }

        BusinessApp3 {
            manifest.srcFile 'BusinessApp3/AndroidManifest.xml'
        }

        BusinessApp4 {
            manifest.srcFile 'BusinessApp4/AndroidManifest.xml'
        }
    }
    }
....................

**Comment by bhurling** [comment]
Please do not disclose secrets for crashlytics or the service email address or passwords in your comments

**Comment by ivanove** [comment]
thank's, but can you help me please ?
I search 2 days but nothing happend, the build succed but no new APK in play store.

**Comment by bhurling** [comment]
What gradle task did you run? Can you please copy the output of that task?

**Comment by ivanove** [comment]
this what happen when I run gradlew play, this is correct or not ?
C:\Users\Euphor\Desktop\Nouveau dossier (4)\AppBusiness>gradlew play 
                                                                                                                                          
FAILURE: Build failed with an exception.
                              
* What went wrong:            
Task 'play' not found in root project 'AppBusiness'.
                              
* Try:                        
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
                              
BUILD FAILED                  
                              
Total time: 26.274 secs

**Comment by enradrol** [comment]
<pre>
signingConfigs {
    debug_config {
        ...
        storeFile file('debug.keystore')
        ...
    }
...
productFlavors {
       ...
        BusinessApp3 {
               ...
               signingConfig signingConfigs.debug_config
               ...
        }
}
...
</pre>
Did you try to upload an APK signed with your debug keystore?

**Comment by ivanove** [comment]
no I modified it, but this my new error
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':app:publishApkBusinessApp3Release'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {           
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Co
nsole.",
      "reason" : "projectNotLinked"
    } ],      
    "message" : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Cons
ole."
  }

**Comment by enradrol** [comment]
Hm, sounds like you should look at this page:
https://developers.google.com/android-publisher/getting_started

**Comment by enradrol** [comment]
Did you enable "Manage Production APKs"?
https://play.google.com/apps/publish/#ApiAccessPlace

**Comment by enradrol** [comment]
Did you enable "Manage Production APKs" 
https://play.google.com/apps/publish/#ApiAccessPlace

**Comment by ivanove** [comment]
thank's, I enable the associed project but it gives me this error :

com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized

**Comment by ivanove** [comment]
and what about this please, sorry If i distrub you.

* What went wrong:
Execution failed for task ':app:publishListingBusinessApp3Release'.
> java.io.FileNotFoundException: C:\Users\Euphor\Desktop\Nouveau dossier (4)\AppBusiness\app\build\outputs\play\BusinessApp3Release

**Comment by enradrol** [comment]
about the FileNotFoundException:
try to run "gradlew bootstrapBusinessApp3PlayResources" before 

about Unauthorized:
check if you use the right pk12File

**Comment by ivanove** [comment]
thank you very much, it works now :dancers:

**Comment by SupzRao** [comment]
I face the same Issue , please help me out  

Execution failed for task ':app:publishApkRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized

**Comment by ivanove** [comment]
about Unauthorized:
check if you use the correct pk12File
