### ISSUE TITLE
Error on play console after move to 3.1.0-agp4.2-2, 3.2.0-agp4.2-2 and 3.2.0-agp4.2-2

### ISSUE THREAD

**Issue by jrcacd** [Triple-T/gradle-play-publisher#906]
Verifier rejected class com.google.android.gms.measurement.internal.AppMeasurementDynamiteService: void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.getCurrentScreenClass(com.google.android.gms.internal.measurement.zzw) failed to verify: void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.getCurrentScreenClass(com.google.android.gms.internal.measurement.zzw): [0x9] cannot access instance field qn3 in3.a from object of type Unresolved Reference: fp3 void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.getCurrentScreenName(com.google.android.gms.internal.measurement.zzw) failed to verify: void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.getCurrentScreenName(com.google.android.gms.internal.measurement.zzw): [0x9] cannot access instance field qn3 in3.a from object of type Unresolved Reference: fp3 void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.setConsent(android.os.Bundle, long) failed to verify: void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.setConsent(android.os.Bundle, long): [0xF] cannot access instance field qn3 in3.a from object of type Unresolved Reference: fp3 void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.setConsentThirdParty(android.os.Bundle, long) failed to verify: void com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.setConsentThirdParty(android.os.Bundle, long): [0xF] cannot access instance field qn3 in3.a from object of type Unresolved Reference: fp3 (declaration of 'com.google.android.gms.measurement.internal.AppMeasurementDynamiteService' appears in /data/app/com.aaa.bbb-yDLxFcPJegV8zNN5Ay094A==/base.apk)

**Comment by SUPERCILEX** [comment]
I doubt that's related to the plugin. Try manually uploading the APK or bundle to see if it works.

**Comment by jrcacd** [comment]
Just waiting to see if is android studio bug.

**Comment by jrcacd** [comment]
Apparently it was a problem with the kotlin version I was using
