### ISSUE TITLE
Tests fails when using Flavors + GPP

### ISSUE THREAD

**Issue by rchampa** [Triple-T/gradle-play-publisher#907]
### Describe the bug

I have the following simple project https://github.com/rchampa/example-gpp with 4 flavors: demo, dev, pre and pro. 
And when i run the command /.gradlew test I'm having an error:

### How To Reproduce
$ ./gradlew test
> Task :app:processDemoReleaseVersionCodes FAILED

#### Versions
- Gradle Play Publisher: 3.2.0
- Gradle Wrapper: 6.5
- Android Gradle Plugin: 4.1.1

\--- com.github.triplet.gradle:play-publisher:3.2.0
     +--- com.github.triplet.gradle:android-publisher:3.2.0
     |    +--- com.github.triplet.gradle:common-utils:3.2.0
     +--- com.github.triplet.gradle:common-utils:3.2.0
     +--- com.github.triplet.gradle:common-validation:3.2.0
Gradle 6.5
+--- com.android.tools.build:gradle:4.1.1

#### Tasks executed

./gradlew test

### Expected behavior

Test task should not execute any GPP task.

### Additional context (if a crash, provide stack trace)

You can clone this project https://github.com/rchampa/example-gpp and run the the tests and check the problem.

Any workarround please?

**Comment by SUPERCILEX** [comment]
What's the error? Also, this is expected because test runs release tests which depend on having a release version code.

**Comment by rchampa** [comment]
I have a CI, and this is a very hello-world project, and the CI fails because of the task ./gradlew test fails on :app:processDemoReleaseVersionCodes FAILED
My point is, if I remove the GPP plugin the task app:processDemoReleaseVersionCodes is not executed and then my tests run successfully. BTW i have only one test  https://github.com/rchampa/example-gpp/blob/master/app/src/test/java/es/algoritmo/myapplication/ExampleUnitTest.kt

**Comment by SUPERCILEX** [comment]
Right, but what's the error message? I doubt publishing will work either if that task is crashing.

**Comment by rchampa** [comment]
It’s easier if you clone my project and run the  ./gradlew test 

However the error message is :
:app:processDemoReleaseVersionCodes FAILED

I don’t know why but that task is executed only when the GPP is declared in the build.gradle file and there are flavors. If I remove flavors everything goes well.

**Comment by SUPERCILEX** [comment]
This is the error: ![image](https://user-images.githubusercontent.com/9490724/104644043-1ee46380-5662-11eb-9906-f36c37e138d8.png)

Your `myserviceaccount.json` is invalid. If you don't want to make your credentials public, the correct way to do that is to not commit the file and then have `play { enabled.set(file("credentials.json").exists() }`.

**Comment by rchampa** [comment]
Thanks for the help but... 
1. If I use enabled.set(file("credentials.json").exists()) the test task works fine :) but the task uploadProReleasePrivateBundle is not generated. Then when i want to use it i have the following error message: 
> * What went wrong:
> Task 'uploadProReleasePrivateBundle' not found in root project 'My Application'.

2. I've tried a valid serviceaccount json file and I have the same error:

```
$ ./gradlew test
> Task :app:processDevReleaseVersionCodes FAILED
> Task :app:processPreReleaseVersionCodes FAILED
> Task :app:processDemoReleaseVersionCodes FAILED

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDevReleaseVersionCodes'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.ProcessArtifactVersionCodes$VersionCoder
   > 404 Not Found
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/es.algoritmo.githubactions.dev/edits
     {
       "code" : 404,
       "errors" : [ {
         "domain" : "global",
         "message" : "Package not found: es.algoritmo.githubactions.dev.",
         "reason" : "notFound"
       } ],
       "message" : "Package not found: es.algoritmo.githubactions.dev.",
       "status" : "NOT_FOUND"
     }

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processPreReleaseVersionCodes'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.ProcessArtifactVersionCodes$VersionCoder
   > 404 Not Found
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/es.algoritmo.githubactions.pre/edits
     {
       "code" : 404,
       "errors" : [ {
         "domain" : "global",
         "message" : "Package not found: es.algoritmo.githubactions.pre.",
         "reason" : "notFound"
       } ],
       "message" : "Package not found: es.algoritmo.githubactions.pre.",
       "status" : "NOT_FOUND"
     }

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDemoReleaseVersionCodes'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.ProcessArtifactVersionCodes$VersionCoder
   > 404 Not Found
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/es.algoritmo.githubactions.demo/edits
     {
       "code" : 404,
       "errors" : [ {
         "domain" : "global",
         "message" : "Package not found: es.algoritmo.githubactions.demo.",
         "reason" : "notFound"
       } ],
       "message" : "Package not found: es.algoritmo.githubactions.demo.",
       "status" : "NOT_FOUND"
     }

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
96 actionable tasks: 4 executed, 92 up-to-date
```

**Comment by SUPERCILEX** [comment]
Those apps need to exist on the play store: https://github.com/Triple-T/gradle-play-publisher#initial-play-store-upload

**Comment by rchampa** [comment]
Ok. I'm going to try to give more details.
The app es.algoritmo.githubactions is working with github actions and there i figured out that the first time I had to upload the aab manually. PS, github actions are working fine with the same service_account in a different repo.

Leaving that aside, in my project I have more than one flavor each one with different application ID's and I don't understand how could I use this plugin GPP considering that I have 3 flavors to upload them to AppCenter and one flavor **es.algoritmo.githubactions** to use it in Google Play Store. 
Is the expected behaviour have several flavors and not able to run tests?

**Comment by SUPERCILEX** [comment]
Then only enable the flavor you need: https://github.com/Triple-T/gradle-play-publisher#disabling-publishing

**Comment by rchampa** [comment]
Ok using `resolutionStrategy.set(ResolutionStrategy.IGNORE)` solves my problem. But I still thinks that if I want to run my tests it shouldn't trigger the GPP tasks as upload or check the version code.
