### ISSUE TITLE
Publish apk fail

### ISSUE THREAD

**Issue by vfa-cannc** [Triple-T/gradle-play-publisher#91]
* What went wrong:
Execution failed for task ':app:publishApkFreeProductionRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {            
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Daily save quota exceeded.",
      "reason" : "publishingDailySaveQuotaExceeded"
    } ],       
    "message" : "Daily save quota exceeded."
  }            
               
* Try:         
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
               
BUILD FAILED

**Comment by ivanove** [comment]
hi bro can you show me your code please ?

**Comment by bhurling** [comment]
Access to the Play Publisher API is limited by a quota. I think you just exceeded this limit by playing around with the plugin. Just try again tomorrow
