### ISSUE TITLE
publishReleaseBundle fails with 400

### ISSUE THREAD

**Issue by Queatz** [Triple-T/gradle-play-publisher#910]
### Describe the bug

I'm getting an error when publishing now.  The publish still succeeds and I'm able to update my app from the Play Store, however I am seeing a 400 error that I didn't used to see.

#### Versions

- Gradle Play Publisher: 
- Gradle Wrapper: 
- Android Gradle Plugin: 

#### Tasks executed

What tasks did you run? For example, `publishReleaseBundle`.

### Expected behavior

Succeeds without error

### Additional context (if a crash, provide stack trace)

```sh
Execution failed for task ':app:publishReleaseBundle'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishBundle$BundleUploader
   > 400 Bad Request
     PUT https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/closer.vlllage.com.closer/edits/09860832089851881935/bundles?uploadType=resumable&upload_id=<I removed the token>
     {
       "code" : 400,
       "errors" : [ {
         "domain" : "global",
         "message" : "A change was made to the application outside of this Edit, please create a new edit.",
         "reason" : "failedPrecondition"
       } ],
       "message" : "A change was made to the application outside of this Edit, please create a new edit.",
       "status" : "FAILED_PRECONDITION"
     }
```

**Comment by SUPERCILEX** [comment]
Does this always happen? And are you using noCommit? I believe the error might mean someone was messing around on the play store. Or it could be that you're running parallel builds that are fighting for an edit.

**Comment by Queatz** [comment]
> Does this always happen?

This happened after it failed for a different reason.  Can't recall the exact error but it was also to do with `androidpublisher.googleapis.com`

Will update if it happens when running again.

**Comment by SUPERCILEX** [comment]
Ohhh, if it's a one-time thing, then there's nothing we can do since it's just an API error.

**Comment by Queatz** [comment]
Will close and reopen if I see it again

**Comment by SUPERCILEX** [comment]
Sounds good, thanks
