### ISSUE TITLE
[3.2.0-agp4.2-2] upgrade to AGP 4.2.0-beta04 breaks build 

### ISSUE THREAD

**Issue by julioromano** [Triple-T/gradle-play-publisher#912]
### Describe the bug
Upgrading from AGP 4.2.0-beta03 to beta04 breaks the build (all else equals).

Gradle output:

```
BUILD FAILED in 35s
Gradle 6.8.1

FAILURE: Build failed with an exception.

* What went wrong:
com.android.build.api.extension.AndroidComponentsExtension$DefaultImpls.androidTest$default(Lcom/android/build/api/extension/AndroidComponentsExtension;Lcom/android/build/api/extension/VariantSelector;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)V
```

### How To Reproduce
Upgrade from AGP 4.2.0-beta03 to beta04

#### Versions
- Gradle Play Publisher: 3.2.0-agp4.2-2
- Gradle Wrapper: 6.8.1
- Android Gradle Plugin: AGP 4.2.0-beta04

#### Tasks executed
Any task

**Comment by SUPERCILEX** [comment]
Can you run `./gradlew help -S`. I don't think this is related to GPP as we don't use the `androidTest` method.

**Comment by julioromano** [comment]
Omg sorry... that's not Triple-T :)
Lately I got so much used of AGP breaking the plugin every new release that I didn't even think that it could be something else.

**Comment by SUPERCILEX** [comment]
Hehe, sounds about right. :)
