### ISSUE TITLE
Two bundle files release

### ISSUE THREAD

**Issue by panpeter** [Triple-T/gradle-play-publisher#914]
### Problem description
When we release our app, we upload two bundle files, one for Android devices and the second one for Wear devices. 

We tried to put both bundle files in one dir and set `artifactDir` but this gives us `ERROR_no-unique-aab-found` error. 

### Potential solutions/workarounds
The `publishBundle` task uploads all bundle files found in the `artifactDir`.

### Additional context
It seems it's possible to upload multiple apks files but not multiple bundle files, correct?

**Comment by SUPERCILEX** [comment]
That's correct. I thought app bundles would include everything necessary to generate both a phone and wear app, but I'm guessing that's wrong?

To help me understand, would you mind sharing a little more about your build process? Are the phone and wear package names different? Is it wear os 2.0? Are these in sperate Gradle modules?

**Comment by panpeter** [comment]
Sure, we use [Multi-APK](https://developer.android.com/training/wearables/apps/packaging) releases, but instead of multiple apks we release multiple bundle files, one for Wear and second for Android. We support Wear 2.0, package names are the same and we have dedicated Gradle modules for Wear and Android apps.

If you don't mind I can add support for multiple bundles releases and open a PR.

**Comment by SUPERCILEX** [comment]
Ohhh, I think I remember how this is supposed to work. We actually do support this if you do a build and publish all in one go by combining the wear and app upload together. There are [some docs](https://github.com/Triple-T/gradle-play-publisher#combining-artifacts-into-a-single-release), but they seem unnecessarily complicated, so I need to fix that.

And yep, seems like the artifact dir case was overlooked. As for opening a PR, go for it! (A fair warning, it'll probably be quite a bit of work. You can take inspiration from how the APK uploads work.)

**Comment by panpeter** [comment]
Ok, thanks for the hint. I'll try to have it ready during the next 2 weeks 👍
