### ISSUE TITLE
Possibility to turn off default `publish` task

### ISSUE THREAD

**Issue by tprochazka** [Triple-T/gradle-play-publisher#917]
I'm still fighting with the fact that this plugin sharing `publish` task name with a normal Gradle publish plugin.
It is an issue on the existing projects which has several library modules that are already published to maven artifactory.
It always has setup CI infrastructure, where it runs simply `gradlew publish`.
And when I add this plugin there it always broke this setup, because it immediately starts to publishing also to Play.
Would be possible to add a switch that allows explicitly turn off this default root task? 
So then will be possible to choose if I want to deploy to artifactory by `publish` or to Play with `publishBundle` for example.

**Comment by SUPERCILEX** [comment]
Yeah, if it's still causing issues may as well remove the dependency.

**Comment by tprochazka** [comment]
You mean remove the dependency on `gradle-play-publisher`? No, this is definitely not a possible way ;-)

**Comment by SUPERCILEX** [comment]
No, sorry I meant GPP should stop adding itself to the publish task. :)

**Comment by tprochazka** [comment]
Thanks!
