### ISSUE TITLE
Unexpected end of file from server

### ISSUE THREAD

**Issue by harshmandan** [Triple-T/gradle-play-publisher#922]
### Describe the bug

On running the command `gradlew publishflavourXRelease` the bundle fails at the end. (After it shows 88% uploaded).
Here's the console output:
```
Execution failed for task ':app:publishFlavourXReleaseBundle'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishBundle$Processor
   > There was a failure while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishBundle$BundleUploader
         > Unexpected end of file from server
```
#### Versions
GPP: `3.3.0`

Is this a server side issue?

**Comment by SUPERCILEX** [comment]
Does the happen every time? If so, it could be a GPP issue, but yeah, it's most likely just a server crashing mid-transmission.

**Comment by harshmandan** [comment]
It was due to my VPN being on. My bad.

**Comment by SUPERCILEX** [comment]
Lol, no prob.
