### ISSUE TITLE
Is possible to get response either success or failure from './gradlew publishBundle'

### ISSUE THREAD

**Issue by Vignesh-dev12** [Triple-T/gradle-play-publisher#924]
I have to do another process based on the response status of './gradlew publishBundle'. Please help me to find out this.

**Comment by SUPERCILEX** [comment]
If the task fails, Gradle will use a non-zero exit code. If you mean doing something within Gradle, you'd have to add a `finalizedBy` dependency and then do something similar to this: https://github.com/Triple-T/gradle-play-publisher/blob/003c2b01649ea7ca58b7e73a044b07729df5096e/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/CommitEdit.kt#L19
