### ISSUE TITLE
Can't set userFraction to 100%

### ISSUE THREAD

**Issue by ConorGarry** [Triple-T/gradle-play-publisher#927]
I just want to distributed to a small team of testers in our internal track, I have no reason to make that a staged rollout, I just want the process automated where they all receive it.
Setting the `userFraction` to 1.0 results in error: `User fraction must be lower than one`, and omitting the field sets it to the default value of `10%`. Am I missing something?

**Comment by SUPERCILEX** [comment]
That field isn't used unless you set the release status to inProgress.

**Comment by ObranS** [comment]
I have the same issue:

```
       "code": 400,
       "errors": [
         {
           "domain": "global",
           "message": "User fraction must be lower than one.",
           "reason": "badRequest"
         }
       ],
```


```
play {
    serviceAccountCredentials.set(file("../***"))
    track.set("beta")
    userFraction.set(1d)
    releaseStatus = ReleaseStatus.IN_PROGRESS
    resolutionStrategy = ResolutionStrategy.AUTO
    artifactDir.set(file("../../build/app/outputs/bundle/release"))
}
```
