### ISSUE TITLE
Request: rename bootstrap task something more specific

### ISSUE THREAD

**Issue by ZacSweers** [Triple-T/gradle-play-publisher#935]
### Problem description

The current "bootstrap" task is generic and collides with another task in our repo and offers little indication of what it pertains to.

### Potential solutions/workarounds

It would be ideal if this was something more specific, such as `bootstrapPlay` or similar. If it's deemed an invasive change, consider allowing customizing it via extension or gradle property.

**Comment by SUPERCILEX** [comment]
I could rename it to `bootstrapListing` which actually seems like an improvement since it would match `publishListing`.

**Comment by ZacSweers** [comment]
Works for me!
