### ISSUE TITLE
Uploading images fails with `This app has more than 8 screenshots for language en-US` even though there are exactly 8 screenshots.

### ISSUE THREAD

**Issue by chimbori** [Triple-T/gradle-play-publisher#944]
### Describe the bug

Uploading images fails with `This app has more than 8 screenshots for language en-US` even though there are exactly 8 screenshots.

I replaced all local PNG images in `app/src/main/play/listings/en-US/graphics/phone-screenshots` with new PNGs, then ran `./gradlew publishListing`. I have only a single set of images for the default locale.

### How To Reproduce

1. Run `./gradlew bootstrap` to sync local from Google Play.
2. Replace images in `app/src/main/play/listings/en-US/graphics/phone-screenshots`, retaining the filenames, and adding no new files.
3. Run `./gradlew publishListing` 

#### Versions

- Gradle Play Publisher: 3.4.0
- Gradle Wrapper: 6.8.3
- Android Gradle Plugin: 4.1.3

#### Tasks executed

`publishListing`

### Expected behavior

Screenshots should have been uploaded, and should have replaced the ones already present in the Store Listing.

### Additional context (if a crash, provide stack trace)

- I only have a single language for screenshots (default), so #524 is not relevant.

```
> A failure occurred while executing com.github.triplet.gradle.play.tasks.CommitEdit$Committer
   > 403 Forbidden
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/com.chimbori.REDACTED/edits/REDACTED:commit
     {
       "code": 403,
       "errors": [
         {
           "domain": "global",
           "message": "This app has more than 8 screenshots for language en-US.",
           "reason": "forbidden"
         }
       ],
       "message": "This app has more than 8 screenshots for language en-US.",
       "status": "PERMISSION_DENIED"
     }
```

```
.
└── en-US
    ├── full-description.txt
    ├── graphics
    │   ├── feature-graphic
    │   │   └── 1.png
    │   ├── icon
    │   │   └── 1.png
    │   ├── large-tablet-screenshots
    │   │   ├── 1.png
    │   │   ├── 2.png
    │   │   ├── 3.png
    │   │   └── 4.png
    │   ├── phone-screenshots
    │   │   ├── 1.png
    │   │   ├── 2.png
    │   │   ├── 3.png
    │   │   ├── 4.png
    │   │   ├── 5.png
    │   │   ├── 6.png
    │   │   ├── 7.png
    │   │   └── 8.png
    │   ├── tablet-screenshots
    │   │   ├── 1.png
    │   │   ├── 2.png
    │   │   ├── 3.png
    │   │   └── 4.png
    │   └── wear-screenshots
    │       ├── 1.png
    │       └── 2.png
    ├── short-description.txt
    └── title.txt

8 directories, 23 files
```

**Comment by SUPERCILEX** [comment]
Hmmm, this is probably an incremental cache bug. Does the issue still happen with `--rerun-tasks`?

**Comment by SUPERCILEX** [comment]
Can't reproduce unfortunately.

**Comment by colintheshots-meetup** [comment]
Could we please re-open this? It's been happening to me on every release. I'll try `--rerun-tasks`.
