### ISSUE TITLE
3.5.0 publishApk - KotlinNothingValueException

### ISSUE THREAD

**Issue by kofsiwon** [Triple-T/gradle-play-publisher#945]
### Describe the bug

I can't publish apk because KotlinNothingValueException
I used 3.4.0, but now there is no 3.4.0-SNAPSHOT.

./gradlew publishApk --artifact-dir $apkPath
...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:publishReleaseApk'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$Processor
   > Could not create an instance of type com.github.triplet.gradle.play.tasks.PublishApk$Processor.
      > Failed to create service 'playApi-com.siwonschool.[MASKED]'.
         > Could not create an instance of type com.github.triplet.gradle.play.tasks.internal.PlayApiService.
            > Could not generate a decorated class for type PlayApiService.
               > kotlin/KotlinNothingValueException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':commitEditForComDotSiwonschoolDotSiwonpen365'.
> Failed to query the value of task ':commitEditForComDotSiwonschoolDotSiwonpen365' property 'apiService'.
   > Failed to create service 'playApi-com.siwonschool.[MASKED]'.
      > Could not create an instance of type com.github.triplet.gradle.play.tasks.internal.PlayApiService.
         > Could not generate a decorated class for type PlayApiService.
            > kotlin/KotlinNothingValueException

### How To Reproduce
React-Native 

dependencies {
        classpath('com.android.tools.build:gradle:4.1.1')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
        classpath 'com.github.triplet.gradle:play-publisher:3.5.0-SNAPSHOT'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }

./gradlew publishApk --artifact-dir $apkPath

#### Versions

+--- com.github.triplet.gradle:play-publisher:3.5.0-SNAPSHOT
|    +--- com.github.triplet.gradle:android-publisher:3.5.0-SNAPSHOT
|    |    +--- com.github.triplet.gradle:common-utils:3.5.0-SNAPSHOT
|    +--- com.github.triplet.gradle:common-utils:3.5.0-SNAPSHOT
|    +--- com.github.triplet.gradle:common-validation:3.5.0-SNAPSHOT
Gradle 6.5
+--- com.android.tools.build:gradle:4.1.3

#### Tasks executed

publishApk --artifact-dir

### Expected behavior

success

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
Please run the gradle build with `--stacktrace` and share the output.

**Comment by kofsiwon** [comment]
solved by

insert into app/bundle.gradle
plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '3.4.0'
}

instead of [classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"]
