### ISSUE TITLE
Add documentation related to gradle tasks

### ISSUE THREAD

**Issue by vivekweb2013** [Triple-T/gradle-play-publisher#950]
What are you having trouble with and how can we help you?

There is no clear documentation related to many of the gradle tasks. So if possible please add a table to list all the gradle tasks offered by this plugin and what exactly they do and their interdependencies

'publishApk', 'publishApps', 'publishBundle', 'publishListing', 'publishProducts', 'publishRelease', 'publishReleaseApk', 'publishReleaseBundle', 'publishReleaseListing', 'publishReleaseProducts'

Many of the tasks from above does not even have documentation 

This will help users more insight of what the specific task do and how is it different from others

**Comment by SUPERCILEX** [comment]
The docs say what task to use to perform some action. If you prefer going the other way around and finding out what a task does, you can do that too: https://github.com/Triple-T/gradle-play-publisher#task-organization. (The last paragraph explains how to get docs for a specific task.)

**Comment by vivekweb2013** [comment]
`./gradlew tasks --group publishing` is helpful. Thanks for pointing out.
