### ISSUE TITLE
Could not create task ':app:uploadPrivateApk'

### ISSUE THREAD

**Issue by jkwiecien** [Triple-T/gradle-play-publisher#951]
### Describe the bug

When trying to publish or even when trying to simply do `./gradlew tasks` I get an error:
```
> Could not create task ':app:uploadProdDebugPrivateApk'.
   > com/android/build/api/artifact/SingleArtifact$APK
```

From the doc I assume it's related to internal app sharing - I don't need to use that with publisher, not sure why is it looking for an artifact.

### How To Reproduce
My configuration is only: 
```
play {
    track = "internal"
}

//also have flavors
    playConfigs {
        flavor1 {
            serviceAccountCredentials.set(file("f1-account-key.json"))
            track.set("internal")
        }

        flavor2 {
            serviceAccountCredentials.set(file("f2-account-key.json"))
            track.set("internal")
        }
    }
```

#### Versions
`3.4.0-agp7.0`

**Comment by SUPERCILEX** [comment]
Use the version that matches your android gradle plugin version: https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.4.0

**Comment by jkwiecien** [comment]
Thanks
