### ISSUE TITLE
Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. 

### ISSUE THREAD

**Issue by izzi888** [Triple-T/gradle-play-publisher#956]
**Problem description**

It seems the library doesn't support this query configuration. During .aab uploading (93% complete) Gradle returns an error on 

Task :commitEditForComDot*** FAILED
Committing changes

* What went wrong:
Execution failed for task ':commitEditForComDot***'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.CommitEdit$Committer
   > 400 Bad Request
     POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/com.williamhill.app.googleplay/edits/{$commit}:commit
     {
       "code": 400,
       "errors": [
         {
           "domain": "global",
           "message": "Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.",
           "reason": "badRequest"
         }
       ],
       "message": "Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.",
       "status": "INVALID_ARGUMENT"
     }

**Comment by SUPERCILEX** [comment]
Does this happen every time? I can't reproduce.

**Comment by izzi888** [comment]
Well, actually it happens when I try to publish a .aab file when an existing app rejected by the play store.
There are few ways to workaround the error:
1. Resolve the rejection and submit again
2. Upload .aab via web google play console for eg. in Alpha - Closed testing track, publish it and status should be set as "Changes in review"

But the issue is, could we decide from the plugin perspective changesNotSentForReview to true or false?

Accordingly to https://developers.google.com/android-publisher/api-ref/rest/v3/edits/commit there is a possibility to set changesNotSentForReview as a query parameter

**Comment by SUPERCILEX** [comment]
Would you want to be able to control this parameter? I'm think of just trying to send the change for review, and if the commit fails, then retrying but without sending them for review.

**Comment by izzi888** [comment]
Actually, there is no necessary to control this parameter so your solution is good

**Comment by SUPERCILEX** [comment]
Can someone try the [snapshot builds](https://github.com/Triple-T/gradle-play-publisher#snapshot-builds). I can't test it properly.

**Comment by izzi888** [comment]
I've tested. Everything works as expected. Thank you!

**Comment by jaynakus** [comment]
So when we can expect this to be released? I have same issue

**Comment by mx1up** [comment]
I had the same problem and tested out the snapshot release, it works, thanks!

**Comment by nibblesnbits** [comment]
I'm still seeing this, and it's preventing me from doing releases.
It seems the tool itself just needs a small update to explicitly send over the query parameter `changesNotSentForReview=true` when the "Send changes for review" flag is not set, as it is by default:
![image](https://user-images.githubusercontent.com/6042917/218290361-4dd6835d-b736-42ba-aa9f-76551d868efc.png)

**Comment by SUPERCILEX** [comment]
This check might not be returning true when it should: https://github.com/Triple-T/gradle-play-publisher/blob/77b069708cfd1bedfce5424af2c4a92cc9439763/play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher/Responses.kt#L90-L91

Someone will need to investigate.
