### ISSUE TITLE
Tasks not created

### ISSUE THREAD

**Issue by Luttik** [Triple-T/gradle-play-publisher#96]
Hi,

Ive added your plugin to my build.gradle (Module:app) file as follows:

apply plugin: 'com.android.application'
apply plugin: 'com.github.triplet.play'

android {...}

play {
	serviceAccountEmail = '...'
	pk12File = file('key.p12')
	track = 'beta'
}

dependencies {...}

But the tasks (publishApkRelease etc.) is not created. I hope you have some pointers for me

**Comment by bhurling** [comment]
Do you have a valid signingConfig defined for your release buildType?

**Comment by Luttik** [comment]
That indeed did it. I missed that instruction.

For those that find it specifications on signingConfig are found [here]{https://www.timroes.de/2013/09/22/handling-signing-configs-with-gradle/}
