### ISSUE TITLE
upload internal sharing problem

### ISSUE THREAD

**Issue by berkayerdi** [Triple-T/gradle-play-publisher#962]
### Describe the bug

Hello,
We run **./gradlew :app:uploadReleasePrivateBundle** task in Jenkins script.
Even if it build aab and give a valid sharing url, it does not upload aab to internal sharing. And also the task completes successfuly.

#### Versions

+--- com.github.triplet.gradle:play-publisher:3.4.0-agp4.2
|    +--- com.github.triplet.gradle:android-publisher:3.4.0-agp4.2
|    |    +--- com.github.triplet.gradle:common-utils:3.4.0-agp4.2
|    +--- com.github.triplet.gradle:common-utils:3.4.0-agp4.2
|    +--- com.github.triplet.gradle:common-validation:3.4.0-agp4.2
Gradle 6.7.1
+--- com.android.tools.build:gradle:4.2.1

#### Tasks executed

app:uploadReleasePrivateBundle

### Expected behavior

Publishing play store.

### Additional context (if a crash, provide stack trace)

There is no stacktrace logs.

**Comment by SUPERCILEX** [comment]
What happens if you click on the link? My guess is that you're confusing the internal track with internal app sharing. Those are different things.

**Comment by berkayerdi** [comment]
I know but, the url redirects play store and when i click download button it downloads older version.

**Comment by SUPERCILEX** [comment]
Maybe your email isn't in the internal sharing list? Either way, that's not a GPP bug since the upload succeeded. Unless you're able to manually upload the aab and have it work?
