### ISSUE TITLE
Retain over CLI

### ISSUE THREAD

**Issue by nohe427** [Triple-T/gradle-play-publisher#964]
**What are you having trouble with and how can we help you?**

Is there a way to retain APKs over the CLI?

I was trying to publish using the CLI and wanted to indicate that I wanted to retain an APK while publishing. Just wanted to know if that was possible.

**Comment by SUPERCILEX** [comment]
There are no CLI args, but we have retention configs: https://github.com/Triple-T/gradle-play-publisher#retaining-artifacts.
