### ISSUE TITLE
Add support to provide Service Account Credentials in JSON format

### ISSUE THREAD

**Issue by mpost** [Triple-T/gradle-play-publisher#97]
Currently you can only use the p12 file to authentication against the google services. It should also be possible to  use the JSON file that you can generate on the google developer console for authentication.

> ![image](https://cloud.githubusercontent.com/assets/73655/9628965/8d65d30a-516f-11e5-906d-86588545c46d.png)

Thereby the content of the file could be more easily consumed on build services like Travis when defining an environment variable with the content of the JSON file as its value.

**Comment by bhurling** [comment]
I see, this JSON contains a private key as well as the service email address. So you no longer have to define it as a property for the plugin. The JSON file should be all that's needed. Shouldn't be too hard to offer both ways of authentication.

But currently I am focusing on #76 to provide variant-based credentials. Having said that, a PR is always very welcome. :)

**Comment by mpost** [comment]
PR is likely not coming in in the near future. But still would love to see it added. :)

**Comment by shiraji** [comment]
Would you mind if I try to implement this, @bhurling ?

**Comment by mpost** [comment]
+1

**Comment by shiraji** [comment]
I'm so sorry if I act like a rude person, but I created pull request for this issue without permission.

I put WIP since I haven't test this credentials in Google Play. Is there any easy way to test this in actual Google Play account?

**Comment by bhurling** [comment]
No need to apologize. Thanks a lot for your contributions. I'm going to run some tests tomorrow but at first sight this looks very good to me.

**Comment by shiraji** [comment]
Sounds good! Let me know if you find a problem.

**Comment by mpost** [comment]
Great to see it added, Thanks,
