### ISSUE TITLE
Gradle 7.1 not working completely with GPP, possibly flavor-related (error 'Querying the mapped value of property' etc)

### ISSUE THREAD

**Issue by mikehardy** [Triple-T/gradle-play-publisher#973]
### Describe the bug

It appears that there is an incompatibility between Gradle 7.1 and GPP here, and publishing does not work, at least for flavor-related publishing

**For other developers that run into this: Gradle 7.0.x should work fine** - no need to be stuck

### How To Reproduce

`./gradlew test` in this repo from current HEAD of main development branch after updating gradle (#971) is sufficient to reproduce

#### Versions

Please forgive me for skipping versions, I posted a PR so there was a crystal clear reproduction though, not trying to be difficult I promise :-)

#### Tasks executed

`./gradlew test` (or `./gradlew publishPlayReleaseApk` in AnkiDroid)

### Expected behavior

Successful tests pass, or successful publish

### Additional context (if a crash, provide stack trace)

Stack trace provided in linked PR #971 - error message is:

> Execution failed for task ':uploadReleasePrivateApk'.
> Querying the mapped value of property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, property(org.gradle.api.file.Directory, map(org.gradle.api.file.Directory flatmap(provider(task 'packageRelease', class com.android.build.gradle.tasks.PackageApplication)) check-type())))) before task ':packageRelease' has completed is not supported

**Comment by mikehardy** [comment]
@SUPERCILEX I was 99% sure you'd know how to nail this one down, excellent! Thanks again for this plugin, I really appreciate it

**Comment by BugsBunnyBR** [comment]
@SUPERCILEX it seems that this issue was fixed 27/06 and the last release was done 23/06. Can we get a release with this fix ?

**Comment by SUPERCILEX** [comment]
I'm hoping to make a release this weekend. In the meantime, you can always use the [snapshot builds](https://github.com/Triple-T/gradle-play-publisher#snapshot-builds).
