### ISSUE TITLE
3.5.0-agp7.0 does not work with Artic Fox (beta version of Android Studio)

### ISSUE THREAD

**Issue by markchristopherng** [Triple-T/gradle-play-publisher#975]
### Describe the bug

When you upgrade to the versions specified below and try to compile your project you get the following error.

Unable to load class 'com.android.build.api.extension.AndroidComponentsExtension$DefaultImpls'.

This is an unexpected error. Please file a bug containing the idea.log file.

### How To Reproduce

Compile your android project

#### Versions

3.5.0-agp7.0 
Gradle 7.1
Artic Fox 2020.3.1 beta 4 
Android Gradle plugin 7.0.0-beta04

- Gradle Play Publisher: 
- Gradle Wrapper: 
- Android Gradle Plugin: 

#### Tasks executed

What tasks did you run? For example, `publishBundle`.

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
See https://github.com/Triple-T/gradle-play-publisher/issues/963#issuecomment-863465114
