### ISSUE TITLE
Task 'publishFreeReleaseBundle' not found in project ':app'.

### ISSUE THREAD

**Issue by ArcherEmiya05** [Triple-T/gradle-play-publisher#976]
### Describe the bug

Good day I am new to this and trying to use GPP in AS locally, I was able to do task like `bootstrapListing` but when I tried `publishFreeReleaseBundle` to release a AAB to internal track it does not work.

_Note: I already have releases in production track only._

### How To Reproduce

This is what the gradle file looks like
```

plugins {
    id 'com.android.application'
    ...
    id 'com.github.triplet.play'
}

android {
    compileSdk Integer.parseInt(ANDROID_BUILD_COMPILED_SDK_VERSION)

    defaultConfig {
        applicationId "com.app.name"
        minSdk Integer.parseInt(ANDROID_BUILD_MIN_SDK_VERSION)
        targetSdk Integer.parseInt(ANDROID_BUILD_TARGET_SDK_VERSION)
        versionCode project.hasProperty('BUILD_NUMBER') ? project['BUILD_NUMBER'].toInteger() : 14
        versionName "1.3.3"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        debug {
            storeFile file(DEBUG_KEYSTORE_FILE)
            storePassword DEBUG_KEYSTORE_PASSWORD
            keyAlias DEBUG_KEYSTORE_KEY_ALIAS
            keyPassword DEBUG_KEYSTORE_KEY_PASSWORD
        }
        release {
            storeFile file(APPNAME_KEYSTORE_FILE)
            storePassword APPNAME_KEYSTORE_PASSWORD
            keyAlias APPNAME_KEYSTORE_KEY_ALIAS
            keyPassword APPNAME_KEYSTORE_KEY_PASSWORD
        }
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled true
            shrinkResources true
            multiDexEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.debug
        }
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            multiDexEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    lintOptions {
        disable "MissingClass"
    }

    buildFeatures {
        viewBinding true
    }
}

play {
    serviceAccountCredentials.set(file(GOOGLE_PLAY_API_KEY_FILE))
}
```

#### Versions

- Gradle Play Publisher: `3.5.0-SNAPSHOT` or `3.6.0-SNAPSHOT`
- Gradle Wrapper: 7.0
- Android Gradle Plugin: 7.1.0

#### Tasks executed

`gradlew -PANDROID_BUILD_COMPILED_SDK_VERSION=30 -PANDROID_BUILD_MIN_SDK_VERSION=21 -PANDROID_BUILD_TARGET_SDK_VERSION=30 -PDEBUG_KEYSTORE_FILE="C:/Users/USERNAME/Keys/Debug Key/debug.keystore" -PDEBUG_KEYSTORE_PASSWORD=android -PDEBUG_KEYSTORE_KEY_ALIAS=androiddebugkey -PDEBUG_KEYSTORE_KEY_PASSWORD=android -PAPPNAME_KEYSTORE_FILE="C:/Users/USERNAME/Keys/Release Key/keystore.jks" -PAPPNAME_KEYSTORE_PASSWORD=release -PAPPNAME_KEYSTORE_KEY_ALIAS=release -PAPPNAME_KEYSTORE_KEY_PASSWORD=release -PGOOGLE_PLAY_API_KEY="C:/Users/USERNAME/Keys/Google Play/google-play-api-key.json" -PBUILD_NUMBER=15 clean :app:publishFreeReleaseBundle
`

### Expected behavior

Success

### Additional context (if a crash, provide stack trace)

Add any other context about the problem here. If this bug is a crash, run the task with
`--stacktrace` to get the full context.

**Comment by SUPERCILEX** [comment]
What does "not work" mean? By default it'll publish to the internal track, you need to specify production if you don't want that.

**Comment by ArcherEmiya05** [comment]
> 
> 
> What does "not work" mean? By default it'll publish to the internal track, you need to specify production if you don't want that.

After executing the above command in AS terminal what I get is in the title `Task 'publishFreeReleaseBundle' not found in project ':app'.`

**Comment by SUPERCILEX** [comment]
Use `publishReleaseBundle`.

**Comment by ArcherEmiya05** [comment]
> 
> 
> Use `publishReleaseBundle`.

Will try this one many thanks, may I also know what are the list of task command available with GPP because as I saw in many article they used `publishFreeReleaseBundle` or `publishProReleaseBundle` instead of just `publishReleaseBundle` and I do not know the difference when not specifying if free or pro version.

**Comment by SUPERCILEX** [comment]
That's if you have flavor dimensions (you don't). See https://github.com/Triple-T/gradle-play-publisher#task-organization

**Comment by ArcherEmiya05** [comment]
> 
> 
> That's if you have flavor dimensions (you don't). See https://github.com/Triple-T/gradle-play-publisher#task-organization

Oh I really missed that part, thank you so much!

**Comment by Faisal-ali-shah** [comment]
@SUPERCILEX i'm using id 'com.github.triplet.play' version '2.2.1' and trying to upload app bundle instead of apk by default 
and apk upload working fine.
play {
    track = 'beta'
    defaultToAppBundles = true
    serviceAccountCredentials = file('k.json')
}

but when I run 
./gradlew  publish

getting exception what am I missing you can please guide me ?
* What went wrong:
BUNDLE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by SUPERCILEX** [comment]
Please follow the readme. 2.2.1 is way too old, you should be on a 3.x.

**Comment by ArcherEmiya05** [comment]
> 
> 
> Use `publishReleaseBundle`.

Still not working as I am getting this instead
```

 Could not create task ':app:publishReleaseBundle'.
   > com/android/build/api/artifact/ArtifactType$BUNDLE

```

**Comment by SUPERCILEX** [comment]
Right, you're using AGP 7.1, so you'll need GPP 3.5.0-agp7.0.

**Comment by ArcherEmiya05** [comment]
It works, this will be very handy on a CI CD setup. Kudos!
