### ISSUE TITLE
Tracks and user fraction

### ISSUE THREAD

**Issue by ArcherEmiya05** [Triple-T/gradle-play-publisher#977]
Good day, I wanted to know more about usage of GPP

1. Does `userFraction` applies to all tracks even in internal track?
2. What does the `releaseStatus` `COMPLETED` and `IN_PROGRESS` means?

Thank you

**Comment by SUPERCILEX** [comment]
https://github.com/Triple-T/gradle-play-publisher#common-configuration

1. Yes
2. In progress when you are rolling out a release, completed when done.

**Comment by ArcherEmiya05** [comment]
Ohh okay so for internal track better to set `userFraction` to 1.
Sorry what does **rolling out** means? Does it mean the track's `userFraction` is not yet in 100%?
Does `userFraction` gradually increase automatically or is it manual?

**Comment by SUPERCILEX** [comment]
If you don't understand what a rollout is, don't mess around with the user fraction settings. It's for releasing a new version of your app to a small population of users and progressively rolling out the release (manually bumping the user fraction) to more users until you complete the release by completely replacing the old version. Basically just a way to avoid doomsday crashes.

**Comment by ArcherEmiya05** [comment]
> 
> 
> If you don't understand what a rollout is, don't mess around with the user fraction settings. It's for releasing a new version of your app to a small population of users and progressively rolling out the release (manually bumping the user fraction) to more users until you complete the release by completely replacing the old version. Basically just a way to avoid doomsday crashes.

Thanks so far I understand the purpose of user fraction but no idea whether it is automatically reaching all user little by little or the developer is the responsible for increasing it manually.

`ReleaseStatus.[COMPLETED/DRAFT/HALTED/IN_PROGRESS]`
Regarding release statuses, are these correct?

`COMPLETED` the availability of the new version in store completely replaced the old version.
`DRAFT` I assumed it is like when you manually publishing a new app or app update but not yet submitting it for rollout.
`HALTED` I do not know this one, I assumed it is when the app update has been rejected?
`IN_PROGRESS` the availability of new version in store does not yet reached all of its user.

**Comment by SUPERCILEX** [comment]
Yes, you have to manually choose when to increase the rollout percentage.

Draft: no idea why you'd use this. It means the app will show up in the release but not do anything.

Halted: you started a rollout and went "oh shit, we done goofed." No new users will be able to download the new release.

You got the other two. 👍

**Comment by ArcherEmiya05** [comment]
> 
> 
> Yes, you have to manually choose when to increase the rollout percentage.
> 
> Draft: no idea why you'd use this. It means the app will show up in the release but not do anything.
> 
> Halted: you started a rollout and went "oh shit, we done goofed." No new users will be able to download the new release.
> 
> You got the other two. 👍

Ohhh so `Halted` is when you decided to pull back and stop releasing the new version because it has a bomb on it.

Since internal track is for testing purposes within a selected group of people e.g. your co-worker or QA. It is safe to put `1` in `userFraction` right?

**Comment by SUPERCILEX** [comment]
`userFraction` doesn't do anything unless your release status is IN_PROGRESS. Just don't use it unless you're actually doing a rollout.

**Comment by ArcherEmiya05** [comment]
> 
> 
> `userFraction` doesn't do anything unless your release status is IN_PROGRESS. Just don't use it unless you're actually doing a rollout.

You mean not use it when not doing a production rollout?

**Comment by SUPERCILEX** [comment]
Are you actually trying to release a new version of your app in stages? If not, don't use `userFraction`.

Staged rollouts can be used with any track (including `internal`). If you are doing a rollout, the release status must be `IN_PROGRESS` (otherwise it defaults to completed meaning the `userFraction` will be ignored).

**Comment by ArcherEmiya05** [comment]
> 
> 
> Are you actually trying to release a new version of your app in stages? If not, don't use `userFraction`.
> 
> Staged rollouts can be used with any track (including `internal`). If you are doing a rollout, the release status must be `IN_PROGRESS` (otherwise it defaults to completed meaning the `userFraction` will be ignored).

Yes I am releasing a new version.

The flow would be like internal track with userFraction of 100% then promote to production by 10% progressively.

**Comment by SUPERCILEX** [comment]
Yup, sounds about right. Though again, a user fraction of 100% does nothing so you'd want to keep the release status as completed instead.

**Comment by ArcherEmiya05** [comment]
> 
> 
> Yup, sounds about right. Though again, a user fraction of 100% does nothing so you'd want to keep the release status as completed instead.

In the console I see no stage rollout option when trying to create new release in internal track, maybe because I am trying it with older version (rollback) from the app bundle explorer library. However stage rollout is available in production track where I can specify its percentage.

**Comment by ArcherEmiya05** [comment]
> 
> 
> > Yup, sounds about right. Though again, a user fraction of 100% does nothing so you'd want to keep the release status as completed instead.
> 
> In the console I see no stage rollout option when trying to create new release in internal track. However stage rollout is available in production track where I can specify its percentage. So I assumed user fraction does not apply in internal track.

It also appears when releasing new app version under open testing track (beta)

**Comment by SUPERCILEX** [comment]
It might just be that they don't show it to you in the console (b/c doing a staged rollout for <10000 people is kinda pointless). If the API lets you though, GPP will be able to set the user fraction for the internal track.

**Comment by ArcherEmiya05** [comment]
> 
> 
> Yup, sounds about right. Though again, a user fraction of 100% does nothing so you'd want to keep the release status as completed instead.

In other words, instead of specifying `userFraction` value to `1` we could just specify the `releaseStatus` to `ReleaseStatus.COMPLETED`. But since by default `releaseStatus` value is `completed` we no longer need to add any additional options specially when what we want is to deliver update release on internal track that will be available on all tester, just executing a gradlew task with `:app:publishReleaseBundle` already does that.

**Comment by SUPERCILEX** [comment]
Yup, that was a perfect explanation!

**Comment by ArcherEmiya05** [comment]
> 
> 
> Yup, that was a perfect explanation!

At last!

One more thing before closing this.

1. If you are previously doing a stage rollout but then you forgot to explicitly specify `releaseStatus` in `IN_PROGRESS` on your current/next release with GPP, will the previous stage rollout will mark automatically as `completed`?

2. Can we use GPP for increasing a `userFraction` only?

3. When promoting an artifact from example, internal to production. What is the basis of GPP to execute this? Is it the  release `versionCode`?

**Comment by SUPERCILEX** [comment]
1. Yup. Come to think of it, that's not the best of ideas. Maybe we can do something where if you've explicitly set the user fraction and not the release status, we'll implicitly set the release status to in progress for you. WDYT?

   The historical reason for not doing this is that the user fraction had to be set, so we provided a default at the DSL level (meaning we couldn't tell if you had set the user fraction or not). Now the default is provided in the business logic layer so the user fraction and release status will be null if you haven't configured them.

2. Yes, that's part of the promotion task. You would make `fromTrack` and `promoteTrack` be the same value (a `--update` CLI flag exists that does this). As per 1, yeah, if you forget to set the release status we'll yeet you into completed. Again, probs not great.

3. The promote task only needs a correct package name. Anything else app related is ignored, so you can have the version code be whatever you want. And right, we don't build the app again. It might help to just look at the API we're messing with yourself: https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Release. There are multiple release objects, so one of them would be `completed` and another (with a higher version code) would be `inProgress`.

**Comment by ArcherEmiya05** [comment]
Alright! Thanks a lot! Will close this now and will just ask more in the future.

**Comment by SUPERCILEX** [comment]
Lemme keep it open for a bit longer... I want to look into the auto in progress thing.

**Comment by SUPERCILEX** [comment]
Whoops.

**Comment by ArcherEmiya05** [comment]
Hi, just a follow up question regarding promotion of track.
When promoting an internal track to production, does it always choose the most recent version in internal track? Thanks

**Comment by SUPERCILEX** [comment]
@ArcherEmiya05 yes, but there's an issue to support choosing specific version codes: #980.
