### ISSUE TITLE
Error completing final release promotion

### ISSUE THREAD

**Issue by la-eln** [Triple-T/gradle-play-publisher#983]
Hi! When I execute this gradle command I got an error with code 400

#### Tasks executed

`./gradlew promoteArtifact --from-track production --promote-track production --release-status completed`

Response:
```
      {
        "code": 400,
        "errors": [
          {
            "domain": "global",
            "message": "COMPLETED release must not have fraction",
            "reason": "badRequest"
          }
        ],
        "message": "COMPLETED release must not have fraction",
        "status": "INVALID_ARGUMENT"
      }
```
Though, as you can see, no fraction was supplied

#### Versions

- Gradle Play Publisher: 3.4.0
- Gradle Wrapper: 7.0.2
- Android Gradle Plugin: 4.1.2

### Additional context (if a crash, provide stack trace)

However, there are no problems with the execution of these commands (with any percentage)
`./gradlew promoteArtifact --from-track production --promote-track production --release-status inProgress --user-fraction 0.5`

**Comment by SUPERCILEX** [comment]
Interesting. I'll need to check, but my guess is that we're carrying over the previous user fraction when we actually need to null it out if the release status is completed.

**Comment by dvdciri** [comment]
I'm also having the same issue, looking forward to the fix.
