### ISSUE TITLE
Error with last update

### ISSUE THREAD

**Issue by EzequielMessore** [Triple-T/gradle-play-publisher#989]
### Describe the bug

When I try run my project in this morning, I saw that I need to update Gradle version and Android Studio version, and I updated but got an error.
Someone could I help me?

### How To Reproduce
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64

And 

classpath "com.android.tools.build:gradle:7.0.0"

#### Build Output

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':app:injectCrashlyticsMappingFileIdS3Debug' (type 'InjectMappingFileIdTask').
  - Type 'com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask' field 'resourceFile' without corresponding getter has been annotated with @OutputFile.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'resourceFile'.
      2. Remove the annotations on 'resourceFile'.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Some problems were found with the configuration of task ':app:generateSafeArgsS3Debug' (type 'ArgumentsGenerationTask').
  - Type 'androidx.navigation.safeargs.gradle.ArgumentsGenerationTask' property 'applicationId' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'androidx.navigation.safeargs.gradle.ArgumentsGenerationTask' property 'applicationIdResource' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s

**Comment by SUPERCILEX** [comment]
There's nothing related to this plugin in those logs.
