### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tir38** [Triple-T/gradle-play-publisher#99]
Where in my project structure is this going to look for my generated .apk?

I'm still not clear on what I need to set up on my Travis build server to enable apk upload, beyond adding `    ./gradlew publishApkRelease` to my list of gradle tasks in `travis.yml`. Where do I supply the key for my p12 file?

**Comment by bhurling** [comment]
The plugin looks at the variant output that always points to the final APK file. You don't have to worry about the exact name and location.

The p12 file can reside anywhere in your project directory. Pease note that a p12 file contains secrets that should not be committed to source control, especially in Open Source projects built with travis. You can, however, encrypt files for travis using the [travis gem](http://docs.travis-ci.com/user/encrypting-files/).

**Comment by FallenRiteMonk** [comment]
Is there a way to also edit the game services listing?

**Comment by tir38** [comment]
@bhurling thanks. That worked. I misunderstood how the .p12 file worked. I thought it was like a keystore where you provided passwords to the keystore via Travis. Once I encrypted the .p12 file like you linked to, I was able to include `.enc` file in repo and do an automated upload. Thanks so much.
