### ISSUE TITLE
Plugin version 3.6.0 for AGP 4.2.2

### ISSUE THREAD

**Issue by BugsBunnyBR** [Triple-T/gradle-play-publisher#990]
I understand that AGP 7.0.0 is stable now, but many of us can't just update to AGP 7.0.0 due other plugins not being so quick to update like this one.

Could we have the fixes for gradle in the AGP 4.2.2 version compatible?

**Comment by SUPERCILEX** [comment]
I don't see why not. I'll try to give that a go sometime this week.

**Comment by SUPERCILEX** [comment]
Done: https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.6.0-agp4.2
