### ISSUE TITLE
Publish succeeded but didn't appear on Google Play

### ISSUE THREAD

**Issue by lordcodes** [Triple-T/gradle-play-publisher#991]
### Describe the bug

I ran the 'publishReleaseBundle' Gradle task, which has been used many times successfully. The task said the release was uploaded and succeeded, I could see output showing it get uploaded and a message to say it was released to the Internal Testing track successfully.
I went to Google Play and the release wasn't there, I checked the next morning and the release still wasn't there. In the end I had to publish again.

#### Versions

- Gradle Play Publisher: 3.6.0
- Gradle Wrapper: 7.1.1
- Android Gradle Plugin: 7.0.0

#### Tasks executed

publishReleaseBundle

### Expected behavior

The release to be on Google Play in the track specified. If the release isn't released I would expect the Gradle task to fail so that I can prevent the next steps in the release process from running.

### Additional context

I have seen this happen before in the past, when I was on Play Publisher 3.4.0 using AGP 4.2, so don't think it was caused by the upgrade to 3.6.0 or AGP 7.

**Comment by SUPERCILEX** [comment]
When you published again, was that with the plugin? If the issue you ran into happened only once, then it's some bug in Google API that's outside of our control.

**Comment by lordcodes** [comment]
When I published again it was the plugin yes. However, they issue has happened before a few times, each time resolved by running again.

The surprise was that the plugin reported it succeeding with then caused further steps in the release process to run afterwards. 

I assume you're saying that the plugin uses Google Play APIs which will have reported a success and so the issue is in there?

**Comment by SUPERCILEX** [comment]
Yes, if the API reports an error, so do we. So if it says everything is fine, there's nothing we can do. I would suggest contacting play support when this happens and seeing if they can figure it out.

**Comment by lordcodes** [comment]
Thank you. Will see if it happens again and if it does take it further. Thank you.
