### ISSUE TITLE
Boostrap downloads JPEG files with incorrect .png file extension 

### ISSUE THREAD

**Issue by rtsisyk** [Triple-T/gradle-play-publisher#992]
### How To Reproduce

```
./gradlew bootstrapGoogleRelease
```

```
file -b src/google/play/listings/en-US/graphics/phone-screenshots/1.png
```

```
JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=5, height=3040, software=Android RP1A.200720.012.G973FXXUAFUE3, orientation=[*0*], width=1440], baseline, precision 8, 1440x3040, components 3
```

All JPEG screenshots downloaded as .png.

#### Versions

```
+--- com.github.triplet.gradle:play-publisher:3.4.0
|    +--- com.github.triplet.gradle:android-publisher:3.4.0
|    |    +--- com.github.triplet.gradle:common-utils:3.4.0
|    +--- com.github.triplet.gradle:common-utils:3.4.0
|    +--- com.github.triplet.gradle:common-validation:3.4.0
Gradle 7.0
+--- com.android.tools.build:gradle:4.1.3
```

- Gradle Play Publisher:  3.4.0
- Gradle Wrapper: 7.0
- Android Gradle Plugin: 4.1.3

#### Tasks executed

`bootstrap`.

### Expected behavior

JPEG files downloaded with .jpg extension instead of .png.

**Comment by biodranik** [comment]
Looks like this line causes the error https://github.com/Triple-T/gradle-play-publisher/blob/ae69e86dc7c5bf561dd719090cb31cd6d3519d7a/play/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/Bootstrap.kt#L160

**Comment by SUPERCILEX** [comment]
Yeah, the logic is pretty dumb as you've noticed. :) I'll have to see if the API tells us what the image type is. If not, I guess we can just read the first few bytes of the file and check it against the magic numbers: https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by rtsisyk** [comment]
Thanks a lot!
