### ISSUE TITLE
Unable to run gradle tasks 

### ISSUE THREAD

**Issue by AnastasiaRainMaker** [Triple-T/gradle-play-publisher#994]
I am unable to run `./gradlew tasks` command due to a failure coming from the publishing plugin. 

The output is 

* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':base:uploadDebugPrivateApk'.
   > com/android/build/api/artifact/ArtifactType$APK

AS - Arctic fox stable
AGP - 7.0.0
Publishing plugin "3.6.0-agp4.2"

Seems to be related to this question as well https://www.gitmemory.com/issue/Triple-T/gradle-play-publisher/961/860139828

**Comment by SUPERCILEX** [comment]
Use 3.6.0, **not** 3.6.0-agp4.2.

**Comment by AnastasiaRainMaker** [comment]
it worked

**Comment by SUPERCILEX** [comment]
Sweet!
